### ISSUE TITLE
How can i fix "car_list"

### ISSUE THREAD

**Issue by regular33** [hyyan/woo-poly-integration#1]
Hello sir,firstly thanks you for the plugin. But I have a little problem, 

When I click on a category directory, I get all the goods of the three languages that I use, but if I click on the catalog of the native language, then everything is working correctly and displays the product only in their native language.

Maybe i should add the some filtr?

**Comment by hyyan** [comment]
@regular33 Did you make sure you have setup your permalinks correctly ? Products Categories are wordpress custom taxonomies which polylang can handle out the box correctly 

I would suggest the following : 

- Enable translation for product categories in the polylang setting page (this plugin will not do this automatically for you at least for now)
- Make sure the product category permalink is similar to something like `product-category` in wordpress permalinks setting page

**Comment by hyyan** [comment]
Hey @regular33  , the plugin has been improved a lot since this Issue is opend , are still having a problems ?
