### ISSUE TITLE
setDefaultPermalinks Undefined Index

### ISSUE THREAD

**Issue by djgadd** [hyyan/woo-poly-integration#10]
I'm getting undefined index warnings for setDefaultPermalinks in Hyyan\WPI\Permalinks on a fresh install (when no woo permalinks have been setup).

**Comment by Xterm** [comment]
I will second that.

Notice: Undefined index: tag_base, src/Hyyan/WPI/Permalinks.php on line 43
Notice: Undefined index: product_base, src/Hyyan/WPI/Permalinks.php on line 44

**Comment by Jon007** [comment]
Can still reproduce this on latest versions.

#### Can you reproduce this issue on default Wordpress theme (eg Storefront)?
yes

#### Can you reproduce this issue when all other plugins are disabled except WooCommerce, Polylang and Hyyan WooCommerce Polylang Integration?

#### What product versions and settings are you using when this issue occurs?
* PHP: 7.0.15 
* WordPress:4.7.5 
* WooCommerce: 3.1.0-alpha
* Polylang: 2.1.5
* Hyyan WooCommerce Polylang Integration: 1.0
* Browser: chrome


#### Steps to Reproduce
1. plain install with WooCommerce, Storefront and wp_debug on  
1. activate Polylang and Hyyan WooCommerce Polylang Integration

#### What I Expected
activate without warnings

#### What Happened Instead
1.  Notice: Undefined index: tag_base in ...wp-content/plugins/woo-poly-integration/src/Hyyan/WPI/Permalinks.php on line 43

> ...wp-content/plugins/woo-poly-integration/src/Hyyan/WPI/Permalinks.php:43:
> array (size=1)
>   'category_base' => string 'product-category' (length=16)


Then on general navigation, still in base language, seeing some follow on errors like:

>  Fatal error: Uncaught Error: Call to undefined function Hyyan\WPI\PLL() in wp-content/plugins/woo-poly-integration/src/Hyyan/WPI/Endpoints.php on line 223

>  Notice: Trying to get property of non-object in /wp-content/plugins/woo-poly-integration/src/Hyyan/WPI/Widgets/SearchWidget.php on line 44

**Comment by Jon007** [comment]
The first error should be fixed by using isset() eg
```
    public function setDefaultPermalinks()
    {
        $permalinks = get_option('woocommerce_permalinks');

        $permalinks['category_base'] = **isset(**$permalinks['category_base']**)** ?: self::PRODUCT_CATEGORY_BASE;
        $permalinks['tag_base'] = isset($permalinks['tag_base']) ?: self::PRODUCT_TAG_BASE;
        $permalinks['product_base'] = isset($permalinks['product_base']) ?: self::PRODUCT_BASE;

```
