### ISSUE TITLE
Attributes do not sync

### ISSUE THREAD

**Issue by JurekSIN** [hyyan/woo-poly-integration#100]
Hello,

I believe product attributes stoped syncing since one of recent updates. Even if I remove product to trash, new product I link to the same translation still shows legacy attributes. I am unable to fix it using any transient cleaner nor any toolkit. What do I do? Attributes do sync, but variants don't.

Sites: 
PL original - 3 variants based on attributes https://shop.sin.org.pl/pl/product/odczynnik-mecke/
EN - none shows up. other products show legacy 2 attributes: 

PL
![capturfiles_1087](https://cloud.githubusercontent.com/assets/24252068/21193960/6c8a3104-c22e-11e6-830a-27c50b9761a3.png)
![capturfiles_1086](https://cloud.githubusercontent.com/assets/24252068/21193961/6cbc6354-c22e-11e6-9c0e-8055428fbb43.png)

EN
![capturfiles_1085](https://cloud.githubusercontent.com/assets/24252068/21193962/6cbcc6c8-c22e-11e6-805b-dd7dffeef750.png)
![capturfiles_1084](https://cloud.githubusercontent.com/assets/24252068/21193963/6cbcf472-c22e-11e6-84e6-8dc5dee0e43d.png)

No problem - https://shop.sin.org.pl/pl/product/odczynnik-mecke/
Problem - https://shop.sin.org.pl/en/product/mecke-reagent/

WC 2.6.9
WP 4.7
Hyyan 0.29

**Comment by decarvalhoaa** [comment]
I have not tested yet with WC 2.6.9 and WP 4.7. With the previous version this was working. I'm assuming at this point , it my be related to one of these upgrades. Do you have the chance to rollback your upgrades?

**Comment by JurekSIN** [comment]
I removed all the english products, removed from trash, at this point polish attributes synced with the legacy english ones. I changed them, saved the updated polish original. Added new english products, phew, finally synced.

**Comment by decarvalhoaa** [comment]
I'm glad to hear that you got it working.
