### ISSUE TITLE
no option to translate the "Price Display Suffix" box value

### ISSUE THREAD

**Issue by jnhghy** [hyyan/woo-poly-integration#104]
Hi,

Nice plugin, it helps a lot but I couldn't find a way of translating "Price Display Suffix" , the option is located in WooCommerce -> Tax. The usual input value for english might sound like "VAT inc." but it should be translated for other languages.

Thank you

**Comment by decarvalhoaa** [comment]
Hi,

this is indeed not implemented in the plugin. I will look into that as soon as I have a little bit of time. Priority right now is making sure this plugin will work with WooCommerce 2.7 that will be released soon.

**Comment by Jon007** [comment]
A couple of observations:

* WooCommerce 3.0 made some breaking changes here when they were simplifying the html for the product variations with price range + tax
* WooCommerce 3.0.5 released today contains a fix:
  * Dev - Make get_price_html handling match 2.6 and pass all values through woocommerce_get_price_html filter.
which means we may be able to implement in way that supports both WooCommerce 2.6 and 3.x

**Comment by Jon007** [comment]
I've done this and tested ok in Dev on WooCommerce 3.0.5 with both simple and variable products, pending testing on WooCommerce 2.6.

Note that wooCommerce uses a different string on the basket page  for example "(ex. tax)" , which is translated via wooCommerce language files and based on the setting in "Display prices during basket and checkout", whereas the Price display suffix is used for the "Display prices in the shop"

I'll reference this issue when I check in.
It will then be added to pull request 0.30RC1, and the code will be available at:
https://github.com/Jon007/woo-poly-integration

This should be treated as beta software until we have completed the testing, merge and release.

It would be great if you can test it!!!
If you find any issues with the RC, please report as separate issues, I will fix asap.

**Comment by Jon007** [comment]
The implementation supports substitution with flexibility to rearrange the parameters, 

for example in English you could set 
WooCommerce\Settings\Price display suffix == ({price_including_tax} inc VAT)
and prices would then be displayed as eg:
$15.00 ($18.00 inc VAT)

And then in Languages\Strings translations\Woocommerce Taxes you could set the Spanish version to:
(con IVA {price_including_tax})
so it would be displayed as:
$15.00 (con IVA $18.00)

**Comment by Jon007** [comment]
Implemented only for WooCommerce 3.x, as this is new functionality that was never in previous version of this plugin.  If needed to operate with WooCommerce 2.6, needs a different function as the filter parameters have changed.
