### ISSUE TITLE
PHP Notice:  Undefined variable: order_id in /var/www/html/tlc-dev/wp-content/plugins/woocommerce/includes/class-wc-ajax.php on line 445

### ISSUE THREAD

**Issue by decarvalhoaa** [hyyan/woo-poly-integration#108]
Steps to reproduce:

1. Go through checkout on the frontend to create an Order with a variable product (variation attribute is taxonomy). Use BACS to pay the order.
2. Go to admin and mark the order as "Processing" in the Admin -> WooCommerce -> Orders page.
3. The message in the subject will pop up in the error log.

**Comment by Delgesh** [comment]
You must define order_id before and the best way to do this is by using if statement isset see example :

global $woocommerce;

if (isset ($order_id)) {
	$order = new WC_Order($order_id);
	$items = $order->get_items();
	foreach ($items as $item) {
		$product_id = $item['product_id'];
		if ($product_id ==  your product id) {
			//do something
		} else {
			//do something
		}

	}
}

**Comment by Jon007** [comment]
this is working with version 1.0 of this plugin and latest WooCommerce3
