### ISSUE TITLE
Error "Value must be less than or equal to 0. Qty" in Shopping Cart

### ISSUE THREAD

**Issue by ArchCarrier** [hyyan/woo-poly-integration#11]
I'm getting an error "Value must be less than or equal to 0. Qty" when I click 'Proceed to checkout' in the Shopping Cart (Basket) view. The error isn't there when WooPoly is disabled.
I'm not able to check if the problem lies with your plugin or with Polylang, since I get an almost blank page when I disable Polylang too.

**Comment by Jon007** [comment]
Closing this is from 2015 as outdated, please re-raise if open on a current version
