### ISSUE TITLE
Sku meta is being sync for Product Variations regardless of the SKU meta setting

### ISSUE THREAD

**Issue by decarvalhoaa** [hyyan/woo-poly-integration#113]
Regardless of the SKU setting in Admin -> WooPoly -> Meta List in the General Metas section, the SKU meta is always sync. 

My personal, expectation for this setting is that, once it it disable both the SKU for the Variable Product and respective Variations Products are not sync.

@hyyan -> Can you please clarify if the synchronization should be skipped for Product Variations if the SKU setting is disabled?

**Comment by hyyan** [comment]
@decarvalhoaa , yes this the correct behavior,  if this is not working like this,  then it is a bug

**Comment by decarvalhoaa** [comment]
Ok. I will fix this.

**Comment by decarvalhoaa** [comment]
Fixed via [b7eb489](https://github.com/hyyan/woo-poly-integration/commit/b7eb489bdab0d6736901700a1a66d735ebcc0e05).
