### ISSUE TITLE
Product variations options are not translated after WC upgrade to 2.6.13

### ISSUE THREAD

**Issue by 4ADSTUDIO** [hyyan/woo-poly-integration#119]
Everything was ok I had variations with their options translated but after upgrade I can see translation on backend but I can't see it on the front of shop.

**Comment by 4ADSTUDIO** [comment]
Still cant get option of my attributes to be translated. As you can see it stay Polish.

![zrzut ekranu 2017-02-22 o 09 04 50](https://cloud.githubusercontent.com/assets/25066778/23202517/94defee6-f8de-11e6-9be0-4c6ffdd8f682.png)

**Comment by Jon007** [comment]
I can't reproduce the problem, did you find a solution?

- You say you can see the attributes under Products/Attributes?
- You have translated the attributes under Languages, String Translations?
- Under Languages, Settings, Custom post types and Taxonomies, your attributes appear under  Custom taxonomies and are checked? 
- you have translated the Terms under configure terms on the attribute name?

**Comment by Jon007** [comment]
If you try with wooCommerce 3 and version 1.0 of this plugin, there are now more options for controlling attribute translation:

- Individual Product Attributes translation by enabling in woo-poly and controlling in Polying settings, see https://github.com/hyyan/woo-poly-integration/wiki/Settings---Features
- custom product attribute value translation can also be controlled as per: https://github.com/hyyan/woo-poly-integration/wiki/Settings-Metas
