### ISSUE TITLE
Unable to translate tax names, eg VAT.

### ISSUE THREAD

**Issue by henrilindeberg** [hyyan/woo-poly-integration#122]
Unable to translate tax names, eg VAT.
Maybe this can be added to String translation?

**Comment by Jon007** [comment]
Yes probably, I'm closing this as it is a duplicate of issue #59 Translate woocommerce tax name, please add any further thoughts/requirements there.

Note I have started work on #104 about the price display suffix, this would be eg '+VAT' after the price name which [soon] we will be able to translate to eg: 'mas IVA' in Spanish etc.
