### ISSUE TITLE
deactivate meta synchronisation 

### ISSUE THREAD

**Issue by tolima** [hyyan/woo-poly-integration#13]
Hi,
If I deselect all checkbox of a group (general, stock etc) of Meta list (in WooPoly Advanced Options) all the check box are reseted and re-checked.
Is there a way to deactivate meta synchronisation ?

**Comment by b-alidra** [comment]
Up

**Comment by tolima** [comment]
In src/Hyyan/WPI/Product/Product.php, function __construct()
comment new Meta();
to deactivate all syncronisation
It's not the solution but it work.

**Comment by b-alidra** [comment]
@tolima Thx

**Comment by hyyan** [comment]
It is part of the plugin job to sync meta , but you can control meta from the plugin options page , working perfectly with v0.27

**Comment by tolima** [comment]
> It is part of the plugin job to sync meta 

yes but if we don't want this part of the plugin ? Or if we don't want it on a whole group (general, stock etc) ?
I have the same problem with 0.28

**Comment by decarvalhoaa** [comment]
I did a few tests and notice that indeed, if one unchecked the settings of an entire Group, after pressing Saving Changes, the settings boxes get re-checked. Apparently, if you only uncheck a few options, it gets saved ok. Still need to test if the fact they are unchecked really takes effect.

On this basis, I would say it is a valid bug.

Also, I would agree that it would be nice to have a button to uncheck/check an entire Group. This would be a feature enhancement.

If I find a little bit of time, I will try to fix it and propose a solution to Hyyan. Unfortunately, I have quite a lot of work right now, and can really promise a date.

**Comment by Jon007** [comment]
Closing - I can't replicate this on current versions.
According to change log, there was a related fix on Issue #51 in version 0.29
