### ISSUE TITLE
'Internal error' after checking out

### ISSUE THREAD

**Issue by SillyMe727** [hyyan/woo-poly-integration#133]
I absolutely love your Plugin, thank you so much for creating it.
After the update to Woocommerce 3.0.1 I am receiving an 'Internal error' after checking out. When I disable Polylang and all its Plugins, the error is gone, but my German customers can't check out in german.
They should receive a 'order received' and an option to download their PDF files immediately, but instead they see the 'Internal error'.
I am a noob when it comes to all this, is anyone able to help me out? 
Will the plugin get updated to be compatible with the new WC?

Any help is appreciated, thank you.

**Comment by dgulias** [comment]
Same problem with me. "Internal Error" - but the sell happens on backend, The costumer after try to chekout doesnt change to Success page so everytime it tries to Finish the Order clicking on the button, they get a Internal Erros and my shop get a new order. If he clicks 4 times i'll recieve 4 new orders from him.

Thank you.

**Comment by SillyMe727** [comment]
Yes, same here. I had a customer pay 3 times and all the payments went through, ut she could not download her patterns. It is very frustrating as a small business that depends on excellent customer service. I have been writing many apology emails daily to customers who don't receive their patterns. I am hoping for a fix soon, as I can't see an alternative to this plugin at the moment.

**Comment by theleemon** [comment]
Apparently, you can install 2.6.14 back. I haven't tried it, though:

https://woocommerce.wordpress.com/2017/04/04/say-hello-to-woocommerce-3-0-bionic-butterfly/#comment-2760

Maybe this is the best solution while an update compatible with 3.0 arrives.

**Comment by SillyMe727** [comment]
Thank you, theleemon. I had done that, but customers still had trouble checking out then, so I installed the new WC again. Nothing I do seems to work. It is very frustrating.

**Comment by Jon007** [comment]
Based on current progress, it will be some weeks or months before this component works with WC3.x.
In the meantime there is no point continuing to try to re-install the new version.

As WooCommerce advised in their release notices and banners:

> 3.0 is a major update. It is important that you make backups and ensure themes and extensions are 3.0 compatible before upgrading.

You must check components are updated before upgrading a production system, and until then you must not upgrade.

**Comment by SillyMe727** [comment]
Since all my customers received a 403 error when trying to download their files today, I did revert to WC 2.6.14 again and now I receive the following error: "Hyyan WooCommerce Polylang Integration Plugin

The plugin can not function correctly , the plugin requires WooCommerce and Polylang plugins"
I am at a loss. It dies not work now either. What can I do?

**Comment by Jon007** [comment]
the plugin returns this error when one of either wooCommerce or Polylang is not activated.

I suggest:

1. deactivate all the plugins
1. reactivate Polylang
1. reactivate wooCommerce
1. reactivate Hyyan WooCommerce Polylang Integration

if it's still not working, check the woocommerce status page:
/wp-admin/admin.php?page=wc-status

also in your circumstances, consider turning on WP_DEBUG in your wp-config.php so you can see any further error messages which may appear:
// Enable WP_DEBUG mode
define( 'WP_DEBUG', true );

**Comment by SillyMe727** [comment]
Thank you, Jon. I restored everything to a previous backup and it seems to work now. Fingers crossed.

**Comment by Jon007** [comment]
Yes, actually restoring from backup may be even better solution, we should  just suggest that first.
