### ISSUE TITLE
Some strings are not translated

### ISSUE THREAD

**Issue by mathew07** [hyyan/woo-poly-integration#134]
Hey, 

first of all - thank you for awesome plugin! :) 

I have issue with translating some strings in woocommerce - mostly errors and messages but also "search products" or "read more". I tried to translate them using function but unfortunatelly it doesn't work. My code is:
```
add_filter('gettext', 'translate_text3');
add_filter('ngettext', 'translate_text3');
function translate_text3($translated) {
		if ( pll_current_language() == 'ru' ) {
			$translated = str_ireplace('View Cart', 'ten', $translated);   
	}
		else { 
			$translated = str_ireplace('View Cart', 'inny', $translated);
	}
return $translated;
}
```
if I remove row 
`if ( pll_current_language() == 'ru' ) {`
function is working but it's translating strings for all languages. I need language condition here. Any ideas how to achieve that? 

Thanks in advance :)

**Comment by Jon007** [comment]
Hi, It's not clear exactly what you are trying to do and why, but standard plugin strings like "View Cart" are translated by standard .po files, which can you customize eg with Loco Translate.

The file /wp-content/plugins/woocommerce/i18n/languages/woocommerce.pot is the template with the strings such as 'View Cart' and WordPress will normally download the translation files to /wp-content/plugins/woocommerce/i18n/languages. 

So it's not part of this plugin, it's part of wooCommerce itself, so please close from here thanks.
