### ISSUE TITLE
Variable product stock sync

### ISSUE THREAD

**Issue by scandiske** [hyyan/woo-poly-integration#136]
Hi and thanks for the plugin!
I have a problem with stock sync on a variable product.
If i buy 1 piece in one language the translation stock decreases by 2.

Any ideas on how to solve this issue?

**Comment by Jon007** [comment]
Can I confirm please the precise conditions you are experiencing?

According to testing on latest code, when purchasing 1 variable item:

-  when stock level is set on each variation, it decreases by 1 correctly
-  however when stock level is set on the parent only, it decreases by 1 in purchased language but by 2 in original language.

This is certainly odd but setting the stock at the variation level might be a good workaround..

**Comment by Jon007** [comment]
Hi, I tested this fix in dev and will included in the next pull request with woo3 support:
stock.php l.137
```
            /* Handle variation stock UNLESS stock is managed on the parent
						 */
            if (($isVariation) && !($isManageStock)) {

```

**Comment by scandiske** [comment]
Thank you!
The change in the code worked perfectly!
