### ISSUE TITLE
Support Message/Flash message often appears in backend

### ISSUE THREAD

**Issue by ibes** [hyyan/woo-poly-integration#14]
Hi there,

since I activated you plugin (thanks for sharing it!) I often see the message in the backend that will be displayed by
getView('Messages/support')

That sucks as I can't click it away and silence it.
I guess this is not how you planed it and maybe there is a bug at your or my end. 

Could you please have a check?

Sebastian

**Comment by hyyan** [comment]
The message appear only once for user when the plugin is activated
