### ISSUE TITLE
Emails translations issues

### ISSUE THREAD

**Issue by dgulias** [hyyan/woo-poly-integration#142]
Hello,

The pull request is great i just see some emails translations issues with Bank Transfer payment method:

My Website have 3 languages: Portuguese PT (main language), Spanish, English UK.

• When I add an "order note" the "email Subject" and the "email content tittle" of the order note is not translated (in portuguese main language). But the content is translated. It happened if English order and Spanish order.

• When i Canceled these test orders (for each language) the Canceled email had translated problems example:

**Canceled spanish email:**

"email Subject" and the "email content tittle" of the Canceled email is not translated (in portuguese main language)

"first phrase content (before payment info)" **NOT** ok - in Portuguese (main language)

"payment informations"  **NOT** ok - in Portuguese (main language)

**Calceled english email:**

"email Subject" and the "email content tittle" of the Canceled email is not translated (in portuguese main language)

"first phrase content (before payment info)" **NOT** ok - in Portuguese (main language)

"payment informations" **NOT** ok - in Portuguese (main language)

Best regards

EDIT: fix some comments.

**Comment by Jon007** [comment]
Hi, I am just looking at this. 

Can you confirm please:

- have you modified the Email subject/heading under WooCommerce, Settings?
 - if so, have you also checked Languages, Strings Translations, WooCommerce Emails?

**Comment by Jon007** [comment]
Also please confirm, did this work for you before the WooCommerce3.0 upgrade?  
as there are some related issues #70 and #89

**Comment by Jon007** [comment]
Hi,

Please note:   New Order, Cancelled Order and Failed order are email which are sent to the shop owner, not the customer, so they do not need to be translated and Cancel Order translation was never implemented.

Actually I have added the translation for Cancelled Order in my Dev in any case since:  

1. it seems to cause some confusion that some of the emails are not translated
2. as a shop owner I like to be reminded that I am dealing with a customer in a different language.

**Comment by dgulias** [comment]
I think the only issue i saw in older versions was the "content tittle not translated" I dont remember another issue.

My tests was selling to myself (in 3 different languages) so i could see the admin email and customer email.


About the Email subject/heading changes. I never did that. I preffer to keep the default configurations. Do i need to do something in the email configurations?

**Comment by Jon007** [comment]
No it's not necessary to customize, it's just that if you do customize you need to check the String Translation table.  
Check anyway in Languages, Strings Translations, WooCommerce Emails, set the Polylang translation filter at the top to Show All Languages and check for missing translations.

(I know you are running in Portuguese, sorry I will refer to the English names for the menus etc).

I can't find anything wrong with order note, please check again and provide more detail if you think there is an issue.

I have implemented translation of Cancelled order and will reference this issue when I check it in.

**Comment by dgulias** [comment]
Yes. If i change the top language tab inside the email admin page, nothing change. Still in Portuguese (main language). Do i need to change manually?

**Comment by dgulias** [comment]
It was in the Cancelled email page.

**Comment by Jon007** [comment]
sorry, I don't understand what you mean

**Comment by Jon007** [comment]
Cancelled email translation is:

a) not necessary because this is the email to the shop owner who should be able to deal with receiving messages in the shop language
b) I implemented anyway but only on my local machine.  
When I check the code in, a message will appear on this issue so you know.

**Comment by dgulias** [comment]
About the note. Was everything translated, except the "Content Tittle" and the "Email Subject Title". Still Portuguese (main language)

Different from the "Cancelled Page" that all the content is not translated. Everything Portuguese (main language).

**Comment by dgulias** [comment]
Ok. Now i understand. I didnt realise that Cancelled doesnt go to Customer. hahah
You are right. So the only problem is the note email. 

Sorry for my mistake.

**Comment by Jon007** [comment]
Oh you are talking about the note email, I don't see any problem with that, can you be more explicit?

**Comment by dgulias** [comment]
Can you give your email? I'll sent you those emails so you can see.

Im not worry about Admin notice emails. My main worry is just about the customer emails not translated. 

The only problem i can see now, after some new testes is:

• Admin Note Email (for the customer) - the "Content Tittle" and the "Email Subject Title" is not tranlated. Still Portuguese (main language)

• Order Processing Email - same problem, the "Content Tittle" and the "Email Subject Title" is not tranlated. Still Portuguese (main language) 

The content of those emails were translated fine.

**Comment by Jon007** [comment]
I don't need to see those emails, it's the configuration of your system.
Need to check what you have under Languages, Strings Translations:
/wp-admin/admin.php?page=mlang_strings&s&group=WooCommerce+Emails&paged=1

**Comment by dgulias** [comment]
Well, in the Language, Strings Translations i dont have those emails strings to translate. I have other things like chackout fields, basic page information fields, somethnig like that.

Sorry if i doens understand your question.

**Comment by Jon007** [comment]
What do you have under Settings, WooPoly, Emails? This should be checked.
Can you try the latest version from https://github.com/Jon007/woo-poly-integration?
I've check and tested all the email stuff fairly carefully and It's all working for me.

Added translation management for:
* On Hold Order Email
* Cancelled Order Email
* Failed Order Email
* Recipient [ie Shop] email for New/Cancel/Failed emails
* Footer test, From name and From address on all emails 

Order notes was already working though, if you've found some special case you are sure it is not working then I need a lot more details of exactly what you did to try to reproduce or understand which step is wrong

**Comment by dgulias** [comment]
Hello again. I Tested. I think is everything ok, including the order email foot translating, except for the "Processing", "Conclusion" and "Note" email that i said before.

Everything is translated, except the "Email Subject"and the "big tittle inside de email".

I notice one thing. The Automatic "New Order" email came translated very well. If a go to Admin Order Page e resend this New Order Email by the "Order Acctions Menu Widget" (sorry dont now english name), the email go to the customer Not Translated.

Maybe The Problem happens when i do it manualy from the Admin Order Page. I dont know.



Other Thing I Notice is: I use a Portuguese Payment Gatway (Ifthanpay for Multibanco Payments) that only Wordk with Portuguese Bank. This plugin is automatic and have a good Callback - only works. When we pay the refference number generated by the plugin and Multibanco System - a Callback action send an automatic Processing email to customer and change the order status to Processing.

If I make an new order in another language (tested with english), and Pay the reffference numbers, i reciev the Payment information from the Multibanco system (because the reference was paid) but the Callback not happens. No email sent and no status sent. So i did a new order with Portuguese language and paid it. The result was: Everything Works fine. Email and Status Changing. 


******* Probably this will goning to be a difficult thing to prevent with this plugin because envolve another plugin, but i dont know whay Callback doesnt works with orde in another language.

This is the Gatway pluging: https://www.webdados.pt/produtos-e-servicos/internet/desenvolvimento-wordpress/multibanco-ifthen-software-gateway-woocommerce-wordpress/

**Comment by dgulias** [comment]
*This plugin is automatic and have a good Callback - always works

fix comment

**Comment by Jon007** [comment]
- for Multibanco please open that as a completely separate issue, also please confirm behaviour with wooCommerce 2.6, and Hyyan WooCommerce Polylang integration 0.26

 - I cant understand the other points you have, for example:
"If a go to Admin Order Page e resend this New Order Email by the "Order Acctions Menu Widget" (sorry ddont now english name), the email go to the customer Not Translated."
The New Order email always goes to the admin address, not the customer, and it is translated.

If it's not translated that means the system is not finding the translation maybe there is an issue with your language files, try customizing the headings in woocommerce settings and then translating them in polying strings translation table.

**Comment by dgulias** [comment]
Ok. Thank you for your attention. 

Best Regards.
