### ISSUE TITLE
Variation "Save changes" button does not trigger variation synchronization 

### ISSUE THREAD

**Issue by Jon007** [hyyan/woo-poly-integration#146]
The Variations tab in Product Data has a "Save changes" button.
This button does an ajax call to save changes on the current product but does NOT currently trigger a synchronization to update translations.

When you press the Update button to save the product, the translations are synchronized at that point.  If you do not press the Update button, the translations will be left in an invalid (unsynchronized) state and continue to show the previous values.

**Comment by Jon007** [comment]
to do this, check admin ajax for Save attributes and Save variations in woocommerce/includes/class-wc-ajax.php

```
public static function save_attributes() {
...
    $product->save();
...
public static function save_variations() {
....
    WC_Meta_Box_Product_Data::save_variations( $product_id, get_post( $product_id ) );

    do_action( 'woocommerce_ajax_save_product_variations', $product_id );

```

**Comment by Jon007** [comment]
@hyyan  Actually I kind of decided not to fix this and I'll explain why:

* The Save on the Attributes panel is an intermediate step to allow you to be able to create the variations.
* The Save on the Variations similarly, just to save the variation you are working on, it doesn't mean you have finished editing the product.

In my view, the error or wrong behaviour is with WooCommerce, WooCommerce should not save these intermediate edit steps to the published product version and we should not synchronise these intermediate edit steps.

Really, only when you completely finish editing the product then you press Save on the Product to really Save the changes, and synchronize the translations.

**Comment by hyyan** [comment]
@Jon007 I see the point now, Ok, I will leave it open to do further testing myself

**Comment by Jon007** [comment]
In the circumstances, and after 2 years of due deliberation, this should be closed as "by design"
