### ISSUE TITLE
Attribute Terms are no synced 

### ISSUE THREAD

**Issue by hyyan** [hyyan/woo-poly-integration#159]
#### What product versions and settings are you using when this issue occurs?
* PHP:  5.6
* WordPress:  4.7
* WooCommerce: 3.0.6
* Polylang: 2.1.3
* Hyyan WooCommerce Polylang Integration: master
* Browser: all

#### Steps to Reproduce
* create new attribute
* add terms to attribute
* create product and choose attribute and termns
* create translation for previous product

#### What I Expected

Terms of the translated products to be synced from the main product

#### What Happened Instead

Attributes are synced , but terms are not

**Comment by Jon007** [comment]
You mean without translating the attribute?

Yes this is fixed quite nicely in my branch:
https://github.com/Jon007/woo-poly-integration/tree/taxnomy-and-product-attributes-enhance

.. but I had to take a break from testing for other tasks....  will finish testing/debugging on variation products next week.

**Comment by hyyan** [comment]
@Jon007 Sounds great, thanks
You are contributor to this project and you do have access to create a new branch directly in the project repo ,
I think it will better that way so I can review your code and contribute too  😄

**Comment by Jon007** [comment]
This is working in 1.0, let's open new issue if there is any specific issue remaining.
