### ISSUE TITLE
Stop Woocommerce Version Check

### ISSUE THREAD

**Issue by hyyan** [hyyan/woo-poly-integration#161]
The plugin must not check for major woocomerce versions . The code must be light as much as possible
After all we do not expect woopoly 1.0.0 to work with woocomerce 2.6 , it is a major update.

Versions check must be for minor changes only in woocommerce and polylang

**Comment by Jon007** [comment]
Tricky decision:

Ideally the first woo3 release should be compatible with both woocommerce 2.6 and woocommerce 3.0 for the convenience of users during their transition period, though it's certainly adding complexity to the code and testing.
As a user myself, my production is up to date with all components except wooCommerce3 and I would be annoyed if the plugins started releasing woo3 only versions.

Should v1 refuse to activate if wooCommerce >3.0 is not detected?
- ie add check for woocommerce3 in `canActivate()` and update activateError.php to indicate dependency on wooCommerce3 or higher ?


At the moment:

- the updates for woo3 should work as well or better with woocommerce 2.6 than the current 0.26 version. 
- New fixes and enhancements are applied to v3 only, leaving execution of old unfixed code for v2.6.

**Comment by hyyan** [comment]
@Jon007 I got your Idea, The last version which supports woo v2.6 will be woopoly v0.29 , the new version must support woo v3.0 only with no support for the old version, and I think this way makes sense. and it is easier to test.
if we need to support users who use woo2.6 or fix some old bugs we can still patch the version 0.29 , these patch versions will be available throw WordPress repo too then users can switch to old version of this plugin using [wp-rollback](https://wordpress.org/plugins/wp-rollback/)

WooPoly 1.0.0 and later versions will handle this type of checks clearly upon activationt , I am already working on a solution for this. for now we must stop the check for Woo3.0 in our new code . we check only for minor changes in Woo3.0 and Polylang 2.0

**Comment by Jon007** [comment]
ok, understood, let's keep a separate branch for 0.29 patches.
Actually there are some in my previous RC which apply to 0.29, but really we need to focus limited available time on moving forward.

Noting WooCommerce 3.0.7 now out, should update the minimum version:  there is no point supporting 3.0.1-3.0.6, only the latest version.
