### ISSUE TITLE
Stock doesn't decrease after selling one variation of a variable product

### ISSUE THREAD

**Issue by Wiloud** [hyyan/woo-poly-integration#162]
Hi there and thanks for your plugin !

Here is the description of an issue I'm experiencing :

#### Can you reproduce this issue on default Wordpress theme (eg Storefront)?

Yes.

#### Can you reproduce this issue when all other plugins are disabled except WooCommerce, Polylang and Hyyan WooCommerce Polylang Integration?

Yes.

#### What product versions and settings are you using when this issue occurs?
* PHP: 5.6.30
* WordPress: 4.7.4
* WooCommerce: 3.0.6
* Polylang: 2.13
* Hyyan WooCommerce Polylang Integration: 0.29.1
* Browser: Chrome (58.0.3029.96)

#### Steps to Reproduce

1. Check the stock in a variable product
2. Go to the variable product in shop
3. Buy the variable product
4. Check the stock in variable product which didn't decrease

#### What I Expected

I expected the stock to decrease itself from 1 item when the user buy 1 item.

#### What Happened Instead

The stock didn't decrease.

**Comment by hyyan** [comment]
Hey @Wiloud  , please note the version 0.29.1 doesn't work with WooCommerce: 3.0.6 , try the to download the plugin from the [master branch ](https://github.com/hyyan/woo-poly-integration) , it contians the latest updates to support WooCommerce: 3.0.6.

The new version will be released soon in the wordpress repo

**Comment by Wiloud** [comment]
Hey @hyyan , thanks a lot for this quick answer.
It worked !

Best !
Wil
