### ISSUE TITLE
No string translation for the content of Emails

### ISSUE THREAD

**Issue by nouinouhamza** [hyyan/woo-poly-integration#163]
#### Can you reproduce this issue on default Wordpress theme (eg Storefront)?
Probably, I'm working with a fresh Wordpress Installation with Twenty Seventeen 

#### Can you reproduce this issue when all other plugins are disabled except WooCommerce, Polylang and Hyyan WooCommerce Polylang Integration?
Yes, this is tested in a fresh website
See video here : https://youtu.be/JkQ8fnrBSnU

#### What product versions and settings are you using when this issue occurs?
* PHP: 
* WordPress:  4.7.5 
* WooCommerce: 3.0.7
* Polylang: 2.1.4 
* Hyyan WooCommerce Polylang Integration: 
* Browser: firefox

#### Steps to Reproduce
1. Install WordPress with plugins
2. Add languages in poly and modify the emails
3. check the Strings translation

#### What I Expected
Can translate the Strings in the email content

#### What Happened Instead
I can only translate the heading and the subject of the email

Is there another way to translate the content of the email ?

**Comment by Jon007** [comment]
You need to say which version of WooCommerce Polylang Integration you are using, however actually the answer will be the same in all cases.

WooCommerce Polylang Integration covers the strings that are user editable under WooCommerce, Setttings, Emails - and the products.

The standard strings in the email template are translated by the WooCommerce language files, so if they are not translated then you maybe don't have the language files downloaded.


Of course if you write a completely custom template it's up to you whether you implement translation via language files or Polylang strings translation...
