### ISSUE TITLE
Up Sells and Cross Sells do not display the translated product

### ISSUE THREAD

**Issue by damiencarbery** [hyyan/woo-poly-integration#165]
Unfortunately Polylang or Woo Poly Integration cannot present the translated up-sells or cross-sells as it requires modifying two template files (cart/cross-sells.php and single-product/up-sells.php).

I have submitted two PR to WooCommerce to add apply_filters() calls to both of these template files and submitted an issue to reference the two PR.
Issue:
https://github.com/woocommerce/woocommerce/issues/15188
PRs:
https://github.com/woocommerce/woocommerce/pull/15174
https://github.com/woocommerce/woocommerce/pull/15175

This is not a bug in Polylang or Woo Poly Integration but, if it gets fixed, it will need changes to this plugin to make use of the change. Also, if you are friends with the WooCommerce developers you could encourage them to accept the PRs or make similar changes.

Here is the code I used when I made the changes on my test installation:

    add_filter( 'woocommerce_cart_up_sells_post_id', 'dsh_polylang_translate_product_id' );
    add_filter( 'woocommerce_cart_cross_sells_post_id', 'dsh_polylang_translate_product_id' );

    function dsh_polylang_translate_product_id( $related_product_id ) {
      if ( function_exists( 'pll_get_post' ) ) {
        return pll_get_post( $related_product_id );
      }
      return $related_product_id;
    }

**Comment by Jon007** [comment]
I use this feature and it works fine.   
Which versions of WooCommerce and this plugin are you using?

It's true that in the admin view, you see the original version not the translated version, but this area should normally be locked and non-editable, and can be safely ignored.

When you switch to view the product, then you see the correct language products.

**Comment by damiencarbery** [comment]
WooCommerce 3.0.7, Polylang 2.1.4 and Woo Poly Integration 1.0.0 (I downloaded from master branch a few days ago - to fix a 500 error on checkout).

Admin has original English products in Up-sells and Cross-sells (for both English and German versions of the product).
Prior to my change to the two template files the English up/cross-sells products were displayed when viewing German products.

I don't see any reference to up/cross sells in this plugin's source code, apart from the meta keys that it must copy when creating the translated product.

Of course, now that I think about it, maybe the up/cross-sells of the German product should be updated to point to German products instead of being left pointing to English products.

**Comment by Jon007** [comment]
ok Woo Poly Integration 1.0.0 is an unreleased version so thanks for helping test it..

what used to happen is:
 - in Admin the upsells and cross-sells show in site primary language (eg English) but *this is not a problem* 
- when viewing as a customer, the upsells and cross-sells are shown in the current display language (so no problem)

I check further in case there is any bug introduced due to all the recent changes.

**Comment by Jon007** [comment]
right, the code for example in wooCommerce 2.6 template upsells.php used to do this which is all now removed:

```
global $product, $woocommerce_loop;

if ( ! $upsells = $product->get_upsells() ) {
	return;
}

$args = array(
	'post_type'           => 'product',
	'ignore_sticky_posts' => 1,
	'no_found_rows'       => 1,
	'posts_per_page'      => $posts_per_page,
	'orderby'             => $orderby,
	'post__in'            => $upsells,
	'post__not_in'        => array( $product->id ),
	'meta_query'          => WC()->query->get_meta_query()
);

$products                    = new WP_Query( $args );
$woocommerce_loop['name']    = 'up-sells';
$woocommerce_loop['columns'] = apply_filters( 'woocommerce_up_sells_columns', $columns );
```

The get_upsells() had opportunity to filter and Polylang I think also filters WP_Query, but now get_upsells() is deprecated...

Now the content-single-product.php hooks woocommerce_upsell_display() which does
```
		// Get visble upsells then sort them at random, then limit result set.
		$upsells = wc_products_array_orderby( array_filter( array_map( 'wc_get_product', $product->get_upsell_ids() ), 'wc_products_array_filter_visible' ), $orderby, $order );
```
(and cross-sells similarly).

Potentially a generically useful place for filter extension would be wc_products_array_filter_visible itself.  

there is also a filter opportunity here:
```
	// Allow 3rd party plugin filter template file from their plugin.
	$located = apply_filters( 'wc_get_template', $located, $template_name, $args, $template_path, $default_path );

```
so the plugin can intercept here.

This is called with:
```
		wc_get_template( 'single-product/up-sells.php', array(
			'upsells' => $upsells,

			// Not used now, but used in previous version of up-sells.php.
			'posts_per_page' => $limit,
			'orderby'        => $orderby,
			'columns'        => $columns,
		) );

```
So here the plugin could catch it and filter the $upsells.

Or, earlier in the chain:
```
	/**
	 * Get upsel IDs.
	 *
	 * @since 3.0.0
	 * @param  string $context
	 * @return array
	 */
	public function get_upsell_ids( $context = 'view' ) {
		return $this->get_prop( 'upsell_ids', $context );
	}

	/**
	 * Get cross sell IDs.
	 *
	 * @since 3.0.0
	 * @param  string $context
	 * @return array
	 */
	public function get_cross_sell_ids( $context = 'view' ) {
		return $this->get_prop( 'cross_sell_ids', $context );
	}
```

The get_prop itself has a filter hook for view context:

`				$value = apply_filters( $this->get_hook_prefix() . $prop, $value, $this );
`
which produces a filter string such as:
"woocommerce_product_get_upsell_ids"

so we could hook this and do a language filter on the upsell ids..
Since this only affects the view context, the admin UI should remain unaffected.

**Comment by Jon007** [comment]
sample implementation eg in woo-poly, Product.php
in constructor:
```
        add_filter('woocommerce_product_get_upsell_ids', array($this, 'getUpsellsInLanguage'), 10, 2);
        add_filter('woocommerce_product_get_cross_sell_ids', array($this, 'getCrosssellsInLanguage'), 10, 2);
```
and then the functions:
```
    /**
     * filter upsells display
     *
     * @param array      $related_ids array of product ids
     * @param WC_Product $product current product
     *
     * @return array filtered result
     */
    function getUpsellsInLanguage($relatedIds, $product)
    {
        return $this->getProductIdsInLanguage($relatedIds, $product);
    }
    /**
     * filter Cross-sells display
     *
     * @param array      $related_ids array of product ids
     * @param WC_Product $product current product
     *
     * @return array filtered result
     */
    function getCrosssellsInLanguage($relatedIds, $product)
    {
        return $this->getProductIdsInLanguage($relatedIds, $product);
    }
    /**
     * filter product ids
     *
     * @param array      $product_ids array of product ids
     * @param WC_Product $product current product
     *
     * @return array filtered result
     */
    function getProductIdsInLanguage($productIds, $product)
    {
        $productLang = pll_get_post_language($product->get_id());
        $mappedIds = array();
        foreach ($productIds as $productId){
            $correctLanguageId = pll_get_post($productId, $productLang);
            if ($correctLanguageId){
                $mappedIds[]=$correctLanguageId;
            }else{
                //what do you want to do if product not available in current display language?
                //allow the available product language to be returned
                $mappedIds[]=$productId;
            }
        }
        return $mappedIds;
    }

```

...  works for me so far, I'll merge it in later ...

**Comment by damiencarbery** [comment]
Wow, you've done a lot of work because of a mistake by my client.

My client translated the product name and description but did not change the up-sells or cross-sells to the equivalent translated products. If they had done that then I would not have investigated the situation.

I don't fully understand your code as the plugin is very new to me.
Will it work when the up/cross-sell is for the translated product?

Thanks for your detailed comments and all the work.

**Comment by Jon007** [comment]
If synchronization is on they don't need to change the up-sells or cross-sells, the system should handle this, however there were changes in wooCommerce 3.0 (which is not yet supported by a release version of this plugin).

So this is now handled with the latest pull request.

**Comment by Jon007** [comment]
Also @damiencarbery please cancel your related requests to the WooCommerce team for this, I'm sure they have lots of other issues to attend to!

I actually developed two different solutions for this without requiring any changes in WooCommerce.

**Comment by damiencarbery** [comment]
I have closed https://github.com/woocommerce/woocommerce/issues/15188
