### ISSUE TITLE
Documentation improvements / wiki

### ISSUE THREAD

**Issue by Jon007** [hyyan/woo-poly-integration#166]
For wiki / documentation improvements, how about:
- [ ] create wiki folder in the root
- [ ] add wiki folder to .gitattributes as /wiki export-ignore  so it is not part of the distribution
- [ ] add index.md and other markdown files

@hyyan   I'd like to do this now so I can include reference to the wiki location in the notes on the settings pages on the next pull request.   does this sound ok??

**Comment by hyyan** [comment]
@Jon007 Sounds Perfect

**Comment by Jon007** [comment]
closing as wiki is created - wiki will always need more improvement but we don't need to keep issue open for that
