### ISSUE TITLE
Different styles per language

### ISSUE THREAD

**Issue by diegocmartin** [hyyan/woo-poly-integration#17]
Hi,
My store is loading different Woocommerce styles per laguage. It can be seen here:
http://on-timeshop.com/es/product-category/rolex-es/
If you change the language you'll see a different button on the product.
Can you help me to call to the correct css?
Thanks a lot,
Diego

**Comment by hyyan** [comment]
Check [Polylang API](https://polylang.wordpress.com/documentation/documentation-for-developers/functions-reference/)

**pll_current_language**

Returns the current language
Usage:

```php
pll_current_language($value);
````

- ‘$value’ => (optional) either ‘name’ or ‘locale’ or ‘slug’, defaults to ‘slug’


returns either the full name, or the WordPress locale (just as the WordPress core function ‘get_locale’ or the slug ( 2-letters code) of the current language.
