### ISSUE TITLE
woo poly integration and cart page

### ISSUE THREAD

**Issue by mupamupa** [hyyan/woo-poly-integration#171]
Hello, the submitted code works beautifully. One thing though, the cart page tends to be in the default language. Is there a way to make it also dynamic in accordance with the language?
Thanks a lot for your time and great work!

#### What product versions and settings are you using when this issue occurs?
* PHP: 
* WordPress: 
* WooCommerce: 
* Polylang: 
* Hyyan WooCommerce Polylang Integration: 
* Browser: 

#### Steps to Reproduce
1. 
1. 
1.

**Comment by mupamupa** [comment]
А brief update for the record:
The current woo-polly plugin is here 
https://github.com/hyyan/woo-poly-integration/tree/product-taxnomy-attributes-dev
and it works like a charm. Thanks for all contributors.
Chears

**Comment by Jon007** [comment]
thanks for the update,
the branch you mentioned is now merged and release as version 1.0 so you can refer to the standard release now
