### ISSUE TITLE
Notice: WC_Shipping_Zone::get_zone_id is deprecated version 3.0 ! 

### ISSUE THREAD

**Issue by jstei** [hyyan/woo-poly-integration#172]
Notice says : Use WC_Shipping_Zone::get_id instead

#### Can you reproduce this issue on default Wordpress theme (eg Storefront)?
Yes
#### Can you reproduce this issue when all other plugins are disabled except WooCommerce, Polylang and Hyyan WooCommerce Polylang Integration?
Yes
#### What product versions and settings are you using when this issue occurs?
* PHP: 7.1.1
* WordPress: 4.7.5
* WooCommerce: 3.0.7
* Polylang: 2.1.5
* Hyyan WooCommerce Polylang Integration: 0.29.1
* Browser: FireFox 53.0.3

#### Steps to Reproduce
1. Install
1. 
1. 

#### What I Expected
No warning notice

**Comment by Jon007** [comment]
Hyyan WooCommerce Polylang Integration: 0.29.1 is not compatible with WooCommerce 3.x, you need to use Hyyan WooCommerce Polylang Integration version 1.0
