### ISSUE TITLE
Fatal error: Using $this when not in object context

### ISSUE THREAD

**Issue by auching** [hyyan/woo-poly-integration#174]
Got below error when I try to add a Chinese copy of a published product (by pressing '+' sign in the product edit page)

**Fatal error: Using $this when not in object context in /public_html/wp-content/plugins/woo-poly-integration/src/Hyyan/WPI/Product/Meta.php on line 372**

* PHP: 5.6.30
* WordPress: 4.7.5
* WooCommerce: 3.0.7
* Polylang: 2.1.5
* Hyyan WooCommerce Polylang Integration: 1.0.0
* Browser: Chrome Version 58.0.3029.110 (64-bit)

**Comment by Jon007** [comment]
ok, this bug occurs when you have not translated the parent categories.

Ideally you should translate all the Categories, Tags and applicable product Attributes before translating the product.  

In this version the code is filling in missing translations for Categories/Tags/Attributes by copying the source language, in this case an error has crept in when trying to also fill in the missing parent category translation.   
If you translate the categories first you won't get this error.
