### ISSUE TITLE
Polylang URL modifications method The language is set from content is not supported yet

### ISSUE THREAD

**Issue by Jon007** [hyyan/woo-poly-integration#176]
The readme includes comment:

> Polylang URL modifications method The language is set from content is not supported yet

Is this still the case?

**Comment by hyyan** [comment]
@Jon007 yes this still the case, it does not seem that anybody is using this feature in polylang , so let us leave it like this for now. as this does not has high priority

**Comment by Jon007** [comment]
Ok, I do have a use case for this so I will reopen and assign to myself for further testing... when I have time...

The use case is:
- I want to use a forum eg bbPress so customers can chat.
- My customers speak different languages (duh!) but I want them to share the same forum.

This all works great if Polylang is turned OFF:
- I can allow front-end user switching in a wide variety of languages so all the system messages and user help can be translated  
- I certainly don't want to create language versions and translations of posts at the backend as Polylang requires.  In fact I wrote my own plugin which adds translate buttons to forum messages so users can translate into current display language.

However... to easily integrate with the shop and have the customer's shop and forum account link up nicely, it would be good to have the forum and the shop on the same site.
To do this, I disable the backend translation for forum posts etc.

Now:
- IF Polylang is set to detect language from URL and set to omit the language code from URL for default language, then it automatically switches to base language when the user clicks on the Forum link (BAD)

It looks like if the Polylang URL options are changed then it is possible to allow other plugins pages to be accessed without automatically switching display language, this needs more investigation as to whether it causes other issues.

**Comment by hyyan** [comment]
Even though I am not sure this the right way to go , but we leave it open for further testing

**Comment by Jon007** [comment]
@hyyan actually the option I will be looking at further will be to turn off Polylang "Hide URL language information for default language" rather than turn on "The language is set from content".

For the "The language is set from content" option what we should do is:
- If this option is not operable then we need to detect that option and disable the plugin or show the warning message.   Otherwise we will continue to get problem reports from new users which may be hard to diagnose.
- Ideally the current warning message system should be changed and the plugin should fully deactivate with relevant messages (whether it is Polylang or WooCommerce which is not installed or not configured)

A support button that dumps out both Polylang and woopoly Settings would also help, to attach to any problem reports.

**Comment by Jon007** [comment]
Rather than having this as an open issue, as I am the only one who raised it I will close it.
It should be absolutely clear in the documentation that this option is simply not supported, rather than not supported yet - the wordpress.org overview text could be improved
