### ISSUE TITLE
Permalink not working and product page not found

### ISSUE THREAD

**Issue by guoyangrui** [hyyan/woo-poly-integration#177]
#### What product versions and settings are you using when this issue occurs?
* PHP: 
* WordPress: 
* WooCommerce: 
* Polylang: 
* Hyyan WooCommerce Polylang Integration: 
* Browser: 

#### Steps to Reproduce
1. 
1. 
1.

**Comment by guoyangrui** [comment]
After I installed this plugin, I was able to create translations for my product. However, both the original and translated pages were not found. Also, there was one extra slash before /product in the permalink, so the URL became //product. I was running WooCommerce 3.0.7 and Polylang 2.1.5. Could you please fix this bug? Thanks so much

**Comment by Jon007** [comment]
I did see one error like this while trying some things out and I checked in some improvement to startup code in this branch:  https://github.com/hyyan/woo-poly-integration/tree/1.0.1-Minor-Fixes

**Comment by hyyan** [comment]
@guoyangrui , @Jon007 closing this as this can not reproduced .
@guoyangrui if you  have can provide the steps to reproduce the issue please feel free to re-open this one
