### ISSUE TITLE
Stock not synced

### ISSUE THREAD

**Issue by bazalt** [hyyan/woo-poly-integration#18]
Hi,

I checked the Stock Sync in settings.
Despite this, when manually changing the stock on a product, its translations are not synced.
I'm talking about this field:
![Stock field](http://kireicosmetic.com/stock.png)

Did I missed something ?
Thanks

**Comment by kochhase** [comment]
Hi bazalt,
have you tried the o,26 master ?
hyyan has done some changes there for Sync.
And he told me we will get a new version of the plugin when Polylang 1.8 is ready. This will be in the near future.
kind regards Henryk

**Comment by bazalt** [comment]
Thanks, I'll give it a try. I'm currently using official version 0.25

**Comment by Jon007** [comment]
Hi, this should be ok in current release version with 1 issue #136 on variations where stock is tracked at parent level, which is fixed in testing in current pull request.  Please reopen if any new problem fount.
