### ISSUE TITLE
Category translations problem.

### ISSUE THREAD

**Issue by mmortezzDev** [hyyan/woo-poly-integration#180]
I've just installed the module and I am able to translate products in woocommerce but there's no possibility to translate categories from WooCommerce. There's no translate section in Category menu and in category edit page even though in module's settings option to translate categories is checked.

PHP: 5.5.29
WordPress: 4.7.5
WooCommerce: 3.0.7
Polylang: 2.1.5
Hyyan WooCommerce Polylang Integration: 
Browser: Chrome 58.0.3029.110 (64-bit)

Best regards,
mrtz

**Comment by Jon007** [comment]
Is Product Categories translation selecte in Polyang Settings?
ie Languages\Settings /wp-admin/admin.php?page=mlang_settings
section Custom post types and Taxonomies\Custom Taxonomies, Product Categories

**Comment by Jon007** [comment]
I'm going to close here as the Languages \ Settings  setting will resolve your issue.

#183 will be left open to track improvements to the management of these settings
