### ISSUE TITLE
Actions for copyVariationMetas

### ISSUE THREAD

**Issue by vendidero** [hyyan/woo-poly-integration#181]
Hi there,

we are developing WooCommerce Germanized (which is an extension to adapt WooCommerce to the german market). We want to make our Plugin compatible with PolyLang - what we need is an action to hook into when updating the meta data for variations. As far as I can see this is done in `Variation::copyVariationMetas`. Would be nice if you could add an action to the end of the method so that plugin developers can manipulate certain meta data after saving/duplicating. 

Same applies for saving/syncing products in `Meta::syncTaxonomiesAndProductAttributes`. Would be nice to have an action here as well (e.g. one for insert/update).

Furthermore` it would be nice to make `Meta::getDisabledProductMetaToCopy` filterable as well (like getProductMetaToCopy is).

cheers

**Comment by Jon007** [comment]
Wouldn't you want a filter rather than an action in that case?
Can you propose via a Pull Request the actions or filters you need?
