### ISSUE TITLE
Filters for Emails

### ISSUE THREAD

**Issue by vendidero** [hyyan/woo-poly-integration#182]
Hi there,

it's me again. As in #181 I'd like to suggest some new filters for Emails.php. 

Is there a reason why you are not using WC()->mailer->emails to loop through all registered emails instead of adding your own array with default emails only?
You could then dynamically construct the filters for subject + heading for each email instead of manually adding the filters for predefined emails only:

```php
foreach( WC()->mailer->emails as $class => $instance ) {
     $this->register_string( $instance->id );
     // Subject filter
     add_filter( 'woocommerce_email_subject_' . $instance->id, array( $this, 'translate_subject' ), 10, 2 ); 
} 
....

public function translate_subject( $subject, $order ) {
     if ( ! is_a( $order, 'WC_Order' ) )
         return $subject; 
     $email = str_replace( 'woocommerce_email_subject_', '',  current_filter() );
     return $this->translateEmailStringToOrderLanguage( $subject, $order, 'subject', $email );
}
```

this is just a draft which I didn't test yet but I think this would make things easier and extension-ready. Otherwise it would be good if methods from your Emails object could somehow be accessible for DRY reasons.

**Comment by Jon007** [comment]
I suggest you fork and add the filters you need and then make a pull request when it's working for your use case.

I agree the code is repetitive, regarding why, I think initial implementation was only for a few emails, and probably at some point only Customer emails were translated Order language and Shop emails sent in shop base language, which probably should still be an option.  [Though one advantage of translating the shop emails is you can translate the shop email address itself to use a different customer service email address for each language.]

Also dynamically constructing the filter names as some components do doesn't always aid debugging etc. Since the filter text string doesn't exist in the source code, if you are reading the code it's a little bit harder to find where the filter came from and if you are implementing it's a bit harder to find what the right filter name to hook should be.

**Comment by vendidero** [comment]
Yes, hope that I'll find time for it soon :) 

Regarding the code-readability you are right. The other option would be inserting hooks or somehow making the string translation methods publicly available (or implement them via (static) functions). You may refactor the `registerCore` method and make the instances a property of the main Plugin class which should be accessible through a global variable/function.

**Comment by Jon007** [comment]
@vendidero  Noted your pull request thanks, I'll mention to Hyyan.
Note the current release branch is actually:
https://github.com/hyyan/woo-poly-integration/tree/1.0.2
which includes some other fixes

**Comment by vendidero** [comment]
Hi @Jon007 
thanks for the feedback. I've updated my pull request to the current release branch..

cheers

**Comment by Jon007** [comment]
@vendidero  thanks for your contribution, I look forward to trying woocommerce-germanized with these features available!
May I ask, what Currency Switcher do you recommend for use with your products?

**Comment by vendidero** [comment]
I did not yet test any currency switchers with Germanized. I think the only problem will be switching currencies for the unit price (which Germanized adds as a feature). Do you have a plugin in mind for switching currencies?

**Comment by Jon007** [comment]
Hi @vendidero  there are a lot of products, maybe none ideal.

1. Some switchers just show indicative price and checkout only in base currency
2. Some allow a separate payment gateway by currency
3. Some are pure javascript processing
4. Some are reliant on server processing and may be incompatible with page output caching  [I recommend Supercaching the static html generated by the product pages]
5. Most are paid with a free edition supporting just one additional currency but some have no free edition.

None of the reviews I've seen are entirely adequate either, hence looking for feedback from the community.
I might need to write my own review - but not on this thread.

**Comment by Jon007** [comment]
@vendidero please note also if you are adding other fields to Products, then it would be useful to control whether these are synchronised or not for product translations.

I was just looking into this for something else and added a note here:
https://github.com/hyyan/woo-poly-integration/wiki/Product-Meta-and-Custom-Fields

and an issue #194 to consider whether this plugin should itself add any handling to help support other plugins.

**Comment by vendidero** [comment]
@Jon007 most of the meta Germanized is adding to the product is prefixed with "_" but still should be synchronized. Do I need to change anything in the code to make sure that the meta is being synchronized in future versions?

**Comment by Jon007** [comment]
@vendidero 
Yes you do, Polylang excludes meta prefixed with "_"  from the Synchronisation.
However there is quite an easy filter to customize that, I put an example at the bottom of the page:
https://github.com/hyyan/woo-poly-integration/wiki/Product-Meta-and-Custom-Fields

I also opened #194 for discussion of whether any enhancement is needed in this plugin to handle unknown 3rd party meta, your comment and input is welcome, but probably for your case it would be very easy for you to add the filter directly..

**Comment by vendidero** [comment]
Yes, I noticed the example but couldn't find the filter within the code. Did you already implement that? Or is it part of a specific branch?

**Comment by Jon007** [comment]
it's in POLYLANG code, it's not part of this plugin, this plugin uses the standard Polylang function for copying the metadata

**Comment by Jon007** [comment]
to give a bit more detail,
woo-poly-integration actually adds the meta from woocommerce to the standard polylang meta to copy using: 
        add_filter('pll_copy_post_metas', array(__CLASS__, 'getProductMetaToCopy'));

it then adds the selected meta on the options screen to the array of meta to copy using array_merge.

The example I gave filters the individual meta items to copy slightly earlier in the process .

**Comment by vendidero** [comment]
Allright, I think I got it. I've registered my fields through the `woo-poly.product.metaSync` so I think this should work as expected :)
