### ISSUE TITLE
Stock Sync issue.

### ISSUE THREAD

**Issue by Tii** [hyyan/woo-poly-integration#184]
#### Can you reproduce this issue on default Wordpress theme (eg Storefront)?
YES

#### Can you reproduce this issue when all other plugins are disabled except WooCommerce, Polylang and Hyyan WooCommerce Polylang Integration?
YES

#### What product versions and settings are you using when this issue occurs?
* PHP: PHP 5.6.30-0+deb8u1 (cli)
* WordPress: 4.7.5
* WooCommerce: 3.0.8
* Polylang: 2.1.5
* Hyyan WooCommerce Polylang Integration: 1.0.1 
* Browser: Chrome latest

#### Steps to Reproduce
1. Setup at least 3 languages, let's say EN = default, FR & NL
2. Set a product, translate it into the 3 languages and set the stock to 3
3. Add 2 of that product into the basket while in FR
4. Go to Basket
5. Change Language to NL
6. proceed to checkout in NL
7. Your order is received, the stock of the product will be 1 in EN  but -1 in NL and 3 in FR !

#### What I Expected
to have 1 as stock in every language as it was 3 and you bought 2.

#### What Happened Instead
Seems like changing language when you added already a product in the basket makes the system to reduce the stock in that language two times and not the other language. Probably because the product ID refers to a product in another language?

**Comment by Jon007** [comment]
What do you have set for the Stock synchronization options, on the WooPoly Features page and Metas page?

**Comment by Tii** [comment]
all stock related features are checked.

I tried on my productive website and I also tried on a freshly installed WordPress / Woocommerce / Polylang / woo-poly-integration and I had the problem too by installing your plugin and not changing any settings in it.

I checked the code and the problem comes from the Stock class on line 185:

`/* Remove the current product from translation array */
            unset($translations[$productLang]);`

when the order does not have the same translation as the product, the product that has the order language is reduced twice.

I could patch it by unsetting the order's language instead of the product's.

So, you would have to pass the order's language to the **change()** function and unset the translation of the order's language:

`/* Remove the current product from translation array */
            unset($translations[$orderLang]);`

then it works but we should consider the case where the user add product in each of the website's language, I guess it should work but I did not try.

**Comment by Tii** [comment]
https://github.com/hyyan/woo-poly-integration/compare/master...Tii:patch-1

**Comment by Jon007** [comment]
ok I reproduced,

1. simple product, stock 44, exists in Base language (English), Spanish and French
2. browse site in Spanish as a visitor and add to basket
3. switch language to French and checkout
4. stock is now French:36, Spanish: 44, English 40
If step 3 is omitted, and the checkout is completed without switching languages then the result is correct, stock reduced to 40 in all languages.

What the code does here is remove the product version language from the set of translations to be updated, however in this case the product language and order language are different...

The simplest correction appears to be to change this line in stock.php function change() l.95:
    //$productLang = pll_get_post_language($productID);
    $productLang = pll_get_post_language($item->get_order_id());

However I have some doubts about rushing into a change:

1. There could be an alternative solution to ensure that an order item is always in the order language, to avoid possible subtle problems later.  
2. Adding the same item in different languages - actually this appears to resolve ok into one line item and correctly impact stock, with the change above
3. Variations need separate testing: stock can be tracked at either parent or variation level.
4. There are also some special cases, for example product is not translated into order language.

**Comment by Tii** [comment]
hey, thanks for review and acknowledgement 👍 

Currently, this is a very problematic bug for our production website as we are doing same day delivery of food and so, the stock is very important as we cannot tell customer it will be sent later. 
It happened multiple time that our stock went negative because of this bug and so, we had to cancel many orders, which means extra work and unhappy customers...

concerning your doubts:

1. I don't think this would be a good approach to the problem as the system would have to pass thru all items and replace it in case of language switch, that's a lot of cpu usage and it will not be able to do so if the product is not translated.
2. I had also already tested this point and did not see any issues there
3. We are currently not using any variations so I cannot help with that, would it be possible to validate a fix for all stock managed products? 
4. In case the product is not translated would not change anything as you are looping through the translations of it in order to sync the stock, so in that case, it will just not loop.

hope my feedback helps, I will do some more testing and come back to you if I  found real solutions.

**Comment by Jon007** [comment]
ok sure, well the 1 line change I suggested should work fine for your case:
 stock.php function change() l.95:
from:
`$productLang = pll_get_post_language($productID);`
to:
`$productLang = pll_get_post_language($item->get_order_id());`
Which as the effect of getting the order language rather than the product language.

This tests ok so far for all language combinations of Orders of Simple Product.
(Your alternative change may also work I didn't specifically test that.)

An official release is likely to wait a few days after testing with variations and bundling in some other fixes.

**Comment by Tii** [comment]
Thanks, I did the change, I guess I don't have to worry about it next time I update then 👍 
Thanks for everything, your plugin is great!
