### ISSUE TITLE
Change the default placeholder text in Checkout in two languages

### ISSUE THREAD

**Issue by OZDstudio** [hyyan/woo-poly-integration#185]
**Can you reproduce this issue on default Wordpress theme (eg Storefront)?**

YES

**Can you reproduce this issue when all other plugins are disabled except WooCommerce, Polylang and Hyyan WooCommerce Polylang Integration?**

YES

**What product versions and settings are you using when this issue occurs?**

PHP: PHP 5.6.30-0+deb8u1 (cli)
WordPress: 4.7.5
WooCommerce: 3.0.8
Polylang: 2.1.5
Hyyan WooCommerce Polylang Integration: 1.0.1
Browser: Chrome latest

**Steps to Reproduce**

I added the following code to my functions file in order to change the default placeholder text in Checkout in two languages:
 
```
add_filter( 'woocommerce_checkout_fields' , 'custom_override_checkout_fields' );
 
function custom_override_checkout_fields( $fields ) {
	$fields['billing']['billing_company']['placeholder'] =__( 'שם העסק' , 'Business name');
	return $fields;
}
```

**What I Expected**

To have different placeholder text in each language.

**What Happened Instead**

The first input is showing in both languages.

**Comment by Jon007** [comment]
Hi, 

The company name or billing_company should be translated by the wooCommerce .mo/.po files.
If a system text string like that isn't being translated, that means the translation is missing.

Please see this help page which I have just added to try to explain better:  https://github.com/hyyan/woo-poly-integration/wiki/Translation-Overview


The meaning of this code:
`__( 'שם העסק' , 'Business name');`
 would be "look up the text שם העסק in the language file 'Business name' and return translation in current language"

This will indeed have an effect but this involves creating additional .mo/.po language files for 'Business name' whereas this is already in the WooCommerce language files.

In any case, this is part of standard Wordpress and WooCommerce translation files, not a functionality that needs to be covered by this plugin.
https://github.com/hyyan/woo-poly-integration/wiki/Translation-Overview
