### ISSUE TITLE
Wordpress 4.8 Breaks new Product Variation Translations

### ISSUE THREAD

**Issue by Jon007** [hyyan/woo-poly-integration#187]
#### Can you reproduce this issue on default Wordpress theme (eg Storefront)?
Yes

#### Can you reproduce this issue when all other plugins are disabled except WooCommerce, Polylang and Hyyan WooCommerce Polylang Integration?
Yes

#### What product versions and settings are you using when this issue occurs?
* PHP: 7.0.15
* WordPress: 4.8
* WooCommerce: tested from 3.0.5 to 3.0.8 
* Polylang: tested from 2.1.3 to 2.1.5
* Hyyan WooCommerce Polylang Integration: tested both 1.0 and 1.1
* Browser: any

#### Steps to Reproduce
1. Create a new variation product
1. Translate

#### What I Expected
All the variations appear correctly in the translated product

#### What Happened Instead
Translated variations are unlinked and appear as "Any _attributename_"

#### FIXED BY ROLLING BACK TO WORDPRESS 4.7.5
After testing individually rolling back WooCommerce, Polylang, woo-poly, bug was only removed after rolling back to 4.7.5.
A simple rollback of test environment was performed by file copy of everything except wp-content from Wordpress 4.7.5 zip file.

after rolling back to 4.7.5:

- variations are created correctly on new translations
- variations which were broken by saving on Wordpress 4.8 can be fixed by opening in base language and saving again

Updating again to 4.8 reintroduces the problem.  Nothing is written to the debug log.

The problem. applies to variations created from translated attributes, non-translated attribute variations work ok, and in variations created from translated attribute + non-translated attribute, the non-translated attribute is matched and the translated attribute unmatched.

**Comment by Jon007** [comment]
in WordPress 4.8 the function call:
`$term = get_term_by('slug', $termSlug, $tax);`
no longer returns any terms for Product Attributes, so translated variations cannot be matched with terms.

**Comment by Jon007** [comment]
the query we need is something like this:
> SELECT t.term_id, t.name, t.slug FROM wp_terms AS t INNER JOIN wp_term_taxonomy AS tt ON (t.term_id = tt.term_id) WHERE tt.taxonomy IN ('pa_color') AND t.slug='chestnut';

but the actual query produced for this example:
> SELECT  t.*, tt.* FROM wp_terms AS t  INNER JOIN wp_term_taxonomy AS tt ON t.term_id = tt.term_id **INNER JOIN wp_term_relationships AS pll_tr ON pll_tr.object_id = t.term_id** WHERE tt.taxonomy IN ('pa_color') AND t.slug = 'chestnut' **AND pll_tr.term_taxonomy_id = 19**  LIMIT 1

which has been filtered by Polylang to add an extra language clause:  the pll_tr.term_taxonomy_id = 19 which in this example is filtering for French, the target language, however the slug is from English, the source language and doesn't exist in French. Since the slugs are unique AND we are going to ask Polylang to check for a term translation if we find a term anyway,  we certainly don't need the extra term filter here.

The actual change is done by Polylang filter: terms_clauses in admin-filters-term.php l.619++
```
	public function terms_clauses( $clauses, $taxonomies, $args ) {
		$lang = $this->get_queried_language( $taxonomies, $args );
		return ! empty( $lang ) ? $this->model->terms_clauses( $clauses, $lang ) : $clauses; // adds our clauses to filter by current language
	}
```
get_queried_language always returns a language so the filter is always added.


Also this never seems to hit the term cache but appears to be always running a more complex query than needed..

So the proposed solution will be to run a very specific query to get the term id from slug.
This is a simple query which is only executed when creating new translation of a variable product which uses translated  Product Attributes so impact in minimal.  Also it is a standard WordPress taxonomy query so no particularly vulnerable to further patches from Polylang or WooCommerce.

**Comment by michiphp** [comment]
hey developers and contributers, first of all thank you very much for this amazing plug in!! I really appreciate all the work and effort you guys put into! You rock!

I'm experiencing the exact same error as Jon007 stated above! Is there already an update or workaround solution for this? 

Jon007 thankfully proposed a solution, but I still don't know how to implement this. I would be very grateful if someone could explain in more detail how to solve the issue, until the next update is released!

**Comment by Jon007** [comment]
1. First, backup

Now if you already installed on live the correct solution is rollback.

If you are able to test rolling forward to pre-release that's great, you can get a .zip here:
https://github.com/hyyan/woo-poly-integration/releases/tag/1.0.2RC
Note that is a pre-release, use at your own risk, and please report any issues.

**Comment by hyyan** [comment]
@Jon007 after deep testing, I found that the solution is not working. the variations are not generated at all in fact.

Anyway, I do not believe it is the right way to go. it is a scary query 😄 , do not you agree ?! , we are not forced to use WordPress `get_term_by` method, we can write our own method and force polylang to fetch data with the correct language. 

What about something like : 

```php
 private function getTermBySlug($taxonomy, $value)
    {

        $query = array(
            'get'                    => 'all',
            'number'                 => 1,
            'taxonomy'               => $taxonomy,
            'update_term_meta_cache' => false,
            'orderby'                => 'none',
            'suppress_filter'        => true,
            'slug'                   => $value,
            'lang'                   => pll_default_language()
        );

        $terms = get_terms($query);
        if (is_wp_error($terms) || empty($terms)) {
            return false;
        }
        
        $term = array_shift($terms);

        return get_term($term, $taxonomy);
    }
```

**Comment by michiphp** [comment]
Hi guys, unfortunately neither of the proposed solutions are working for me. I've updated to the beta version 1.02 and changed the code of the variation.php to the code in 35cfb66 from hyyan, and I'm still having trouble with the sync of the variable products. 

What I do is:

1. Create Product in Default language, set producttype variable, set attributes, set price for variations. publish.
2. Create correlated Product in second language, set any random price, Publish.
3. Go into original product and link it to second language product. Update.

Then it syncs everything but the variations. :-(

Am I doing something wrong?

Thanks for your help guys! Really appreciate it!

**Comment by Jon007** [comment]
Hi, @michiphp the commit from Hyyan doesn't fix the problem which is related to variable.php not variation.php.
The working version is the 1.0.2 branch:
https://github.com/hyyan/woo-poly-integration/tree/1.0.2

**Comment by Jon007** [comment]
@michiphp on re-reading a few points in your explanation seem odd 

> 1. Create Product in Default language, set producttype variable, set attributes, set price for variations. publish.
Ok fine

> 2. Create correlated Product in second language, 
Ok...
> set any random price
Say what???
the translation should already have a price, it should be created by using the + button in the language panel...  This is standard Polylang functionality not part of this plugin, see eg: https://polylang.wordpress.com/documentation/setting-up-a-wordpress-multilingual-site-with-polylang/translating-posts-or-pages/


> 3. Go into original product and link it to second language product. Update.
Woah, what, why?   I think this won't work for variations in any version of this plugin.
Variations are currently linked to the master translation originally used to create the variations using a hidden meta key.  If you originally created the parent products unlinked I think the variations might stay un-linked, that's not a use case I've tried.  
Why would you be doing it that way?

**Comment by michiphp** [comment]
@Jon007 thank you very much for your qick reply. 

there is a reason why I'm doing it that way:

I'm using WP All Import Plug in to import my products with all the details from an excel file. It works great, apart from the syncing problem. What I do is, I import all the products in default language and then in second language, and after that I'm linking the products to each other. And it works absolutely great for simple products, you can even leave everything blank for the translated products (or put random stuff in it) because the syning overwrites the meta data. (which is good) However for some reason it has problems to link/sync the product variations.

And I think that polylang has intentionally implemented a text space next to the + in the language editor, to be able to link the product with existing pages. 

And yes, I can reproduce the error without using WP All Import, so it is definitely not a compatibility issue here.

**Comment by michiphp** [comment]
also what I found out (might be helpful to solve the problem), when I create the according product in the second language, as a simple product with translated title, translated description and any random price, and then link it from the original product, then it syncs everything, SKU, attributes, price etc. but no variations. (like the list is literally blank). but then, when I go "Edit" on the translated product and without changing anything, just press update, it suddenly syncs the variations perfectly. So actually, after linking the products I would have to go into each translated product and just press update. 

So the solution would be to trigger the update button of the translated product, when I press the Update button in the original product. Unfortunately I'm very very bad at php otherwise I would help to build the code. :-(

Hope that someone can help me out here.

**Comment by Jon007** [comment]
Yes, just import the second language without the variations.
Then when you go link the translations the variations will be created automatically, that's expected.
It doesn't matter if you do the linking and saving from master language or second language.
Or just don't import the second language, just copy and paste the translated description.


Creating variations is only supported in master language according to the current design of this plugin. If you actually try to create a new variation product in second language there are warnings like: 
"Wrong Language For Variable Product
Variable product must be created in the default language first or things will get messy. "
Your import process has skipped past the user interface so you didn't see these warnings.


I suggest the problem now described could be raised as a separate issue for 
"Change translated product link for Variation products" 
To note problem if you change the translation links for variation products already in the system.
 
 
There is a lot of confusion on this issue, partly because the original problem report says:

Steps to Reproduce

1. Create a new variation product
2. Translate
 
Step 2, translate is normally to press the + button on the language and create the translation, which also had some problems but this is not the process you are talking about.
