### ISSUE TITLE
Synchronization not working on rapid modification

### ISSUE THREAD

**Issue by frederickjeanguerin** [hyyan/woo-poly-integration#190]
#### Can you reproduce this issue on default Wordpress theme (eg Storefront)?

Yes.

#### Can you reproduce this issue when all other plugins are disabled except WooCommerce, Polylang and Hyyan WooCommerce Polylang Integration?

Not tested. 

#### What product versions and settings are you using when this issue occurs?
* PHP: 5.5
* WordPress: 4.8 
* WooCommerce: 3.0.8
* Polylang: 2.1.5
* Hyyan WooCommerce Polylang Integration: 1.0.1 
* Browser: Chrome 58

#### Steps to Reproduce
1. In the product list, select rapid modification for any one of them.
1. Change any attribute, for example the stock count. 
1. Update the changes

#### What I Expected

The stock count to update with translated products (synchronization).

#### What Happened Instead

The stock count does not update for translated products. 

#### Remark

However, if I go to the dedicated product screen for a modification, and change the stock count (or say the product price) then it gets synchronized for translated products. Of course I could do that every time I need to modify such an attribute, but the rapid (AJAX) modification from within the product list is so much faster... Is that a bug or a current plugin limitation?

**Comment by Jon007** [comment]
Actually I think this plugin might always have that limitation, it should be possible to implement though.
The Meta synchronisation is only being applied on current_screen action where the screen is the product screen.

**Comment by Jon007** [comment]
Ooo  I seem to have a fix, I'll test a bit more and check it in, 30mins..

**Comment by Jon007** [comment]
@frederickjeanguerin  this is now implemented in 1.0.2 branch

relevant changes are in meta.php, 
add to constructor:
```
        add_action(
            'woocommerce_product_quick_edit_save', array($this, 'saveQuickEdit')
        );
```
and add function:
```
    public function saveQuickEdit(\WC_Product $product)
    {
        // sync product meta with polylang
        add_filter('pll_copy_post_metas', array(__CLASS__, 'getProductMetaToCopy'));
        
        //some taxonomies can actually be changed in the QuickEdit
        $this->syncTaxonomiesAndProductAttributes($product->get_id(), $product, true);
    }
```

**Comment by frederickjeanguerin** [comment]
O well thank you very much for the added feature!

**Comment by hyyan** [comment]
@Jon007 I have avoided adding this feature before cause it requires Javascript Update for the interface too, or it will be just misleading, your piece of code update the meta correctly, but the interface is not updated unless you hit a page refresh. I will re-open the issue to keep that in mind for the future.

**Comment by Jon007** [comment]
If viewing Products in base language - a good idea when editing - then it's ok to do a Quick Edit or even a bulk update with no additional refresh needed.

The circumstance could only arise when viewing multiple translations in the same products screen at the same time.  

For example, this also cannot happen when filtering products by Category, assuming the categories are translated, then only products in one language are shown.

**Comment by Jon007** [comment]
I think this can be closed with documentation note:  https://github.com/hyyan/woo-poly-integration/wiki/Upload,-Bulk-Edit,-Quick-Edit

to advise that normally the Bulk Edit and Quick Edit should be done in 1st language only.
