### ISSUE TITLE
Synchronisation handling for unknown meta

### ISSUE THREAD

**Issue by Jon007** [hyyan/woo-poly-integration#194]
Many plugins add additional metadata to Products, users also raise support tickets about the handling of the additional data, so the behaviour should clarified and enhanced.

Example components include:

- Yoast SEO (meta keys like '_yoast_%' not synchronised, most fields not desirable to synchronise across translations)
- WP-Lister Lite for eBay and other synchronization tools (mix of field types) 
- Currency switchers with per product/language pricing capability (normally should synchronize).
- Autoposters such as NextScripts: Social Networks Auto-Poster
- Some themes such as Flatsome apparently add data to products 

Normally this data cannot be synchronised, Polylang appears to be not synchronising the data regardless of the options selected (eg Settings, Synchronisation, Custom fields has no effect).   One user appeared to be experiencing the opposite with the Flatsome theme and complained that he could not turn off integration, but did not provide sufficient information to diagnose.

Actually, most of these metas start with `'_'` underscore character.
Polylang `copy_post_metas` skips meta keys matching `is_protected_meta()` which starts by assuming any meta key beginning with '_' is protected [and should not be copied], there is also a filter is_protected_meta to override this. 

One woo-poly user recommended: Currency Switcher for WooCommerce By Algoritmika Ltd 
[free on WordPress.org for 2 extra currencies](https://wordpress.org/plugins/currency-switcher-woocommerce/)   (also authors of Booster for WooCommerce, not sure if this is the same as related Booster feature or not)
This supports setting product level pricing per language which is then saved in wp_postmeta under meta keys such as:
```
_alg_currency_switcher_per_product_regular_price_EUR
_alg_currency_switcher_per_product_sale_price_EUR
_alg_currency_switcher_per_product_regular_price_GBP
_alg_currency_switcher_per_product_sale_price_GBP
```
If used, these should normally be synchronised to the different language versions, one wouldn't expect to have to set the EUR price manually in each language translation.

So how to extend the metas list / fields locker?
Options:

1. - detect Meta keys and add them to "Other Metas" section in the list:  Tricky:  there are a lot, SELECT distinct meta_key FROM wp_postmeta returns >1,000 in my db and as these are not taxonomies there is no definition or grouping of which are valid/relevant.  Also this function gets called a *lot*, not only for the settings screen and on save of product but also for fields locker and other internal functions which test whether meta setting is set.
2. - implement Meta extension panels for particular plugins worth supporting, in the same way as Variables Metas, and open that extension api
3. - in Settings, Meta List, add text boxes for "additional fields to copy" and "additional fields to lock"

For the particular example here, this filter code could be placed in a theme functions.php or plugin to allow these values to be synchronised:

```
/**
 * Polylang meta filter, if true meta item will not be synchronized.
 *
 *
 * @param string      $meta_key Meta key
 * @param string|null $meta_type
 * @return bool True if the key is protected, false otherwise.
 */
function allowSyncCurrencyMeta($protected, $meta_key, $meta_type)
{
    $meta_prefix = '_alg_currency_switcher_per_product_';
    $length = strlen($meta_prefix);
    if (substr($meta_key, 0, $length) === $meta_prefix){
        return false;
    } else {
        return $protected;
    }
}
add_filter( 'is_protected_meta', 'allowSyncCurrencyMeta', 10, 3);
```

added to wiki at https://github.com/hyyan/woo-poly-integration/wiki/Product-Meta-and-Custom-Fields

**Comment by hyyan** [comment]
@Jon007 

[PRODUCT_META_SYNC_FILTER](https://github.com/hyyan/woo-poly-integration/blob/master/src/Hyyan/WPI/HooksInterface.php#L55) and [FIELDS_LOCKER_SELECTORS_FILTER ](https://github.com/hyyan/woo-poly-integration/blob/master/src/Hyyan/WPI/HooksInterface.php#L38) hooks are for this purpose 
These hooks will allow other plugins to extend the meta list which should be synced and the fields which should be disabled by Fields Locker 

But I agree that at least we should add a basic support for the most popular plugins which are used in conmbination with woopoly.

Closing for now as the basic support is already there
