### ISSUE TITLE
Variations add to cart error

### ISSUE THREAD

**Issue by janyazul** [hyyan/woo-poly-integration#196]
When I click on add to cart, but I do not select a variation of the product, I get this error message.
Fatal error: Uncaught exception 'Exception' with message 'Please choose product options&hellip;' in /public_html/wp-content/plugins/woo-poly-integration/src/Hyyan/WPI/Cart.php:300 Stack trace: #0 [internal function]: Hyyan\WPI\Cart->addToCartHandlerVariable('') #1 /public_html/wp-includes/class-wp-hook.php(298): call_user_func_array(Array, Array) #2 /public_html/wp-includes/class-wp-hook.php(323): WP_Hook->apply_filters('', Array) #3 /public_html/wp-includes/plugin.php(453): WP_Hook->do_action(Array) #4 /public_html/wp-content/plugins/woocommerce/includes/class-wc-form-handler.php(702): do_action('woocommerce_add...', '') #5 [internal function]: WC_Form_Handler::add_to_cart_action('') #6 /public_html/wp-includes/class-wp-hook.php(298): call_user_func_array(Array, Array) #7 /public_html/wp-includes/class-wp-hook.php(323): WP_Hook->apply_filters('', Array) #8 /public_html/wp-includes/plugin.php(453): WP_Hook->do_action(Ar in /public_html/wp-content/plugins/woo-poly-integration/src/Hyyan/WPI/Cart.php on line 300

* PHP: 
* WordPress: 4.8
* WooCommerce: 3.0.8
* Polylang: 2.1.5
* Hyyan WooCommerce Polylang Integration: 1.0.1
* Browser:

**Comment by Jon007** [comment]
are you able to try this version:
https://github.com/hyyan/woo-poly-integration/releases/tag/1.0.2-beta2

Yes I also saw something about this, but was unable to definitely reproduce it.
It should normally be impossible to do add the item to cart without selecting variation, there is normally a javascript alert like:  "Please select some product options before adding this product to your basket."

**Comment by Jon007** [comment]
Sorry I just noticed you are running: WordPress: 4.8

woo-poly 1.0.1 is not compatible with WordPress 4.8, especially for variations, as per the pinned note on the support forum:  https://wordpress.org/support/topic/do-not-install-wordpress-4-8-if-you-use-variations/
and the related issue #187

To run with 4.8 you will need woo-poly 1.0.2 which is only available in this beta version right now:
https://github.com/hyyan/woo-poly-integration/releases/tag/1.0.2-beta2

So I'll close this issue but you are welcome to open further issues if you have any problem with 1.0.2.
