### ISSUE TITLE
shop error message

### ISSUE THREAD

**Issue by vjdobermann** [hyyan/woo-poly-integration#197]
Hi every body,

could some please help me ? I can't have WC in english language

#### What product versions and settings are you using when this issue occurs?
* PHP: 
* WordPress: 4.8
* WooCommerce:  3.0.8
* Polylang: 2.1.5
* Hyyan WooCommerce Polylang Integration: 1.0.1
* Browser: Opera

#### Steps to Reproduce
1. Set the english language by the main menu

#### What I Expected
My shop in english language

#### What Happened Instead
Error message "No products were found matching your selection." when clicking on the English language.

Great thanks in advance

**Comment by Jon007** [comment]
Was your shop fully set up and working before? on which versions?
If it is a new setup, please check the wiki https://github.com/hyyan/woo-poly-integration/wiki/Getting-Started

"No products were found matching your selection." is a perfectly normal WooCommerce message when there are no products matching the selection so there are a very large number of reasons why that could come up, including missing translations, and various possible misconfigurations.
For example if you are on a category, tag or other archive page which does not yet have translations in English, this would be an expected result.


Note there are some compatibility issues with WordPress 4.8 and Hyyan WooCommerce Polylang Integration: 1.0.1, the latest pre-release to address these is this one:  https://github.com/hyyan/woo-poly-integration/releases/tag/1.0.2-beta2 
However this unlikely to be related to your issue.

**Comment by vjdobermann** [comment]
Hi Jon007,

Thanks for your message.

I'm a complet noob on WC, my shop is still under construction. 

One of my issue has been solved by creating the products in each language, thanks for help ;) 

But all the other pages related to the shop like the Cart, My Account, Order are blank

**Comment by Jon007** [comment]
Have you created the Page translations for the pages like Cart, My Account, Order ... ?
Just open each page and press the '+' button next to the language flags in the Languages section.

This is standard Polylang functionality not part of this plugin, see eg: https://polylang.wordpress.com/documentation/setting-up-a-wordpress-multilingual-site-with-polylang/translating-posts-or-pages/

If the pages are created but blank, maybe you have not copied the shortcode?

Eg the contents area for each page should contain the same shortcode as the original language version eg:

- Shop:  [woocommerce_checkout]
- Basket: [woocommerce_cart]
- Checkout: [woocommerce_checkout]
- My Account: [woocommerce_my_account]

The pages are full WordPress pages so can also contain your own text, but they must have these shortcodes.

**Comment by vjdobermann** [comment]
Hi Jon007,
I missed the short codes steps, there are now on the english pages and now they are translated in english :)

Many thanks for you help !

**Comment by Jon007** [comment]
ok no problem, I'll close the issue then
