### ISSUE TITLE
Some translations are not in "String translations" setting

### ISSUE THREAD

**Issue by auching** [hyyan/woo-poly-integration#199]
There are some default translations not appearing in the setting of "Strings translations" table, but I would like to modify them.  How may I do that with the plugin?  Thank you.

**Comment by Jon007** [comment]
That rather depends what sort of translations you are talking about.
Default strings do not need to appear in the Strings translation table, they come from the woocomerce .po/.mo language translation files and can be managed with Loco Translate for example.

please see:
https://github.com/hyyan/woo-poly-integration/wiki/Translation-Overview
https://github.com/hyyan/woo-poly-integration/wiki/Strings-translations
