### ISSUE TITLE
Discount code error

### ISSUE THREAD

**Issue by Armannas** [hyyan/woo-poly-integration#20]
First of all, thanks for the plugin, it is very essential and all your work is greatly appreciated, good job!
I am having problems with adding coupon codes and by deactivating and reactivating plugins one by one I found out that this plugin is preventing me from entering coupon codes.

The message is "Value must be less than or equal to 0" whenever I want to apply a coupon in the cart. Any ideas how to reslove? Using latest of everything with SwiftIdeas Dante theme

thanks

**Comment by Jon007** [comment]
Closing as I don't believe this issue applies on recent versions of the product.
If something like this happens again, please re-raise with the details of which versions of WooCommerce, Polylang, woo-poly-integration you are using.
