### ISSUE TITLE
Synchronization in wrong direction when linking products from existing second language page

### ISSUE THREAD

**Issue by michiphp** [hyyan/woo-poly-integration#202]
#### Can you reproduce this issue on default Wordpress theme (eg Storefront)?
yes
#### Can you reproduce this issue when all other plugins are disabled except WooCommerce, Polylang and Hyyan WooCommerce Polylang Integration?
yes
#### What product versions and settings are you using when this issue occurs?
* PHP: 4.0.10.14
* WordPress: 4.8
* WooCommerce: 3.08
* Polylang: 2.1.5
* Hyyan WooCommerce Polylang Integration: 1.0.2
* Browser: any

#### Steps to Reproduce
1. create product page in default language, set price to 100. (simple or variable product, doesnt matter,). Publish.
2. create product page in second language by clicking on "Add product" NOT by clicking on the + in the language settings editor. Set price to 200. Publish.
3. Now go into the just created page in second language and link it to the page in the default language.

#### What I Expected
The product in the second language would have the price and all other metas syncd to the metas of the product in the default language. So both would show the price of 100.

#### What Happened Instead
The product in the default language had the price and all other metas syncd to the metas of the product in the second language. So both showed the price of 200.

**Comment by Jon007** [comment]
This is correct normal behaviour and the same as for Pages, Posts etc, last save wins.
The variations behaviour is the exception due to the implementation strategy used by this plugin, ideally it would work in the same way.
