### ISSUE TITLE
[ERROR] shop product is missing - Integration to WordPress 4.8 and Woocommerce 3.0.8-3.0.9

### ISSUE THREAD

**Issue by KingGeneral** [hyyan/woo-poly-integration#204]
#### Can you reproduce this issue on default Wordpress theme (eg Storefront)?
Quality-Construction (http://justfreethemes.com/demo?theme=Quality%20Construction)

#### What product versions and settings are you using when this issue occurs?
* PHP: 5.3.29
* WordPress: 4.8
* WooCommerce: 3.0.8 - 3.0.9
* Polylang: 2.1.5
* Hyyan WooCommerce Polylang Integration: 1.0.1
* Browser: All browser
* Language used : en_US

#### Steps to Reproduce (CASE 1)
1. get your newest woocommerce
2. install woo-poly-integration
3. My shop is missing / gone after initializing CH_zh language pack from woo-poly-integration

#### Steps to Reproduce (continue from CASE 1) (after uninstall drawbacks)
4. + After i delete the woo-poly-integration plugin, my shop product is still missing (not show any products) (but cart and checkout works fine).
5. + then i try to uninstall my woocommerce , but woocommerce still updating from woo-poly-integration (even though i already delete everything from woo-poly-integration ).

#### What I Expected
dual language for woocommerce

#### What Happened Instead
the shop product is missing (not showing any products), the product isnt appear like usual (but cart and checkout works fine).

reference to : https://github.com/hyyan/woo-poly-integration/issues/137 **(woo-poly-integration)**

**Comment by KingGeneral** [comment]
![error 1](https://user-images.githubusercontent.com/9468485/27521818-10306a3a-5a4b-11e7-8a87-2b4109b147ea.png)

is this related to polylang ?

**Comment by Jon007** [comment]
Hi,
You still need the language files for WooCommerce with any solution.

 - Strings inside the code are translated by the language files for Wordpress and WooCommerce, you need these.
 - Strings in the database you need to translate yourself and this plugin extends Polylang by registering extra information for translation

Your shop is not missing/gone, the translated shop is not created yet...
You will not see any translated shop/products until you create the standard shop Pages and the translated Products.. this is basically the Polylang functionality so check the Polylang help if you are new to that. 

Please see also this plugin documentation eg:
- [Getting-Started](https://github.com/hyyan/woo-poly-integration/wiki/Getting-Started)
- [Translation-Overview](https://github.com/hyyan/woo-poly-integration/wiki/Translation-Overview)


Additionally, as per pinned posts on the support forum, note that WordPress 4.8 will require the 1.0.2 version of this plugin available from this branch: https://github.com/hyyan/woo-poly-integration/tree/1.0.2
