### ISSUE TITLE
String Translations

### ISSUE THREAD

**Issue by bopatynski** [hyyan/woo-poly-integration#206]
Hi, i've noticed there is missing string translations.
Most items translate automatically, but there is a few strings that are missing such as CART, you have %s items in your cart, my account.

#### What product versions and settings are you using when this issue occurs?
* PHP: 7
* WordPress: 4.7
* WooCommerce: latest
* Polylang: latest
* Hyyan WooCommerce Polylang Integration: latest
* Browser: chrome

#### Steps to Reproduce
1. 
1. 
1.

**Comment by Jon007** [comment]
These should be translated using the WooCommerce translation files, not part of this plugin so I'll close it off from here.

There have been lots of updates in WooCommerce so it's quite possible something got missed out of their translations.  I recommend Loco Translate for filling in missing translations, you can use their sync function to pull in strings missing from either the template or the translation file, and create your own translation override file with just the extra translations or changed translations which you need.

see our wiki for a few notes and links:
https://github.com/hyyan/woo-poly-integration/wiki/Translation-Overview
