### ISSUE TITLE
How to add another language manually?

### ISSUE THREAD

**Issue by igorjik1992** [hyyan/woo-poly-integration#21]
Dear all, 

I am trying to use this plugin to translate woo-commece to the Russian language. Unfortunalty i get an error that the language is not suported.. Is there anyway i  contribute to the plugin with my own translations? or add it manually as a seperate file or something like that?

Thank you. 
Regards, 
I.O.

**Comment by Jon007** [comment]
Hi, thanks for your offer of help, there are two ways to contribute:

1. Wordpress.org provides built-in tool for this for all plugins: https://translate.wordpress.org/projects/wp-plugins/woo-poly-integration

2. you can use Loco Translate plugin to create the language files, this is a very easy way to do this, then you can just make a pull request in Github to add the relevant files

**Comment by Jon007** [comment]
Note also that the language file only adds translation to the admin screens for this plugin, it doesn't affect the general site usage.
thanks for your interest and please let us know if there is any other problem!
