### ISSUE TITLE
Paypal IPN Notify URL being translated = Order awaiting payment!

### ISSUE THREAD

**Issue by frafor1988** [hyyan/woo-poly-integration#218]
Hi there,

I'm translating an e-commerce based on WordPress, here's my setup:

Wordpress 4.8
WooCommerce 3.1.1
Polylang 2.1.6
Storefront 2.2.4 + Child Theme
Hyyan 1.0.2 beta 2

Everything works fine, except that the IPN Notify URL is being translated by Polylang too: this means that orders do not receive payment notification correctly.

You can easily reproduce this bug:

1. Set up your URLs to be mysite.com/it/ mysite.com/en/ mysite.com/es/
2. Turn on Paypal IPN logging on WooCommerce
3. Place and pay an order in Sandbox mode
4. Check the log: you'll find that the IPN Notify URL is something like my https://mysite.com/wc-api/WC_Gateway_Paypal/
5. If you copy & paste that url in your browser, you'll get a 404
6. if you add /it/ /es/ or /en/, then you'll see the Paypal IPN message (stating that's failed, as obviously it is not supposed to be visited by browser).

The issue is old and described here:
http://polylang2.rssing.com/chan-7074893/all_p462.html

The user mario.scalabrino posts two different solutions (which I'm going to test in few minutes)

It would be great if WooPoly could fix this Polylang issue by itself!

FF

**Comment by frafor1988** [comment]
Here I'm am after a flash test :) The function below rewrites the URL correctly and fixes the issue

/** Fix PAYPAL IPN URL translated by polylang */
function custom_rewrite_basic_wc() {
add_rewrite_rule('^wc\-api/(.+)/?', 'index.php?wc-api=$matches[1]', 'top');
}
add_action('init', 'custom_rewrite_basic_wc');

**Comment by Jon007** [comment]
thanks for the proposed solution.
 - Have you tried this with other API usage eg #23?
 - I note this solution is only needed if “Hide URL language information for default language” is not set so it needs testing with the various different Polylang settings to be sure of effect

**Comment by frafor1988** [comment]
Hi @Jon007 
This is the situation:

- No, unfortunately I haven't tried to use the fix together with the API
- I've tested the proposed solution with "Hide URL language..." checked and not checked, and it works anyway, eg. not affecting the standard language-less URL. Language-informed IPN URL are being redirected to the language-less one.

**Comment by Jon007** [comment]
Hi, I couldn't reproduce this and reviewing related issues it may have been previously fixed.
If anyone is able to reproduce on more current versions, let's open a new issue for it.
