### ISSUE TITLE
Hello!

### ISSUE THREAD

**Issue by MarianaCuervo** [hyyan/woo-poly-integration#219]
Hello
I am using Polylang + Hyyan integration to have a web/shop in spanish and english. Everything is working quite well except for the dropdown cart widget that still shows in English. The title is "CART" and when you display it you get "VIEW CART" and "CHECKOUT". 
Please, I would like to have all that in spanish as well. They do not show in the string translation. Somehow, ccopy pasting some code snippet into the functions.php, I have managed to have them appear in the translation strings (Polylang) but still transalation is not working on the website.
Thank you for your help!

**Comment by Jon007** [comment]
Maybe there is a problem with your theme?
The standard Storefront theme has no title for the mini-cart and the buttons are: Ver carrito and  Finalizar Compra.

**Comment by Jon007** [comment]
Also, please note, the built-in labels from wooCommerce, Wordpress and the theme should be translated using the standard wordpress translation files mechanism (.mo/.po) files.

So it is not the job of this plugin to translate this type of label.
See https://github.com/hyyan/woo-poly-integration/wiki/Translation-Overview
for some notes about this.
