### ISSUE TITLE
admin-ajax.php process on homepage that delay loading of website

### ISSUE THREAD

**Issue by jihes** [hyyan/woo-poly-integration#22]
Hello,
First thank you for the plugin very useful to connect Polylang and WooCommerce.
I had performance issue with the loading of my website and after some investigation I discover that one source of issue was with your plugin that run a process admin-ajax.php which takes more than 2 secondes to load. This process is loaded on the homepage of my website even there isn't any woocommerce module on this specific page. 
When I inspect the process I found these informations: "div.widget_shopping_cart_content: "<div class="widget_shopping_cart_content">↵↵<ul class="cart_list product_list_widget ">↵↵	↵		<li class="empty">Votre panier est vide.</li>↵↵	↵</ul>↵↵↵</div>""
So I guess it's testing if there is a basket already with products, or something like that. Even that no basket is shown on homepage.
I had try to deactivate the plugin to see if it was from there (or if it was woocommerce himself) and I had the confirmation that it's your plugin.
Is it a normal way of working? Is there a configuration that I've done wrong? Is is a way to correct this?
Thanks a lot for the feedback.
jihes

**Comment by hyyan** [comment]
Closing this as I release version 0.27 , if it still problem please reopen
