### ISSUE TITLE
HTTP ERROR 500 When I activate this plugin

### ISSUE THREAD

**Issue by coreanartist** [hyyan/woo-poly-integration#220]
#### What product versions and settings are you using when this issue occurs?
* PHP: 
* WordPress: 4.8
* WooCommerce: 3.1.1
* Polylang: 2.1.6
* Hyyan WooCommerce Polylang Integration: 1.0.2
* Browser: Chrome Version 60.0.3112.78 (Official Build) (64-bit)

#### Steps to Reproduce
1. Only plugins activated are WooCommerce and Polylang.
2. I activate Hyyan/woo-poly-integration.
3. I refresh my webpage.
4. My webpage will not work and the following message appears...
This page isn’t working

bqtoday.com is currently unable to handle this request.
HTTP ERROR 500

**Comment by itsmir** [comment]
Upgraded to Hyyan WooCommerce Polylang Integration: 1.0.2 today and am getting the same issue.  
WP: 4.8.1
Woo:  3.1.1
Polylang: 2.1.6

**Comment by josk79** [comment]
What PHP version? You need 5.3+

**Comment by itsmir** [comment]
On PHP 7.0 here

**Comment by hyyan** [comment]
@itsmir Please update to version 1.0.3

**Comment by itsmir** [comment]
v1.0.3  solved it for me!   Thanks hyyan

**Comment by coreanartist** [comment]
Is this 1.0.3 a plug-in. I asked my provider to upgrade to PHP 1.0.3, but
he said that's something he doesn't do. He said it is PHP Depend and not
PHP? He said currently it is PHP 5.0 or 7.0

**Comment by hyyan** [comment]
Haha, sorry my bad, update the plugin to version 1.0.3

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by coreanartist** [comment]
Looks okay now. Thanks for the update. Cheers.
