### ISSUE TITLE
Variations Attribute is not synced

### ISSUE THREAD

**Issue by dimay08** [hyyan/woo-poly-integration#221]
#### Can you reproduce this issue on default Wordpress theme (eg Storefront)?
Yes
#### Can you reproduce this issue when all other plugins are disabled except WooCommerce, Polylang and Hyyan WooCommerce Polylang Integration?
Yes
#### What product versions and settings are you using when this issue occurs?
* PHP: version 5.6.30
* WordPress: version 4.7.5
* WooCommerce: Versión 3.0.5
* Polylang: Versión 2.1.3
* Hyyan WooCommerce Polylang Integration: Versión 1.0.1

I vahe a problem with the synchronization of variations. I created a product in the default language (Spanish) and then copy for the second language (English). All is copy but the variations meta is not synced. The other metas are being copied (SKU, Weight, price, etc).

I check the fix #26 and I did all to sync. And view that it's works in the default value, but still its not working with the others variations. 

I show these screenshot:
Default language 
![image](https://user-images.githubusercontent.com/30554202/28804753-cf19173a-762a-11e7-9faa-155661c721e0.png)
Second language
![image](https://user-images.githubusercontent.com/30554202/28805298-a77d63f8-762e-11e7-9c67-c31aadb9060f.png)

I have enabled Sync for all attributes on woo-poly metas list and enabled Synchronization fro taxonomies. 

I don't know what to do more. Can you help me?

**Comment by Jon007** [comment]
Version 1.0.1 has some issues, please use version 1.0.2 which is now released.
After update if you open in first language (ie Spanish is your case) and then save, it should synchronise.

Having said that I also would recommend updating to latest versions of Wordpress and WooCommerce at the same time, ie: Wordpress 4.8.x and WooCommerce 3.1.x

I think WooCommerce 3.0.5 was only out for a couple of weeks before being replaced by 3.0.6, 3.0.7, 3.0.8, etc so there would be no specific testing done for 3.0.5, and in fact some minor suggestions from this project included in 3.1.

**Comment by Jon007** [comment]
Please note this plugin is now version 1.0.3, which should be working well with 3.1.1
I've just added an additional language and hundreds of products including variations to a site this week with this software, it seems ok.

**Comment by raz0r7** [comment]
Hi Everyone,

I'm having this exact issue today. Sync is lost when creating a page in others languages from default, for example, the default language is English, when I add to Spanish or any other, the variations and attributes are lost and I have to add it manually. I use AliDrop plugin, which at ffirst hand, imports all attributes and variations normally. However, adding product page in any other language, this issue happens.

**Comment by Jon007** [comment]
@raz0r7 this is an issue closed 2 years ago on what are now quite old versions of woocommerce and this plugin.
If you still have an issue please open a new issue and provide the detail including your plugin versions.  Also confirm if you are just having a problem with the Alidrop plugin and whether it is working fine for you with Alidrop turned off

**Comment by raz0r7** [comment]
Hi Jon, ok, will do it. thanks
