### ISSUE TITLE
Emails for each language are not editable

### ISSUE THREAD

**Issue by kotyzap** [hyyan/woo-poly-integration#223]
#### What product versions and settings are you using when this issue occurs?
* PHP: 
* WordPress: 4.8.1.
* WooCommerce: 3.1.1.
* Polylang: 2.1.6.
* Hyyan WooCommerce Polylang Integration: 1.0.3.
* Browser: Chrome

#### What I Expected
I would expect that for each available language I will be able to create all WooCommerce order emails. 

#### What Happened Instead
Always the main language is used as a template. And if I select language (menu at the top of the Admin Area) all other languages are using always same template.

Is there some process how to have separate emails for each language activated in WooPoly? And if it is solved, where can I edit each language?

Thank you
Pavel

**Comment by Jon007** [comment]
Yes there is one set of templates, and all the strings in that template are translatable, either as standard wordpress translation files, or (for the strings customisable in the woocommerce admin UI) the Polylang strings translation table.

If you want additional text blocks or per-language formatting customizations, then just copy the email templates from wooCommerce to your theme directory\woocommerce\emails and then you can implement however you like.
