### ISSUE TITLE
product and product-category bases in wrong language for polylang language switcher links

### ISSUE THREAD

**Issue by CultureInspired** [hyyan/woo-poly-integration#225]
#### Can you reproduce this issue on default Wordpress theme (eg Storefront)?

Yes.

#### Can you reproduce this issue when all other plugins are disabled except WooCommerce, Polylang and Hyyan WooCommerce Polylang Integration?

Yes.

#### What product versions and settings are you using when this issue occurs?
* PHP: 7.1
* WordPress: 4.8.1 
* WooCommerce: 3.1.1
* Polylang: [state if using Polylang PRO] No, just the basic free Polylang
* Hyyan WooCommerce Polylang Integration: 1.03
* Browser: Chrome

#### Steps to Reproduce
1. Enable two languages for your site, in my case it's English and French.
2. Keep permalink settings completely default.
3. Add a Polylang language switcher to your primary nav menus for both languages. 
4. Create an English test category, then create a French translation for it and associate them together. For example a product category called "Cooking" with the French translation category "Cuisine".
5. Create a simple product in English and French, associate them together and mark them under the newly created categories. For example we'll say the English product is named "Cutting Board" and the French version "Planche à découper".
6. View the French product on the site, then hover over the English language switcher link in your nav menu and look at the URL it intends to take you too.

#### What I Expected

example.com/en/product/cutting-board

#### What Happened Instead

example.com/en/produit/cutting-board

So the issue is that the default product and product category bases that get translated natively by your plugin are being presented in the destination links for the language switcher, but in the language you're currently viewing the page in, not the language you intend to switch to.

**Comment by emreavsar** [comment]
i'm having the same issue. is there a way to fix this issue (other than using `.htaccess`)?

cheers

**Comment by emreavsar** [comment]
Other example would be:

```https://www.example.com/en/product-category/my-english-category/```

When clicking on the Language switcher (wich works on all other pages, except product + categories), the link looks like this:

```https://www.example.com/product-category/my-german-category/```

note: german is my primary language, so no /de/ can be found. this is ok.

It rather should be (note produ>k<t instead of 'c')
```https://www.example.com/produkt-category/my-german-category/```

**Comment by CultureInspired** [comment]
One temporary measure I'm using for now is replacing the default product category base with something else, for example I changed it to "selection" because luckily the word is spelled the same for the two languages I need, so my urls are example.com/selection/my-category, it's not a fix, but this way it doesn't incorrectly translate the product category base causing 404s.

**Comment by emreavsar** [comment]
@CultureInspired Well this does work for you, but not for me. Since product-category and produkt-kategorie are not identical. :-(

**Comment by Jon007** [comment]
it's just the permalink part that's not translated.

I just set my Product permalinks to be shop or actually "/shop/%product_cat%/" then it is only the word "shop" which is not actually translated, so the site urls for products etc within the shop are like:
mysite.com/**shop/**english-products
mysite.com/**fr/shop/**produits-francais
mysite.com/**es/shop/**productos-espanoles

Also I set my Product category base to be simply "shops" or "cat" rather than having a full product-category or produkt-kategorie etc in every url.

You could also set the permalink bases to "a", "b", "c" etc or possibly remove them: they don't need to be user-meaningful, they exist really to avoid url collision between Product Categories and Product tags with the same name.


Ideas and pull requests for improvements welcome...

**Comment by mohdqasim98** [comment]
Getting the same issue

**Comment by Jon007** [comment]
then you can use the same workarounds as I suggested on 18 Aug above ...
for example go to Settings Permalinks and set the product permalinks to something like:
` /p/%product_cat%/`
or, you can propose an implementation - feel free to fork and submit pull request.

The implementation would be quite similar to endpoints.php (see latest commit) with 2 parts:

**Register strings**
similar to regsiterEndpointsTranslations() in endpoints.php:
first to loop through all the permalinks and call pll_register_string to register them in the strings translation table and make them available for translation, in the 

**Add translated permalinks**
similar to addEndpoints() in latest commit to endpoints.php 
need to loop through the permalinks and for each permalink loop through available languages and add_rewrite_endpoint.   this is hooked via pre_update_option_rewrite_rules to ensure the rules are updated whenever permalinks are saved.
(Note it is not called when updating the strings translations, only when saving from the Settings, Permalinks.)

**Comment by mohdqasim98** [comment]
Thanks for the quick repy, 
Will give it a try

**Comment by mohdqasim98** [comment]
Just Entered 'product-category' in "Product category base" field in permalink settings , and saved .
It solved the problem

**Comment by Jon007** [comment]
@mohdqasim98 the problem described in this post is that the string 'product-category' is not translated when you switch language.  

This means the links would be eg:
english.myshop.com/product-category/my-product/
spanish.myshop.com/product-category/mi-producto/
french.myshop.com/product-category/mon-produit/
chinese.myshop.com/product-category/我的产品

My point was that this doesn't really matter, and that if anyone is worried they can simply shorten the permalink, as it doesn't need to be that meaningful, so if you were worried about someone seeing product-category in english on the url you could just change it to 'p' or whatever you like:
english.myshop.com/p/my-product/
spanish.myshop.com/p/mi-producto/
french.myshop.com/p/mon-produit/
chinese.myshop.com/p/我的产品

My explanation was for how to implement a translation for this slug if necessary (which I don't think it is).

I don't know what problem you fixed but I guess it wasn't that one.

**Comment by Jon007** [comment]
I think this issue can be closed then, as long as something is saved in "Product category base" field in permalink settings there is no problem with the language switcher.
