### ISSUE TITLE
woocommerce Easy Booking System Integration

### ISSUE THREAD

**Issue by ivocarrion** [hyyan/woo-poly-integration#227]
Woocommerce Easy Booking Integration

Hello,
I’m trying to integrate Woocommerce Easy Booking and Polylang. I have Installed Your plugin and all the navigation along two languages works fine, but not the stocks Sync. Is there not integration at all with bookable products?
Thank you very much.

#### Can you reproduce this issue on default Wordpress theme (eg Storefront)?
               yes
#### Can you reproduce this issue when all other plugins are disabled except WooCommerce, Polylang and Hyyan WooCommerce Polylang Integration?
         yes
#### What product versions and settings are you using when this issue occurs?
* PHP:   5.6.21
* WordPress: 4.7.5
* WooCommerce: 3.0.7
* Polylang: [state if using Polylang PRO]  2.2
* Hyyan WooCommerce Polylang Integration:  1.0.3
* Browser:  chorme, opera, mozilla

#### Steps to Reproduce
1.  Selecting dates
1.  add to cart
1.  checkout

#### What I Expected
   Stock of available rooms should be updated to same number for both (/en and /es) .

#### What Happened Instead
  Stock of rooms does not match with reality. Both rooms in /en and /es should be the same, and does not do it. At the same time, you can buy more days than the stock available.

**Comment by Jon007** [comment]
I'm not familiar with Easy Booking System, but I suggest:
 - first check that stock synchronisation works for standard wooCommerce products (without EasyBooking), if not check that Stock options are selected on both the Features and Metas pages of the woopoly settings.   Have a look around [this project's wiki](https://github.com/hyyan/woo-poly-integration/wiki/Stock) for more info.
 - once standard stock synchronisation is working, check Easy Booking.

If it doesn't work, mostly likely they are using some custom fields. 

Does the problem occur on saving the product or when a customer makes a reservation?

- Admin screen Synchronisation of custom fields is covered here:
https://github.com/hyyan/woo-poly-integration/wiki/Product-Meta-and-Custom-Fields
- checkout stock synchronisation is done by 'woocommerce_reduce_order_stock' action, if there are custom fields, probably some similar action to this plugin's Stock.php would be needed.

**Comment by Jon007** [comment]
@ivocarrion did you find a solution?  please feel free to post 

closing as:
 - Easy Booking System Integration is not within scope of this plugin - scope is limited to woocommerce and polylang plugins only
 - no feedback for 10 months
 -  there are some other open issues about stock synchronisation eg #299
