### ISSUE TITLE
Woocommerce API Limitations

### ISSUE THREAD

**Issue by falahati** [hyyan/woo-poly-integration#23]
Hi,
It seems that using this API, woocommerce api is limited to the default language. So it is not possible to get all the products or the products available on the other languages. Please provide a fix for this. thanks

**Comment by hyyan** [comment]
@falahati  thanks , I will work on this to provide a solution

**Comment by nickstamat** [comment]
@hyyan is there any update on this?

I have 3 languages on my store. When I try to get the orders through the WooCommerce API, I only get the ones made with the default language (English). The orders made with the rest of the languages are not fetched.

If you have any idea on how to resolve this, please let me know.
Thanks a lot for your effort  :)

**Comment by Jon007** [comment]
this seems to be something not done by Polylang, but there are a few references around, have you tried playing with:
https://nology.de/wordpress-api-v2-with-polylang-and-acf.html

**Comment by Jon007** [comment]
This seems to be a general problem not limited to WooCommerce so should perhaps be raised directly with polylang.

You can verify this by trying with the wordpress api eg:
http://mysite.com/wp-json/wp/v2/pages

will only list pages in the default site language as Polylang is detecting the language and filtering it.
However if you put a language in the permalink is not understood.  Say you have /fr/ as the French version of the site:
https://mysite.com/fr/wp-json/wp/v2/pages
will simple return 404 page and not return the French version of the api

**Comment by Jon007** [comment]
Has anyone tried this recently?
... noting that Polylang 2.3 to 2.3.3 have various fixes relating to Rest api..

**Comment by Jon007** [comment]
ok I retested this with WooCommerce 4.2.2 Polylang 2.7.3 and can confirm:

- the documentation on docs.woocommerce.com is rubbish, if you want to get the rest api working check the [github documentation](https://woocommerce.github.io/woocommerce-rest-api-docs/#) in detail - I've failed to get this working on several previous occasions
- /wp-json/wc/v3/products will get products in all languages.  Maybe you want one particular language?  do it by category.  note the api works  by id not by slug so request as eg:  /wp-json/wc/v3/products?category=36  - if 36 is a Spanish category, the Spanish products in this category will be listed
- /wp-json/wc/v3/orders will get all orders regardless of language

There are possible enhancements one could think of - if needed please raise a separate issue.

With that, voila, we close the oldest open issue on this plugin.
