### ISSUE TITLE
Woocommerce Emails sent out of Dashboard not fully translated

### ISSUE THREAD

**Issue by Leonhard24** [hyyan/woo-poly-integration#230]
#### What product versions and settings are you using when this issue occurs?
* PHP: 5.3.10-1ubuntu3.26 
* WordPress: 4.8.1
* WooCommerce: 3.1.2
* Polylang: 2.2.1
* Hyyan WooCommerce Polylang Integration: 1.0.3 
* Browser: Safari

#### Steps to Reproduce
1. Make a test order in a foreign language (English, Netherlands or Spanish. Admin Language is German) for testing the Email function 
2. Send the "order complete" E-Mail (or any other) out of the Dashboard

#### What I Expected

An completly translated Order Complete Mail from the Webshop.

#### What Happened Instead

While the Email which is generated right after the order is made is completly translated in the right language, the Emails which are sent after actions on the Dashboard are not completly translated.

In particular only the Subject (the Month is translated), the Header and the Content are not translated.

Do you know how to fix this?

Thank you very much!
Leo

**Comment by Jon007** [comment]
see https://github.com/hyyan/woo-poly-integration/wiki/Strings-translations

When the strings under WooCommerce, Settings, Email are not edited, the translations should be provided by WooCommerce language files.  If the strings are edited, the new translations for the new strings should be added to Polylang String translation table

**Comment by Leonhard24** [comment]
The Subject of the Mail was not changed from the default language, so there is no string in the Polylang string section.

The Content has been changed but I have already translated the strings for that.

**Comment by Jon007** [comment]
well, 
either use Loco Translate to check and adjust the WooCommerce translation files
or just make a change to the subject and then use the Polylang string translation table

**Comment by Leonhard24** [comment]
There are already translations for every String within the mail. The Problem seems to be, that for some of them the right language is not detected.

I am really clueless how to fix this. Thanks for caring!

**Comment by Jon007** [comment]
the code: 
- switches to order language
- compares the configured source string to the expected default string: if they are the same then it doesn't do the lookup in the string table, it returns for WooCommerce to look up the translation from the WooCommerce language files

So that means the translation in the string table may not be used even if it exists... and in your case the language files don't have the translations you expected.

Does that make sense?

**Comment by Leonhard24** [comment]
That can't be the problem either, since it works perfectly well for the order confirmed mail which is not created from the Dashboard.  By the same Email is not translated when it is "sent again" out of the Dashboard.

**Comment by Jon007** [comment]
hmm, it sounds like there are several different languages involved here:
1. order language
2. wordpress base language
3. your user language which may or may not be the same as 2.
4. whatever language you have selected in Polylang for admin view (or 'all languages') 

I haven't time to retest this right now but it sounds like maybe languages translated by string translation table are using the correct language (1) but unchanged strings using the woocommerce fallback are picking up eg your language (3) and causing a mixed language email?
You could confirm this by changing your user language to the order language and then trying to send again.

**Comment by Leonhard24** [comment]
I have edited the Header and the Subject of the Emails so I could translate them individually and now they are working fine.

Now the only problem remaining is that the Text is still shown in German while it should be in another language.

I use "Woocommerce Pretty Emails" to configure my Emails and the Texts are Translated in the Polylang String section. The Emails look something like this:

<img width="844" alt="bildschirmfoto 2017-09-16 um 18 16 27" src="https://user-images.githubusercontent.com/31736224/30513882-59cdd6ae-9b0b-11e7-866e-d2b1b1a6626a.png">

Thank you very much for your time!

**Comment by Jon007** [comment]
I'm not familiar with Woocommerce Pretty Emails but I would suggest the problem could be there.
If this plugin saves enhanced email templates to your theme for example then you would need to modify those templates to use the pll__ string translation functions.

Also note that Woocommerce Pretty Emails is a paid product with support and woo-poly-integration is not.

**Comment by Leonhard24** [comment]
The problem maintains, when Pretty Emails is deactivated and the default woocommerce emails are sent. So I don't think Pretty Emails is the problem. I contacted their support anyway.

Thank your very much for your support. Really appreciating it, since your Plug-In is all for free.

I noticed I am stillt running on PHP version 5.3.10, so I am fixing this first and let you know If this helps.

Leo

**Comment by Jon007** [comment]
If Pretty Emails user interface has saved an override woocommerce email template in your theme directory (wp-content/themes/mytheme/woocommerce/emails), then it will still be there after Pretty Emails is turned off so it's still an Pretty Emails / your theme issue.
[I don't know, I haven't seen this plugin, but it's a point worth checking]

**Comment by Leonhard24** [comment]
The E-Mail template still looks like this, which I think is the original version:

<?php
/**
 * Customer completed order email
 *
 * This template can be overridden by copying it to yourtheme/woocommerce/emails/customer-completed-order.php.
 *
 * HOWEVER, on occasion WooCommerce will need to update template files and you
 * (the theme developer) will need to copy the new files to your theme to
 * maintain compatibility. We try to do this as little as possible, but it does
 * happen. When this occurs the version of the template file will be bumped and
 * the readme will list any important changes.
 *
 * @see 	    https://docs.woocommerce.com/document/template-structure/
 * @author 		WooThemes
 * @package 	WooCommerce/Templates/Emails
 * @version     2.5.0
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * @hooked WC_Emails::email_header() Output the email header
 */
do_action( 'woocommerce_email_header', $email_heading, $email ); ?>

<p><?php printf( __( "Hi there. Your recent order on FEISOL has been completed. Your order details are shown below for your reference:
", 'woocommerce' ), get_option( 'blogname' ) ); ?></p>




/**
 * @hooked WC_Emails::order_details() Shows the order details table.
 * @hooked WC_Structured_Data::generate_order_data() Generates structured data.
 * @hooked WC_Structured_Data::output_structured_data() Outputs structured data.
 * @since 2.5.0
 */
do_action( 'woocommerce_email_order_details', $order, $sent_to_admin, $plain_text, $email );

/**
 * @hooked WC_Emails::order_meta() Shows order meta data.
 */
do_action( 'woocommerce_email_order_meta', $order, $sent_to_admin, $plain_text, $email );

/**
 * @hooked WC_Emails::customer_details() Shows customer details
 * @hooked WC_Emails::email_address() Shows email address
 */
do_action( 'woocommerce_email_customer_details', $order, $sent_to_admin, $plain_text, $email );

/**
 * @hooked WC_Emails::email_footer() Output the email footer
 */
do_action( 'woocommerce_email_footer', $email );

**Comment by Jon007** [comment]
that isn't the bit that displays the message you are asking about.
something is adding this pretty email stuff before the 
do_action( 'woocommerce_email_order_details'

However since this isn't part of standard wooCommerce or this plugin..  and the plugin in question isn't open source for people to examine, it really needs to be closed on here.
