### ISSUE TITLE
Shop Page Content Not Showing Up In Romanian 

### ISSUE THREAD

**Issue by OurCoterie** [hyyan/woo-poly-integration#232]
#### What product versions and settings are you using when this issue occurs?
* PHP: 5.6.30
* WordPress: 4.8.1 
* WooCommerce: 3.1.2
* Polylang: Free
* Hyyan WooCommerce Polylang Integration: 1.0.3
* Browser: Safari & Chrome

#### Steps to Reproduce
1. 
1. 
1. 

#### What I Expected

I installed the Hyyan WooCommerce Polylang Integration, followed all instructions and moved on to the "click +" and translate the shop page into the Romanian language. I did, but the page content that is supposed to have is not showing up. Every other translated page works fine.

#### What Happened Instead

This is my website: www.ourcoterie.com
Shop in English: http://ourcoterie.com/shop/
Shop in Romanian: http://ourcoterie.com/shop-2/
Product page English: http://ourcoterie.com/shop/diff-eyewear/
Product page Romanian: http://ourcoterie.com/shop/diff-eyewear-2/

The info that's on the English shop page is fully translated in the Romanian version, but it's not showing up outside of the page editor. Neither the product that's supposed to show up nor the "make sure to subscribe" bit that's in the page description. What am I doing wrong?

**Comment by Jon007** [comment]
Hi, your links are not set up right.

There is nothing in the link http://ourcoterie.com/shop-2/ to identify whether the language is supposed to be Romanian or English, so the Polylang filters don't detect the language to filter correctly.

See note 4 from the plugin home page on https://wordpress.org/plugins/woo-poly-integration/
"Polylang URL modifications method The language is set from content is not
supported yet"

go to Languages, Settings /wp-admin/admin.php?page=mlang_settings and check the options for URL modifications

Valid options are:
 The language is set from the directory name in pretty permalinks
Example: https://www.ourcoterie.com/en/my-post/
 The language is set from the subdomain name in pretty permalinks
Example: https://en.ourcoterie.com/my-post/

You can choose the option "Hide URL language information for default language"
in this case any url like http://ourcoterie.com/shop/ http://ourcoterie.com/shop-2/ will refer to the default language. 
And the urls for the other language will have the language code like
https://www.ourcoterie.com/en/shop
https://www.ourcoterie.com/ro/shop

**Comment by OurCoterie** [comment]
Hi Jon,

Thank you. I did the changes you recommended, but now I'm seeing this (please see attached).

![screen shot 2017-09-12 at 12 49 19 pm](https://user-images.githubusercontent.com/31858045/30319741-5cd83bf0-97b9-11e7-880f-eaf5e174f5ba.png)
![screen shot 2017-09-12 at 12 52 29 pm](https://user-images.githubusercontent.com/31858045/30319742-5d077a78-97b9-11e7-9e69-84df5e963022.png)

**Comment by Jon007** [comment]
Hi,

In polylang you have chosen the option:
http://ourcoterie.com/**ro/**shop-2/

but in the picture you have navigated to:
http://**ro.**ourcoterie.com/shop-2/

Also if you choose the subdomain option, you need to configure the server to point that subdomain at the wordpress installation, which also hasn't been done..

**Comment by OurCoterie** [comment]
I didn't navigate there, that's where it took me after clicking the "română" tab (language switcher) after making the changes.

I also didn't choose the subdomain option because it's more complicated and I'm not experienced enough to do it.

**Comment by Jon007** [comment]
Well Polylang clearly thinks it is suppose to redirect to subdomain, maybe something is not refreshed/saved properly.
This is a pure server setup and Polylang issue not related to this plugin...
.. try deactivating other plugins (including this one) and get WordPress and Polylang set up and working properly first.

**Comment by OurCoterie** [comment]
Well, now it's working. Maybe it needed to calibrate or something.

If I'm on the Romanian version of the site and click on the Shop tab, it reverts to English (default language) and it needs to be once again set to Romanian. Is there a way to make it not revert back to the English language and instead show the shop page in Romanian if accessed from the Romanian version of the website?

**Comment by Jon007** [comment]
you need to edit your menu and update the link..

**Comment by OurCoterie** [comment]
Done!

You're awesome! Thanks so much!

Maria
