### ISSUE TITLE
Featured product taxonomy term not synchronised

### ISSUE THREAD

**Issue by henrilindeberg** [hyyan/woo-poly-integration#234]
"Featured" is now a term in product_visibility taxonomy. Unfortunately it is not synchronised when I add the star to the main language product.

**Comment by Jon007** [comment]
Actually it can be synchronized and there were fixes done for this in #148 
Note, as per: https://github.com/hyyan/woo-poly-integration/wiki/Settings-Metas
Visibility: Product Catalogue Visibility and Featured Product are implemented as one taxonomy in WooCommerce3, so turning this option off will stop synchronisation of both features.

That said, a quick retest indicates "Featured" is synchronised correctly when updated:
1. From product edit screen
2. from Quick edit and bulk edit within all products view

However Featured is not synchronised when simply clicking on the star in the all products view.
Feel free to implement this!

**Comment by Jon007** [comment]
as a clue clicking on the favourite button fires a request like:
/wp-admin/admin-ajax.php?action=woocommerce_feature_product&product_id=nnnnn&_wpnonce=xxxxxxx

**Comment by Jon007** [comment]
add_action( 'wp_ajax_woocommerce_feature_product' ...  should catch it
