### ISSUE TITLE
The plugin also translate part of the wordpress dashboard

### ISSUE THREAD

**Issue by ImpExcel** [hyyan/woo-poly-integration#235]
#### What product versions and settings are you using when this issue occurs?
* PHP: 
* WordPress: 4.8.2
* WooCommerce: 3.1.2
* Polylang: [state if using Polylang PRO]2.2.3
* Hyyan WooCommerce Polylang Integration: 1.0.3
* Browser: Chrome

#### Steps to Reproduce
1. 
1. 
1. 

#### What I Expected
Only translate website, not wordpress dashboard

#### What Happened Instead
It also translates part of wordpress dashboard.

**Comment by Jon007** [comment]
What part of the wordpress dashboard do you think is translated by this plugin?
Steps to Reproduce above is blank.

In particular retest with this plugin turned off but Polylang still turned on, to ensure that you are not seeing a normal Polylang behaviour. 

Please feel free to reopen if you identify a valid issue.
