### ISSUE TITLE
Gif images are not showing in the Wiki Pages

### ISSUE THREAD

**Issue by hyyan** [hyyan/woo-poly-integration#236]
@Jon007 Any idea how to solve this, I can not figure it out ? is this a Github issue or the problem is in the images?

**Comment by Jon007** [comment]
It seems there was a bad images commit:
https://github.com/hyyan/woo-poly-integration/commit/c6677908d57d273a3633e3e03bdb793dfadb1b32?diff=unified

On further testing it looks like my Github Desktop on OSX is not handling the images properly at all.
I've just fixed manually by checking in the uncorrupted file versions again.

It's now working again on the wiki eg:
https://github.com/hyyan/woo-poly-integration/wiki/Product-Attributes

**Comment by hyyan** [comment]
@Jon007 Great news , Thanks  :)
