### ISSUE TITLE
WooCommerce Subscriptions compatibility

### ISSUE THREAD

**Issue by Sti3bas** [hyyan/woo-poly-integration#237]
#### Can you reproduce this issue on default Wordpress theme (eg Storefront)?
Yes.
#### Can you reproduce this issue when all other plugins are disabled except WooCommerce, Polylang and Hyyan WooCommerce Polylang Integration?
Yes.(it requires WooCommerce Subscriptions)
#### What product versions and settings are you using when this issue occurs?
* PHP: 7.1
* WordPress: 4.8.2
* WooCommerce: 3.1.2
* Polylang: 2.2.3
* Hyyan WooCommerce Polylang Integration: 1.0.3
* Browser: Safari 11.0

#### Steps to Reproduce
1. Add variable subscription product to the cart;
2. Go to the cart;

#### What I Expected
![29872620-090e4f02-8d99-11e7-8f37-bd1fc6f70777](https://user-images.githubusercontent.com/17280721/31276338-00c29100-aaa4-11e7-9b69-9aeab8a92673.png)

#### What Happened Instead
Wrong price interval.

![29872606-fb148a06-8d98-11e7-9cb0-768e0a7e0915](https://user-images.githubusercontent.com/17280721/31276344-061fda04-aaa4-11e7-9c14-72421de1df38.png)

PR: https://github.com/hyyan/woo-poly-integration/pull/228

**Comment by Sti3bas** [comment]
@Jon007 199$ is for 1 year of updates and support :)

This seems like official repo of the plugin: https://github.com/wp-premium/woocommerce-subscriptions

GPLv3 license is also included in the plugin files downloaded from woocommerce.com.

**Comment by Jon007** [comment]
wp-premium says it is just a mirror, it is not the master repository.
curiously the repo does not include the GPL licence text however the readme file is marked with the licence.  This may be historic or error since none of the other wp-premium projects I sampled include a GPL reference.  I would guess from the name "wp-premium" that they are normally intended to be premium, ie paid.

**Comment by Sti3bas** [comment]
@Jon007 I've asked the creators (https://prospress.com) of WooCommerce Subscriptions about the repository, here is the answer:

![screen shot 2017-10-07 at 00 17 49](https://user-images.githubusercontent.com/17280721/31299034-573a990a-aaf5-11e7-9189-0f802003ab27.png)

So believe it or not this plugin is free :)

**Comment by hyyan** [comment]
wontfix , This is out of the plugin's scope
