### ISSUE TITLE
Product page redirects to home page or to 404 not found

### ISSUE THREAD

**Issue by abdulet** [hyyan/woo-poly-integration#238]
#### Can you reproduce this issue on default Wordpress theme (eg Storefront)?
Yes

#### Can you reproduce this issue when all other plugins are disabled except WooCommerce, Polylang and Hyyan WooCommerce Polylang Integration?
Yes

#### What product versions and settings are you using when this issue occurs?
Wordpress: 4.8.2
woocomerce: 3.1.2
polylang: 2.2.3
Hyyan WooCommerce Polylang Integration: 1.0.3
OS: Ubuntu 17.04
Mysql server: 5.7.19-0ubuntu0.17.04.1
Apache2: 2.4.25-3ubuntu2.3
PHP: libapache2-mod-php 1:7.0+49
Browser: Firefox 55.0.2 (64 bits) 

#### Steps to Reproduce
-Install wordpress
-Remove all plugins
-Install woocommerce and basic setup
-Install polylang
    -Define Spanish-es_ES as lang 0
    -Define Catalan as lang 1
    -Create woocommerce pages for each language
    -Create language menú for each language
-Install Hyyan WoooCommerce and basic setup
-Create a product with its translations
    -Setup title, description, price and image
-Go to site, shop and product

#### What I Expected
The product's details

#### What Happened Instead
-It goes to home page or to a 404 error page

**Comment by Jon007** [comment]
Hi, this is a setup issue: check your Permalinks and Polylang settings.

Make sure everything is working for standard post/page translation with Polylang before doing products, any issues refer to Polylang setup.

Permalinks should be set and Polylang Languages, Settings, URL Modifications option "The language is set from content" cannot be used, easiest option to set up is "The language is set from the directory name in pretty permalinks".

If it's all products, then Polylang cannot find the product in the requested language  or can't determine the requested language.
If it's an individual product, a bad rule in .htaccess or mod_security can also trigger this type of behaviour.

**Comment by abdulet** [comment]
Hi!

Thanks for the quick response, yeah u'r right, it was a simple permalink problem, by default woocommerce set the base for permalink as /product/ but in the setup of Hyyan it's translated to the required languages, just setting it up to default, in wp-admin>permalink, everything works as expected.

Thanks!
