### ISSUE TITLE
cart, checkout, account not translated

### ISSUE THREAD

**Issue by Apfelsinchen** [hyyan/woo-poly-integration#24]
Hi, 
I try to make my woocommerce shop bilingual, English and German.
I use woocommerce, hyyan woo poly integration, Polylang theme strings. 
A lot of the translations work.
But the cart, my accout and checkout pages are not translated from English to German.
I got poedit and looked at the files. The wp-content/languages/plugins/woocommerce-de_DE.po has all the right translations. But they don't show in the shop.
What am I doing wrong?
Please help me!

**Comment by Apfelsinchen** [comment]
Very poor support everywhere. No answers here, on woocommerce support forum, or wordpress support. Dissappointing.

**Comment by 4mbit** [comment]
I think you have to add the german version of the basket too.
Create a german version of basket and add [woocommerce_cart]
similear to checkout [woocommerce_checkout] 
For me it works

**Comment by hyyan** [comment]
You need to translate the the woocommerce pages

**Comment by stefanomonteiro** [comment]
Not working
