### ISSUE TITLE
WooCommerce 3.2 compatibility

### ISSUE THREAD

**Issue by Jon007** [hyyan/woo-poly-integration#240]
just to note WooCommerce 3.2 has come out:
https://woocommerce.wordpress.com/2017/10/11/woocommerce-3-2/
I expect some compatibility issues possible with carts and maybe coupons.

Also, and this may be a good point, woo-poly will be flagged as not tested for compatibility so users will be warned before upgrading, see:
https://woocommerce.wordpress.com/2017/08/28/new-version-check-in-woocommerce-3-2/

If you have tested already or are able to help with testing or have found any issue, please comment.

**Comment by Jon007** [comment]
version 3.2.1  checkout page, after load does an extra call to ?wc-ajax=update_order_review which appears to switch the order review and payments section back to site default language.

Works fine in 3.1, I guess this is added for the changes around basket recalculation and coupons.
The extra UI weirdness of greying out and refreshing the payment section doesn't add to the user experience.

In fact the whole checkout process is up for review at the moment, will probably be Q1 2018, see woocommerce github 10672

**Comment by ktheodor** [comment]
So how can we deal with this? Is there something we can do to switch back to current language?

**Comment by Jon007** [comment]
Unless you have time to debug it, I recommend continuing to use version 3.1.2 until version 3.2 has stabilised, taking into account the release patch velocity:

- October 11: 3.2 release "fully backwards compatible with 3.1 and 3.0." 
- October 13: 3.2.1 patch with 43 commits.

This project is only supported by volunteers like you and me, so there is limited capacity to retest and debug issues with new WC releases every week or every 2 days.

**Comment by Jon007** [comment]
Here's an example of some locale switching code if you want to try it:
https://github.com/hyyan/woo-poly-integration/wiki/Translation-locale-switching

**Comment by ktheodor** [comment]
I found a temporary solution for both checkout and wishlist which gave me a 404 error when changing from default to current language.
1. Go to Language --> Settings --> URL Modifications
2. Check "The language is set from content" (for  wishlist 404 error) 
3. Uncheck "Hide URL language information for default language " (for checkout problem)

**Comment by Jon007** [comment]
"The language is set from content" is NOT supported as stated in the readme file,  it will give many other problems.
Which wishlist plugin is that?

**Comment by ktheodor** [comment]
YITH WooCommerce Wishlist. When i switch from default (greek) to english it gives me a 404 error. I searched in the web and did not find any working answers. So i played with settings in polylang and that change worked.

**Comment by Jon007** [comment]
I'm using https://wordpress.org/plugins/ti-woocommerce-wishlist/ 
I identified 1 fix which they included very quickly, it seems to work fine.

Polylang "The language is set from content" will not work for WooCommerce, regardless of whether it worked for you for that wishlist.

**Comment by jeesus** [comment]
Quite serious issue with the checkout being rerendered in default language. Using WooCommerce 3.2.1. What hooks are used to set the current language or where should I look for debugging?

Perhaps one temporary solution would be to send an hidden parameter with current language value, hook into `woocommerce_checkout_update_order_review` and force the given language?

**Comment by Jon007** [comment]
- the temporary solution is to continue to use WooCommerce 3.1.2 where this problem does not occur
 - to debug, I suggest check the code path for update_order_review and diff the 3.2.1 version back to the 3.1.2 source code to find out what has changed, where the problem is likely to be.

There is no need for extra hidden parameters since Polylang will be initialised and will know what the correct language is (and the Polylang cookies will be already set), it's just a question of some change to the code path such that Polylang is no longer hooked.

**Comment by bene25** [comment]
Hi everyone. I am new to this plugin and wordpress at all. 
For now I have a problem with woocommerce and woo-poly-integration plugin.
1)If you install the latest version of woocommerce (3.2.1) and do all getting started steps, then default language shop menu item will redirect to the second language shop page. (I dont know how to resolve it , installing and uninstalling several times and doing all steps from start like described in getting started section are not help)
2)When I tied to install manually WooCommerce 3.1.2 (zip archive from woocommerce github repo) then woo-poly-integration plugin argue that he needs Woocommerce not less then 3.0 and polylang 2.0

In both cases Polylang Version 2.2.4, Wordpress Version 4.8.2

Any help. Thanks.

**Comment by Jon007** [comment]
@bene25 it works fine with WooCommerce 3.1.2, however if you already installed WooCommerce 3.2.1 it may not be supported to just install manually the 3.1.2 zip file as the database may already be upgraded.  Check a fresh installation or completely uninstall and delete data from 3.2 before reinstalling 3.1.2

**Comment by bene25** [comment]
@Jon007 thanks for response. F
Fully delete data by adding define( 'WC_REMOVE_ALL_DATA', true); to wpconfig and deleting woocommerce plugin, then manually install woocommerce and make all initial steps. Then install woo-poly-integration from plugin menu. Message appears again:
"The plugin can not function correctly , the plugin requires minimum plugin versions WooCommerce version 3 or higher and Polylang 2 or higher. Please configure Polylang by adding a language before activating WooCommerce Polylang Integration.See alsoInstallation Guide."

**Comment by jeesus** [comment]
@Jon007 do you know does AJAX checkout issue also affect the e-mails sent out to the customer? I also get all my e-mails in default language. Haven't used WooCommerce for a while, so don't know whether this is expected or not.

**Comment by Jon007** [comment]
@bene25 just comment out the activation check in plugin.php, force function canActivate() to return true.  This check is too simple and failing if you have plugin in different directory from expected - please raise as separate issue.  @hyyan couldn't canActivate() just use function_exist tests?

@jeesus  I haven't had time to test 3.2.1 but emails in language work fine in 3.1.2.  I also added some sample code here https://github.com/hyyan/woo-poly-integration/wiki/Translation-locale-switching which I used in a different plugin to send an emails in the right language

**Comment by bene25** [comment]
@Jon007 @hyyan on 3.1.2 plugin works correct. Thanks for helping

**Comment by hyyan** [comment]
This fix for issue is merged on the master branch now
