### ISSUE TITLE
Translate categories issue

### ISSUE THREAD

**Issue by andagent** [hyyan/woo-poly-integration#242]
#### Can you reproduce this issue on default Wordpress theme (eg Storefront)?
Yes

#### Can you reproduce this issue when all other plugins are disabled except WooCommerce, Polylang, and Hyyan WooCommerce Polylang Integration?
Yes

#### What product versions and settings are you using when this issue occurs?
* PHP: 7.0.22
* WordPress: 4.8.2
* WooCommerce: 3.2.1
* Polylang: 2.2.3
* Hyyan WooCommerce Polylang Integration:  1.0.3
* Browser: Chrome 61.0.3163.100

#### Steps to Reproduce
1. Go to Settings -> Woopolly
2. Put tick in translate categories 
3. Save settings

#### What I Expected
Have a possibility to make multilingual categories

#### What Happened Instead
The site doesn't show categories at all. On category page, it shows it like normal WP post
How it looked before

![3](https://user-images.githubusercontent.com/23004232/31579383-5da37672-b135-11e7-81dc-56d1f9e27604.png)
After enabling the function

![2](https://user-images.githubusercontent.com/23004232/31579382-5d868a62-b135-11e7-9059-b419bcab4036.png)
When you go to category link (shows like WP post)

![1](https://user-images.githubusercontent.com/23004232/31579381-5d6c544e-b135-11e7-9437-23dfb31d9dc7.png)

**Comment by Jon007** [comment]
check:
https://github.com/hyyan/woo-poly-integration/wiki/Product-Categories

- Check the Product categories translation is turned on in both Settings\WooPoly,Features and Polylang settings (Languages, Settings, Custom post types and Taxonomies) 
- Create the category translations in Products, Categories
- Check your shop settings, WooCommerce, Settings, Products, Display, Default Category display:   it's an option whether you want to show categories or not when browsing your shop.  It's also an option on each individual category whether to show subcategories
