### ISSUE TITLE
Stock Metas synchronization issue

### ISSUE THREAD

**Issue by vrvrvrvrvr** [hyyan/woo-poly-integration#244]
#### Can you reproduce this issue on default Wordpress theme (eg Storefront)?

Yes

#### Can you reproduce this issue when all other plugins are disabled except WooCommerce, Polylang and Hyyan WooCommerce Polylang Integration?

Yes

#### What product versions and settings are you using when this issue occurs?

Wordpress: 4.8
WooCommerce: 3.1.1
Polylang: 2.1.6
Hyyan WooCommerce Polylang Integration: 1.0.3

#### Steps to Reproduce

Having product with stock management in main and secondary language
Product quantity in stock = 1
settings, woopoly, Features - all enabled
settings, woopoly, Metas List - all enabled

1.     Sold product in main language
2.     Returned stock quantity back to 1 for main language page
3.     Stock quantity and stock status "out of stock" changed to "in stock" for main and secondary language pages.
4.     Product appears only in shop main language pages but not in secondary language pages

#### What I Expected

After restocking product should appear in both language pages

#### Troubleshooting / Workaround

1. settings, woopoly, Metas List -> Disable "Stock Metas"
2. change stock status to be "out of stock" for main and translated product, update product
3. change stock status to be "in stock" for main and translated product, update product

Product appears for main and secondary language shopping pages

**Comment by hyyan** [comment]
@vrvrvrvrvr I can't reproduce this one, I followed the steps you wrote, the behavior is working as expected. could you please check your WordPress log file to see whether there are any errors thrown. and 
can you try please to apply the same steps on different products to see whether you get the same result

**Comment by hyyan** [comment]
Close as inactive.
Please feel free to re-open if this is still an issue
