### ISSUE TITLE
order menu problem

### ISSUE THREAD

**Issue by atai1960** [hyyan/woo-poly-integration#245]
Hello!

I am using this plugin to integrate Woocommerce and Poilylang.
Everything works perfect except for one thing that I have just discovered.
I have set up the menu order of the items for show all in a specific importance order but I am not able to change this order order set up on the other languages.
Do you know why?

Thanks

#### What product versions and settings are you using when this issue occurs?
* PHP: 
* WordPress: 
* WooCommerce: 
* Polylang: [state if using Polylang PRO]
* Hyyan WooCommerce Polylang Integration: 
* Browser: 

#### Steps to Reproduce
1. 
1. 
1.

**Comment by Jon007** [comment]
See:
https://github.com/hyyan/woo-poly-integration/wiki/Settings-Metas
Settings, WooPoly, Metas

If you check the box for Menu Order then menu order should always be copied from main site language and not editable in other languages.

If you clear the Metas/Menu Order box then it becomes editable and is not synchronized.
