### ISSUE TITLE
String "related products" not translated

### ISSUE THREAD

**Issue by bobrock4** [hyyan/woo-poly-integration#246]
#### Can you reproduce this issue on default Wordpress theme (eg Storefront)?

Don't know

#### Can you reproduce this issue when all other plugins are disabled except WooCommerce, Polylang and Hyyan WooCommerce Polylang Integration?

Don't know

#### What product versions and settings are you using when this issue occurs?
* PHP: 
* WordPress: 4.8.2
* WooCommerce: 3.1.2
* Polylang: [state if using Polylang PRO] 2.2.1 not Pro
* Hyyan WooCommerce Polylang Integration: 1.0.3
* Browser: all

#### Steps to Reproduce
Watching related products in products page

#### What I Expected
To see the subtitle "related products" translated in italian

#### What Happened Instead

It's not translated in italian, it remains in English also on italian product pages

**Comment by Jon007** [comment]
Related products is part of the WooCommerce language files, check your language files and if necessary use Loco Translate to customize the translation. 

This plugin only localizes data and strings configured in admin screens, not the texts supplied as part of wordpress/woocommerce.
See https://github.com/hyyan/woo-poly-integration/wiki/Translation-Overview for an overview of translation.
