### ISSUE TITLE
Couldn't install woo-poly-integration on WooCommerce 3.1.2

### ISSUE THREAD

**Issue by bene25** [hyyan/woo-poly-integration#249]
When I tried to install manually WooCommerce 3.1.2 (zip archive from woocommerce github repo) then woo-poly-integration plugin argue that he needs Woocommerce not less then 3.0 and polylang 2.0

Fully delete data by adding define( 'WC_REMOVE_ALL_DATA', true); to wpconfig and deleting woocommerce plugin, then manually install woocommerce and make all initial steps. Then install woo-poly-integration from plugin menu. Message appears again:
"The plugin can not function correctly , the plugin requires minimum plugin versions WooCommerce version 3 or higher and Polylang 2 or higher. Please configure Polylang by adding a language before activating WooCommerce Polylang Integration.See alsoInstallation Guide."

Polylang Version 2.2.4, Wordpress Version 4.8.2

**Comment by hyyan** [comment]
@bene25 Just tried it, it works perfectly, woocommerce has been downloaded from [here ](https://github.com/woocommerce/woocommerce/releases/tag/3.1.2)

After you unpack the woocommerce package in the plugin folder , make sure it is named `woocommerce`  otherwise woopoly will fail to detect the plugin

**Comment by bene25** [comment]
I have tried with archive name woocommerce-3.1.2.zip

**Comment by hyyan** [comment]
@bene25 Correct, but after you unpack the archive the folder name must be named `woocommerce`


![capture](https://user-images.githubusercontent.com/4313420/32100461-1f62d9c8-bb14-11e7-8480-59e95a051be4.PNG)

**Comment by bene25** [comment]
That way it works:) Thanks

**Comment by hyyan** [comment]
@bene25 Great, closing the issue then
