### ISSUE TITLE
No translation in shipping estimate in Cart Page and Checkout Page

### ISSUE THREAD

**Issue by ylt04** [hyyan/woo-poly-integration#254]
#### What product versions and settings are you using when this issue occurs?
* PHP: 7.0.24
* WordPress: 4.8.3
* WooCommerce: 3.2.2
* Polylang: [state if using Polylang PRO]
* Hyyan WooCommerce Polylang Integration: 1.0.3
* Browser: 

#### Steps to Reproduce
1. 
1. 
1. 

#### What Happened Instead
My default language is in English. However, when I am in the Traditional Chinese version of my shopping cart page and wanted to change the estimate of the shipping method, the estimate frame will change from Chinese to English after I select another shipping method.

Furthermore, when I am in the Chinese version of the checkout page, the shipping method and payment method didn't show in Chinese and instead it shows English.

I am sure that I had added translation for Woocommerce Payment Gateways and Woocommerce Payment Gateways in Polylang string translation page.

**Comment by Jon007** [comment]
This is a known issue introduced in woocommerce 3.2.x and addressed on #240 and hopefully solved in master - you are welcome to test the master code branch
