### ISSUE TITLE
Please, can you proceed to an update of your great plugin for woocommerce 3.2.2 and wordpress 4.8.3 ? It would be nice to continue to use this very important plugin for multilingual e-commerce website... Thank you so much !

### ISSUE THREAD

**Issue by karine-nowak** [hyyan/woo-poly-integration#255]
#### What product versions and settings are you using when this issue occurs?
* PHP: 
* WordPress: 
* WooCommerce: 
* Polylang: [state if using Polylang PRO]
* Hyyan WooCommerce Polylang Integration: 
* Browser: 

#### Steps to Reproduce
1. 
1. 
1.

**Comment by Jon007** [comment]
GitHub is for reporting specific issues.
The general incompatibilities introduced in woocommerce 3.2.x are addressed on #240 and hopefully solved in master - you are welcome to test the master code branch
