### ISSUE TITLE
Ajax call: update_order_review

### ISSUE THREAD

**Issue by avezzelli** [hyyan/woo-poly-integration#258]
#### Can you reproduce this issue on default Wordpress theme (eg Storefront)?
yes
#### Can you reproduce this issue when all other plugins are disabled except WooCommerce, Polylang and Hyyan WooCommerce Polylang Integration?
yes

#### What product versions and settings are you using when this issue occurs?
* PHP: 7.0.25
* WordPress: 4.8.3
* WooCommerce: 3.2.3
* Polylang: 2.2.4 (free version)
* Hyyan WooCommerce Polylang Integration: 1.0.3
* Browser: Chrome, Firefox

#### Steps to Reproduce
1. Put product in the cart.
2. Go to checkout 
3. Change billing address or refresh page
4. Wait the ajax call for update order review 

#### What I Expected
The labels in woocommerce-checkout-review-order-table and in woocommerce-checkout-payment don't change the current translation.

#### What Happened Instead
After the ajax call (update_order_review), the labels in woocommerce-checkout-review-order-table and in woocommerce-checkout-payment change in the original form

![screen-01](https://user-images.githubusercontent.com/26743412/32551234-23a44e10-c490-11e7-9126-43a458916224.jpg)
![screen-02](https://user-images.githubusercontent.com/26743412/32551235-24e5529c-c490-11e7-9a2f-7f33254d1093.jpg)
![screen-03](https://user-images.githubusercontent.com/26743412/32551237-2534d574-c490-11e7-8203-97bc5ee2cfcc.jpg)

![screen-05](https://user-images.githubusercontent.com/26743412/32551239-25d2935e-c490-11e7-9f32-c37f5c571aa2.jpg)
![screen-06](https://user-images.githubusercontent.com/26743412/32551240-2676d568-c490-11e7-9874-97b676a8d7da.jpg)

.

**Comment by hyyan** [comment]
@avezzelli please use the code from the master branch, this issue was fixed in master but the fix is not published in Wordpress Repo yet. 

Please feel free to reopen if this stills an issue

**Comment by rrrjan** [comment]
Hi, sorry, new to GitHub.
Where can I find that code from the master branch to fix the issue?
I've looking for another issue ID but not lucky and don't know where to find the "master ranch code".
Thanks in advance for your help!
