### ISSUE TITLE
Error on activation

### ISSUE THREAD

**Issue by sergsoft** [hyyan/woo-poly-integration#259]
I've got following error
Parse error: syntax error, unexpected T_STRING in /wp-content/plugins/woo-poly-integration/__init__.php on line 35

#### Can you reproduce this issue on default Wordpress theme (eg Storefront)?
Yes

#### Can you reproduce this issue when all other plugins are disabled except WooCommerce, Polylang and Hyyan WooCommerce Polylang Integration?
Yes

#### What product versions and settings are you using when this issue occurs?
* PHP: 5.2.17
* WordPress: 4.8.3
* WooCommerce: 3.2.3
* Polylang:  2.2.5
* Hyyan WooCommerce Polylang Integration:  1.0.3
* Browser: Chromium

#### Steps to Reproduce
1. Install
1. Activate

#### What I Expected
Activated plugin

#### What Happened Instead
I've got error:
Parse error: syntax error, unexpected T_STRING in /wp-content/plugins/woo-poly-integration/__init__.php on line 35

**Comment by hyyan** [comment]
@sergsoft  You need at least PHP5.3 to run the plugin
