### ISSUE TITLE
Trouble Hyyan WooCommerce Polylang Integration

### ISSUE THREAD

**Issue by Rtutis** [hyyan/woo-poly-integration#260]
When you install the plugin causes a fatal error Hyyan WooCommerce Polylang Integration Parse error: syntax error, unexpected T_STRING in /home/u12169/nadintango.com/www/wp-content/plugins/woo-poly-integration/__init__.php on line 35
Please help.

**Comment by theleemon** [comment]
Which PHP version is your hosting running? The plugin needs 5.3 at least.

**Comment by Rtutis** [comment]
Thanks, after changing PHP version, plugin earned. The only built - in product slider in the template stopped working.

**Comment by theleemon** [comment]
@hyyan @Jon007 Might be a good idea to add the new "Requires PHP" tag in the readme.txt file in the next version of the plugin:

https://make.wordpress.org/plugins/2017/08/29/minimum-php-version-requirement/

**Comment by hyyan** [comment]
@theleemon That is a good idea , I did not know about this tag , Thanks :)
