### ISSUE TITLE
Attribute's terms are not translated

### ISSUE THREAD

**Issue by sergsoft** [hyyan/woo-poly-integration#262]
#### Can you reproduce this issue on default Wordpress theme (eg Storefront)?
y

#### Can you reproduce this issue when all other plugins are disabled except WooCommerce, Polylang and Hyyan WooCommerce Polylang Integration?
y

#### What product versions and settings are you using when this issue occurs?
* PHP: 7.1.11
* WordPress: 4.8.3 
* WooCommerce: 3.2.3 
* Polylang: 2.2.5
* Hyyan WooCommerce Polylang Integration: 1.0.3
* Browser: Chromium

#### Steps to Reproduce
1. Make a variative product
1. Make a attribute
1. Fill attribute with EN and RU terms
1. Assign it to main EN product
1. In RU product atributes & terms had been synchronized

#### What I Expected
In RU product terms for attributes should be translated

#### What Happened Instead
I observe still EN terms

**Comment by Jon007** [comment]
Please check the settings are set correctly:  you can change the settings to either synchronise or translate for each attribute, it's up to you, see:  https://github.com/hyyan/woo-poly-integration/wiki/Product-Attributes

note that Hyyan WooCommerce Polylang Integration: 1.0.3 does not support WooCommerce: 3.2.3 as yet.  If after checking the settings you still have a problem, it may be best to raise as a new issue with more details about your chosen synchronization settings.

**Comment by sergsoft** [comment]
There is my settings
![bug](https://user-images.githubusercontent.com/7553788/32832323-c2550806-ca03-11e7-8e28-f7c678902711.png)

**Comment by Jon007** [comment]
check the woopoly settings as well.

It's difficult for me to understand your screen in Russian and I haven't tested woocommerce 3.2.3
However I assure you this does work on other sites, at least with woocommerce 3.1.2...

**Comment by sergsoft** [comment]
Thanks for fast answer.
I'll try to downgrade Woo version.
If it doesn't help I'll resend settings in En location (But I don't see any lang switcher in admin panel, I'm a newbie in WP).

**Comment by Jon007** [comment]
Users, Your Profile, Language switches languages.   Don't know what it is called in Russian though.

**Comment by sergsoft** [comment]
I've downgraded Woo, but it didn't help!
![bug2](https://user-images.githubusercontent.com/7553788/32835031-49b3e0b6-ca0d-11e7-822e-631749df94c2.png)

**Comment by sergsoft** [comment]
I've forgotten to all polylang settings
![poly settings](https://user-images.githubusercontent.com/7553788/32835207-f09e8e08-ca0d-11e7-8452-6030c8ec130f.jpg)

**Comment by sergsoft** [comment]
It seems it was data quality problem.
I've removed attribute in that product and readded it again. Now it works well.

**Comment by sergsoft** [comment]
Many thanks for your support!
