### ISSUE TITLE
activation causes infinite loop in wp-admin with some other plugin (and memory exhausted)

### ISSUE THREAD

**Issue by philippehenri** [hyyan/woo-poly-integration#266]
When a plugin such as XML-RPC (https://wordpress.org/plugins/manage-xml-rpc/) is installed and active,

the activation of woo-poly-integration causes an infinite loop and memory exhaustion in wp-admin (only in wp-admin)

This problem can probably happen with other plugins as well...
 
If we deactivate xml-rpc, woo-poly-integration will activate sucessfully. But then if we activate xml-rpc the infinite loop will happen again…
 
the problem is linked to the call to "flush rewrite rules", i guess that there is an infinite loops which eats all memory there. Here is some code showing how some changes will avoid the problem (but do not fix it obviously):
 
- in "endpoints.php" if we comment out "flush_rewrite_rules();" ("function rewriteEndpoints()")  then both plugins can live together
 
- similarlly if we leave your "endpoints.php" untouched, and comment out  the function " mxr_htaccess_contents" in xml-rpc (which call $wp_rewrite->flush_rules) then both plugin can also live together

It was extremely hard to find out where the problem occurs, so maybe a check/notification to avoid this crash or a solution might be useful :)

regards
philippe

**Comment by Jon007** [comment]
Was this against 1.0.3 or master branch?
This might be related to #248 for which there was a fix in master?

**Comment by Jon007** [comment]
correction, I can't find this fix in master but try:
https://github.com/hyyan/woo-poly-integration/commit/c489d54ee15e812bd3f5d895862db8d6a5d7d446

**Comment by Jon007** [comment]
see new fix on #248

**Comment by Jon007** [comment]
Let's close this then as solved by the commit on #248
#248 will remain open for now for consideration as to whether to do a one time flush rewrite rules on upgrade or leave to manual instruction

**Comment by hyyan** [comment]
Re-open after revert of e71df4d6a88e78ee03220152782a2eaaaf3e7773
