### ISSUE TITLE
Header cart icon of second language redirects to default language cart

### ISSUE THREAD

**Issue by bene25** [hyyan/woo-poly-integration#274]
Hello. Header cart icon of second language redirects to default language cart.

WP Version 4.9
WooCommerce 3.2.5
Hyyan WooCommerce Polylang Integration 1.0.3
PolyLang 2.2.6
Theme Flash 1.1.7 (https://demo.themegrill.com/flash/demos/)

**Comment by stilabdo** [comment]
I am having the same problem here. When you add a product to cart in a second language, the default language variant of the product got chosen.

**Comment by Jon007** [comment]
@bene25 in that case the cart page is not translated into the second language, or for example it is translated but not in the status published.

@stilabdo that's a different problem not the same problem.  In your case the product is not published in the other language.
This is fallback behaviour of this plugin, in case you switch language and the product is not available in the other language, it will show the original language version of the product rather than invisible product.

Please note Hyyan WooCommerce Polylang Integration 1.0.3 does not support WooCommerce 3.2.5 and some issues may be expected, please test with the master branch where some changes are being made.

**Comment by stilabdo** [comment]
@Jon007 Thanks for your feedback, in my case, the products are translated, integrated and published. Maybe the problem caused due to the lack of support for WooCommerce 3.2.5

**Comment by bene25** [comment]
@Jon007 @stilabdo in my case second language cart is also translated and published.

**Comment by Jon007** [comment]
@stilabdo, @bene25 Please note, this functionality is not part of this plugin so can't be kept as an open issue against this plugin.  I have retested on my installation and language switcher continues to work properly on both cart pages and product pages _even after this plugin is deactivated_.

If your permalinks are set up correctly the language switcher will work correctly for cart page and product pages in exactly the same way as they work for any other page or post, which is what these are as far as Polyang knows.  check you have this working for normal page and normal post.
So no, this should not be affected by WooCommerce 3.2.5 etc.

So please check your permalinks, translations and Polylang documentation.
Avoid "language is set from content" option for polylang permalinks.

**Comment by stilabdo** [comment]
You're right @Jon007 in my case it turned out that it has nothing to do with WooPoly, Thanks for the lead. @bene25 I re-adjusted the Synchronization setting in Polylang, and the issue resolved.

**Comment by bene25** [comment]
I have "The language is set from the directory name in pretty permalinks", all blog, posts, pages are work correctly in two languages. When I cover product cart on the second language and cart is empty or has something it shows me items or empty cart message on default language.

**Comment by Jon007** [comment]
@bene25 oh wow that's a completely different problem and not what I understood.

This will be a woo 3.2.x problem, can you change the title to "cart ajax call always returns mini-cart in base language"
This is the same thing that happens with the ajax calls on the cart and checkout page with 3.2.x. - see #256 

Please would you try:

1. update to Polylang 2.2.7
1. confirm whether you see this behaviour for anonymous users, logged in users or both
1. there is a fix for this #251 which is included on the master branch please use the latest code from master branch.
After updating to the latest code please go to Settings, Permalinks and Save.  This is for another fix to avoid saving permalinks on every page load....

**Comment by bene25** [comment]
1) update to Polylang 2.2.7
Updated
2) confirm whether you see this behaviour for anonymous users, logged in users or both
Confirm for both
3)I have permalinks settings
![image](https://user-images.githubusercontent.com/11219968/33544656-477025b8-d8e4-11e7-99ea-4ab2e96f40aa.png)
and 

![image](https://user-images.githubusercontent.com/11219968/33544670-58221786-d8e4-11e7-8a05-1c22cd5b68f6.png)

Looks like it works). Cart on second language redirects to the second (correct)  language checkout and shows items on second (correct) language.
