### ISSUE TITLE
How to properly and completely uninstall Woo Poly Integration?

### ISSUE THREAD

**Issue by ana-do-kastelo90** [hyyan/woo-poly-integration#275]
Hi. I like the plugin, but it's not what I am looking for. Instead of Polylang I'm looking forward for an automatized translation plugin like GTranslate.

 How to properly uninstall the Woo Poly plugin? Cache included.

 Thanks

**Comment by Jon007** [comment]
Just uninstall like any other plugin.

This plugin doesn't keep a cache but you might want to clear transients using WooCommerce, Status, Tools.  Any similarly if you have any caching plugin like WP Super Cache.

You may or may not want to delete any translations you have created.  You can just switch the Polylang language view, select all and delete.
