### ISSUE TITLE
Instead of the thousands separator, the symbol �

### ISSUE THREAD

**Issue by lavytory** [hyyan/woo-poly-integration#277]
![screenshot_2](https://user-images.githubusercontent.com/34288644/33636502-27f460ae-da25-11e7-8575-01763c3dc67b.png)
Hello. Instead of the thousands separator in the price of the goods, a symbol is displayed - �. When the plug-in is deactivated, the price is displayed normally.

**Comment by hyyan** [comment]
@lavytory believe this is related to the encoding you are using,  are using UTF-8 ?

**Comment by Jon007** [comment]
Note, woopoly is using standard PHP api to format the number according to the current page locale.
It looks like your font isn't supporting your locale's thousands separator...

This feature of the plugin can be turned off on Settings, WooPoly, Features, "Use locale number formats"

**Comment by lavytory** [comment]
Thank you so much. Everything works as it should.
