### ISSUE TITLE
Error changing the language on the store page

### ISSUE THREAD

**Issue by jBenejam** [hyyan/woo-poly-integration#279]
Hello, I'm new here and I do not know if I can ask in this forum, but I'll expose my problem.
The plugin works perfectly except when I go to the shop page configured in the woocommerc settings, from the browser and change the language, I get the following error: Call to a member function get_id () on null in public_html/wp-content/themes/cena/woocommerce/item-product/inner-list.php on line 3.
The shop page is correctly translated and published. 
Any ideas?
Thank you.

**Comment by hyyan** [comment]
@jBenejam This error is coming from your theme `cena` it is not because of this plugin, check the file which throws the error.

Closing as not related to the plugin.
