### ISSUE TITLE
Variation Does not Synchronise in another language

### ISSUE THREAD

**Issue by arkerphyo92** [hyyan/woo-poly-integration#281]
using Storefront

only with WooCommerce, Polylang and Hyyan WooCommerce Polylang Integration 3 plugins

What product versions and settings are you using when this issue occurs?
* PHP: 5.6.30
* WordPress: 4.9.1
* WooCommerce: 3.2.6
* Polylang: 2.2.7
* Hyyan WooCommerce Polylang Integration: 1.0.4
* Browser: Mozilla

1. adding attributes from Attributes page.
1. adding variation in add new product page(variable product).
(4 variation)
1. i use only 2 language (english and myanmar)
1. when i buy from one language, another language stock does not reduce.

cart page like this when i buy 1 from each language.
![25530238_1899260540403210_777932658_n](https://user-images.githubusercontent.com/16502145/34157663-f25cdb66-e4f0-11e7-86d3-1fa803d9b3da.png)

**Comment by Jon007** [comment]
there are quite a few settings that might affect this.

- please confirm Stock synchronisation is checked in Settings/woopoly/features and Settings/woopoly/meta
- please check the actual product:  when you edit the product go to the Inventory section, and look at:
Manage stock?  []  Enable stock management at product level

If you want stock to be managed at the variation level, this checkbox must be cleared on the product.
Then go to the variations section and ensure Manage Stock is checked on the individual variations.

I don't use this feature and haven't checked it on 3.2.6 but it did work on previous versions

**Comment by arkerphyo92** [comment]
select in stock synchronisation
nth filled in inventory.
enable in manage stock on the individual variations.

still it does not work in different language of variation product. :(

**Comment by arkerphyo92** [comment]
i got it sit.
when i change themes. it is ok. thz

**Comment by arkerphyo92** [comment]
it also need clear in shipping information of product level.
after that i got it. really thz sir.

**Comment by Jon007** [comment]
ok good!
since it is resolved, let's close the issue
