### ISSUE TITLE
How to update the title in languages via PHP

### ISSUE THREAD

**Issue by ajkoft** [hyyan/woo-poly-integration#282]
Hello,

I've a small big problem,  how to edit the title of the Woocommerce product via PHP in non-main language with this plugin and polylang?

e.g. I have a post in English, and have addition languages in Thai and Chinese.

If I update the 'post_title' only the main language is updated,  but not the other languages.

**Comment by Jon007** [comment]
you need to switch to the Thai version of the post and edit the title there....
Please read the Polylang documentation and make sure you understand how to use Polylang for editing normal posts before applying to products - it's the same, a Product is a special type of Post.

This plugin does not change the handling of title, it mainly extends the Polylang Post handling for the extra woocommerce fields and concepts, so will close as out of scope of this plugin.
