### ISSUE TITLE
About Restock In Both Language

### ISSUE THREAD

**Issue by arkerphyo92** [hyyan/woo-poly-integration#284]
i wanna know about restock.
woo poly can effect or not to restock both languages?
my site woocommerce restock only work in one language.

thz sir.

**Comment by Jon007** [comment]
It's an option whether you want stock to be synchronized across both languages or whether you have separate stock for each language.

Please check the documentation on https://github.com/hyyan/woo-poly-integration/wiki regarding Stock feature and synchronisation settings and please use the required templated for opening issues on this project.
