### ISSUE TITLE
WooCommerce-Polylang-Hyyan WooCommerce Polylang Integration Problem

### ISSUE THREAD

**Issue by KavehKavandi** [hyyan/woo-poly-integration#285]
Hi
I have a big problem and I thank you can help me.
Tow week ago every thing was ok but now in English version of my site every thing is ok but in turkish it is not!
My site is www.nikasys.com .
In Products menu in English, the Product categories's and Product 's links are ok but in Turkish they are not. 

For Example in Turkish of one product, the true links is:
http://www.nikasys.com/product/toosun-tr/

But when I use the Menu (in Turkish Menu: ÜRÜNLER > PDKS ve Erişim Kontrol > TOOSUN),
the link is change to :
http://www.nikasys.com/urun/toosun-tr/
(this is wrong link)

And in Product categories I have a problem like this too.

Very thanks for your help.

Kind Regards, Kaveh.

**Comment by Jon007** [comment]
the plugin doesn't really affect your menu, the menu is not filtered by language so it is quite possible to add English products to your Turkish menu.
When editing the Turkish menu, switch your Polylang language to Turkish and make sure you pick the Turkish versions of the products to add to the menu.

Also, this might also be incorrect or missing permalinks setup, make sure you have permalink information set for woocommerce under settings, permalinks.   
if left blank they revert to the woocommerce default for the current display language (which doesn't actually work, these settings are not translatable and need to be set)

**Comment by KavehKavandi** [comment]
Hey @Jon007 
Thanks for your replay
I did not add English products to Turkish Menu and you can see the link is ok in Menu Structure :
[https://drive.google.com/open?id=1ICDd9OzipNHx7jXTqAGDxbzoJbqZEDA3](url)

But when anyone use the menu, another link is showing! :
[https://drive.google.com/open?id=1HmpN6hl0yx-IDcZyCdqe7TxYVIZZOGks](url)

And i don't know the true setting for permalinks! What can I do?
And very very thanks for your help.

My Permalink Settings:
[https://drive.google.com/open?id=1ajgFbOATkvWgm-lHqVOw09VMXbaBD-aa](url)
[https://drive.google.com/open?id=16G5PwOanA73GJclV19E5DADbPrYLSo8U](url)
[https://drive.google.com/open?id=1exXXrmtehgfzRlqIro9IryaqNwV3HZDR](url)

Regards, Kaveh

**Comment by KavehKavandi** [comment]
Hey @Jon007 
Thanks for your replay
I did not add English products to Turkish Menu and you can see the link is ok in Menu Structure :
https://drive.google.com/open?id=1ICDd9OzipNHx7jXTqAGDxbzoJbqZEDA3

But when anyone use the menu, another link is showing! :
https://drive.google.com/open?id=1HmpN6hl0yx-IDcZyCdqe7TxYVIZZOGks

And i don't know the true setting for permalinks! What can I do?
And very very thanks for your help.

My Permalink Settings:
https://drive.google.com/open?id=1ajgFbOATkvWgm-lHqVOw09VMXbaBD-aa
https://drive.google.com/open?id=16G5PwOanA73GJclV19E5DADbPrYLSo8U
https://drive.google.com/open?id=1exXXrmtehgfzRlqIro9IryaqNwV3HZDR

Regards, Kaveh

**Comment by Jon007** [comment]
I think the product permalink base needs to be set rather than default, here:
https://drive.google.com/file/d/1exXXrmtehgfzRlqIro9IryaqNwV3HZDR/view

you can call it product or p or whatever you like but this part must be set

**Comment by KavehKavandi** [comment]
Hey @Jon007 
Very very thanks, now every thinks are ok.

Kind Regards, Kaveh

**Comment by Jon007** [comment]
great, let's close the issue then.
