### ISSUE TITLE
Elementor Compatibility

### ISSUE THREAD

**Issue by RashidSy** [hyyan/woo-poly-integration#286]
Hallo
Can you help me please?
When I activate the plugin, I can not edit the texts in the Elementor(Plugin).
What should i do?
Thanks for your support
Best regards
Rashid

**Comment by hyyan** [comment]
@RashidSy I do not know what Elementor is ? but If got this right you can disable 'Fields Loker' in woopoly settings page

**Comment by hyyan** [comment]
close for inactivity
