### ISSUE TITLE
Translate email contents

### ISSUE THREAD

**Issue by ddstreetfood** [hyyan/woo-poly-integration#287]
#### Can you reproduce this issue on default Wordpress theme (eg Storefront)?
Yes

#### Can you reproduce this issue when all other plugins are disabled except WooCommerce, Polylang and Hyyan WooCommerce Polylang Integration?
Yes

#### What product versions and settings are you using when this issue occurs?
* PHP: 
* WordPress: 4.9.1.
* WooCommerce: 3.2.6
* Polylang: 2.2.7
* Hyyan WooCommerce Polylang Integration: 1.0.4
* Browser: Safari

#### Steps to Reproduce

Trying to edit the content (not just easily editable fields like Subject) of emails to clients in both EN and CZ.
1. WooCommerce>Settings>Emails>Processing Order
2. I click "Copy File to Theme" and then edit the content and save.

#### What I Expected
That the newly edited strings would show up in the Strings Translation of Polylang.

#### What Happened Instead
No new strings show up in the Strings Translation. I assume that this process only works for translating predefined fields like Subject and Email Heading and not for the actual content? I installed Loco Translate but it seems to also only apply to predefined strings and not to email content.

Just for clarification, I have the CZ language packs installed so getting the emails to send in both languages is no problem, just getting them edited so the CZ content matches the EN.

Thanks!

**Comment by Jon007** [comment]
well which part of the content are you trying to edit exactly?

1) If it is the message part you can simply use Loco Translate to create additional language files to override the default messages which are provided in the woocommerce .mo and .po files - see Loco Translate documentation.
Personally this is the option I use.   
Note that it is the plugin woocommerce itself that is providing these message in its translation files.

2.If you prefer to add a separate message and add it to the string translation table then you need to register the string yourself using the __pll() and pll_register_string() functions - see Polylang documentation for how to do that.
you can either 

2.1 add to your copy of the template 
2.2 Or add your own hook to the woocommerce actions in your theme functions.php file or your own plugin

I have an example here of adding a translatable message to the shipping calculator area of the woocommerce cart and checkout pages, you could use similar technique to add an extra message to the emails.  
https://jonmoblog.wordpress.com/2017/12/03/quick-multi-lingual-messages-for-wordpress-woocommerce/
But option 1 with Loco translate is all you need in my opinion.

see also https://github.com/hyyan/woo-poly-integration/wiki/Translation-Overview and elsewhere on this wiki to understand about the different types of translations.

**Comment by ddstreetfood** [comment]
Great, I'll give it a shot through Loco Translate. Thanks so much!
