### ISSUE TITLE
Plugin prevents adding/changing/removing product image

### ISSUE THREAD

**Issue by jgorgulho** [hyyan/woo-poly-integration#288]
Hello,

   I'm currently using your plugin to set up a page with two languages, but when using your plugin I'm not able to set the product image. Given that I'm doing the website for a client, I can't just deactivate your plugin whenever I want to add new products.

#### Can you reproduce this issue on default Wordpress theme (eg Storefront)?
The problem happens at the admin page so the theme should be irrelevant(?), but I'm using a child theme of Storefront.

#### Can you reproduce this issue when all other plugins are disabled except WooCommerce, Polylang and Hyyan WooCommerce Polylang Integration?
Having all other plugins deactivated except these three doesn't make any difference.

#### What product versions and settings are you using when this issue occurs?
* PHP: 7.2.0
* WordPress: 4.9.1,
* WooCommerce: 3.2.6
* Polylang: [state if using Polylang PRO] 2.2.7 (not PRO)
* Hyyan WooCommerce Polylang Integration: 1.0.4 
* Browser:  Firefox 57.0.1, Chromium 63.0.3239.108

#### Steps to Reproduce
A. Adding Product picture
1. Create a product on the admin interface of Wordpress with Woocommerce
2. Click the "Set product image" and select an image 
3. Press "Set featured image" 

B. Changing Product picture
1. Access a product page on the admin interface of Wordpress with Woocommerce
2. Click the Product image and select a new image 
3. Press "Set featured image" 

C. Removing product image
1. Access a product page on the admin interface of Wordpress with Woocommerce
2. Click on Remove product image

#### What I Expected
A. Adding Product picture
There would be a featured image for the project.

B. Changing Product picture
There would be a new featured image for the project.

C. Removing product image
The featured image would no longer be selected.

#### What Happened Instead
A. Adding Product picture
After pressing "Set featured image" there's still no featured image selected.

B. Changing Product picture
After pressing "Set featured image" the featured image is still the same.

C. Removing product image
After clicking on Remove product image, nothing happens and the featured image is still selected.

**Comment by Jon007** [comment]
featured image synchronisation has always worked fine, I just retested on the versions you specified.
I suggest you must have a some conflicting function in your theme or another plugin.

Please try it with Storefront and with other plugins deactivated (only woocommerce, polylang, woopoly turned on).  You should find that works, so then you can activate other plugins until you find which one is having the conflict.
 
In any case post Featured Image synchronisation is provided by Polylang, it is not a special feature of woocommerce or this plugin so I'll close it here for that reason.
