### ISSUE TITLE
Translation Categories settings doesn't appear

### ISSUE THREAD

**Issue by germanoproiettibartolucci** [hyyan/woo-poly-integration#289]
Hi everyone, I Installed Woo Poly Integration on Woocommerce 3.2.4

Permalink settings go well, and also polylang settings of permalink.

But in setting section on category and tag translation it shows a blank page. What's about?

Thanks to everyone who could answer.

Germano

#### What product versions and settings are you using when this issue occurs?
* PHP: 
* WordPress: 
* WooCommerce: 
* Polylang: [state if using Polylang PRO]
* Hyyan WooCommerce Polylang Integration: 
* Browser: 

#### Steps to Reproduce
1. 
1. 
1.

**Comment by Jon007** [comment]
check the Polylang settings:
Languages, Settings, Custom post types and Taxonomies, Settings

and ensure that:
Custom taxonomies
 Product categories, Product tags
are enabled

**Comment by hyyan** [comment]
@germanoproiettibartolucci   still an issue ?

**Comment by hyyan** [comment]
close for inactivity
