### ISSUE TITLE
Notice: get_translations was called incorrectly

### ISSUE THREAD

**Issue by smeric** [hyyan/woo-poly-integration#29]
Hi,

Thanks for the plugin :)

I wanted to report a notice. I'm using WP 4.5, Hyyan WooCommerce Polylang Integration 0.25 and Polylang 1.8.5 :
`Notice: get_translations was called incorrectly in .../wp-content/plugins/woo-poly-integration/src/Hyyan/WPI/Endpoints.php on line 306: the call to $polylang->model->get_translations() has been deprecated in Polylang 1.8, use PLL()->model->post->get_translations() instead. Error handler in .../wp-content/plugins/polylang/include/model.php on line 546`

Hope that will help.

Séb.

**Comment by hyyan** [comment]
Fixed now
