### ISSUE TITLE
Products not added to shipping classes

### ISSUE THREAD

**Issue by ddstreetfood** [hyyan/woo-poly-integration#290]
#### Can you reproduce this issue on default Wordpress theme (eg Storefront)?
YES

#### Can you reproduce this issue when all other plugins are disabled except WooCommerce, Polylang and Hyyan WooCommerce Polylang Integration?
YES

#### What product versions and settings are you using when this issue occurs?
* PHP:
WordPress: 4.9.1.
WooCommerce: 3.2.6
Polylang: 2.2.7
Hyyan WooCommerce Polylang Integration: 1.0.4
Browser: Safari

#### Steps to Reproduce
1. Create 2 shipping classes: Catering and Retail
2. Bulk edit products and assign each product to appropriate shipping class OR assign products to shipping classes manually in the product editing panel.
3. Settings>Shipping>Shipping Classes

#### What I Expected
-Shipping Classes panel will show 2 classes, each with the proper number of products.
-Correct shipping cost will be applied to each product in the shopping cart based on its shipping class.

#### What Happened Instead
-2 new shipping classes were automatically created to correspond to the other language that my site is in, for a total of 4 shipping classes.
-The "Product Count" displayed next to each shipping class adds up to more than my total number of products. I added 8 products, 4 CZ and 4 EN, to the Retail shipping class. The panel now shows a product count of 7 Retail CZ and 5 Retail EN.
-When clicking on the positive number "Product Count" link, I'm shown a panel that says "no products found".
-Shipping prices aren't applied correctly to products in the shopping cart.

**Comment by Jon007** [comment]
I didn't reproduce this for standard editing but maybe the bulk edit isn't handling this as per #234

**Comment by ddstreetfood** [comment]
Yeah, bulk editing isn't handling shipping class changes, and when I enter the shipping classes while setting up the products, about 80% of them revert back to "no shipping class" after saving. The workaround I've been using is to Quick Edit all the products and then the shipping class sticks for like 90% of them. I still have 5 stubborn products that have a set shipping class but don't display the proper shipping price in the cart/checkout.

**Comment by Jon007** [comment]
if you are seeing inconsistent behaviour like that, it could be a multiple window problem?
ie if you have multiple windows open and change something in one window by bulk editing and another in a product edit window, then you might lose the first change  - the product windows don't auto-refresh the details so if you do open a load of windows it is easy to accidentally overwrite with old details

**Comment by ddstreetfood** [comment]
Nope, no multiple windows open. I really can't see anything that these 5 products have in common.

**Comment by Jon007** [comment]
@ddstreetfood , one more thing to try.

Please try the following:
– go to the Polylang settings, Language, Settings (usually at /wp-admin/admin.php?page=mlang_settings), Custom post types and Taxonomies, Custom Taxonomies
– if Product shipping classes is selected please unselect it and Save Changes

Shipping class should now work normally.
As Shipping Class is not translatable, when this option is selected the translated shipping class cannot be found so is not copied correctly.

**Comment by ddstreetfood** [comment]
Yes, that fixed it! Thanks a lot!
