### ISSUE TITLE
Cannot edit a product that does not have a translation in the default language

### ISSUE THREAD

**Issue by fakeartist** [hyyan/woo-poly-integration#294]
#### Steps to Reproduce
1. Create a product in the language that is not the default (eg. my default language is english, and i want to create a product in german only).
1. Try to change the price or product type.

#### What I Expected

To be able to edit a product that does not have a translation in the default language.

#### What Happened Instead

Cannot edit the product that does not have a translation in the default language.

**Comment by hyyan** [comment]
You can disable `Fields Locker` in the plugin settings page 

Feel free to re-open if stills an issue
