### ISSUE TITLE
Translate Form Fields

### ISSUE THREAD

**Issue by ddstreetfood** [hyyan/woo-poly-integration#297]
I'm having a bit of trouble translating a couple things which don't appear in the Loco Translate panel or in the PolyLang strings translate:

1. Fields on the Checkout page that were added with the plug-in Checkout Field Editor (their support doesn't know anything about this).

2. "There are no shipping methods available. Please ensure that your address has been entered correctly, or contact us if you need any help."

Any ideas?
Thanks!

**Comment by Jon007** [comment]
1. This plugin only adds additional Polylang support to WooCommerce, it does not add Polylang support to other plugins such as Checkout Field Editor, you would request Polylang support on Checkout Field Editor or implement an alternative solution.
2. This string is provided by the WooCommerce plugin translation files, so it can be customised with Loco Translate.
