### ISSUE TITLE
Error checkout

### ISSUE THREAD

**Issue by miraged** [hyyan/woo-poly-integration#3]
When i want to confirm order i get:
Fatal error: Call to undefined function Hyyan\WPI\wc_get_product() in /home/****/domains/****.com/public_html/wp-content/plugins/woo-poly-integration/src/Hyyan/WPI/Utilities.php on line 72

**Comment by hyyan** [comment]
@mirgaed the plugins works with woocommerce 3  and above only , are you sure you are using the latest version of woocommerce

**Comment by miraged** [comment]
thank you, i was testing with 2.1.12 version
