### ISSUE TITLE
Online payment page not in the proper language 

### ISSUE THREAD

**Issue by tomchap** [hyyan/woo-poly-integration#30]
Hi, 
our site has two languages, English and French. We're using Woocommerce, Polylang and Hyyan Woo Poly integration. Whatever the language that we're using when using the web site - English or French - , we're always redirected to the French version of the bank page (Monetico system). We can see with the debug page that the site does always call the French version of the bank page, so not an issue on the bank side.
Would you know what might be wrong?
Thanks,
Thomas

**Comment by theblackhole** [comment]
What plugin do you use for your payment system (it's working for me with [WooCommerce ATOS Gateway](https://github.com/doctype-fr/woocommerce-gateway-atos))

**Comment by tomchap** [comment]
We're using WooCommerce Monetico Gateway, but it seems we have resolved the issue. Thanks.

**Comment by DanielBonnery** [comment]
Hi,
We have the same problem, and we do not know how to solve the issue.
Any clue ?

Bests,
Daniel
