### ISSUE TITLE
How to duplicate products?

### ISSUE THREAD

**Issue by mai1809** [hyyan/woo-poly-integration#301]
#### Can you reproduce this issue on default Wordpress theme (eg Storefront)? 
yes

#### Can you reproduce this issue when all other plugins are disabled except WooCommerce, Polylang and Hyyan WooCommerce Polylang Integration?
yes

#### What product versions and settings are you using when this issue occurs?
* PHP: 7.0.27
* WordPress: 4.9.2
* WooCommerce: 3.2.6
* Polylang: 2.3
* Hyyan WooCommerce Polylang Integration: 1.0.4
* Browser: safari

#### Steps to Reproduce
1. 
1. 
1. 

#### What I Expected
I expected to be able to set the products to the languages i wish but I can't choose language. I just want to know how to duplicate / set up a product from one language to another so that it works. 

#### What Happened Instead
I can't set the product language

## WordPress Environment

<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.
```
</details>

**Comment by mai1809** [comment]
Hi,

I just started using this plugin so that I can setup woo commerce to different languages. The pages "shop", "my account" ect. works fine but how do I duplicate the products / set the products to the new languages?

**Comment by Jon007** [comment]
it's the same as translating a post - check the Polylang documentation.
First, create the product in base language, then, while still in the product edit screen, go the the 'Languages' box and under Translations, press the plus next to the language flag.
Do not change the language of existing products, do it as translation instead.

Closing as this is standard Polylang functionality not implemented by this plugin.
