### ISSUE TITLE
Product can be editable in only main language

### ISSUE THREAD

**Issue by dogukanoksuz** [hyyan/woo-poly-integration#302]
Hey, first thanks for sharing this plugin for free.

I have a problem, when i add products no problem but after i wanna edit them i just be able to do that on main language.

Tried couple of versions of plugins
Wordpress: latest
Woocommerce: latest / 3.1.1
Polylang: free latest
PHP: 5.6/7.0/7.1/7.2 doesn't even matter

When i disable the plugin it works like a charm but you know the deal.

<details>
`
### WordPress Environment ###

Home URL: http://eticaret.loc
Site URL: http://eticaret.loc
WC Version: 3.1.1
Log Directory Writable: ✔
WP Version: 4.9.4
WP Multisite: –
WP Memory Limit: 4 GB
WP Debug Mode: –
WP Cron: ✔
Language: tr_TR

### Server Environment ###

Server Info: nginx/1.12.1
PHP Version: 7.1.9
PHP Post Max Size: 2 GB
PHP Time Limit: 180
PHP Max Input Vars: 8000
cURL Version: 7.29.0
NSS/3.21 Basic ECC

SUHOSIN Installed: –
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.1.1
WC Database Prefix: dd_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ❌ MaxMind GeoIP veritabanı bulunmuyor - Geo konumlama çalışmayacak. http://dev.maxmind.com/geoip/legacy/geolite/ adresinden indirip şuraya kendiniz kurabilirsiniz: . "Downloads" bölümüne gelerek "GeoLite Country" satırındaki "Binary / gzip" dosyasını indiriniz. Lütfen GeoIP.dat.gz dosyasını açmayı ve sadece GeoIP.dat dosyasını yüklemeyi unutmayınız.

### Security ###

Secure connection (HTTPS): ❌Mağazanız HTTPS kullanmıyor. HTTPS and SSL sertifikaları hakkında bilgi alın.
Hide errors from visitors: ✔

### Active Plugins (5) ###

Polylang: (Frédéric Demarle) – 2.3
Fancy Admin UI: (Bob Orchard) – 2.1
Woo Multi Currency: (VillaTheme) – 2.0.7.3
Hyyan WooCommerce Polylang Integration: (Hyyan Abo Fakher) – 1.0.4
WooCommerce: (Automattic) – 3.1.1 – 3.3.1 mevcut

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: TRY (₺)
Currency Position: left_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Mağaza giriş sayfası: #4 - /tr/magaza/
Sepet sayfası: #5 - /tr/sepet/
Ödeme sayfası: #6 - /tr/odeme/
Hesabım sayfası: #7 - /tr/hesabim/

### Theme ###

Name: Storefront
Version: 2.2.7
Author URL: https://woocommerce.com/
Child Theme: ❌ – WooCommerce'i kendinizin oluşturmadığı ana bir temada düzenliyorsanız
yardımcı bir tema kullanmanızı öneririz. Bkz.: Nasıl yardımcı tema oluşturulur?

WooCommerce Support: ✔

### Templates ###

Overrides: –
`
</details>

**Comment by hyyan** [comment]
@dogukanoksuz  The is a plugin feature which can be disabled from the settings page `Settings -> Woopoly -> Fields Locker`

Please feel free to re-open if stills a problem
