### ISSUE TITLE
JS conflict

### ISSUE THREAD

**Issue by ddstreetfood** [hyyan/woo-poly-integration#306]
#### Can you reproduce this issue on default Wordpress theme (eg Storefront)?
Yes
#### Can you reproduce this issue when all other plugins are disabled except WooCommerce, Polylang and Hyyan WooCommerce Polylang Integration?
No
#### What product versions and settings are you using when this issue occurs?
* PHP: 
* WordPress: 4.9.4
* WooCommerce: 3.3.1
* Polylang: [state if using Polylang PRO] 2.3.1
* Hyyan WooCommerce Polylang Integration: 1.0.4
* Browser: Chrome and Safari

#### Steps to Reproduce

There seems to be a conflict between WooPoly and various FAQ plugins which disables the Javascript toggle function on the FAQs. When WooPoly is deactivated, the FAQ answers toggle open normally when clicked. When WooPolly is activated, they either become unclickable or they open in a new window.

This conflict has been isolated to WooPoly. I'm currently using the plugin Ultimate FAQ but I also tested out Acronix FAQ and ran into the exact same problem.

Is there anything in the WooPoly that uses JS that could be causing this conflict?

## WordPress Environment

<details>
```
`
### WordPress Environment ###

Home URL: http://www.ddstreetfood.cz
Site URL: http://www.ddstreetfood.cz
WC Version: 3.3.1
Log Directory Writable: ✔
WP Version: 4.9.4
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.31
PHP Post Max Size: 128 MB
PHP Time Limit: 30
PHP Max Input Vars: 5000
cURL Version: 7.57.0
OpenSSL/1.0.2m

SUHOSIN Installed: –
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.3.1
WC Database Prefix: wp_
MaxMind GeoIP Database: ❌ The MaxMind GeoIP Database does not exist - Geolocation will not function. You can download and install it manually from http://dev.maxmind.com/geoip/legacy/geolite/ to the path: . Scroll down to "Downloads" and download the "Binary / gzip" file next to "GeoLite Country". Please remember to uncompress GeoIP.dat.gz and upload the GeoIP.dat file only.
Total Database Size: 16.49MB
Database Data Size: 13.20MB
Database Index Size: 3.29MB
wp_woocommerce_sessions: Data: 0.06MB + Index: 0.02MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_order_itemmeta: Data: 0.05MB + Index: 0.03MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB
wp_comments: Data: 0.02MB + Index: 0.09MB
wp_foodlist_menu_tagmeta: Data: 0.02MB + Index: 0.03MB
wp_links: Data: 0.02MB + Index: 0.02MB
wp_my_calendar: Data: 0.02MB + Index: 0.02MB
wp_my_calendar_categories: Data: 0.02MB + Index: 0.00MB
wp_my_calendar_events: Data: 0.02MB + Index: 0.02MB
wp_my_calendar_locations: Data: 0.02MB + Index: 0.00MB
wp_nf3_actions: Data: 0.02MB + Index: 0.00MB
wp_nf3_action_meta: Data: 0.05MB + Index: 0.00MB
wp_nf3_fields: Data: 0.02MB + Index: 0.00MB
wp_nf3_field_meta: Data: 1.45MB + Index: 0.00MB
wp_nf3_forms: Data: 0.02MB + Index: 0.00MB
wp_nf3_form_meta: Data: 0.02MB + Index: 0.00MB
wp_nf3_objects: Data: 0.02MB + Index: 0.00MB
wp_nf3_object_meta: Data: 0.02MB + Index: 0.00MB
wp_nf3_relationships: Data: 0.02MB + Index: 0.00MB
wp_nf_objectmeta: Data: 0.02MB + Index: 0.00MB
wp_nf_objects: Data: 0.02MB + Index: 0.00MB
wp_nf_relationships: Data: 0.02MB + Index: 0.00MB
wp_ninja_forms_fav_fields: Data: 0.05MB + Index: 0.00MB
wp_ninja_forms_fields: Data: 0.02MB + Index: 0.00MB
wp_options: Data: 6.25MB + Index: 0.27MB
wp_postmeta: Data: 2.48MB + Index: 1.88MB
wp_posts: Data: 1.47MB + Index: 0.31MB
wp_termmeta: Data: 0.02MB + Index: 0.03MB
wp_terms: Data: 0.03MB + Index: 0.03MB
wp_term_relationships: Data: 0.05MB + Index: 0.02MB
wp_term_taxonomy: Data: 0.06MB + Index: 0.03MB
wp_usermeta: Data: 0.19MB + Index: 0.03MB
wp_users: Data: 0.02MB + Index: 0.05MB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB
wp_wpgmza: Data: 0.02MB + Index: 0.00MB
wp_wpgmza_categories: Data: 0.02MB + Index: 0.00MB
wp_wpgmza_category_maps: Data: 0.02MB + Index: 0.00MB
wp_wpgmza_maps: Data: 0.02MB + Index: 0.00MB
wp_wpgmza_polygon: Data: 0.02MB + Index: 0.00MB
wp_wpgmza_polylines: Data: 0.02MB + Index: 0.00MB
wp_wplc_chat_msgs: Data: 0.02MB + Index: 0.00MB
wp_wplc_chat_sessions: Data: 0.02MB + Index: 0.00MB
wp_wplc_offline_messages: Data: 0.02MB + Index: 0.00MB
wp_wplc_webhooks: Data: 0.02MB + Index: 0.00MB
wp_yoast_seo_links: Data: 0.06MB + Index: 0.02MB
wp_yoast_seo_meta: Data: 0.05MB + Index: 0.00MB

### Post Type Counts ###

attachment: 274
calendar: 1
custom_css: 2
customize_changeset: 16
envira: 5
faq: 4
fdm-menu: 2
fdm-menu-item: 1
fl-menu-item: 185
fl-menu-section: 17
jetpack-testimonial: 2
nav_menu_item: 54
nf_sub: 4
nova_menu_item: 19
page: 44
polylang_mo: 2
post: 2
product: 107
product_variation: 166
revision: 645
shop_order: 8
ufaq: 40
wafs: 1

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (25) ###

Polylang: by Frédéric Demarle – 2.3.1
Akismet Anti-Spam: by Automattic – 4.0.2
Autoptimize: by Frank Goossens (futtta) – 2.3.2
Envira Gallery Lite: by Envira Gallery Team – 1.6.2
Facebook for WooCommerce: by Facebook – 1.7.11 – Not tested with the active version of WooCommerce
Foodlist: by Artprima – 1.13
Google Analytics for WordPress by MonsterInsights: by MonsterInsights – 6.2.8
Simple Calendar: by Simple Calendar – 3.1.14
Homepage Control: by WooThemes – 2.0.2
Jetpack by WordPress.com: by Automattic – 5.8
Loco Translate: by Tim Whitlock – 2.1.1
Ninja Forms: by The WP Ninjas – 3.2.13
Remove Query Strings: by LittleBizzy – 1.2.8
ShortPixel Image Optimizer: by ShortPixel – 4.9.1
Ultimate FAQ: by Etoile Web Design – 1.6.16 – Not tested with the active version of WooCommerce
W3 Total Cache: by Frederick Townes – 0.9.6
WC Hide Shipping Methods: by Rynaldo Stoltz – 1.3
WC Speed Drain Repair: by WP Fix It – 1.2 – Not tested with the active version of WooCommerce
Woo IC and DIC: by Vladislav Musílek – 1.1.2
Hyyan WooCommerce Polylang Integration: by Hyyan Abo Fakher – 1.0.4 – Not tested with the active version of WooCommerce
WooCommerce AdWords Conversion Tracking: by Wolf+Bär Agency – 1.4.7 – Not tested with the active version of WooCommerce
Booster for WooCommerce: by Algoritmika Ltd – 3.4.5
WooCommerce Show Attributes: by Isabel Castillo – 1.6.4 – Not tested with the active version of WooCommerce
WooCommerce: by Automattic – 3.3.1 – 3.3.2 is available
Yoast SEO: by Team Yoast – 6.3.1

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: CZK (Kč)
Currency Position: right_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 0
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Shop base: #1519 - /cs/shop/
Cart: #1520 - /cs/kosik/
Checkout: #1521 - /cs/pokladna/
My account: #1522 - /cs/my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 2.2.8
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –
`
```
</details>

**Comment by Jon007** [comment]
>Is there anything in the WooPoly that uses JS that could be causing this conflict?
No, I can't think of anything.
There is almost no css and js in this plugin, it only hooks a couple of things like:
            $('#post_lang_choice').change()
            $('#product-type').change()


In your system status report you show 25 plugins activated, can you reproduce this with only these plugins activated?
Polylang: [state if using Polylang PRO] 2.3.1
Hyyan WooCommerce Polylang Integration: 1.0.4
WooCommerce (preferably earlier than 3.3.1 as this is very new)
Ultimate FAQ

**Comment by ddstreetfood** [comment]
Yes, the conflict was isolated by turning off all plugins and then reactivating them one by one. The error occurs with Polylang, WooPoly, WooCommerce and Ultimate FAQ as the only plugins activated. Then it stops occuring when deactivating WooPoly but leaving the other 3 plugins activated.

Not sure if this helps, but here's what support from Ultimate FAQ had to say about the issue:

> Please note that the toggle for FAQ requires you to have jquery properly loaded to your WordPress site.
> There’s definitely a conflict somewhere. We just have to figure out where. This functionality works. I can see in the source code that the toggle functionality is enabled. We are not familiar enough with that Polylang extension [WooPoly] to know what in it might be causing an issue with our JavaScript toggle functionality. It seems strange that a language plugin would have JS that would conflict. Additionally, there are no console errors that would indicate why the JS might not work on that page. The only thing we can suggest is to look and see if there are any options in that plugin for anything that might use JS (e.g. animations, filtering, etc.) and see if you can disable those options and if it makes a difference. You can also contact the developer of that plugin and check to see what in that plugin might use JS.

**Comment by ddstreetfood** [comment]
Do you have any ideas about how to fix this? I really need to get my FAQs working properly.

Thanks

**Comment by Jon007** [comment]
Are any of these FAQ plugins open source?  if so I might be able to try one..
.. it's quite likely to be a different plugin conflict, eg some caching (either server or client) was hiding the real issue during your test

**Comment by ddstreetfood** [comment]
I'll check out if any of them are open source and get back to you.

I guess it could theoretically be some sort of cache hiding a different problem, but toggling WooPoly on and off made the error appear and disappear in real time. No other plugin had this effect even when it was the only plugin activated, or the only plugin activated alongside WooCommerce.

**Comment by Jon007** [comment]
is it this one?
https://wordpress.org/plugins/ultimate-faqs/

**Comment by ddstreetfood** [comment]
Yup, that's the one.

**Comment by Jon007** [comment]
It works fine - I installed on a test site with only the polylang/woocommerce/woopoly and the free version ultimate faqs, and added a couple of FAQs
I added the shortcode to a product page, the FAQs expand and collapse as one might expect.

**Comment by ddstreetfood** [comment]
OK, then I have no idea what the problem here could be. I'll keep digging, I guess. Thanks for looking into it.

**Comment by ddstreetfood** [comment]
Problem solved, you were absolutely right. It turned out to be a speed-up plugin that my hosting service runs by default on all Wordpress installations. I have no idea why toggling WooPoly on and off was affecting the error.

Thanks again for your help.
