### ISSUE TITLE
Tags are not syncing

### ISSUE THREAD

**Issue by andagent** [hyyan/woo-poly-integration#307]
#### Can you reproduce this issue on default Wordpress theme (eg Storefront)?
Yes
#### Can you reproduce this issue when all other plugins are disabled except WooCommerce, Polylang and Hyyan WooCommerce Polylang Integration?
Yes
#### What product versions and settings are you using when this issue occurs?
* PHP: 7.0.22-0ubuntu0.16.04.1
* WordPress: 4.9.4
* WooCommerce: 3.3.3
* Polylang: 2.3.1 (using FREE edition)
* Hyyan WooCommerce Polylang Integration: 1.0.4
* Browser: 63.0.3239.132 (64 bit)

#### Steps to Reproduce
1.  Added tag in RUS version of product, so it automatically appears in SLO version of this product
2. Deleting the tag in one of the versions, for example RUS, and it doesn't sync with SLO version 

#### What I Expected
Deleting the tag from all the versions of the current product. 

#### What Happened Instead
Tag has been deleted only in RUS version.

#### Another question
Also the same thing happens when I change status (Like "Draft") it changes only in one version (Should it be like this or this is a bug?)

**Comment by Jon007** [comment]
Tags, should synchronise but check you have enabled:
 - Settings, WooPoly, Translate Tags
 - Languages, Settings, Custom Taxonomies, Product Tags
see also:  https://github.com/hyyan/woo-poly-integration/wiki/Product-Categories

Status should not synchronise: for example a product may be published in one language but the translation is not finished yet / in draft..
