### ISSUE TITLE
url subdomain gets translated

### ISSUE THREAD

**Issue by Apfelsinchen** [hyyan/woo-poly-integration#31]
Hi,

I have my woocommerce shop installed in a subdomain.
Polylang, Poly Integration and the language switcher work fine.
But when I am in the German shop:
http://www.shop.domain.com/shop
and want to change the language to french the url is translated.
Instead of
http://www.shop.domain.com/magasin
it changes to
http://www.magasin.domain.com/magasin 

A wrong url of course leads to a wrong or not existing page.

Why is the url translated? How can I repair that?

Thank you!

**Comment by Apfelsinchen** [comment]
Has anybody an idea how I can fix this?

**Comment by theblackhole** [comment]
I had the same issue with a French shop http://boutique.domain.com/boutique . When I switch to English it changes to http://shop.domain.com/shop
I changed the page slug to `la-boutique` http://boutique.domain.com/la-boutique and now it doesn't change the subdomain.

So in your case you may change your page slug to `the-shop` or something like that

**Comment by Apfelsinchen** [comment]
Thank you so much!
I couldn't wait and changed to a differnet subdomain without a "shop" or "store" or "boutique" in the name.
Maybe I'll change back and try it, but I kind of like my new exotic subdomain name as well ;-)
But thank you for your answer!

**Comment by AlekseyArder** [comment]
I have the same problem but with main URL. When I switch to Russian lang redironshop.com changes to redironмагазин.com

Can you please help me?

**Comment by AlekseyArder** [comment]
I had changed Pages.php

public function translateShopUrl($url, $language)
   ...
      if ($shopPageTranslation) {
           ...
              // $shopPage->post_name, $shopPageTranslation->post_name, $url
              $shopPage->post_name, $url

Now all work as expected

**Comment by Jon007** [comment]
I confirm this issue is still there in the current code, which is that the page slug is replaced in the url, so yes, if the url is http://shop.com/shop then the 'shop' part will be translated twice:
in pages.php
```
                $result = str_replace(
                        $shopPage->post_name, $shopPageTranslation->post_name, $url
                );
```
This is however avoidable by changing the shop slug.

@AlekseyArder your quoted code is incomplete, can you confirm corrected version?

**Comment by Jon007** [comment]
I saw some draft fix for this somewhere as eg:
                //#31 url subdomain gets translated
                $result = strrev(preg_replace(strrev("/$shopPage->post_name/"),strrev($shopPageTranslation->post_name),strrev($url),1));

**Comment by Jon007** [comment]
@WalidChatelain 
Sorry I think I picked this up a long time ago I don't remember where it came from.
AlekseyArder solution may be fine or better but it's not completely posted here  

Yes this is in pages.php to replace the part:
```
                $result = str_replace(
                        $shopPage->post_name, $shopPageTranslation->post_name, $url
                );
```

with either a more intelligent replace or to rebuild the statement.

this problem can also easily be avoided by avoiding duplicating the url and shop slug.

**Comment by Jon007** [comment]
closing as no feedback for >6 months and plenty of workarounds exist to avoid this problem,
Please feel free to reopen if this is giving you a problem.

**Comment by vinvin27** [comment]
hey guys

We 've got the same issue over.


I tried to figure out how to fix it and maybe find a solution:

`$u = parse_url( $url);
                 $new_slug = str_replace(
                        $shopPage->post_name, $shopPageTranslation->post_name, $u['path']
                );
                $result = $u['scheme'] . '://' . $u['host'] .$new_slug;`

what do you think?
