### ISSUE TITLE
Can't dismiss plug for supporting plugin

### ISSUE THREAD

**Issue by Oclair** [hyyan/woo-poly-integration#310]
Hey there,

Your plug won't be dismissed, it loads on every admin page now...
![plug the plug](https://image.ibb.co/iRykV7/Screen_Shot_2018_03_06_at_12_35_04_PM.jpg)

Thanks for the awesome plugin,
OC

#### What product versions and settings are you using when this issue occurs?
* PHP: 
* WordPress: 
* WooCommerce: 
* Polylang: [state if using Polylang PRO]
* Hyyan WooCommerce Polylang Integration: 
* Browser: 

#### Steps to Reproduce
1. 
1. 
1. 

## WordPress Environment

<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.
```
</details>

**Comment by Oclair** [comment]
another issue while reviewing your plug is your using content which is not https, which is deemed to be uncool, I had to research what happened to my green check!
![Image of nonssl](https://image.ibb.co/epfrnn/Screen_Shot_2018_03_06_at_2_58_41_PM.jpg)
![Image of nonssl](https://image.ibb.co/eRTNtS/Screen_Shot_2018_03_06_at_2_58_25_PM.jpg)

**Comment by theleemon** [comment]
I think the following bug is related to yours:

https://github.com/hyyan/woo-poly-integration/issues/311

**Comment by theleemon** [comment]
I'm having the same problem, but just in one site where the plugin is installed. Weird.

**Comment by hyyan** [comment]
@Oclair  which PHP version are you using?

**Comment by theleemon** [comment]
Maybe it's related with the latest Polylang update (2.3.2) two days ago

**Comment by theleemon** [comment]
I thought that this only was happening in one of the sites with the plugin installed, but it seems it's happening in every site.

**Comment by Oclair** [comment]
@hyyan PHP 5.6.34 (cli) (built: Mar  4 2018 13:56:39)

**Comment by Oclair** [comment]
Things seem to really be messed up...
This randomly appeared and returned to the plug spam problem reported above.

![Image of badthings](https://ibb.co/kMQZhn)

**Comment by Jon007** [comment]
Yes, it happens on PHP7.0 as well and has been reported on wordpress.org too

**Comment by hyyan** [comment]
@Jon007 I have just tested with PHP `7.0.10` , the message can be dismissed with no Problems, I will upgrade to PHP 7.2 later this day and test again

**Comment by Jon007** [comment]
ok right - I had moved to 7.1 briefly so maybe it was then

**Comment by Jon007** [comment]
no, it keeps popping up... you can dismiss it, and it appears to be dismissed, but the dismissal is only temporary and sooner or later it will pop up again (PHP7.0, latest wordpress)

**Comment by Oclair** [comment]
dude...  every admin page...

**Comment by theleemon** [comment]
I see that there's no JS event attached to the dismiss button (to call a PHP function to update the corresponding database option to dismiss it persistently), so I don't know how this worked before.

https://www.alexgeorgiou.gr/persistently-dismissible-notices-wordpress/

**Comment by Oclair** [comment]
It appears the issue has been resolved with the latest update from Polylang!

Thanks everyone for the assistance!

**Comment by theleemon** [comment]
Confirmed. I installed the latest Polylang version (2.3.3) and I stopped getting the non-dismissible WooPoly notification. Really weird.
