### ISSUE TITLE
Utilities::polylangVersionCheck fails on composer installations

### ISSUE THREAD

**Issue by grappler** [hyyan/woo-poly-integration#312]
I was shocked to see this code.

```php
        $filepath = ABSPATH . 'wp-content/plugins/polylang/polylang.php';
        if (! file_exists($filepath)) {
            $filepath = ABSPATH . 'wp-content/plugins/polylang-pro/polylang.php';
            if (! file_exists($filepath)) {
                error_log('Polylang version not tested - polylang file not found');
                return true;
            }
        }
```

The reason is that the `wp-content` folder does not need to be `wp-content` it can be `abcd`.

There are constants that a developer can change like `WP_CONTENT_DIR`.

Use `POLYLANG_VERSION` or even `$filepath = str_replace('woo-poly-integration/','polylang/polylang.php',plugin_dir_path(Hyyan_WPI_DIR));`

**Comment by hyyan** [comment]
@grappler This is a valid issue and common case use, it will be fixed in the next version.
PR is more than welcomed

**Comment by grappler** [comment]
@hyyan Which solution do you prefer?

1. `POLYLANG_VERSION`
or
2. `$filepath = str_replace('woo-poly-integration/','polylang/polylang.php',plugin_dir_path(Hyyan_WPI_DIR));`

**Comment by Jon007** [comment]
The path versions don't work 100% and are just annoying for example if you use version numbered directories, or polylang pro or rename for any other reason.  I would prefer to test for the existence of particular required function, and show a warning banner (once we've worked out how to make these dismissible again).

**Comment by Jon007** [comment]
The woocommerce part of the test can be changed to this:
```
        /* check woocommerce plugin */
    	if ( class_exists( 'WooCommerce' ) && version_compare( WC()->version, 3.0, ">=" ) ) {
            $woocommerce = true;
        }

```
