### ISSUE TITLE
my features and meta list are empty

### ISSUE THREAD

**Issue by harabidi** [hyyan/woo-poly-integration#314]
Hello guys, and thank you for helping the others, 
my features and meta list are empty, i don't know why, maybe I executed the composer where it doesn't work?

#### What product versions and settings are you using when this issue occurs?
* PHP: 5.4.45
* WordPress: 4.9.4–fr_FR
* WooCommerce: 3.3.3
* Polylang: [state if using Polylang PRO]
* Hyyan WooCommerce Polylang Integration: par Hyyan Abo Fakher – 1.0.4
* Browser: firefox

![woopoly](https://user-images.githubusercontent.com/16189566/37243630-bcb466f0-2474-11e8-884e-13c23cd526bc.png)

**Comment by Jon007** [comment]
PHP5.4 isn't widely supported, that's really old now.
Try using 7.0.
Many plugins have some issues with 7.1 and 7.2 but 7.0 is pretty safe.

**Comment by harabidi** [comment]
Thank you for answer,
I changed the version of PHP, but nothing to change, on the other hand my version of MySQL is 5.5.57, is that the cause?

**Comment by Jon007** [comment]
I really don't know why that could be blank, it's not dependent on the sql version, I would try:
- switch to a standard theme (eg storefront) in case there is some odd conflict in the theme code
- delete and reinstall the plugin
- in case there is some corrupted option, search the options table for keys containing wpi [for woo-poly-integration](there are two keys) - could delete these entries and should be recreated

**Comment by harabidi** [comment]
Hello Jon007,

-i can't switch to a standard theme , because we bought a theme(Infystore)
- i delete and reinstall but nothing change
- I deleted both keys, but they are still empty in the database and admin interface.
![empty](https://user-images.githubusercontent.com/16189566/37330838-3451eda0-269a-11e8-8235-36884c5bbab7.png)
thanks for answer

**Comment by Jon007** [comment]
You need to switch theme temporarily just to see if the theme is causing the problem.  Which is quite likely because no-one else ever had this problem

**Comment by harabidi** [comment]
You're right, i tested Storefront and it's worked , i'm gonna write an e-mail to the tech team.
Thank you for the time.
