### ISSUE TITLE
Duplicate Content and SEO

### ISSUE THREAD

**Issue by steampunkgems** [hyyan/woo-poly-integration#315]
#### What product versions and settings are you using when this issue occurs?
* PHP: 
* WordPress: 
* WooCommerce: 
* Polylang: [state if using Polylang PRO]
* Hyyan WooCommerce Polylang Integration: 
* Browser: 

#### Steps to Reproduce
1. 
1. 
1. 

## WordPress Environment

<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.
```
</details>
Hi,

No problems with the plugin, everything works fine.
My issue is with the natural creation of duplicate content of the products and the negative effect on SEO. Currently my site has 47% duplicate content which is all my products in /English and Dutch.
How do you get round this? 
Is the only way to have the products in one language

Regards

Gwendolyne Blaney

**Comment by Jon007** [comment]
It's not counted as duplicate content from an SEO point of view.  What makes you think that it is?

Pages are tagged with 
```
<html lang=
<link rel="alternate" href="other-language-version" hreflang="..
```
so Google etc knows that it is alternative language version of the page, not a duplicate page.

This is a general polylang and SEO question and not specific to this plugin.
