### ISSUE TITLE
My account page just supports main language

### ISSUE THREAD

**Issue by dogukanoksuz** [hyyan/woo-poly-integration#316]
My problem is on the title,
My account page is only working with the primary language. When i click a link it goes again to default language.

php 7.0, mariadb 11.1, vps, wordpress latest, everything is updated and no plugin conflict.

**Comment by yokataj** [comment]
I have the same issue with cart and checkout pages. When I click on the cart button it goes to default language. Same with checkout page. 

When I switch the language being on the cart or checkout pages, it actually redirects to the right language. 

Please advise how this could be fixed. Many many thanks!

**Comment by Jon007** [comment]
make sure you have created translated pages for my-account (and cart and checkout) and that these pages are translated.
You don't need to do anything special, just create the new translation page and publish.

If a permalink issue, go to Settings, Permalinks and press Save.

@yokataj may have a different issue, for example maybe your theme is using a fixed link for its cart button in a way that doesn't change for the languages.  Try switching to a standard theme (eg storefront) to confirm if this is the case. 

In case of further issues, please raise the issue separately including all the information requested, which is needed to correctly identify the problem..
