### ISSUE TITLE
$table_prefix issue

### ISSUE THREAD

**Issue by masato-igarashi** [hyyan/woo-poly-integration#320]
https://github.com/hyyan/woo-poly-integration/blob/c7f3db84dbfb4767e5106a3ef40776842ba19915/src/Hyyan/WPI/Product/Variation.php#L118

this line select **wp_** postmeta table.
**wp_** is $table_prefix. different each other.

sorry my broken english.

**Comment by Jon007** [comment]
you are right, that's a bug, should use $table_prefix which is configurable and not always 'wp_'
Amazing no-one spotted that before...
.. please feel free to change the prefix in your copy of the source code to get it working before the next release, or even better, raise a pull request in github with the correct fix to pull in the correct table_prefix.

**Comment by masato-igarashi** [comment]
hi
i fixed this issue and pushed PR
if this commit is no problem please close this issue
thank you for your response
