### ISSUE TITLE
Wocoommerce automatic emails sent in English

### ISSUE THREAD

**Issue by innovanity** [hyyan/woo-poly-integration#321]
Hello,
We have installed your plugin in a multilanguage site in Spanish, English and German.
We have done several orders, with the site in Spanish (including Cart and Checkout pages in Spanish), but the Wocoommerce emails are sent in English.

#### What product versions and settings are you using when this issue occurs?
* PHP: 5.6.35
* WordPress: 4.9.4
* WooCommerce: 3.3.4 (we have also downgraded to 3.2.6, as jonmoore said us is not tested for 3.3.x)
* Polylang: 2.3.4
* Hyyan WooCommerce Polylang Integration: 1.0.4 (we have marked every option)
* Browser: -

#### Steps to Reproduce
It's just the automatic emails sent by Woocommerce after an order is done.

#### What I Expected
As I am making the order in Spanish, the emails should be sent in Spanish, but we receive it in English (eve the primary language in Polylang is Spanish). However, If I change afterwards the order status in the backend, those emails are sent in Spanish; but the automatic ones (like the “new order” email for customer and admin), always in English.

#### What Happened Instead
Automatic Woocommerce emails sent always in English.

Thanks in advance.

**Comment by innovanity** [comment]
UPDATE: We have just realised it only happens with TPV payment; with bank transfer emails are sent in Spanish.
We have tried two different Redsys modules, and also with two different bank account gateways.
In all cases, the TPV payment returns Woocommerce emails in English... 
Could it be a bug in your module?

**Comment by Jon007** [comment]
what is TPV payment ?
there is no standard payment gateway called TPV, have you added another plugin, which is not compatible with the language switching?
Note, when raising a ticket you are supposed to paste in WooCommerce\Status\Get System Report which would include this and other information.

**Comment by Jon007** [comment]
well, taking into account that:
- the problem only occurs with this gateway Pasarela de pago para Redsýs
- the gateway Pasarela de pago para Redsýs is "No probado con la versión activa de WooCommerce"
- the gateway Pasarela de pago para Redsýs is a paid product and should have support available
- this component is a free product only supported by volunteers in their spare time, who have no access to the code for Pasarela de pago para Redsýs

.. really you should raise a call with Pasarela de pago para Redsýs

**Comment by innovanity** [comment]
Hello back Jon,
We have been doing some new tests, and we can confirm now that Redsýs (POS) is not the problem.
Using PayPal payment (just with the Woocommerce plugin) it happens the same: automatic sent emails after payment, admin-new-order.php & customer-completed-order.php, are both sent in English.

We even have even try adding inside those templates this code: echo get_locale(), and we get: [es_ES], but all strings in English (although translations are present, since you get Spanish mails if you change order status manually).

So, problem must be in the "trigger" of that automatic emails when the payment is done...
Any clue about that issue?
Thanks in advance.

**Comment by Jon007** [comment]
Thanks for investigating, 
for info I haven't had time to look at this - actually I run Woo 3.1.2 though I hope to test upgrade to 3.3.4 soon.

I do remember there are two ways of triggering email in woocommerce, one is immediate and the other is with asynchronous with cron, there isn't an option for it in the user interface but you can turn the cron off by returning false on the filter woocommerce_defer_transactional_emails and then the email will be send from the UI in the correct language.  

It may be that extra code is needed to force the language switch (reload the translation files) when in cron context - I thought something was already done for this, I'll check (but probably not this week), in the meantime please try the workaround with woocommerce_defer_transactional_emails

**Comment by Jon007** [comment]
for the record, I retested that this is working for me with woo 3.1.2
The site main language is English, secondary language is Spanish
I make an order in Spanish I get the customer email in Spanish.
I don't use woocommerce_defer_transactional_emails filter.

There is a setting to enable the email translation in Settings, WooPoly, Features - but I suppose you already have this.
And the language switching in the Email.php specifically gets order language and forces reload of the text domain for translation.

**Comment by Jon007** [comment]
for me, it's Fixed in #329
as per related discussion on #319
Note that as of writing this isn't merged yet, just pick up the replacement ajax file from the commit on #329  : 
https://github.com/marian-kadanka/woo-poly-integration/blob/888df716c43c0191c32e2b8bfc11d7ea0a9ed055/src/Hyyan/WPI/Ajax.php
props @marian-kadanka

**Comment by hyyan** [comment]
Fixed in #329

**Comment by mylzmylo** [comment]
Hola me pasa algo muy similar, tengo un sitio en Frances e Ingles pero Woocommerce solo funciona en ingles al enviar el email al cliente.  Existe alguna forma para los email esten en el idioma del usuario?

**Comment by mylzmylo** [comment]
Hello, something very similar happens to me, I have a site in French and English but Woocommerce only works in English when sending the email to the client. Is there a way for emails to be in the user's language?

**Comment by Jon007** [comment]
make sure you are using the latest from https://github.com/hyyan/woo-poly-integration/releases 
I don't think it was released to wordpress.org
