### ISSUE TITLE
After activating Let's Encrypt SSL certificate plugin isn't working anymore

### ISSUE THREAD

**Issue by ilyavovnenko** [hyyan/woo-poly-integration#323]
#### Can you reproduce this issue on default Wordpress theme (eg Storefront)?

Yes.

#### Can you reproduce this issue when all other plugins are disabled except WooCommerce, Polylang and Hyyan WooCommerce Polylang Integration?

Yes.

#### What product versions and settings are you using when this issue occurs?
* PHP: 7.1.14
* WordPress:  4.9.5
* WooCommerce: 3.3.4
* Polylang: FREE 2.3.4
* Hyyan WooCommerce Polylang Integration: 1.0.4
* Browser:  chrome 65.0.3325.181 (64-bit)

#### Steps to Reproduce
1. Install Let's Encrypt SSL certificate for your domain;
2. Go to the plugins page;
3. See the message "The plugin can not function correctly , the plugin requires minimum plugin versions WooCommerce version 3 or higher and Polylang 2 or higher. Please configure Polylang by adding a language before activating WooCommerce Polylang Integration.See alsoInstallation Guide."

#### What I Expected
I expected, that if I add SSL certificate to my domain, than this plugin can wark also, and I have possibility to create product dublicates for different languages in my shop :)

#### What Happened Instead
I can't create dublicates for different languages in my shop. I haven't different languages, in my products page in admin panel, anymore.

## WordPress Environment

<details>
`
### WordPress Environment ###

Home URL: https://wp.diversland.ru
Site URL: https://wp.diversland.ru
WC Version: 3.3.4
Log Directory Writable: ✔
WP Version: 4.9.5
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache/2.4.6 (CentOS) mpm-itk/2.4.7-04 OpenSSL/1.0.2k-fips PHP/5.4.16
PHP Version: 7.1.14
PHP Post Max Size: 32 MB
PHP Time Limit: 600
PHP Max Input Vars: 1000
cURL Version: 7.29.0
NSS/3.28.4

SUHOSIN Installed: –
Max Upload Size: 32 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.3.4
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
Total Database Size: 4.66MB
Database Data Size: 4.24MB
Database Index Size: 0.42MB
wp_woocommerce_sessions: Data: 0.01MB + Index: 0.00MB
wp_woocommerce_api_keys: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_order_items: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_order_itemmeta: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_tax_rates: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_log: Data: 0.00MB + Index: 0.00MB
wp_commentmeta: Data: 0.00MB + Index: 0.01MB
wp_comments: Data: 0.00MB + Index: 0.01MB
wp_eg_grids: Data: 0.02MB + Index: 0.01MB
wp_eg_item_elements: Data: 0.00MB + Index: 0.00MB
wp_eg_item_skins: Data: 1.10MB + Index: 0.01MB
wp_eg_navigation_skins: Data: 0.06MB + Index: 0.01MB
wp_links: Data: 0.00MB + Index: 0.00MB
wp_options: Data: 1.83MB + Index: 0.06MB
wp_postmeta: Data: 0.60MB + Index: 0.15MB
wp_posts: Data: 0.32MB + Index: 0.04MB
wp_revslider_css: Data: 0.09MB + Index: 0.00MB
wp_revslider_layer_animations: Data: 0.00MB + Index: 0.00MB
wp_revslider_navigations: Data: 0.00MB + Index: 0.00MB
wp_revslider_sliders: Data: 0.02MB + Index: 0.00MB
wp_revslider_slides: Data: 0.09MB + Index: 0.00MB
wp_revslider_static_slides: Data: 0.00MB + Index: 0.00MB
wp_termmeta: Data: 0.00MB + Index: 0.01MB
wp_terms: Data: 0.01MB + Index: 0.02MB
wp_term_relationships: Data: 0.01MB + Index: 0.02MB
wp_term_taxonomy: Data: 0.01MB + Index: 0.01MB
wp_usermeta: Data: 0.02MB + Index: 0.02MB
wp_users: Data: 0.00MB + Index: 0.01MB
wp_wc_download_log: Data: 0.00MB + Index: 0.00MB
wp_wc_webhooks: Data: 0.00MB + Index: 0.00MB
wp_yoast_seo_links: Data: 0.04MB + Index: 0.02MB
wp_yoast_seo_meta: Data: 0.01MB + Index: 0.01MB

### Post Type Counts ###

attachment: 64
custom_css: 1
customize_changeset: 1
mc4wp-form: 1
nav_menu_item: 67
page: 33
polylang_mo: 2
post: 15
product: 13
product_variation: 6
revision: 69
services: 11
team: 6
testimonial: 3
tribe_events: 6
tribe_organizer: 1
tribe_venue: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (17) ###

Polylang: by Frédéric Demarle – 2.3.4
Akismet Anti-Spam: by Automattic – 4.0.3
Booked Add-On: Calendar Feeds: by Boxy Studio – 1.1.5
Booked Add-On: Front-End Agents: by Boxy Studio – 1.1.15
Booked Add-On: WooCommerce Payments: by Boxy Studio – 1.4.9 – Not tested with the active version of WooCommerce
Booked: by Boxy Studio – 2.1
Essential Grid: by ThemePunch – 2.1.0.2
Instagram Feed: by Smash Balloon – 1.8
WPBakery Visual Composer: by Michael M - WPBakery.com – 5.1.1
MailChimp for WordPress: by ibericode – 4.2
Slider Revolution: by ThemePunch – 5.4.3.1
The Events Calendar: by Modern Tribe
Inc. – 4.6.13

ThemeREX Utilities: by ThemeREX – 3.0
Hyyan WooCommerce Polylang Integration: by Hyyan Abo Fakher – 1.0.4 – Not tested with the active version of WooCommerce
WooCommerce PayPal Express Checkout Gateway: by WooCommerce – 1.5.3
WooCommerce: by Automattic – 3.3.4
Yoast SEO: by Team Yoast – 7.2

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: 
Decimal Separator: .
Number of Decimals: 0
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #199 - /en/booking/
Cart: #373 - /cart/
Checkout: #374 - /checkout/
My account: #375 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: DiveIt Child
Version: 1.0
Author URL: http://ancorathemes.com/
Child Theme: ✔
Parent Theme Name: DiveIt
Parent Theme Version: 1.1
Parent Theme Author URL: http://ancorathemes.com/
WooCommerce Support: ✔

### Templates ###

Overrides: –
`
</details>

**Comment by Jon007** [comment]
I expect everyone that uses this plugin uses SSL certificate and there's isn't any known related issue.
There are some issues with the dependency check though and you can comment the related lines out if they are causing you a problem.
The common problem is if you have activated woocommerce or polylang in a different directory from the normally expected directory

**Comment by hyyan** [comment]
@ilyavovnenko  is this still an issue?

**Comment by ilyavovnenko** [comment]
Can be closed.
