### ISSUE TITLE
Linking to the relevant translated product from a custom language switcher

### ISSUE THREAD

**Issue by RussMorg** [hyyan/woo-poly-integration#328]
Thanks for the plugin, so far it's awesome!

I've made a custom language switcher, and I can make it switch languages on the home page just fine.  The problem comes when I want to switch language and I'm already on a product page.  How do I link to the translated product?

My site is originally in Norwegian, with translations being in English, so the original site is mysite.com and the translated is mysite.com/en - I tried this:

`<a href="http://mysite.com/en/product/?p=<?php the_ID(); ?>">English</a>`

But of course this just takes me right back to the page I'm on, because products have been duplicated and as such have different IDs.  So how do I link to the translated product?

Thanks again.

**Comment by Jon007** [comment]
you can just use the standard language switcher for example you can put a language switcher anywhere you like in your theme using something like:
`<?php pll_the_languages();?>`
..  this is standard Polylang functionality, not related to this plugin.
Products are just a type of Post so they follow the existing language switching the same as posts and pages, no special functionality in this plugin so closing from here, if difficulty using Polylang please raise in appropriate Polylang forum...
