### ISSUE TITLE
Wrong url for orders in "My Account" Page

### ISSUE THREAD

**Issue by theblackhole** [hyyan/woo-poly-integration#33]
There is a bug on "my account" page : if I view an order (`/my-account/view-order/123/`) and I want to go back on "my account", it will redirect to `/my-account/view-order/` instead of `/my-account/` so when I click again on an order, it will open `/my-account/view-order/view-order/123/` instead of `/my-account/view-order/123/`

( @hyyan I know you dropped support of this plugin but if, one day, you want to work on it again, this can be useful :smile:  )

**Comment by decarvalhoaa** [comment]
Hi Have you found a fix for this issue?

I commented 2 hooks in woo-poly-integration/src/Hyyan/WPI/Endpoints.php and it solved my issue
https://github.com/decarvalhoaa/woo-poly-integration/blob/master/src/Hyyan/WPI/Endpoints.php#L55-L71

**Comment by theblackhole** [comment]
Hi @decarvalhoaa thank you very much for your response ! :smiley: 
Commenting `filterPermalink` seems to work. That's weird : I don't know why it's there since it's working without it...
Maybe it was needed for an older version of polylang and now it's creating conflics...
