### ISSUE TITLE
in variable products additional product price isn’t adding in cart.

### ISSUE THREAD

**Issue by ipsmayur** [hyyan/woo-poly-integration#330]
in variable products additional product price isn’t adding in cart.

I’m using This plugin “https://wordpress.org/plugins/woocommerce-product-addon/”
” WooCommerce Product Addons”

in variable products i have added some additional accessories products but when we add product to the cart then only main products price added in the cart
accessories product price isn’t adding in cart
and if i deactivate your plugin (Hyyan WooCommerce Polylang Integration » )then all working fine.
Any information on this would be greatly appreciated. Thanks!

**Comment by Jon007** [comment]
You need to raise this to the author of WooCommerce Product Addons.

If you would like to implement synchronisation for additional fields we wrote some help on how to use the is_protected_meta filter here:
https://github.com/hyyan/woo-poly-integration/wiki/Product-Meta-and-Custom-Fields

Please note that is Polylang functionality, not the functionality of this plugin.

I'm closing this information for 2 reasons:
1. required information (version numbers etc) not provided when opening the issue
2. it's not a problem with this plugin or the functionality provided by this plugin.  You or the WooCommerce Product Addons plugin author need to implement the Polylang filter as suggested, which is a filter from Polylang itself not from this plugin.

Please bear in mind that this is a free plugin supported by volunteers in their spare time and provide all requested information when raising issues.
