### ISSUE TITLE
Product attributes translation

### ISSUE THREAD

**Issue by mmmab** [hyyan/woo-poly-integration#336]
Hi,

sorry for hassle but I have a problem with translation integration.

I have pasted the Woocommerce System Status Report below and the issue is on the product attributes added. I can not translate the attr. : Serie, Return Method, Mounting Width(mm), Stroke(mm), Angle(degree), Shut Height(mm), Working Force(kN) and Return Force(N).

Can you give some idea about it.

Thank you.

<details>
### WordPress Environment ###

Home URL: https://www.cam-units.com
Site URL: https://www.cam-units.com/wp-cu
WC Version: 3.3.5
Log Directory Writable: ✔
WP Version: 4.9.5
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 7.1.14
PHP Post Max Size: 16 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.54.0
OpenSSL/1.0.2k

SUHOSIN Installed: –
MySQL Version: 5.6.39
Max Upload Size: 4 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.3.5
WC Database Prefix: wp_
Total Database Size: 23.56MB
Database Data Size: 16.17MB
Database Index Size: 7.39MB
wp_woocommerce_sessions: Data: 0.01MB + Index: 0.00MB
wp_woocommerce_api_keys: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_order_items: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_order_itemmeta: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_tax_rates: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_log: Data: 0.00MB + Index: 0.00MB
wp_commentmeta: Data: 0.00MB + Index: 0.01MB
wp_comments: Data: 0.00MB + Index: 0.00MB
wp_cp_calculated_fields_form_discount_codes: Data: 0.00MB + Index: 0.00MB
wp_cp_calculated_fields_form_posts: Data: 0.00MB + Index: 0.00MB
wp_cp_calculated_fields_form_settings: Data: 0.04MB + Index: 0.00MB
wp_links: Data: 0.00MB + Index: 0.00MB
wp_options: Data: 2.23MB + Index: 0.23MB
wp_pms_member_subscriptionmeta: Data: 0.00MB + Index: 0.00MB
wp_pms_member_subscriptions: Data: 0.00MB + Index: 0.00MB
wp_pms_paymentmeta: Data: 0.00MB + Index: 0.00MB
wp_pms_payments: Data: 0.00MB + Index: 0.00MB
wp_postmeta: Data: 11.34MB + Index: 4.45MB
wp_posts: Data: 1.07MB + Index: 0.42MB
wp_social_users: Data: 0.00MB + Index: 0.00MB
wp_termmeta: Data: 0.03MB + Index: 0.03MB
wp_terms: Data: 0.09MB + Index: 0.14MB
wp_term_relationships: Data: 0.92MB + Index: 1.98MB
wp_term_taxonomy: Data: 0.17MB + Index: 0.10MB
wp_usermeta: Data: 0.11MB + Index: 0.02MB
wp_users: Data: 0.00MB + Index: 0.01MB
wp_wc_download_log: Data: 0.00MB + Index: 0.00MB
wp_wc_webhooks: Data: 0.00MB + Index: 0.00MB
wp_woof_query_cache: Data: 0.00MB + Index: 0.00MB
wp_wpgmza: Data: 0.02MB + Index: 0.00MB
wp_wpgmza_categories: Data: 0.02MB + Index: 0.00MB
wp_wpgmza_category_maps: Data: 0.02MB + Index: 0.00MB
wp_wpgmza_circles: Data: 0.02MB + Index: 0.00MB
wp_wpgmza_maps: Data: 0.02MB + Index: 0.00MB
wp_wpgmza_polygon: Data: 0.02MB + Index: 0.00MB
wp_wpgmza_polylines: Data: 0.02MB + Index: 0.00MB
wp_wpgmza_rectangles: Data: 0.02MB + Index: 0.00MB

### Post Type Counts ###

attachment: 79
custom_css: 1
customize_changeset: 10
ml-slide: 76
ml-slider: 4
nav_menu_item: 21
page: 39
polylang_mo: 3
post: 2
product: 3453
revision: 392

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (15) ###

Polylang: by Frédéric Demarle – 2.3.5
Akismet Anti-Spam: by Automattic – 4.0.3
Calculated Fields Form: by CodePeople – 1.0.228
Limit Login Attempts: by Johan Eenfeldt – 1.7.1
MetaSlider: by Team Updraft – 3.7.2
Nextend Social Login: by Nextendweb – 3.0.7
Paid Member Subscriptions: by Cozmoslabs
Mihai Iova
Madalin Ungureanu
Adrian Spiac
Cristian Antohe – 1.7.2

Tabby Responsive Tabs: by cubecolour – 1.2.3
Theme My Login: by Jeff Farthing – 6.4.11
Hyyan WooCommerce Polylang Integration: by Hyyan Abo Fakher – 1.1.0 – Not tested with the active version of WooCommerce
WOOF - WooCommerce Products Filter: by realmag777 – 2.2.0
WooCommerce: by Automattic – 3.3.5
WOOF by Category: by KAGG Design – 1.6.2
WP Google Maps: by WP Google Maps – 7.0.04
YITH WooCommerce Catalog Mode: by YITHEMES – 1.5.9

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: TRY (₺)
Currency Position: left_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #10 - /online-catalog/
Cart: ❌ Page not set
Checkout: ❌ Page not set
My account: ❌ Page not set
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront Child
Version: 1.1.0
Author URL: http://www.azelirbrevo.com
Child Theme: ✔
Parent Theme Name: Storefront
Parent Theme Version: 2.3.1
Parent Theme Author URL: https://woocommerce.com/
WooCommerce Support: ✔

### Templates ###

Overrides: –
</details>

**Comment by Jon007** [comment]
Please see:
https://github.com/hyyan/woo-poly-integration/wiki/Product-Attributes
and note that you can turn translation on or off for each individual attribute in the Polylang settings page as explained on this wiki page.

If you still have a problem  after that we can reopen the issue but please explain very clearly what the problem is, what you did, what you expected to happen, what actually happened, otherwise we can't tell what problem you are having.

**Comment by mmmab** [comment]
@Jon007 

The translations of the attributes are already assigned, as seen. But the problem is not solved by any means.


![1](https://user-images.githubusercontent.com/39294919/40323671-cbdfe57a-5d3e-11e8-99f9-9b89bc400301.jpg)

**Comment by Jon007** [comment]
Are you saying that when viewing the site in Spanish you still see "Width" and not "Anchura"?

Please check the documentation at:
https://github.com/hyyan/woo-poly-integration/wiki/Product-Attributes

and if you are still having problems, come back with more details about what problem you are having.

**Comment by mmmab** [comment]
Yes. That is what I am having as a problem, unfortunately.
I have read the link before, no solutions there. It only has information about the plugin tough.
What more details you ask for?

**Comment by Jon007** [comment]
Well the most likely was the settings not set correctly in Settings\WooPoly\Features\Translate Attributes or Languages\Settings, Custom post types and Taxonomies
that is why I referred you to the documentation pages.

If it is not that, the most likely cause is a conflict with other theme or plugin code.
This is why we ask these questions before you open an issue:

#### Can you reproduce this issue on default Wordpress theme (eg Storefront)?

#### Can you reproduce this issue when all other plugins are disabled except WooCommerce, Polylang and Hyyan WooCommerce Polylang Integration?

**Comment by mmmab** [comment]
This is "Settings\WooPoly\Features\Translate Attributes":

![1](https://user-images.githubusercontent.com/39294919/40393540-8573e31c-5e28-11e8-8f28-4298e88f058a.jpg)

And this is "Languages\Settings, Custom post types and Taxonomies":

![2](https://user-images.githubusercontent.com/39294919/40393581-b12da4e8-5e28-11e8-8c62-5cecc9a9f159.jpg)

As these taxonomies are not selected, you can say that this is my fault but you are not right.
When these taxonomies are not checked as above, the translations don't work for other languages but they are shown on the page as seen below.

![3](https://user-images.githubusercontent.com/39294919/40393674-1db300d6-5e29-11e8-98a4-1aa8763af675.jpg)

Now the taxonomies are selected:

![4](https://user-images.githubusercontent.com/39294919/40393703-32cd7e38-5e29-11e8-82d5-97fbb6274c40.jpg)

They gone wild, they gone invisible, they made me open up this dispute but to be treated like a dirt as seen below.

![5](https://user-images.githubusercontent.com/39294919/40393860-c1d67f4e-5e29-11e8-805c-74255b17e09a.jpg)


I am just wondering how long will it take for you to just log in and crawl the site and chase the problem rather than just talk off the top of one's head.

**Comment by mmmab** [comment]
BTW, I have tried all possible reactions without other plugins as well.

Thank you for your time.

**Comment by Jon007** [comment]
What feature are you using to produce this menu on the left hand side, is it produced by another plugin? It looks like this functionality has a compatibility problem.
I am guessing from your report that it is:
 WOOF - WooCommerce Products Filter: by realmag777 – 2.2.0

When you open the individual product you should see the product attributes translated on the product page, this is the standard woocommerce feature supported by this plugin and so I assumed you were asking about this functionality.  I was not able to guess that you were asking about a different plugin. 

Please note the scope of this plugin is only to make the WooCommerce plugin compatible with the Polylang plugin.
Polylang support for WOOF - WooCommerce Products Filter compatibility is not in scope of this plugin, if realmag777 want to support Polylang either they need to implement their own compatibility or you need to implement your own version or a different tool.  realmag also have a paid version of their plugin so I suggest you raise the issue with them.


Please note this plugin is supported entirely for free by volunteers in their spare time instead of doing other things like sleeping.. so this is why we need as much information as possible and we are not able to spend time guessing about your problem.
Also your website product information is not public and I am not going to register with my personal details just to give you free support.

**Comment by mmmab** [comment]
**Here we go.**

I will be pasting the link of this issue written here to realmag777 as you told, to embarrass you (maybe you will), this is why I am writing these.

I didn't ask you to "guess" the problem issued. The WC System Status Report is given from the very begining of this thread. "You" didn't even looked at it like you didn't looked at the website which the problem occured. If you have checked it at the begining, you wouldn't have to steal from your sleep and give me unanswered replies until this time.

The login page is not asking for personal details. This is bullshit. If your 1st time behaviour was to "help" people "free of charge", you can kindly ask a login credentials which I can arrange easily, like I have asked kindly at all above messages.

Giving "free" support doesn't mean smacking people around. You better go and get some sleep.

If everything is about charging some fee, the plugin does not have any option for me to do so, so emphasizing the "free support" procedures is meaningless.

After all, again, thank you for your spare time.
After after all, again, I am sorry for the hassle. Thank you.

**Comment by Jon007** [comment]
You did not follow the instructions before raising this issue to confirm that the software was working with only Polylang, WooCommerce and this plugin enabled.

You did not clarify that you were asking for support for a different plugin.

If you had described the issue more clearly it would have been easier and quicker to confirm the issue, which is not an issue with this plugin.
