### ISSUE TITLE
WooCommerce 3.4 GDPR changes - privacy policy

### ISSUE THREAD

**Issue by Jon007** [hyyan/woo-poly-integration#337]
With the imminent release of WooCommerce 3.4 for GDPR, two new strings are added at WooCommerce, Settings, Accounts and Privacy:  Registration Privacy Policy and Checkout Privacy Policy.
These strings need to be added to the Polylang Strings translation table, with support for translating them where they appear.

**Comment by Jon007** [comment]
Checked in implementation
Additionally, if you are using the beta WooCommerce 3.4 you may not have updated translations files so you might not get a translation for the string "Privacy Policy" from:
`__( 'privacy policy', 'woocommerce' )`
This can be addressed by using Loco Translate or by waiting for 3.4 official release.

**Comment by bonovski** [comment]
I hope this will be added soon, it is critical for a lot of multilingual sites.

**Comment by Jon007** [comment]
this change is checked into master and I've been using in production along with a WooCommerce 3.4 pre-release for a few days and it seems ok..  woo 3.4 release is now out finally so hopefully @hyyan will go for a release of this..

**Comment by izzycart** [comment]
Thanks so much for this @Jon007 , you are a life saver.
