### ISSUE TITLE
Translate WooCommerce Store Notice (theme customizr)

### ISSUE THREAD

**Issue by jenskastensson** [hyyan/woo-poly-integration#339]
Hi and thanks for a great plugin!
Is it possible to translate WooCommerce Store Notice? I cannot find such an option anywhere
If you haven't got time to work on it now,  maybe you can indicate how and where I can implement  a temporary solution?
Jens

**Comment by Jon007** [comment]
done in master branch

**Comment by jenskastensson** [comment]
Thanks Jonathan!
Any ideas when you plan to release it?

**Comment by Jon007** [comment]
that will be up to @hyyan  but the GDPR update should go out soon, whenever @hyyan has time..

**Comment by jenskastensson** [comment]
Thx!
