### ISSUE TITLE
Menu Order does not sync in other languages and can not be modified

### ISSUE THREAD

**Issue by JPtheCrow** [hyyan/woo-poly-integration#341]
#### What product versions and settings are you using when this issue occurs?
* PHP: 
* WordPress: 
* WooCommerce: 
* Polylang: [state if using Polylang PRO]
* Hyyan WooCommerce Polylang Integration: 
* Browser: 

#### Steps to Reproduce
1. 
1. 
1. 

## WordPress Environment

<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.
```
</details>

**Comment by Jon007** [comment]
This should be controlled by Polylang setting under Languages, Settings, Page order, but in some different releases of Polylang this got restricted to working on Posts and Pages only, though I thought they put it back again.

From this plugin point of view, the fields locker is controlled by Settings, WooPoly, Metas List, Menu Order.
If this WooPoly setting is unchecked, then the product Menu Order becomes editable in other languages, regardless of whether the Polylang setting is turned on or taking effect.
