### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Call to a member function get_home_url() 

### ISSUE THREAD

**Issue by bmpf** [hyyan/woo-poly-integration#342]
#### What product versions and settings are you using when this issue occurs?
* PHP: 7.1.18
* WordPress: WordPress 4.9.6
* WooCommerce: 3.4.2
* Polylang: [state if using Polylang PRO]: 2.3.7 [No pro version]
* Hyyan WooCommerce Polylang Integration: 1.2.0
* Browser: Opera, Chrome.

#### Steps to Reproduce
1. 
1. 
1. 

#### What Happened Instead
PHP Fatal ERROR;
Uncaught Error: Call to a member function get_home_url() on null in wp-content/plugins/woo-poly-integration/src/Hyyan/WPI/Ajax.php:44
#0 wp-includes/class-wp-hook.php(286): Hyyan\WPI\Ajax->filter_woocommerce_ajax_get_endpoint('/?wc-ajax=%%end...', '%%endpoint%%')
#1 wp-includes/plugin.php(203): WP_Hook->apply_filters('/?wc-ajax=%%end...', Array)
#2 wp-content/plugins/woocommerce/includes/class-wc-ajax.php(32): apply_filters('woocommerce_aja...', '/?wc-ajax=%%end...', '%%endpoint%%')
#3 wp-content/plugins/woocommerce/includes/class-wc-frontend-scripts.php(537): WC_AJAX::get_endpoint('%%endpoint%%')
#4 wp-content/plugins/woocommerce/includes/class-wc-frontend-scripts.php(435): WC_Frontend_Scripts::get_script_data('wc-cart-fragmen...')
#5 wp-content/plugins/woocommerce/includes/class-wc-frontend-scripts.php(598):  in wp-content/plugins/woo-poly-integration/src/Hyyan/WPI/Ajax.php on line 44
[19-Jun-2018 07:36:42 UTC] PHP Fatal error:  Uncaught Error: Call to a member function get_home_url() on null in wp-content/plugins/woo-poly-integration/src/Hyyan/WPI/Ajax.php:44

## WordPress Environment

<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.
```
</details>

**Comment by Jon007** [comment]
Maybe there is a problem with your permalinks?
Try going to Settings, Permalinks, set actual values, especially for Product Permalinks - I use something like /p/%product_cat%/  and Save.
The Permalinks should then be set.
(the permalink part is not translated and can cause problems if not set)

**Comment by Jon007** [comment]
closing due to no further response, please feel free to reopen if you have identified a bug
