### ISSUE TITLE
Translated product category loses its parent

### ISSUE THREAD

**Issue by tamelander** [hyyan/woo-poly-integration#344]
Hi,

I have a product category that is "brand" which I have translated to Swedish.  And under that different ski brands, like Salomon and Volkl. The ski brands name are obviously the same for both English and Swedish, but I give them different slugs (e.g. salomon-en and salomon-sv). But. Whenever I try to save a brand (or the Swedish equivalent) to it's place under the parent category, the linked Swedish brand name loses it's place under it's parent. Hard to explain ... Should two identically named categories (en and sv) with different slugs be able to exist? Or what am I missing here? 

All the best
A

**Comment by Jon007** [comment]
It sounds like a corrupted taxonomy.
Something like this can happen if someone accidentally changes the language of an existing category when they meant to create a new category, this sort of thing can mess up the Polylang linkage.

It may be easiest to delete the faulty categories and create new ones.

**Comment by Jon007** [comment]
closing due to lack of response - feel free to reopen if you have identified a bug..

**Comment by tamelander** [comment]
Sorry, I totally missed your answer in July. I just experimented with it again and the problem seems to stick. I will try to delete all setup some new doing it from the parent and down. 

 It might  be something with it being the free version of Polylang, being unfriendly to me trying to circumvent the two things in Free that Pro offers: Share permalinks and Translating Permalinks.

**Comment by Jon007** [comment]
>It might be something with it being the free version of Polylang
No I don't think so, I use free Polylang, 3 languages and loads of categories, no problem except once when I used the wooCommerce importer which was unable to cope with some categories with a comma in the text and really messed things up bad.
