### ISSUE TITLE
I wanted a product on 3 different languages, but got 3 products on the shop page

### ISSUE THREAD

**Issue by izmalkoff** [hyyan/woo-poly-integration#347]
#### What product versions and settings are you using when this issue occurs?
* PHP: 7.2
* WordPress: 4.8 
* WooCommerce: 3.4 
* Polylang: [state if using Polylang PRO] free
* Hyyan WooCommerce Polylang Integration: 
* Browser:  Chrome 64

#### Steps to Reproduce
1.  I added a page for every language of a product
2. I got 3 pages for a product on a different laguages instead of having 1 product on 3 languages. 
3. website https://euro-gallery.com

#### What I Expected

Get 1 product page which can be opened with different language

#### What Happened Instead

3 products on the different languages

## WordPress Environment

<details>
`
### WordPress Environment ###

Home URL: https://euro-gallery.com
Site URL: https://euro-gallery.com
WC Version: 3.4.4
Log Directory Writable: ✔
WP Version: 4.9.7
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips mod_fcgid/2.3.9 PHP/5.4.16
PHP Version: 7.2.5
PHP Post Max Size: 128 MB
PHP Time Limit: 60
PHP Max Input Vars: 1000
cURL Version: 7.29.0
NSS/3.28.4

SUHOSIN Installed: –
MySQL Version: 5.5.56-MariaDB
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.4.4
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
Total Database Size: 16.51MB
Database Data Size: 14.45MB
Database Index Size: 2.06MB
wp_woocommerce_sessions: Data: 0.05MB + Index: 0.02MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_commentmeta: Data: 0.05MB + Index: 0.03MB
wp_comments: Data: 0.02MB + Index: 0.09MB
wp_duplicator_packages: Data: 0.02MB + Index: 0.02MB
wp_gglcptch_whitelist: Data: 0.02MB + Index: 0.02MB
wp_links: Data: 0.02MB + Index: 0.02MB
wp_options: Data: 3.03MB + Index: 0.16MB
wp_postmeta: Data: 1.52MB + Index: 0.41MB
wp_posts: Data: 1.48MB + Index: 0.06MB
wp_revslider_css: Data: 0.13MB + Index: 0.00MB
wp_revslider_layer_animations: Data: 0.02MB + Index: 0.00MB
wp_revslider_navigations: Data: 0.02MB + Index: 0.00MB
wp_revslider_sliders: Data: 0.03MB + Index: 0.00MB
wp_revslider_slides: Data: 0.13MB + Index: 0.00MB
wp_revslider_static_slides: Data: 0.02MB + Index: 0.00MB
wp_smush_dir_images: Data: 0.02MB + Index: 0.03MB
wp_termmeta: Data: 0.02MB + Index: 0.03MB
wp_terms: Data: 0.02MB + Index: 0.03MB
wp_term_relationships: Data: 0.05MB + Index: 0.02MB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB
wp_ulp_campaigns: Data: 0.02MB + Index: 0.00MB
wp_ulp_campaign_items: Data: 0.02MB + Index: 0.00MB
wp_ulp_layers: Data: 0.22MB + Index: 0.00MB
wp_ulp_popups: Data: 0.08MB + Index: 0.00MB
wp_ulp_subscribers: Data: 0.02MB + Index: 0.00MB
wp_ulp_targets: Data: 0.02MB + Index: 0.00MB
wp_ulp_webfonts: Data: 0.09MB + Index: 0.00MB
wp_usermeta: Data: 0.02MB + Index: 0.03MB
wp_users: Data: 0.02MB + Index: 0.05MB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB
wp_wfBadLeechers: Data: 0.02MB + Index: 0.00MB
wp_wfBlockedCommentLog: Data: 0.02MB + Index: 0.00MB
wp_wfBlockedIPLog: Data: 0.02MB + Index: 0.00MB
wp_wfBlocks7: Data: 0.02MB + Index: 0.05MB
wp_wfConfig: Data: 0.39MB + Index: 0.00MB
wp_wfCrawlers: Data: 0.02MB + Index: 0.00MB
wp_wfFileChanges: Data: 0.02MB + Index: 0.00MB
wp_wfFileMods: Data: 3.52MB + Index: 0.00MB
wp_wfHits: Data: 1.02MB + Index: 0.28MB
wp_wfHoover: Data: 0.02MB + Index: 0.02MB
wp_wfIssues: Data: 0.02MB + Index: 0.06MB
wp_wfKnownFileList: Data: 1.52MB + Index: 0.00MB
wp_wfLeechers: Data: 0.06MB + Index: 0.00MB
wp_wfLiveTrafficHuman: Data: 0.02MB + Index: 0.02MB
wp_wfLocs: Data: 0.02MB + Index: 0.00MB
wp_wfLogins: Data: 0.02MB + Index: 0.03MB
wp_wfNotifications: Data: 0.02MB + Index: 0.00MB
wp_wfPendingIssues: Data: 0.02MB + Index: 0.06MB
wp_wfReverseCache: Data: 0.02MB + Index: 0.00MB
wp_wfScanners: Data: 0.02MB + Index: 0.00MB
wp_wfSNIPCache: Data: 0.02MB + Index: 0.05MB
wp_wfStatus: Data: 0.06MB + Index: 0.03MB
wp_wfVulnScanners: Data: 0.02MB + Index: 0.00MB
wp_yoast_seo_links: Data: 0.02MB + Index: 0.02MB
wp_yoast_seo_meta: Data: 0.02MB + Index: 0.00MB

### Post Type Counts ###

attachment: 46
customize_changeset: 26
jetpack_migration: 2
jp_img_sitemap: 1
jp_sitemap: 1
jp_sitemap_master: 1
nav_menu_item: 24
page: 52
polylang_mo: 3
post: 20
product: 53
revision: 91
shop_coupon: 1
tt_font_control: 1
wpcf7_contact_form: 3

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (25) ###

Polylang: by Frédéric Demarle – 2.3.8
Redux Framework: by Team Redux – 3.6.9
Akismet Anti-Spam: by Automattic – 4.0.8
Autoptimize: by Frank Goossens (futtta) – 2.3.4
CMB2: by CMB2 team – 2.4.2
Contact Form 7: by Takayuki Miyoshi – 5.0.3
Cookie Notice: by dFactory – 1.2.44
Duplicator: by Snap Creek – 1.2.40
Easy Google Fonts: by Titanium Themes – 1.4.3
Envato Market: by Envato – 2.0.0
Google Analytics Dashboard for WP (GADWP): by ExactMetrics – 5.3.5
Google Captcha (reCAPTCHA) by BestWebSoft: by BestWebSoft – 1.36
Jetpack by WordPress.com: by Automattic – 6.3.2
WPBakery Page Builder: by Michael M - WPBakery.com – 5.5.2
Layered Popups: by Halfdata
Inc. – 6.40

Really Simple SSL: by Rogier Lankhorst
Mark Wolters – 3.0.5

Slider Revolution: by ThemePunch – 5.4.8
TinyMCE Advanced: by Andrew Ozz – 4.7.11
Hyyan WooCommerce Polylang Integration: by Hyyan Abo Fakher – 1.2.0 – Not tested with the active version of WooCommerce
WooCommerce: by Automattic – 3.4.4
Wordfence Security: by Wordfence – 7.1.9
Yoast SEO: by Team Yoast – 7.9
Facebook Login: by Damian Logghe – 1.2.3
Artday Shortcodes: by WossThemes – 1.2.3
Smush: by WPMU DEV – 2.7.9.1

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #842 - /parduotuve-lt2/
Cart: #808 - /kortele/
Checkout: ❌ Page not set
My account: ❌ Page not set
Terms and conditions: ❌ Page not set

### Theme ###

Name: Artday Child Theme
Version: 1.1.1
Author URL: http://themeforest.net/user/wossthemes
Child Theme: ✔
Parent Theme Name: Artday
Parent Theme Version: 1.6
Parent Theme Author URL: http://themeforest.net/user/wossthemes
WooCommerce Support: ✔

### Templates ###

Overrides: artday/woocommerce/archive-product.php
artday/woocommerce/cart/cart-totals.php
artday/woocommerce/cart/cart.php
artday/woocommerce/cart/proceed-to-checkout-button.php
artday/woocommerce/cart/shipping-calculator.php
artday/woocommerce/checkout/form-billing.php
artday/woocommerce/checkout/form-checkout.php
artday/woocommerce/checkout/form-coupon.php version 3.4.0 is out of date. The core version is 3.4.4
artday/woocommerce/checkout/form-shipping.php
artday/woocommerce/content-product.php
artday/woocommerce/content-product_cat.php
artday/woocommerce/global/form-login.php
artday/woocommerce/global/wrapper-end.php
artday/woocommerce/global/wrapper-start.php
artday/woocommerce/loop/loop-end.php
artday/woocommerce/loop/loop-start.php
artday/woocommerce/myaccount/dashboard.php
artday/woocommerce/myaccount/form-login.php
artday/woocommerce/myaccount/form-lost-password.php
artday/woocommerce/myaccount/my-address.php
artday/woocommerce/myaccount/view-order.php
artday/woocommerce/notices/error.php
artday/woocommerce/notices/notice.php
artday/woocommerce/notices/success.php
artday/woocommerce/order/order-details-customer.php version 3.3.0 is out of date. The core version is 3.4.4
artday/woocommerce/order/order-details.php
artday/woocommerce/single-product/add-to-cart/simple.php
artday/woocommerce/single-product/product-image.php
artday/woocommerce/single-product/related.php
artday/woocommerce/single-product/tabs/additional-information.php
artday/woocommerce/single-product/tabs/description.php
artday/woocommerce/single-product/tabs/tabs.php
artday/woocommerce/single-product-reviews.php
artday/woocommerce/single-product.php

Outdated Templates: ❌
					
					
						Learn how to update
`
</details>

**Comment by Jon007** [comment]
closing as no further response and domain quoted has no ip address configured.
