### ISSUE TITLE
Multicurrency issue

### ISSUE THREAD

**Issue by franciskjijo** [hyyan/woo-poly-integration#349]
Multicurrency product display on product display >> display GEO currency >> checkout USD currency

1. My website displays different products with different currency price tag. eg: products 1 from singapore $$/ product 2 from Malaysia Ring / Product 3 from Canada $$ / Product 4 from Australia $$ / Product 5 from United states. $$
2. When a person from any country views the product, the get the see the product in actual country price and below Approximate price (currency conversion) of GEO country
3. Now a customer from Australia wanted to buy two products 1 (Singapore) 2 ( Malaysia)
3. for the Australian customer the product should display the actual currency value and below Approximate value in AUD on the detail page on each product.
4. At the time of checkout they should see Actual value (singapore / malaysia) two product items converted to USD as common price where the customer pays in USD.

Can anyone suggest me which is the best plugin of yours

**Comment by Jon007** [comment]
Language and currency are two separate things, this plugin is only an extension for Polylang language.
You can also use a currency conversion plugin and some of these do use geolocation.

There is a discussion on currency switchers here:
https://github.com/hyyan/woo-poly-integration/wiki/Pricing

Your mileage may vary and some customisation could be needed.
