### ISSUE TITLE
No products in translated shop page

### ISSUE THREAD

**Issue by Gan-** [hyyan/woo-poly-integration#351]
#### Can you reproduce this issue on default Wordpress theme (eg Storefront)?
Yes

#### Can you reproduce this issue when all other plugins are disabled except WooCommerce, Polylang and Hyyan WooCommerce Polylang Integration?
Yes

#### What product versions and settings are you using when this issue occurs?
* PHP: 7.0
* WordPress: 4.8.9
* WooCommerce: 3.4.4
* Polylang: 2.3.8
* Hyyan WooCommerce Polylang Integration: 1.2.0
* Browser: Chrome

#### Steps to Reproduce
1. I've followed the [getting started](https://github.com/hyyan/woo-poly-integration/wiki/Getting-Started) instructions (translated all 4 woocommerce pages, links are ok ; product categories are translated too).
2. I've created 3 products ; 1 in EN only, 1 in FR only, 1 in both.  Note: EN is the default language.

#### What I Expected
2 products in EN shop, 2 products in FR shop

#### What Happened Instead
2 products in EN shop, 0 product in FR shop.
Plus, there's something strange with the urls.
- With my polylang settings, EN shop page url is /shop and FR is /fr/boutique. When on the EN shop page, the link to the FR page is correct (/fr/boutique). But when you access /fr/boutique, it automatically redirects to /boutique, removing the /fr
- When I enter the url /fr/shop, it shows the expected FR shop page with my 2 FR products.

**Comment by Jon007** [comment]
ok thanks for update - closing
