### ISSUE TITLE
No products in WCFM in secondary language

### ISSUE THREAD

**Issue by entjesbe** [hyyan/woo-poly-integration#355]
#### What product versions and settings are you using when this issue occurs?
* PHP: 5.4.17 (USB webserver)
* WordPress: 4.9.8
* WooCommerce: 3.4.4
* Polylang: [state if using Polylang PRO] 2.3.10
* Hyyan WooCommerce Polylang Integration: 1.2.0
* Browser: Chrome

#### Steps to Reproduce
1. 
1. 
1. 

#### What I Expected
After installing the woo-poly-integration plugin I expected to be able to edit products in the secondary language. But they just don't show up in the WCFM product page. In the WP-admin page they are visible though in Dutch (primary language) as well as Englisch (secondary language).

#### What Happened Instead
Secondary language products don't show up in WCFM product page.

## WordPress Environment

<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.
```
</details>

**Comment by entjesbe** [comment]
Problem solved. Just forgot to create an English WCFM shop manager page.

**Comment by Jon007** [comment]
ok, closing issue then
