### ISSUE TITLE
"Any ..." Variation is not synced

### ISSUE THREAD

**Issue by WooPoolyFix** [hyyan/woo-poly-integration#359]
#### Can you reproduce this issue when all other plugins are disabled except WooCommerce, Polylang and Hyyan WooCommerce Polylang Integration?
Yes
#### What product versions and settings are you using when this issue occurs?
* PHP: 7.2.4
* WordPress: latest
* WooCommerce: latest
* Polylang: [state if using Polylang PRO]
* Hyyan WooCommerce Polylang Integration: latest
* Browser: chrome

#### Steps to Reproduce
1. Select product in main language and set few variations few options selected but also leave few as "Any ..."
2. Translate product to another language.
3. Go to product page in another language.

For example there are these attributes:
Size: Big, Medium, Small
Color: Red, Yellow, Green
Then select these variations:
Size | Color
Any | Red
Any | Yellow
Any | Green
Then translate to other language, and go to product page. The option "Size" dropdown is empty.

#### What I Expected
Variations should have been synced.

#### What Happened Instead
The option "Any ..." wasn't synced. Product page any options which was selected as "Any ..." has the dropdown empty.

**Comment by Jon007** [comment]
The "Any" variations are not valid so cannot be synchronised properly to translations.
If you actually want a variation called "Any"  then you would need to add that to your attributes, for example:
Size: Big, Medium, Small, **Any**
Or if you dont need to set up sizes, just uncheck the box on the attributes tab to stop using size for variation.
