### ISSUE TITLE
Product not translated

### ISSUE THREAD

**Issue by MuhammadWaqasAnsari** [hyyan/woo-poly-integration#360]
Hi Hayyan!
i want to translate products in four different lang.
but issue is that shown product in one lang and other lang show 404 error.
please help me.

M. Waqas Ansari (Wordpress Developer)

**Comment by Jon007** [comment]
Hi, I can't tell exactly what the situation is from this brief description, but my suggestion is:
 - go to Settings, Permalinks
 - make sure you have a value set for Product Permalinks for example Custom Base set to  `/shop/%product_cat%/`
 - save

If you are still having a problem, make sure you can translate Posts with Polylang and the post translation and language switching is working properly.

See also the getting started guide here: https://github.com/hyyan/woo-poly-integration/wiki/Getting-Started

If you are still having a problem, please raise the issue again with a lot more details.
