### ISSUE TITLE
I am making a wordpress website on Oceanwp theme and using polylang along with woo-commerce. The issue is as soon as i activate the "Hyyan" woo-poly-integration plugin the short-code that is supposed to show products on the home page gets disabled. If any one has faced a similar issue please let me know how you did you fix it, any help would be greatly appreciated, thanks

### ISSUE THREAD

**Issue by zaheer11c** [hyyan/woo-poly-integration#363]
#### What product versions and settings are you using when this issue occurs?
* PHP: 
* WordPress: 
* WooCommerce: 
* Polylang: [state if using Polylang PRO]
* Hyyan WooCommerce Polylang Integration: 
* Browser: 

#### Steps to Reproduce
1. 
1. 
1. 

## WordPress Environment

<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.
```
</details>

**Comment by Poromies** [comment]
Hey!

I was facing similar issues, but not fully sure if it is the same case.

When I activated "Hyyan" woo-poly-integration plugin, all the products in the shop disapperared. I had to click them trough and set the language for every product. Then I got them visible again.

**Comment by Jon007** [comment]
Polylang also has the feature to set to default language, in this sort of situation, when you check the Polylang Admin menu "Languages" there is normally a link at the bottom saying that some of your posts have no language set, click here to set them to base language automatically

**Comment by hyyan** [comment]
Closing as Jon007 provided a solution
