### ISSUE TITLE
Polylang + WooCommerce – products categories dissapears!

### ISSUE THREAD

**Issue by justdudeone** [hyyan/woo-poly-integration#364]
Hello,

After a first install WP with StoreFront and WooCommerce works good. Then I install plugins: Polylang with [Hyyan WooCommerce Polylang Integration]. All seems nice, except one huge problem - all products categories that was added or edited with PolyLang - just dissapear from a form where you adding a new product - so all new products can not be setted to any categories and so products just does not shows at a website! When I create a new product category directly from a form of new product adding - this category does not shows at website! So it seems that "original WooCommerce products categories" stop to show at a website and new "PolyLang multilanguage products categories" does not exist at product adding form.
How to fix this??? :(((

UPDATE: It sems that when user creating a new products at ProductCreatingForm - user need to change primary language for this product at top right corner - after that all categories appears based on their primary language. But I dont understand where a text fields for a different languages for one product??? So with this software I need to create each product separately for each language?!?! Is there are possibility just to add another text at different language for already existing products??? (It much easy for add a products, for controlling a quantity of goods remains, for statistic analize of buyers interest, etc.)

UPDATE2:
If disable: [WP-CP -> Languages -> Settings -> Custom taxonomies] then ProductCategories are identical for all languages - what at url is OK, but at website menu is unacceptable!

So it seems that [Hyyan WooCommerce Polylang Integration plugin] have a fundamental logical problem/complexity - it devide/split all Products/ProductCategories/Tags/etc for all languages at WordPress as different items and then even link them. But it would be much comfortable to just add to all existing items (Products/ProductsCategories/Tags/etc) a new text fields for all information that see readers&buyers (maybe via tabs etc), or just in one original sql table cell add new language info by separating with commas like $$$en$$$/$$$de$$$ that will devide each language from enother languages for showing to admin-editor and users-readers.

So I dont really like to fash with all this complexity of [Hyyan WooCommerce Polylang Integration plugin], I just want to open existing product and just add a new translation for a just 2-3 text fields.

PS By the way it will be nice to add for multilanguage products categories not only "different languages categories name" but also a bigger fields for a "different languages categories detailed info (description)" for each language!

**Comment by waritthornnudee** [comment]
In my case my product has only in Thai language. You need to  create product in English language It make you can choose product category(englisdh) in english language.

**Comment by Jon007** [comment]
>So with this software I need to create each product separately for each language
This plugin extends Polylang which works by associating posts and taxonomies with languages, and yes, creating a separate post for each language.  
WooCommerce products are extended posts, so any WooCommerce Polylang will work in the same way by creating separate posts/products for each language.

For simple language blocks without any tool you can just use css and a front end language switcher but that's not a topic for here.
