### ISSUE TITLE
Subject and title of downloadable products email not translated

### ISSUE THREAD

**Issue by mairav** [hyyan/woo-poly-integration#365]
#### Can you reproduce this issue on default Wordpress theme (eg Storefront)?
It's a production site, I can't change the theme.

#### Can you reproduce this issue when all other plugins are disabled except WooCommerce, Polylang and Hyyan WooCommerce Polylang Integration?
It's a production site, I can't disable all plugins.

#### What product versions and settings are you using when this issue occurs?
* PHP: 7.1
* WordPress: Last version
* WooCommerce: Last version
* Polylang: [state if using Polylang PRO] Free Last version
* Hyyan WooCommerce Polylang Integration: Last version
* Browser: Chrome

#### Steps to Reproduce
1. I have created virtual, downloadable products, free with related downloads. 
1. When someone purchases a product in my spanish site, he receives an email translated to spanish except for the title and subjet. They still are:
- Subject: Your xxxsite order from 18 septiembre, 2018 is complete - download your files
- Title: Your order is complete - download your files
1. I read in the tutorials, that I have to go to Woocommerce email settings and save the template "completed order" so the string can be created. That template is for orders without downloadable products. If I remove from the product the downloadable files, the title and subject are translated.
If I add the files again, the subject and title are not translated. I couldnt find where to force the strings to be created for that option.
I also have a plugin that creates license keys. If the products has no files attached the term License key is translated to "Clave de licencia" as it should. If I attach files, and starts using the "download your files" option, it stops translating the "license keys" part.

#### What I Expected
The title and subject in emails sent for downloadable products to be translated.

#### What Happened Instead
They are not translated.
Other plugins that add content to that particular email are not translated either.

## WordPress Environment

<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.
```
</details>

**Comment by Jon007** [comment]
you missed out copying the system status report from WooCommerce.
Do try testing this on a test site with a standard theme like Storefront, as there may well be a theme or other customisation which might be interfering with the translation

**Comment by hyyan** [comment]
Closing as there is no feedback, and the system status is missing, please feel free to reopen if this stills an issue
