### ISSUE TITLE
WooCommerce email footer text line-breaks

### ISSUE THREAD

**Issue by m0n0mind** [hyyan/woo-poly-integration#366]
I noticed missing line breaks on woocommerce email notifications in the footer text part when using your plugin.
Line breaks from the woocommerce email footer input setting are being stripped away, at least for plain-text emails and the related translation (here both in html and plain-text).

I didn’t dig too deep into this right now (looking in the db tables and such) but think that one line text inputs for the translation interface are not quite enough for translating some texts that were entered in textareas that have line-breaks in’em. But that's a polylang issue I suppose...

Didn't anyone else notice this behaviour.

As of today, using most recent WP and plugin versions on PHP 7.0.

**Comment by Jon007** [comment]
>one line text inputs for the translation interface are not quite enough
this plugin is only translating the subject and shop email address using the string translation table...

For adding extra text for the footer check what template overrides you are using and also check if you've been putting custom translation in Loco Translate

**Comment by Jon007** [comment]
oh right yes that field - actually that supports html so you can add links, line breaks <br />, whatever you want

**Comment by m0n0mind** [comment]
Sure ok, but it's strange because the line breaks entered in the email footer text box in WC settings gets stripped once you translate with the poly string translations interface. It's just not very user friendly. But oh my ;)
