### ISSUE TITLE
Ajax URL filtering when no language is selected in admin returns empty URL.

### ISSUE THREAD

**Issue by gonzomir** [hyyan/woo-poly-integration#367]
I discovered the issue when working with [WooCommerce Appointments](https://bizzthemes.com/plugins/woocommerce-appointments/) plugin and creatin appointment in the admin backend. If no language is selected in the admin bar `Hyyan\WPI\Ajax->filter_woocommerce_ajax_get_endpoint()` returns empty string and the AJAX calls fail.

#### Can you reproduce this issue on default Wordpress theme (eg Storefront)?
Haven't tried, the theme is not relevant to the issue.

#### Can you reproduce this issue when all other plugins are disabled except WooCommerce, Polylang and Hyyan WooCommerce Polylang Integration?
Haven't tried, as the issue is related to AJAX calls, made by WooCommerce Appointments. I'm not sure where to find AJAX calls in the admin backend.

#### What product versions and settings are you using when this issue occurs?
* PHP: 7.0 and 7.2
* WordPress: 4.9.8
* WooCommerce: 3=5=4
* Polylang: 2=3=10
* Hyyan WooCommerce Polylang Integration: 1.2.0
* Browser: any

**Comment by gonzomir** [comment]
@Jon007 I submitted a PR that fixed the issue for me: #368. The problem may affect other plugins that do AJAX in the admin area.

**Comment by Jon007** [comment]
Your solution is good, may even fix some wider issues, I need to think and review the test cases.

I do think that we could just add an extra check to your pull request to return the original $url if there is any unexpected  problem with the polylang, but may not be necessary.
But more testing needed

**Comment by gonzomir** [comment]
I'll add that check, if there's anything I can do, please, let me know.

**Comment by Jon007** [comment]
fixed in #368
I've previously been using alternative of not applying the filter at all if is_admin() .. still not convinced it would ever be necessary to apply the filter when in admin mode but in any case should work better than previously checked in version
