### ISSUE TITLE
variable product with attributes that have empty values

### ISSUE THREAD

**Issue by mephistopheles4** [hyyan/woo-poly-integration#369]
#### Steps to Reproduce
1.  create a product with more than one attribute (I used color and size)
2. create variations with the color attributes and set the size to any size
3. translate the product

#### What I Expected
the translated product would have the same attributes and values

#### What Happened Instead
the translated product size attribute got translated with the wrong value (first one in the list)

## My fix
in the file Variation.php i replaced the line 268 from:
`if (pll_is_translated_taxonomy($tax)) {`
to
`if (pll_is_translated_taxonomy($tax) && !empty($termSlug)) {`

other than that, thanks for the great plugin! :)

**Comment by Jon007** [comment]
you might be onto something but I don't quite get it...   you are creating variations based on color and size, but then leaving the size blank?

**Comment by pascalknecht** [comment]
@Jon007 Please have a look at the screenshot. This is a perfectly valid variable product in woocommerce and it also works perfectly in the untranslated version. It means that any attribute value is allowed and can be bought in combination with the set value. It currenty only does not work in the translated products.

**Comment by mephistopheles4** [comment]
it's completely valid to leave the attribute unset for the variation.
I noticed that on issue #359 you mention to not check the box "use this attribute for variations" but when you uncheck that box the choice won't appear to clients in the front end.

in my case, I have a lot of t-shirts which with variable colours but they all have the same sizes. so I create variations for the colours and set the size to any that way they could get any size of any colour.
that configuration works well without polylang. 
with woo-poly, the translated product automatically gets the first value if that attribute when you set it to any which isn't correct.

**Comment by Jon007** [comment]
Ok I get it, I guess it never worked with this plugin!
who wants to make this a pull request?
