### ISSUE TITLE
Problem with cart translations 

### ISSUE THREAD

**Issue by Artech-Solutions** [hyyan/woo-poly-integration#37]
Hi,

i have a problem with the translations of the cart when adding, removing or updating items.
While everything else works fine with the translations the popup windows i get aren't translated.
The url of one product is here http://cretanflavors.com/sidal/?product=klidi-germaniko-cr-v-12-13
If you add it to the cart by pushing ΠΡΟΣΘΗΚΗ ΣΤΟ ΚΑΛΑΘΙ you will get an english popup message and not a greek one even though to .po & .mo files are correctly translated.
If i disable the plugin everything works fine with the translations but i have other issues.
Looking forward for your help.

Thank you very much.

**Comment by decarvalhoaa** [comment]
Hi,

as far as I know, the woo-poly-integration plugin doesn't touch the "add to cart" notification message in the single product page.

I understand that you deactivated the plugin and it works, but I think this is more related with a conflict with your theme. What theme are you using? Does the theme, or you in you on your child theme, overwrite some woocommerce templates?

I believe 'wc_print_notices' function is responsible for this notice message.

Look in your theme or child theme code that are messing around with this part of the single product template: https://github.com/woothemes/woocommerce/blob/master/templates/content-single-product.php#L26-L31
Things that may be using the action 'woocommerce_before_single_product' or modifying 'wc_print_notices' function that is hooked to this action.

**Comment by Artech-Solutions** [comment]
Hi,

thanks for the information.
I did some tests and the problem is fixed only when i deactivate the polylang plugin and not the hyan plugin and i have only one version of the website.
if i have both english and greek versions i get only the english cart notifications.
The theme i use is genesis from studiopress.

**Comment by decarvalhoaa** [comment]
I would then recommend reaching out to studiopress guys, since this is a premium/paid theme they should support you if you are still entitled for support. Does genesis have support for woocommerce? didn't find that piece of information in their website.

**Comment by Artech-Solutions** [comment]
Thank you for your help,
did some tries with the plugins and everything and it works fine right now.
Don't know how it was fixed but i am happy :)
Thanks again!

**Comment by decarvalhoaa** [comment]
Glad to hear it!
