### ISSUE TITLE
Woocommerce Shop Page is not always showing the products, need to resave again after....?

### ISSUE THREAD

**Issue by wesweat** [hyyan/woo-poly-integration#371]
#### What product versions and settings are you using when this issue occurs?
* PHP: 5.6.12
* WordPress: 4.9.8
* WooCommerce: 1.12.21
* Polylang: free [state if using Polylang PRO]
* Hyyan WooCommerce Polylang Integration: 1.2.0
* Browser: Firefox 62.0.3

#### Steps to Reproduce
1. select languages -> setttings 

#### What I Expected
http://localhost/mysite.com/shop page products  shown

#### What Happened Instead
http://localhost/mysite.com/shop gives the message:
No products were found matching your selection.

### This is what i notice
1/ If  I select languages -> setttings  again
2/ subselect -> Custom post types and Taxonomies and save
3/ http://localhost/mysite.com/shop products are shown again???
(so i need to resave Custom post types and Taxonomies again after visiting languages -> settings)

**Comment by Jon007** [comment]
I just replied to the similar topic on wordpress.org, and I still don't understand it:
https://wordpress.org/support/topic/selecting-pagemlang_settings-and-my-shop-page-is-empty/

Shop products don't appear and disappear just by visiting another page or by saving with no changes: at least there are 10,000 installations which don't have this type of problem, so if you have encountered some strange incompatibility you need to provide more detail before it can be diagnosed.

So please specify more detail and include the system status report as requested.

Also, to open an issue on here, please answer these questions:
Can you reproduce this issue on default Wordpress theme (eg Storefront)?
Can you reproduce this issue when all other plugins are disabled except WooCommerce, Polylang and Hyyan WooCommerce Polylang Integration?

As these are very important in diagnosing compatibility issues.

I'm going to close the issue as the required questions are not answered, please either add the information and reopen or start again with a new issue explaining in more detail what actions you are taking.
