### ISSUE TITLE
Shop page in portuguese redirect to home page in english

### ISSUE THREAD

**Issue by ivex001** [hyyan/woo-poly-integration#372]
#### Can you reproduce this issue on default Wordpress theme (eg Storefront)?

Yes!

#### Can you reproduce this issue when all other plugins are disabled except WooCommerce, Polylang and Hyyan WooCommerce Polylang Integration?

Yes!

#### What product versions and settings are you using when this issue occurs?

* PHP: 5.6.38
* WordPress: 4.9.8
* WooCommerce: 3.4.5
* Polylang: 2.3.11 [Free Version]
* Hyyan WooCommerce Polylang Integration: 1.2.0
* Browser: Any

#### Steps to Reproduce

1. Go to shop page in portuguese
2. Change Language to English 

#### What I Expected

The shop page in english to show up

#### What Happened Instead

Goes to home page in english

## WordPress Environment

<details>
```
URL da página inicial: |   | https://cogent.cv
-- | -- | --
URL do site: |   | https://cogent.cv
Versão do WooCommerce.: |   | 3.4.5
Diretório de Registos Log com permissão de escrita..: |   | /home/cogent/public_html/wp-content/uploads/wc-logs/
Versão do WordPress: |   | 4.9.8
WordPress multisite: |   | –
Limite de memória do WordPress: |   | 512 MB
Modo de depuração do WordPress: |   | –
Tarefas agendadas do WordPress: |   |  
Idioma: |   | pt_PT
Cache de objectos externa: |   | –


```
</details>

**Comment by Jon007** [comment]
Which language is the base language?
Is the Shop page translated into English and is the English version published?
Check Pages in wp-admin and find the English shop page.
The key woocommerce pages need to be translated to all site languages:  the pages themselves can be blank but they must exist and be published, 
see also:
https://github.com/hyyan/woo-poly-integration/wiki/Getting-Started

**Comment by ivex001** [comment]
Thanks it working fine now. I think the problem is when the store is empty. When it doesn't have products it  behaves like that. I installed woo poly and started testing and it wasn't working. but after putting some produtcs now its working
Thank you again

**Comment by Jon007** [comment]
ok, closing the issue then
