### ISSUE TITLE
Custom taxonomy, acf image and synchronization

### ISSUE THREAD

**Issue by yarovikov** [hyyan/woo-poly-integration#378]
Hi) A use my wp template with custom product category and acf image as category image. Сan i make automatic synchronization for this image?

<img width="753" alt="screenshot 2018-10-22 at 19 19 53" src="https://user-images.githubusercontent.com/30932012/47304546-9ec02680-d62f-11e8-81f3-cd859f14fab4.png">

PHP 7.2
Wordpress 4.9.8
WooCommerce 3.4.7
Polylang 2.3.11 (not pro)
Hyyan WooCommerce Polylang Integration 1.2.0

Thanks in advance!

**Comment by hyyan** [comment]
This possible but it is out of this plugin scope , you need to check [polylang docs here ](https://polylang.pro/doc/working-with-media/)
