### ISSUE TITLE
Woocomerce Pages (like checkout/basket) not showing in selected language

### ISSUE THREAD

**Issue by AndrewBrettWatson** [hyyan/woo-poly-integration#379]
Hi, I read that you don't want to issues to be posted on the WordPress forum, so here i am. I have what i think is a simple issue.

**What I Expected**: When I add a product to the cart and click checkout, it should be in the same language that is currently set.

**What Happened Instead**: I click "checkout" with the page set to English and I get the checkout page in French (which is the default language)

What I think is happening: When I first put the site together and clicked on "checkout", nothing happened until I use the woocommerce tools to “Create default WooCommerce pages” now the checkout pages work. But it’s pretty clear to me these pages only exist in french and I think the solution is to create them in the other languages but I don’t know how. I have the language files installed, so do you happen to know how I create the default WooCommerce pages in each language?

Any help gratefully received

Steps to Reproduce:
1. Got to site, choose English as language
2. Add item to shopping cart and click "checkout"
3. Arrive at the French checkout page (not the checkout page in English as intended)

Can you reproduce this issue on default Wordpress theme (eg Storefront)? Yes.
Can you reproduce this issue when all other plugins are disabled except WooCommerce, Polylang and Hyyan WooCommerce Polylang Integration? Yes.

What product versions and settings are you using when this issue occurs?
* PHP:  7.2.12
* WordPress:  4.9.8
* WooCommerce: Verson 3.5.1 (also tried with 3.2.1)
* Polylang: Standard
* Hyyan WooCommerce Polylang Integration: 
* Browser: Firefox, Chrome

WordPress Environment
<details>
WooCommerce version: |   | 3.5.1
WordPress version: |   | 4.9.8
WordPress multisite: |   | –
WordPress memory limit: |   | 256 MB
WordPress debug mode: |   | –
WordPress cron: |   |  
Language: |   | en_GB
PHP version: |   | 7.2.12
PHP post max size: |   | 32 MB
PHP time limit: |   | 300
PHP max input vars: |   | 1000
cURL version: |   | 7.62.0, OpenSSL/1.0.2p
Shop base: |   | #5498 - /fr/shop/
Basket: |   | #5499 - /fr/cart/
Checkout: |   | #5500 - /fr/checkout/
My account: |   | #5501 - /fr/my-account/
Terms and conditions: |   | Page not set
</details>

**Comment by AndrewBrettWatson** [comment]
Update. It only happens when Polylang is activated.
i.e. If I Polylang IS activated and I choose English, then add a product to the cart and click checkout, it sends me to the french checkout page (even I have also set English to my default language in polylang). If I deactivate polylang and put a product in the cart and click checkout then I go through to the English checkout, everything is in English.

**Comment by AndrewBrettWatson** [comment]
Update. I have establish that single language is working perfectly. That is to say, if i set the language to either English, French or German the whole site functions perfectly and all the woocommerce pages are translated. I also asked at the polylang forum and they confirmed that out of the box Polylang does not work with woocommrece so I need this plugin.

All i need to do now is try to solve the problem that when a user goes to the checkout or shopping cart it just changes to the french language.

With over 10,000 installs and a rating of 5+ I am guessing something is wrong with my installation I would appreciate any help you can offer in finding it.

**Comment by hyyan** [comment]
@AndrewBrettWatson You need to translate WooCommerce pages manually. Please checkout the [plugin docs ](https://github.com/hyyan/woo-poly-integration/wiki) and [polylang docs](https://polylang.wordpress.com/documentation/setting-up-a-wordpress-multilingual-site-with-polylang/translating-posts-or-pages/)
