### ISSUE TITLE
My-account page and check-out entirely not translated..?

### ISSUE THREAD

**Issue by igorjik1992** [hyyan/woo-poly-integration#38]
Hello all, 

Some how non of the woo-commerce pages are translated... Is this common behaviour? Or is there something conflicting?

http://www.13grandmothersremedies.com/cart

Regards, 
Igor

**Comment by decarvalhoaa** [comment]
It is not common behaviour. Did you created the english translated pages in the admin backend -> pages. Just leave the content empty.
