### ISSUE TITLE
Cannot change product type on translated only product

### ISSUE THREAD

**Issue by repli2dev** [hyyan/woo-poly-integration#380]
#### What product versions and settings are you using when this issue occurs?
* PHP: 7.1
* WordPress: 4.9.8
* WooCommerce: 3.5.1
* Polylang: 2.4
* Hyyan WooCommerce Polylang Integration: 1.2.0 
* Browser: nay

#### Steps to Reproduce
1. Create new product in one of translated languages (only in that language)
1. Save
1. You cannot change product type, nor virtuality or downloadability.

#### What I Expected

Change of the product type, virtuality or downloadability will work as usual...

#### What Happened Instead

The fields are read-only.

**Comment by hyyan** [comment]
@repli2dev  Go to the plugin settings page and disable the Fields Locker feature , usually you need to update the original product only and on save the changes will be synced to its translation

**Comment by repli2dev** [comment]
Thx for clarification.
