### ISSUE TITLE
 I have read and agree to the website ...terms... -> no string in polylang

### ISSUE THREAD

**Issue by BaltasarParreira** [hyyan/woo-poly-integration#381]
At the checkout this phrase  is always in English and does't exist on the Polylang strings for translation.
Is this a bug? Or I'm missing something?

**Comment by BaltasarParreira** [comment]
Also no translation for woocommerce_gateway_description !

**Comment by hyyan** [comment]
Hey @BaltasarParreira  , you have not filled your system details section so we can not help a lot.
Please read the plugin [wiki -> String Translations ](https://github.com/hyyan/woo-poly-integration/wiki/Strings-translations).

**Comment by BaltasarParreira** [comment]
Sorry didn't understand what you mean, anyway here is a screen capture from one of the translated strings that shows always in English on the front office.
![wp-strings](https://user-images.githubusercontent.com/1650425/49334840-af24d300-f5d7-11e8-93bc-907151101f15.jpg)

**Comment by BaltasarParreira** [comment]
Sorry, found the problem.
I was using the the standard PayPal payment and the string translation was referring to the PayPal checkout gateway, so as soon I change to that gateway the string started being translated.
Now only the initial problem stays, which is the phrase:
"I have read and agree to the website... terms ..." in the bottom of checkout payment, this one does's really show on any polylang strings to translate but I think this is related with woocomerce translations or something fixed with my theme and has nothing to do with your plugin.
Thanks for the support anyway.
