### ISSUE TITLE
"Add to cart" fails on product category view; mini cart drop-down message invisible.

### ISSUE THREAD

**Issue by suite2e11** [hyyan/woo-poly-integration#384]
While Hyyan plugin is activated:
"Add to cart" fails on product CATEGORY view, nothing can be added to cart; 
"Add to cart" works on product DETAILS view, and immediately reflected on the mini cart;
mini cart drop-down message is invisible.

If Hyyan plugin is deactivated:
"Add to cart" works on product category view, item can be added to cart; 
"Add to cart" works on product details view, and immediately reflected on mini cart;
mini cart drop-down message appears normally.

One more problem:
On cart view, no item can be removed by clicking the "x" button.  No matter what theme is in use.  Is it a woocommerce problem?  Spent many days on googling, no luck.

Your help is much appreciated.

#### Can you reproduce this issue on default Wordpress theme (eg Storefront)?
Yes, same problems for different themes, all of them woocommerce compatible.
eStore, StoreFront, OceanWP 

#### Can you reproduce this issue when all other plugins are disabled except WooCommerce, Polylang and Hyyan WooCommerce Polylang Integration?
Yes.

#### What product versions and settings are you using when this issue occurs?
* PHP:  7.2 (also tried 7.0)
* WordPress:  4.9.9 (also tried 4.8.7 and 4.9.8)  installed with git clone
* WooCommerce: 3.5.1 (also tried 3.4)
* Polylang:  2.5 (also tried earlier versions)  [not using Polylang PRO]
* Hyyan WooCommerce Polylang Integration: 1.2.0
* Web server: Nginx 1.14.1  (no Apache)
* Browser: Chrome, IE

**Comment by Jon007** [comment]
This works fine for me with:
Storefront 2.4.2
WP 5.0.2
woocommerce 3.5.1
polylang 2.5 (standard)
woopoly 1.2.0

both adding from category page and removing from minicart

**Comment by Jon007** [comment]
Sorry, I'll correct that, as the currently checked in version of the polylang aware cart doesnt align with the woocommerce version (or the version I was testing)
