### ISSUE TITLE
Compatibility issues with WooCommerce MercadoPago

### ISSUE THREAD

**Issue by leandroprz** [hyyan/woo-poly-integration#385]
#### Can you reproduce this issue on default Wordpress theme (eg Storefront)?

Yes.

#### Can you reproduce this issue when all other plugins are disabled except WooCommerce, Polylang and Hyyan WooCommerce Polylang Integration?

The compatibility issue is with another plugin, so no.

#### What product versions and settings are you using when this issue occurs?
* PHP: 7.2.11
* WordPress: 4.9.8
* WooCommerce: 3.5.3
* Polylang: 2.5 free 
* Hyyan WooCommerce Polylang Integration: 1.2.0
* Browser: Chrome 71.0.3578.98 on Windows 10

#### Steps to Reproduce
1. Install WooCommerce MercadoPago but don't enable it.
2. Enable Hyyan WooCommerce Polylang Integration
3. Enable WooCommerce MercadoPago

#### What I Expected
I expected the page to load with no delay.

#### What Happened Instead
The page loads incredible slow, then the plugin is enabled but every single page take minutes to load.

## WordPress Environment

<details>
`
### WordPress Environment ###

Home URL: http://localhost/polylang
Site URL: http://localhost/polylang
WC Version: 3.5.3
Log Directory Writable: ✔
WP Version: ❌ 4.9.8 - Hay una versión nueva de WordPress disponible (5.0.2)
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: es_ES
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.35 (Win64) OpenSSL/1.1.0i PHP/7.2.11
PHP Version: 7.2.11
PHP Post Max Size: 2 GB
PHP Time Limit: 36000
PHP Max Input Vars: 1000
cURL Version: 7.61.1
OpenSSL/1.1.0i

SUHOSIN Installed: –
MySQL Version: 5.7.24
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Tu servidor no tiene la clase SoapClient habilitada - puede que algunos plugins de puerta de enlace que utilizan SOAP no funcionen como se espera.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.5.3
WC Database Prefix: ss67mkxo_
MaxMind GeoIP Database: ✔
Tamaño total de la base de datos: 70.37MB
Tamaño de los datos de la base de datos: 58.89MB
Tamaño del índice de la base de datos: 11.48MB
ss67mkxo_woocommerce_sessions: Datos: 0.01MB + Índice: 0.00MB
ss67mkxo_woocommerce_api_keys: Datos: 0.00MB + Índice: 0.01MB
ss67mkxo_woocommerce_attribute_taxonomies: Datos: 0.00MB + Índice: 0.00MB
ss67mkxo_woocommerce_downloadable_product_permissions: Datos: 0.00MB + Índice: 0.01MB
ss67mkxo_woocommerce_order_items: Datos: 0.00MB + Índice: 0.00MB
ss67mkxo_woocommerce_order_itemmeta: Datos: 0.02MB + Índice: 0.01MB
ss67mkxo_woocommerce_tax_rates: Datos: 0.00MB + Índice: 0.00MB
ss67mkxo_woocommerce_tax_rate_locations: Datos: 0.00MB + Índice: 0.00MB
ss67mkxo_woocommerce_shipping_zones: Datos: 0.00MB + Índice: 0.00MB
ss67mkxo_woocommerce_shipping_zone_locations: Datos: 0.00MB + Índice: 0.01MB
ss67mkxo_woocommerce_shipping_zone_methods: Datos: 0.00MB + Índice: 0.00MB
ss67mkxo_woocommerce_payment_tokens: Datos: 0.00MB + Índice: 0.00MB
ss67mkxo_woocommerce_payment_tokenmeta: Datos: 0.00MB + Índice: 0.00MB
ss67mkxo_woocommerce_log: Datos: 0.00MB + Índice: 0.00MB
ss67mkxo_appreciate: Datos: 0.00MB + Índice: 0.00MB
ss67mkxo_commentmeta: Datos: 0.02MB + Índice: 0.02MB
ss67mkxo_comments: Datos: 0.03MB + Índice: 0.02MB
ss67mkxo_icl_cms_nav_cache: Datos: 0.00MB + Índice: 0.00MB
ss67mkxo_icl_content_status: Datos: 0.00MB + Índice: 0.00MB
ss67mkxo_icl_core_status: Datos: 0.00MB + Índice: 0.00MB
ss67mkxo_icl_flags: Datos: 0.00MB + Índice: 0.00MB
ss67mkxo_icl_languages: Datos: 0.00MB + Índice: 0.01MB
ss67mkxo_icl_languages_translations: Datos: 0.10MB + Índice: 0.10MB
ss67mkxo_icl_locale_map: Datos: 0.00MB + Índice: 0.00MB
ss67mkxo_icl_message_status: Datos: 0.00MB + Índice: 0.00MB
ss67mkxo_icl_mo_files_domains: Datos: 0.00MB + Índice: 0.00MB
ss67mkxo_icl_node: Datos: 0.00MB + Índice: 0.00MB
ss67mkxo_icl_reminders: Datos: 0.00MB + Índice: 0.00MB
ss67mkxo_icl_strings: Datos: 4.16MB + Índice: 2.91MB
ss67mkxo_icl_string_packages: Datos: 0.00MB + Índice: 0.00MB
ss67mkxo_icl_string_pages: Datos: 0.00MB + Índice: 0.00MB
ss67mkxo_icl_string_positions: Datos: 0.05MB + Índice: 0.02MB
ss67mkxo_icl_string_status: Datos: 0.00MB + Índice: 0.00MB
ss67mkxo_icl_string_translations: Datos: 1.83MB + Índice: 0.58MB
ss67mkxo_icl_string_urls: Datos: 0.00MB + Índice: 0.00MB
ss67mkxo_icl_translate: Datos: 3.32MB + Índice: 0.46MB
ss67mkxo_icl_translate_job: Datos: 0.04MB + Índice: 0.02MB
ss67mkxo_icl_translations: Datos: 0.29MB + Índice: 0.51MB
ss67mkxo_icl_translation_batches: Datos: 0.00MB + Índice: 0.00MB
ss67mkxo_icl_translation_status: Datos: 3.81MB + Índice: 0.05MB
ss67mkxo_itsec_distributed_storage: Datos: 16.32MB + Índice: 0.00MB
ss67mkxo_itsec_fingerprints: Datos: 0.00MB + Índice: 0.00MB
ss67mkxo_itsec_geolocation_cache: Datos: 0.00MB + Índice: 0.00MB
ss67mkxo_itsec_lockouts: Datos: 0.00MB + Índice: 0.00MB
ss67mkxo_itsec_logs: Datos: 3.87MB + Índice: 0.03MB
ss67mkxo_itsec_temp: Datos: 0.00MB + Índice: 0.00MB
ss67mkxo_links: Datos: 0.00MB + Índice: 0.00MB
ss67mkxo_login_fails: Datos: 0.00MB + Índice: 0.00MB
ss67mkxo_opanda_leads: Datos: 0.00MB + Índice: 0.00MB
ss67mkxo_opanda_leads_fields: Datos: 0.00MB + Índice: 0.00MB
ss67mkxo_opanda_stats_v2: Datos: 0.00MB + Índice: 0.01MB
ss67mkxo_options: Datos: 6.02MB + Índice: 0.16MB
ss67mkxo_postmeta: Datos: 14.15MB + Índice: 4.20MB
ss67mkxo_posts: Datos: 3.42MB + Índice: 0.44MB
ss67mkxo_redirection_404: Datos: 0.16MB + Índice: 0.06MB
ss67mkxo_redirection_groups: Datos: 0.00MB + Índice: 0.00MB
ss67mkxo_redirection_items: Datos: 0.01MB + Índice: 0.02MB
ss67mkxo_redirection_logs: Datos: 0.05MB + Índice: 0.02MB
ss67mkxo_statistics_search: Datos: 0.00MB + Índice: 0.00MB
ss67mkxo_termmeta: Datos: 0.05MB + Índice: 0.04MB
ss67mkxo_terms: Datos: 0.19MB + Índice: 0.24MB
ss67mkxo_term_relationships: Datos: 0.61MB + Índice: 1.24MB
ss67mkxo_term_taxonomy: Datos: 0.30MB + Índice: 0.23MB
ss67mkxo_usermeta: Datos: 0.04MB + Índice: 0.04MB
ss67mkxo_users: Datos: 0.00MB + Índice: 0.01MB
ss67mkxo_wc_download_log: Datos: 0.00MB + Índice: 0.00MB
ss67mkxo_wc_webhooks: Datos: 0.00MB + Índice: 0.00MB
ss67mkxo_woopricesim_fields: Datos: 0.01MB + Índice: 0.00MB
ss67mkxo_woopricesim_regex: Datos: 0.00MB + Índice: 0.00MB
ss67mkxo_woopricesim_settings: Datos: 0.00MB + Índice: 0.00MB
ss67mkxo_woopricesim_simulations: Datos: 0.01MB + Índice: 0.00MB
ss67mkxo_woopricesim_simulators: Datos: 0.00MB + Índice: 0.00MB

### Post Type Counts ###

attachment: 1910
customize_changeset: 2
ds-gallery: 6
feedback: 83
fluxus_portfolio: 27
mc4wp-form: 2
nav_menu_item: 139
opanda-item: 6
options: 1
page: 48
polylang_mo: 2
post: 68
product: 855
product_variation: 932
project_media: 336
revision: 25
shop_coupon: 6
shop_order: 25

### Security ###

Secure connection (HTTPS): ❌
					Tu tienda no está usando HTTPS. Aprende más sobre HTTPS y los certificados SSL.
Hide errors from visitors: ✔

### Active Plugins (26) ###

Polylang: por Frédéric Demarle – 2.5
Ad Inserter: por Igor Funa – 2.4.5
Ajax Search Lite: por Ernest Marcinko – 4.7.20
All In One SEO Pack: por Michael Torbert – 2.10.1
Better Search Replace: por Delicious Brains – 1.3.2
iThemes Security: por iThemes – 7.2.0
Customer Reviews for WooCommerce: por ivole – 3.52
Disqus for WordPress: por Disqus – 3.0.16
Funciones: por The Internet – 1.0
Jetpack by WordPress.com: por Automattic – 6.8.1
MailChimp for WordPress: por ibericode – 4.3.2
No Right Click Images Plugin: por Keith P. Graham – 3.1
Play The Video (Map,image) On Mouseover For WooCommerce: por Rednumber – 2.3 – No probado con la versión activa de WooCommerce
Re-add text underline and justify: por Brice Capobianco – 0.2
Redirection: por John Godley – 3.6.3
Social Locker | BizPanda: por OnePress – 5.3.0
TWB Woocommerce Reviews: por Abu Bakar – 1.6 – No probado con la versión activa de WooCommerce
Twenty20 Image Before-After: por Zayed Baloch – 1.5.5
W3 Total Cache: por Frederick Townes – 0.9.7
Woo Checkout for Digital Goods: por Multidots – 2.3
Hyyan WooCommerce Polylang Integration: por Hyyan Abo Fakher – 1.2.0 – No probado con la versión activa de WooCommerce
AWS Price Calculator: por Altos Web Solutions Italia – 2.3.1 – No probado con la versión activa de WooCommerce
WooCommerce PayPal Checkout Gateway: por WooCommerce – 1.6.5
Booster for WooCommerce: por Algoritmika Ltd – 4.1.0
WooCommerce: por Automattic – 3.5.3
YITH WooCommerce Name Your Price: por YITH – 1.1.2

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Base de la tienda: #13120 - /en/store/
Carrito: #10041 - /tienda/carrito/
Finalizar compra: #10042 - /tienda/checkout/
Mi cuenta: #10043 - /tienda/mi-cuenta/
Términos y condiciones: #15090 - /terminos-y-condiciones/

### Theme ###

Name: Storefront
Version: 2.4.2
Author URL: https://woocommerce.com/
Child Theme: ❌ – Si estás modificando WooCommerce en un tema padre que no has creado personalmente
te recomendamos utilizar un tema hijo. Ver: Cómo crear un tema hijo

WooCommerce Support: ✔

### Templates ###

Overrides: –
`
</details>

**Comment by Jon007** [comment]
That's very odd!
So it only happens when both MercadoPago and Hyyan are activated at the same time?

I'm not familiar with MercadoPago but some payment plugins do load themselves on every page to allow instant checkout from product pages/listings so it is possible that there is a conflict.

- Try running wordpress query monitor to find what the most long running operations are.
- Enable WP_DEBUG and check your logs.
- if you have the capability to run a copy of your website in debug, you may also be able to trace through and find the possible problem/conflict.

For general performance,  woocommerce caching can of course hammer the wp_options table, I recommend redis cache instead.  And enable opcache.

**Comment by Jon007** [comment]
@leandroprz closing as no further feedback
