### ISSUE TITLE
dont see language options in product categories, nor attributes

### ISSUE THREAD

**Issue by gasket1988** [hyyan/woo-poly-integration#386]
Hello,

My website is translated from English to French with Polylang already.

Just added the woo commerce plugin as I will be setting up an ecommerce section.

After Creating the French pages for "shop" "my account" etc, im trying to set up the "categories" and "tag" in English and French, but I don't see the options to do this? (the language flags don't show.
Though the language flags show in "attributes" and in "products" 

Need some help to solve this and/or guidance to translate to french

**Comment by Jon007** [comment]
Hi, category translations can be turned on/off for individual categories,
have a general look around the wiki:  https://github.com/hyyan/woo-poly-integration/wiki
and in particular:  https://github.com/hyyan/woo-poly-integration/wiki/Product-Categories
