### ISSUE TITLE
restore order stock quantity not working for translations

### ISSUE THREAD

**Issue by gsqrt2** [hyyan/woo-poly-integration#391]
#### Can you reproduce this issue on default Wordpress theme (eg Storefront)?
Yes.

#### Can you reproduce this issue when all other plugins are disabled except WooCommerce, Polylang and Hyyan WooCommerce Polylang Integration?
Yes.

#### What product versions and settings are you using when this issue occurs?
* PHP: 7.2.12
* WordPress: 5.0.3
* WooCommerce: 3.5.4
* Polylang: 2.5.1 Free
* Hyyan WooCommerce Polylang Integration: 1.2.0
* Browser: All (back-end issue)

#### Steps to Reproduce
1. Add a second language in Polylang.
2. Create a product translated in both languages.
3. As a user make a purchase of the product in a certain language.
4. As the admin cancel the purchase.

#### What I Expected
The stock quantity would be reduced for all translations upon purchase, and then be restored for all translations upon cancellation.

#### What Happened Instead
The stock quantity was reduced for all translations upon purchase, but was restored only for the purchased translation upon cancellation

## WordPress Environment

<details>
`
### WordPress Environment ###

Home URL: http://localhost/testpress
Site URL: http://localhost/testpress
WC Version: 3.5.4
Log Directory Writable: ✔
WP Version: 5.0.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.37 (Win32) OpenSSL/1.1.1 PHP/7.2.12
PHP Version: 7.2.12
PHP Post Max Size: 64 MB
PHP Time Limit: 600
PHP Max Input Vars: 1000
cURL Version: 7.61.1
OpenSSL/1.1.1

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.1.37-MariaDB
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.5.4
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
Total Database Size: 2.65MB
Database Data Size: 1.69MB
Database Index Size: 0.96MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB
wp_comments: Data: 0.02MB + Index: 0.09MB
wp_links: Data: 0.02MB + Index: 0.02MB
wp_options: Data: 1.03MB + Index: 0.05MB
wp_postmeta: Data: 0.11MB + Index: 0.11MB
wp_posts: Data: 0.05MB + Index: 0.06MB
wp_termmeta: Data: 0.02MB + Index: 0.03MB
wp_terms: Data: 0.02MB + Index: 0.03MB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB
wp_usermeta: Data: 0.02MB + Index: 0.03MB
wp_users: Data: 0.02MB + Index: 0.05MB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB

### Post Type Counts ###

attachment: 16
custom_css: 1
customize_changeset: 1
nav_menu_item: 5
page: 8
polylang_mo: 3
post: 2
product: 14
revision: 3
shop_order: 7

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (8) ###

Polylang: by Frédéric Demarle – 2.5.1
Child Theme Configurator: by Lilaea Media – 2.4.1
Classic Editor: by WordPress Contributors – 1.3
Jetpack by WordPress.com: by Automattic – 6.9
Hyyan WooCommerce Polylang Integration: by Hyyan Abo Fakher – 1.2.0 – Not tested with the active version of WooCommerce
WooCommerce PayPal Checkout Gateway: by WooCommerce – 1.6.6 – 1.6.8 is available
WooCommerce Services: by Automattic – 1.18.0
WooCommerce: by Automattic – 3.5.4

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #5 - /shop/
Cart: #6 - /cart/
Checkout: #7 - /checkout/
My account: #8 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront Child
Version: 2.4.2.1548149872
Author URL: https://woocommerce.com/
Child Theme: ✔
Parent Theme Name: Storefront
Parent Theme Version: 2.4.2
Parent Theme Author URL: https://woocommerce.com/
WooCommerce Support: ✔

### Templates ###

Overrides: –
`
</details>

**Comment by remidatroa** [comment]
Same issue!
