### ISSUE TITLE
Translate WCMP vendor’s shop page

### ISSUE THREAD

**Issue by Webguyssweden** [hyyan/woo-poly-integration#396]
Hi,
We are running WooCommerce and use Hyyan WooCommerce Polylang Integration to translate products, categories and so on which works perfectly.

We can’t translate WC Marketplace vendor’s store page. I have been in contact with WCMP. This is there answer:
“Our vendor shop page is like any other taxonomy page i.e. category/tag etc. So, can you please check with polylang support, and ask them why this page is not translating properly.”

Is this something that you can help with?

**Comment by Jon007** [comment]
this is a free plugin bridging woocommerce and polylang.
it does not claim to support WC Marketplace or any other plugin (it can't, its free).

If you need polylang translation support for WC Marketplace then you could write your own customisations or ask WC Marketplace or Polylang to do so.
