### ISSUE TITLE
 中文 (中国) a:3:{s:6:”locale”;s:5:”zh_CN”;s:3:”rtl”;i:0;s:9:”flag_code”;s:2:”cn”;}

### ISSUE THREAD

**Issue by tuncent** [hyyan/woo-poly-integration#398]
#### Can you reproduce this issue when all other plugins are disabled except WooCommerce, Polylang and Hyyan WooCommerce Polylang Integration?
when I stopped Hyyan WooCommerce Polylang Integration plugin the issue have disappeared 
if I re activate the issue display again
#### What product versions and settings are you using when this issue occurs?
* PHP: 7.2.15
* WordPress: 5.1
* WooCommerce: 3.5.4
* Polylang: 2.5.2
* Hyyan WooCommerce Polylang Integration: 1.2.0
* Browser: google chrome

#### Steps to Reproduce
1. polylang add language
2. polylang settings
3. activate Hyyan WooCommerce Polylang Integration

#### What I Expected

click the menu iterm then show 

首页 » 语言 » 中文 (中国)

中文 (中国)
a:3:{s:6:”locale”;s:5:”zh_CN”;s:3:”rtl”;i:0;s:9:”flag_code”;s:2:”cn”;}

## WordPress Environment

<details>
WooCommerce 版本:		3.5.4
WordPress 版本:		5.1
WordPress 多站点:		–
WordPress 内存限制:		256 MB
WordPress 调试模式:		–
WordPress cron:		
语言:		zh_CN
theme：giga store 1.1.2
</details>

**Comment by Jon007** [comment]
我听不懂， 问题舍什么？

**Comment by Jon007** [comment]
@tuncent 
What is the issue?
What did you expect to happen?
What actually happened?

I do understand Chinese (and this plugin will work with Chinese language) but I do not understand what issue you are trying to report.
