### ISSUE TITLE
Testing on current Wordpress version?

### ISSUE THREAD

**Issue by jzlcdh** [hyyan/woo-poly-integration#402]
On the current version of Wordpress (5.1 at time of writing) I get

"Warning: this plugin has not been tested with your current version of WordPress."

So if there are bugs with it on 5.1 would you like us to report them here or should we wait for a new version of the plugin?

**Comment by Jon007** [comment]
Yes they should be reported here

this plugin is unlikely to be broken by wordpress core (much more likely by woocommerce updates), so there is no particular need to do re-releases just to bump the wordpress compatibility number
