### ISSUE TITLE
ce no translate products

### ISSUE THREAD

**Issue by sirius82** [hyyan/woo-poly-integration#403]
#### What product versions and settings are you using when this issue occurs?
* PHP: 
* WordPress: 
* WooCommerce: 
* Polylang: [state if using Polylang PRO]
* Hyyan WooCommerce Polylang Integration: 
* Browser: 

#### Steps to Reproduce
1. 
1. 
1. 

## WordPress Environment

<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.
```
</details>

**Comment by Jon007** [comment]
Please follow the getting started guide at: 
https://github.com/hyyan/woo-poly-integration/wiki/Getting-Started
and if you still have a problem, report with more details.
