### ISSUE TITLE
After activate Hyyan Shop page is broken

### ISSUE THREAD

**Issue by viatc** [hyyan/woo-poly-integration#405]
Good day!

I use siteorigin witch theme influence.
I have installed Woocommerce Polylang and Hyyan WooCommerce Polylang Integration.
After i activate Hyyan WooCommerce Polylang Integration my layout of my shop page was broken.
After activation hyyan, products of this page change their look and we see [products on this page like a list of posts.](https://viamybox.com/wp-content/uploads/2019/03/err.png)
For your convenience I attach the picture.
After I deactivate Hyyan WooCommerce Polylang Integration, [things are getting back to normal](https://viamybox.com/shop).
It Looks like the problem’s with the theme, because if i get standard wordpress theme, the shop page is good.
What could be the reason why the layout was destroyed?

Sorry from my english.
Thanks you in advance.

#### Can you reproduce this issue on default Wordpress theme (eg Storefront)?
yes shop page working in standart theme working good.

#### What product versions and settings are you using when this issue occurs?
PHP 7.0.30-0+deb9u1
Siteorigin PageBuilder 2.10.2
Siteorigin theme influence.
Hyyan 1.2.0
Polylang 2.5.2
WooCommerce 3.5.6

#### Steps to Reproduce
-activate Hyan
-shop site after that, looks like list of post

**Comment by Jon007** [comment]
as you say, this will be a problem with the theme.
I suggest starting with Storefront and creating a child theme of that for your own customisations.
This is a free plugin and cannot offer support for incompatibilities introduced by third party themes.
