### ISSUE TITLE
Getting WooCommerce product title translation

### ISSUE THREAD

**Issue by Daaaaad** [hyyan/woo-poly-integration#409]
* PHP: 7.0.28
* WordPress: 4.8.2
* WooCommerce: 3.1.2
* Polylang: 2.2.3 (no pro)
* Hyyan WooCommerce Polylang Integration: 1.2.0
* Browser: N/A

Hello, I have a problem with product title translations. When using the WooCommerce shortcode [product id="1005"] the product title is not automatically translated. I would like to obtain the product title in the current visitor language and I get the title of the product having the id 1005 :(

Product 1005 is translated in 3 languages:

- 1005 is Bain carbogazeux (FR)
- 1996 is KOOLZUURBAD (NL)
- 2711 is Carbonated bath (EN)

All 3 translations are correctly linked with Polylang in the Wordpress admin:

<img width="929" alt="Capture d'écran 2019-04-08 16 12 57" src="https://user-images.githubusercontent.com/167037/55730745-32888200-5a19-11e9-88cc-445b77db33da.png">

Can you help?

**Comment by Daaaaad** [comment]
Someone? 😞

**Comment by Daaaaad** [comment]
If I disable your module the title is translated in the right language 🤔

**Comment by Daaaaad** [comment]
I just tested with the last version of Polylang and last version of your plugin and that's not working neither 😔

**Comment by Jon007** [comment]
in the release version of the plugin:
- if you are adding the product to a french post, use [product id="1005"] 
- if you are adding the product to an english post, use [product id="2711"] 
or use [products ids="1005"] and I think it will already translate ok.

I did happen to see a fix though, so I am checking in a fix which fixes the behaviour for shortcodes:
[product id= 
as well as:
[product_categories ids="3234,3314"]
[product_categories parent="1"]

WooCommerce has a lot of shortcodes and options so by no means all of them are guaranteed to automatically translate.
