### ISSUE TITLE
Woocommerce hide out of stock products settings + restock = BUG

### ISSUE THREAD

**Issue by fkoomek** [hyyan/woo-poly-integration#411]
#### Can you reproduce this issue on default Wordpress theme (eg Storefront)?
YES
#### Can you reproduce this issue when all other plugins are disabled except WooCommerce, Polylang and Hyyan WooCommerce Polylang Integration?
YES

#### What product versions and settings are you using when this issue occurs?
* PHP: 7.3.1
* WordPress: 5.1.1
* WooCommerce: 3.6.1 
* Polylang: 2.5.3
* Hyyan WooCommerce Polylang Integration: 1.3.0
* Browser: Chrome,Firefox

#### Steps to Reproduce
1. Set Polylang with at least 2 languages
2. Enable hide out of stock products in Woocommerce settings -> Products -> Inventory
3. Make product and set stock quantity 1 
4. Translate the product
5. Buy the product in any language version
6. Go to Woocommerce - products and set stock quantity from 0 to 1 again.
7. See the product from front-end in every language version

#### What I Expected
Products are visible in both language versions.

#### What Happened Instead
Product is visible again only in the default language. It's not possible to show the product in another language version again.

## WordPress Environment

<details>

WordPress environment
--
WordPress address (URL): |   | https://test.liberlapidum.com
Site address (URL): |   | https://test.liberlapidum.com
WooCommerce version: |   | 3.6.1
Log directory writable: |   | /data/web/virtuals/200558/virtual/www/domains/liberlapidum.com/wp-content/uploads/wc-logs/
WordPress version: |   | 5.1.1
WordPress multisite: |   | –
WordPress memory limit: |   | 256 MB
WordPress debug mode: |   |  
WordPress cron: |   |  
Language: |   | en_US
External object cache: |   | –

</details>

**Comment by fkoomek** [comment]
I found out that when I change the visibility of the product and save, it appears again.
And it doesn't matter if the product is bought from the frontend. 
This bug happens every time I set some product quantity to 0 and then to 1 again.

**Comment by Jon007** [comment]
a volunteer maintainer is needed to look at the whole stock issue along with #391 and #299 

There were already issues but with WooCommerce 3.6 it will be worse, as per #408 : 3.6 adds stock status and quantity to new Product Data Lookup Tables which, as they are new, are not synchronised by this plugin at all.  (this plugin leverages Polylang synchronisation of post meta, whereas it is now necessary to use the woocommerce api to correctly update the new product data lookup tables and other woocommerce caching mechanisms.)

**Comment by fkoomek** [comment]
Hello.
Thank you very much for the information.
How many volunteer maintainers besides you are currently working on Woo
Poly integration?
Best Regards,

Radan

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Bez
virů. www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

po 6. 5. 2019 v 23:09 odesílatel Jonathan Moore <notifications@github.com>
napsal:

**Comment by Jon007** [comment]
@fkoomek this should be fixed by new version of the Stock.php file checked in here https://github.com/hyyan/woo-poly-integration/commit/17e29b9927eb2fea3afbc3947d48e2b68e3d2185
