### ISSUE TITLE
Attribute values not translated , instead shown their slugs! even worse, cyrillic letters in slug shown as "%x%x%x"

### ISSUE THREAD

**Issue by cenk100** [hyyan/woo-poly-integration#412]
#### Can you reproduce this issue on default Wordpress theme (eg Storefront)?
I am using PORTO WP, and I am not sure what u mean default?
#### Can you reproduce this issue when all other plugins are disabled except WooCommerce, Polylang and Hyyan WooCommerce Polylang Integration?
Yes
#### What product versions and settings are you using when this issue occurs?
* PHP: 7.0
* WordPress: 5.1.1
* WooCommerce: 3.5.7 
* Polylang: [state if using Polylang PRO] Free version
* Hyyan WooCommerce Polylang Integration:  YES I use.
* Browser: Chrome

#### Steps to Reproduce
1. Create 2 custom attribs: 
  a- STYLE: "wooden, white, black"(EN) and set (RU) and (TR) translations.
  b-SIZE: "extra, regular"(EN) and set (RU) and (TR) translations

2. When in (RU) version ShopPage, I add a Product with such attribs: 
   STYLE(RU)=wooden(RU), SIZE(RU)=extra(RU) 
by choosing variable product attribs.
  
3. Then I switch the language switcher from (RU) to (EN) on same page

#### What I  GOT:

What I expect is to see fully (EN) translation of the item added to cart..Everythin is translated , even attrib names SIZE and STYLE.....But the terms of attribs are not translated and even worse not their content but their slug names are seen..And if slug name chosen was in cyrillic(RU) then I see extended char representation such:
" STYLE : %b0%80%b%81%...,  SIZE: %d0%50%54%d0...."  
and if I chose latin letters for slug for (RU) versions, then in (EN) and in (TR) both time I see like : 
"STYLE: wooden-ru, SIZE: extra-ru " 
  .......

#### What I EXPECTED:

......while I expect to see 
"SIZE: wooden ; STYLE: extra", that are not slugs but real attrib values entered.

## WordPress Environment

<details>

`
### WordPress Environment ###

Home URL: https://market.mikkins.com
Site URL: https://market.mikkins.com
WC Version: 3.5.7
Log Directory Writable: ✔
WP Version: 5.1.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.2.17
PHP Post Max Size: 64 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.64.0
OpenSSL/1.0.2r

SUHOSIN Installed: –
MySQL Version: 5.6.41-84.1
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.5.7
WC Database Prefix: dcd_
MaxMind GeoIP Database: ✔
Total Database Size: 29.59MB
Database Data Size: 18.46MB
Database Index Size: 11.13MB
dcd_woocommerce_sessions: Data: 0.01MB + Index: 0.00MB
dcd_woocommerce_api_keys: Data: 0.00MB + Index: 0.00MB
dcd_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.00MB
dcd_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB
dcd_woocommerce_order_items: Data: 0.00MB + Index: 0.00MB
dcd_woocommerce_order_itemmeta: Data: 0.00MB + Index: 0.00MB
dcd_woocommerce_tax_rates: Data: 0.00MB + Index: 0.00MB
dcd_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB
dcd_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB
dcd_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.00MB
dcd_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB
dcd_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB
dcd_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB
dcd_woocommerce_log: Data: 0.00MB + Index: 0.00MB
dcd_adsw_ali_meta: Data: 0.00MB + Index: 0.00MB
dcd_categorymeta: Data: 0.00MB + Index: 0.00MB
dcd_commentmeta: Data: 0.00MB + Index: 0.00MB
dcd_comments: Data: 0.03MB + Index: 0.02MB
dcd_failed_jobs: Data: 0.00MB + Index: 0.00MB
dcd_links: Data: 0.00MB + Index: 0.00MB
dcd_mailchimp_carts: Data: 0.00MB + Index: 0.00MB
dcd_member_catmeta: Data: 0.00MB + Index: 0.00MB
dcd_newsletter: Data: 0.00MB + Index: 0.01MB
dcd_newsletter_emails: Data: 0.02MB + Index: 0.00MB
dcd_newsletter_sent: Data: 0.00MB + Index: 0.00MB
dcd_newsletter_stats: Data: 0.00MB + Index: 0.00MB
dcd_newsletter_user_logs: Data: 0.00MB + Index: 0.00MB
dcd_options: Data: 2.35MB + Index: 0.11MB
dcd_portfolio_catmeta: Data: 0.00MB + Index: 0.00MB
dcd_postmeta: Data: 12.50MB + Index: 9.89MB
dcd_posts: Data: 3.20MB + Index: 0.56MB
dcd_product_catmeta: Data: 0.00MB + Index: 0.00MB
dcd_queue: Data: 0.00MB + Index: 0.00MB
dcd_revslider_css: Data: 0.09MB + Index: 0.00MB
dcd_revslider_layer_animations: Data: 0.00MB + Index: 0.00MB
dcd_revslider_navigations: Data: 0.00MB + Index: 0.00MB
dcd_revslider_sliders: Data: 0.00MB + Index: 0.00MB
dcd_revslider_slides: Data: 0.00MB + Index: 0.00MB
dcd_revslider_static_slides: Data: 0.00MB + Index: 0.00MB
dcd_termmeta: Data: 0.02MB + Index: 0.02MB
dcd_terms: Data: 0.02MB + Index: 0.04MB
dcd_term_relationships: Data: 0.19MB + Index: 0.42MB
dcd_term_taxonomy: Data: 0.02MB + Index: 0.03MB
dcd_usermeta: Data: 0.01MB + Index: 0.01MB
dcd_users: Data: 0.00MB + Index: 0.01MB
dcd_wc_download_log: Data: 0.00MB + Index: 0.00MB
dcd_wc_product_meta_lookup: Data: 0.00MB + Index: 0.00MB
dcd_wc_webhooks: Data: 0.00MB + Index: 0.00MB
dcd_wpf_filters: Data: 0.00MB + Index: 0.00MB
dcd_yith_wcwl: Data: 0.00MB + Index: 0.00MB
dcd_yith_wcwl_lists: Data: 0.00MB + Index: 0.01MB

### Post Type Counts ###

attachment: 143
block: 25
custom_css: 1
customize_changeset: 2
jetpack_migration: 1
jp_img_sitemap: 1
jp_sitemap: 1
jp_sitemap_master: 1
jp_vid_sitemap: 1
member: 8
nav_menu_item: 126
oceanwp_library: 1
option-tree: 1
page: 78
polylang_mo: 3
post: 8
product: 60
product_variation: 6977
revision: 91
scheduled-action: 2
shop_order: 150
um_directory: 1
um_form: 3
wpcf7_contact_form: 10
wpforms: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (21) ###

Polylang: by Frédéric Demarle – 2.5.3
Contact Form 7: by Takayuki Miyoshi – 5.1.1
Dropship Me: by Vitaly Kukin – 1.0.1
Duplicate Post: by Enrico Battocchi – 3.2.2
Dynamic Featured Image: by Ankit Pokhrel – 3.7.0
Google Analytics for WordPress by MonsterInsights: by MonsterInsights – 7.5.1
Jetpack by WordPress.com: by Automattic – 7.2.1
WPBakery Page Builder: by Michael M - WPBakery.com – 5.7
Newsletter: by Stefano Lissa & The Newsletter Team – 5.9.3
Porto Theme - Functionality: by P-Themes – 1.3.6
Really Simple SSL: by Rogier Lankhorst
Mark Wolters – 3.1.5

Slider Revolution: by ThemePunch – 5.4.8
SSL Insecure Content Fixer: by WebAware – 2.7.2
WooCommerce Blocks: by Automattic – 1.4.0
Hyyan WooCommerce Polylang Integration: by Hyyan Abo Fakher – 1.3.0
WOOCS - WooCommerce Currency Switcher: by realmag777 – 1.2.8
WooCommerce PayPal Checkout Gateway: by WooCommerce – 1.6.11
WooCommerce: by Automattic – 3.5.7 – 3.6.1 is available
WPForms Lite: by WPForms – 1.5.2.2
YITH WooCommerce Wishlist: by YITH – 2.2.9

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #3597 - /en/shop/
Cart: #208 - /en/cart/
Checkout: #209 - /checkout/
My account: #210 - /en/my-account/
Terms and conditions: #3918 - /en/terms-of-service/

### Theme ###

Name: Porto Child
Version: 1.1
Author URL: https://www.portotheme.com/
Child Theme: ✔
Parent Theme Name: Porto
Parent Theme Version: 4.11.1
Parent Theme Author URL: http://www.portotheme.com/
WooCommerce Support: ✔

### Templates ###

Overrides: porto/woocommerce/archive-product.php
porto/woocommerce/cart/cart-shipping.php
porto/woocommerce/cart/cart-totals.php
porto/woocommerce/cart/cart.php
porto/woocommerce/cart/cross-sells.php
porto/woocommerce/cart/mini-cart.php
porto/woocommerce/cart/proceed-to-checkout-button.php
porto/woocommerce/cart/shipping-calculator.php
porto/woocommerce/checkout/form-billing.php
porto/woocommerce/checkout/form-checkout.php
porto/woocommerce/checkout/form-coupon.php
porto/woocommerce/checkout/form-login.php
porto/woocommerce/checkout/form-pay.php
porto/woocommerce/checkout/payment.php
porto/woocommerce/checkout/review-order.php
porto-child/woocommerce/content-product.php
porto/woocommerce/content-product_cat.php
porto/woocommerce/content-single-product.php
porto/woocommerce/content-widget-product.php
porto/woocommerce/global/form-login.php
porto/woocommerce/global/quantity-input.php
porto/woocommerce/global/wrapper-start.php
porto/woocommerce/loop/add-to-cart.php
porto/woocommerce/loop/loop-end.php
porto/woocommerce/loop/loop-start.php
porto/woocommerce/loop/no-products-found.php
porto/woocommerce/loop/orderby.php
porto/woocommerce/loop/pagination.php
porto/woocommerce/loop/rating.php
porto/woocommerce/loop/sale-flash.php
porto/woocommerce/myaccount/downloads.php
porto/woocommerce/myaccount/form-add-payment-method.php
porto/woocommerce/myaccount/form-edit-account.php
porto/woocommerce/myaccount/form-edit-address.php
porto/woocommerce/myaccount/form-login.php
porto/woocommerce/myaccount/form-lost-password.php
porto/woocommerce/myaccount/form-reset-password.php
porto/woocommerce/myaccount/lost-password-confirmation.php
porto/woocommerce/myaccount/my-account.php
porto/woocommerce/myaccount/my-address.php
porto/woocommerce/myaccount/my-downloads.php
porto/woocommerce/myaccount/my-orders.php
porto/woocommerce/myaccount/orders.php
porto/woocommerce/myaccount/payment-methods.php
porto/woocommerce/myaccount/view-order.php
porto/woocommerce/order/form-tracking.php
porto/woocommerce/order/tracking.php
porto/woocommerce/single-product/add-to-cart/simple.php
porto/woocommerce/single-product/add-to-cart/variable.php
porto/woocommerce/single-product/meta.php
porto/woocommerce/single-product/product-attributes.php
porto-child/woocommerce/single-product/product-image.php
porto-child/woocommerce/single-product/product-thumbnails.php
porto/woocommerce/single-product/rating.php
porto/woocommerce/single-product/related.php
porto/woocommerce/single-product/review-meta.php
porto/woocommerce/single-product/review-rating.php
porto/woocommerce/single-product/review.php
porto/woocommerce/single-product/sale-flash.php
porto/woocommerce/single-product/short-description.php
porto/woocommerce/single-product/tabs/tabs.php
porto/woocommerce/single-product/title.php
porto/woocommerce/single-product/up-sells.php
porto/woocommerce/single-product-reviews.php

`

</details>

**Comment by cenk100** [comment]
NOW I realised...I have the exact same problem like "Issue #262"...but still couldn't solve!!:((

**Comment by Jon007** [comment]
Your comments refer to the appearance within the Shopping Cart itself, when the product attributes are defining the variation and the cart is trying to show the product variation?
The cart normally shows the title of the variation product which is created by woocommerce using the variation details and would not normally use the slug.

Please do test a standard theme such as Storefront or Twenty Sixteen in case your custom theme PORTO WP has code which is affecting the display.

And also please confirm whether your problem is with the product page itself or the cart.

**Comment by Jon007** [comment]
@cenk100 I cannot tell what your issue is unless you answer the previous questions

**Comment by Jon007** [comment]
closing due to no reply
