### ISSUE TITLE
WooCommerce freezes when updating variable product

### ISSUE THREAD

**Issue by designs-hidra** [hyyan/woo-poly-integration#422]
Hi there,

First of all thank you for your work, awesome plugin!

Well, I was one of those early adopters of WooCommerce 3.6 hence am experiencing a problem when updating variable products, if the product has any other language that is not the default language assigned when you click on update it takes +1min to update sometimes 2mins.

Although the product is updated in a matter of seconds the page keeps updating forever... See this video:  https://streamable.com/3x3pv

I have upped the server php config and maxxed everything out including memory limit, max_vars... hoping that could do the trick but did not help.

So here I am asking for the much needed help as my client is going nuts at me heheh.

#### Can you reproduce this issue on default Wordpress theme (eg Storefront)?
Yes.

#### Can you reproduce this issue when all other plugins are disabled except WooCommerce, Polylang and Hyyan WooCommerce Polylang Integration?
Yes.

#### What product versions and settings are you using when this issue occurs?
* PHP: 7.3
* WordPress: 5.2.1
* WooCommerce: 3.6.3
* Polylang: [state if using Polylang PRO] v2.5.3(Free)
* Hyyan WooCommerce Polylang Integration: 1.3.0
* Browser: Chrome, Firefox, Safary... All up to date Versions

#### Steps to Reproduce
1. Open any VARIABLE PRODUCT
1. Link a translation to it
1. Click Update... And make a coffee

#### What I Expected
To take average 5-6scs

#### What Happened Instead
Takes 1-2 mins

## WordPress Environment

<details>
```


WordPress environment
--
WordPress address (URL): |   | http://www.vossflamenco.es/v3
Site address (URL): |   | http://www.vossflamenco.es/v3
WooCommerce version: |   | 3.6.3
Log directory writable: |   | /var/www/vhosts/vossflamenco.es/httpdocs/v3/wp-content/uploads/wc-logs/
WordPress version: |   | 5.2.1
WordPress multisite: |   |  
WordPress memory limit: |   | 256 MB
WordPress debug mode: |   | –
WordPress cron: |   |  
Language: |   | es_ES
External object cache: |   | –


Server environment
--
Server info: |   | Apache
PHP version: |   | 7.3.5
PHP post max size: |   | 32 MB
PHP time limit: |   | 300
PHP max input vars: |   | 5000
cURL version: |   | 7.35.0, OpenSSL/1.0.1f
SUHOSIN installed: |   | –
MySQL version: |   | 5.5.63-MariaDB-1ubuntu0.14.04.1
Max upload size: |   | 3 MB
Default timezone is UTC: |   |  ok
fsockopen/cURL: |   |  ok
SoapClient: |   |  ok
DOMDocument: |   |ok  
GZip: |   |  ok
Multibyte string: |   |  ok
Remote post: |   |  ok
Remote get: |   |  ok


Active plugins (39)
--
Polylang |   | by Frédéric Demarle – 2.5.3
Airi Package Demo Data |   | by LA Studio – 1.0.0
Akismet Anti-Spam |   | by Automattic – 4.1.2
Contact Form 7 |   | by Takayuki Miyoshi – 5.1.3
Duplicate Page |   | by mndpsingh287 – 3.5
Envato Market |   | by Envato – 2.0.1
Hello Dolly |   | by Matt Mullenweg – 1.7.1
Jetpack by WordPress.com |   | by Automattic – 7.3.1
WPBakery Page Builder |   | by Michael M - WPBakery.com – 5.6
LA-Studio Core |   | by LA-Studio – 1.0.5
Mailchimp for WooCommerce |   | by Mailchimp – 2.1.15 – Not tested with the active version of WooCommerce
Product Input Fields for WooCommerce |   | by Tyche Softwares – 1.2.4 – Not tested with the active version of WooCommerce
Slider Revolution |   | by ThemePunch – 5.4.8
WooCommerce Variation Swatches |   | by ThemeAlien – 1.0.4 – Not tested with the active version of WooCommerce
WooCommerce Services |   | by Automattic – 1.20.0
WooCommerce |   | by Automattic – 3.6.3
WordPress Importer |   | by wordpressdotorg – 0.6.4
Easy Forms for Mailchimp |   | by YIKES, Inc. – 6.5.2
Airi Package Demo Data |   | by LA Studio – 1.0.0
Akismet Anti-Spam |   | by Automattic – 4.1.2
Contact Form 7 |   | by Takayuki Miyoshi – 5.1.3
Envato Market |   | by Envato – 2.0.1
Jetpack by WordPress.com |   | by Automattic – 7.3.1
LA-Studio Core |   | by LA-Studio – 1.0.5
Product Input Fields for WooCommerce |   | by Tyche Softwares – 1.2.4 – Not tested with the active version of WooCommerce
Slider Revolution |   | by ThemePunch – 5.4.8
WooCommerce |   | by Automattic – 3.6.3
WooCommerce Services |   | by Automattic – 1.20.0
WooCommerce Variation Swatches |   | by ThemeAlien – 1.0.4 – Not tested with the active version of WooCommerce
WPBakery Page Builder |   | by Michael M - WPBakery.com – 5.6
Hyyan WooCommerce Polylang Integration |   | by Hyyan Abo Fakher – 1.3.0 – Not tested with the active version of WooCommerce
WP Mail SMTP |   | by WPForms – 1.4.2
Magic Liquidizer Responsive Table |   | by Elvin D. – 2.0.3
UpdraftPlus - Backup/Restore |   | by UpdraftPlus.Com, DavidAnderson – 1.16.14
Popup Maker |   | by WP Popup Maker – 1.8.6
Duplicate Page |   | by mndpsingh287 – 3.5
Conditionally display featured image on singular pages and posts |   | by Cyrill Bolliger – 1.4.0
Loco Translate |   | by Tim Whitlock – 2.2.2
GA Google Analytics |   | by Jeff Starr – 20190501




```
</details>

**Comment by Jon007** [comment]
Hi, thanks for well reported issue.
Variations can be a bit slow sometimes - 5-6secs is believable - but I'm not seeing anything like this testing with a few variations and 3 languages on the release version of this plugin and woo3.6... 

- How many variations are there in an example where this happens?
- How many languages?
- Are there any php debug messages logged?
- There are quite a few other plugins enabled - do you have an environment where you can try turning off other plugins (apart from Polylang and woocommerce)?  in case there could be a conflict with another plugin?

**Comment by Jon007** [comment]
believe this fix to stock.php will solve your compatibility issue, please try it!
