### ISSUE TITLE
Currency switch - 1.4.0 - bug 

### ISSUE THREAD

**Issue by fkoomek** [hyyan/woo-poly-integration#427]
#### Can you reproduce this issue on default Wordpress theme (eg Storefront)?
Yes

#### Can you reproduce this issue when all other plugins are disabled except WooCommerce, Polylang, and Hyyan WooCommerce Polylang Integration?
Yes

#### What product versions and settings are you using when this issue occurs?
* PHP: 7.3.6
* WordPress: 5.2.1
* WooCommerce: 3.6.4
* Polylang: Free
* Hyyan WooCommerce Polylang Integration: 1.4.0
* Browser: any

#### Steps to Reproduce
1. Set up Polylang with at least 2 languages.
2. Create a product in both languages. 
3. Install any Woocommerce currency switcher (I used Currency Switcher by Realmag and switcher by algoritmika)
4. Set 2 currencies.
5. Go to the shop and switch to the additional currency (not the default one).
6. Add the product to the cart.
7. Go to the Cart page.
8. Switch to the second language.

#### What I Expected

The product prices are correct.

#### What Happened Instead
The prices of products in the cart are not correct.
Although, the subtotal in the Shipping calculator is correct. 

This is a bug introduced in pre-release 1.4.0. I tested it now for a few hours.
![image](https://user-images.githubusercontent.com/41650225/59151866-aa375500-8a3a-11e9-9152-74ffd6c84bf6.png)

Also, possible to test here (EURO is the additional currency):
https://www.test2.liberlapidum.com/test2/

**Comment by Jon007** [comment]
Hmm yes there is a thing added for compatibility with other plugins which manipulate the price - fixes #390, #346 Cart: retain price when switching languages - you can remove the code added in this commit:
https://github.com/hyyan/woo-poly-integration/commit/ec272c0d921e39ebfd497fb2303454d7793bf60d

Or change the priority of the filters....
I will take a look...

**Comment by Jon007** [comment]
for anyone else following this, Algoritmika seem to be rebranding as WP Wham, plugin referred to should be:
https://en-gb.wordpress.org/plugins/currency-switcher-woocommerce/
https://github.com/algoritmika/currency-switcher-woocommerce

and the realmag one:
https://wordpress.org/plugins/woocommerce-currency-switcher/

**Comment by Jon007** [comment]
ok so realmag with the modification, the code is copying the converted price across when changing languages, then the currency switcher is converting it again because it does not know the cart price is already converted.

**Comment by fkoomek** [comment]
Great! Thanks for the fix :)
