### ISSUE TITLE
Cancel order does not sync product stock for all languages

### ISSUE THREAD

**Issue by daining1298** [hyyan/woo-poly-integration#428]
Can you reproduce this issue on default Wordpress theme (eg Storefront)?
- Yes

Can you reproduce this issue when all other plugins are disabled except WooCommerce, Polylang and Hyyan WooCommerce Polylang Integration?
- Yes

What product versions and settings are you using when this issue occurs?
* PHP: 7.2.18
* WordPress: 5.1.1
* WooCommerce: 3.6.4
* Polylang: Free Polylang
* Hyyan WooCommerce Polylang Integration: 
* Browser: 

#### Steps to Reproduce
1. Create a product has translation for multiple languages.
2. Make an order for the product.
3. Go to backend dashboard, cancel the order. Only product in one language, that makes the order, increases stock back.

#### What I Expected
Product stock amount should be synced for all languages.

#### What Happened Instead
stock level is not synced.

**Comment by Jon007** [comment]
please try Hyyan WooCommerce Polylang Integration 1.4 preview see
https://github.com/hyyan/woo-poly-integration/releases
This version replaces the previous stock module

**Comment by Jon007** [comment]
@daining1298 this should be fixed since early versions on 1.4 release, please try 1.4.3
https://github.com/hyyan/woo-poly-integration/releases
