### ISSUE TITLE
Pages are duplicated when editing them.

### ISSUE THREAD

**Issue by dmytro-kindrat** [hyyan/woo-poly-integration#434]
**Can you reproduce this issue on default Wordpress theme (eg Storefront)?**
Yes

**Can you reproduce this issue when all other plugins are disabled except WooCommerce, Polylang and Hyyan WooCommerce Polylang Integration?**
Yes

**What product versions and settings are you using when this issue occurs?**
* PHP: 7.3.0
* WordPress: 5.2.2
* WooCommerce: 3.6.4
* Polylang
* Hyyan WooCommerce Polylang Integration: 1.4.2
* Browser: Firefox 67.0.4

**Steps to Reproduce**
1. Updated the plugin version to 1.4.2
2. Go to the Pages
3. Edit page Homepage RU
4. Save page Homepage RU
5. Edit Homepage EN
6. Save page Homepage EN
7. Go to pages and saw a lot of duplicate pages.
![Screenshot_2019-06-26 Страницы ‹ Mesh Intimates — WordPress](https://user-images.githubusercontent.com/51969083/60212328-a80e2c80-9869-11e9-8147-0b9eafe37eaf.png)

**WordPress Environment**

<details>
`
### WordPress Environment ###

WordPress address (URL): https://mesh-intimates.com
Site address (URL): https://mesh-intimates.com
WC Version: 3.6.4
Log Directory Writable: ✔
WP Version: 5.2.2
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: ru_RU
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.3.0
PHP Post Max Size: 256 MB
PHP Time Limit: 60
PHP Max Input Vars: 16384
cURL Version: 7.22.0
OpenSSL/1.0.1

SUHOSIN Installed: –
MySQL Version: 5.6.34
Max Upload Size: 196 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.6.4
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
Общий размер базы данных: 17.28MB
Размер данных в базе данных: 11.61MB
Размер индекса базы данных: 5.67MB
wp_woocommerce_sessions: Данные: 0.02 Мб + Индекс: 0.02 Мб
wp_woocommerce_api_keys: Данные: 0.02 Мб + Индекс: 0.03 Мб
wp_woocommerce_attribute_taxonomies: Данные: 0.02 Мб + Индекс: 0.02 Мб
wp_woocommerce_downloadable_product_permissions: Данные: 0.02 Мб + Индекс: 0.06 Мб
wp_woocommerce_order_items: Данные: 0.02 Мб + Индекс: 0.02 Мб
wp_woocommerce_order_itemmeta: Данные: 0.02 Мб + Индекс: 0.03 Мб
wp_woocommerce_tax_rates: Данные: 0.02 Мб + Индекс: 0.06 Мб
wp_woocommerce_tax_rate_locations: Данные: 0.02 Мб + Индекс: 0.03 Мб
wp_woocommerce_shipping_zones: Данные: 0.02 Мб + Индекс: 0.00 Мб
wp_woocommerce_shipping_zone_locations: Данные: 0.02 Мб + Индекс: 0.03 Мб
wp_woocommerce_shipping_zone_methods: Данные: 0.02 Мб + Индекс: 0.00 Мб
wp_woocommerce_payment_tokens: Данные: 0.02 Мб + Индекс: 0.02 Мб
wp_woocommerce_payment_tokenmeta: Данные: 0.02 Мб + Индекс: 0.03 Мб
wp_woocommerce_log: Данные: 0.02 Мб + Индекс: 0.02 Мб
wp_commentmeta: Данные: 0.02 Мб + Индекс: 0.03 Мб
wp_comments: Данные: 0.02 Мб + Индекс: 0.09 Мб
wp_failed_jobs: Данные: 0.02 Мб + Индекс: 0.00 Мб
wp_links: Данные: 0.02 Мб + Индекс: 0.02 Мб
wp_mailchimp_carts: Данные: 0.02 Мб + Индекс: 0.00 Мб
wp_nova_poshta_city: Данные: 0.33 Мб + Индекс: 0.66 Мб
wp_nova_poshta_locations: Данные: 0.20 Мб + Индекс: 0.00 Мб
wp_nova_poshta_region: Данные: 0.02 Мб + Индекс: 0.03 Мб
wp_nova_poshta_update_locations: Данные: 0.02 Мб + Индекс: 0.00 Мб
wp_nova_poshta_warehouse: Данные: 2.34 Мб + Индекс: 2.95 Мб
wp_options: Данные: 2.45 Мб + Индекс: 0.09 Мб
wp_postmeta: Данные: 2.52 Мб + Индекс: 0.72 Мб
wp_posts: Данные: 2.52 Мб + Индекс: 0.27 Мб
wp_queue: Данные: 0.02 Мб + Индекс: 0.00 Мб
wp_revslider_css: Данные: 0.13 Мб + Индекс: 0.00 Мб
wp_revslider_layer_animations: Данные: 0.02 Мб + Индекс: 0.00 Мб
wp_revslider_navigations: Данные: 0.02 Мб + Индекс: 0.00 Мб
wp_revslider_sliders: Данные: 0.02 Мб + Индекс: 0.00 Мб
wp_revslider_slides: Данные: 0.19 Мб + Индекс: 0.00 Мб
wp_revslider_static_slides: Данные: 0.02 Мб + Индекс: 0.00 Мб
wp_termmeta: Данные: 0.02 Мб + Индекс: 0.03 Мб
wp_terms: Данные: 0.05 Мб + Индекс: 0.03 Мб
wp_term_relationships: Данные: 0.16 Мб + Индекс: 0.13 Мб
wp_term_taxonomy: Данные: 0.05 Мб + Индекс: 0.03 Мб
wp_usermeta: Данные: 0.02 Мб + Индекс: 0.03 Мб
wp_users: Данные: 0.02 Мб + Индекс: 0.05 Мб
wp_wc_download_log: Данные: 0.02 Мб + Индекс: 0.03 Мб
wp_wc_product_meta_lookup: Данные: 0.05 Мб + Индекс: 0.09 Мб
wp_wc_webhooks: Данные: 0.02 Мб + Индекс: 0.02 Мб

### Post Type Counts ###

attachment: 381
chart: 5
mc4wp-form: 1
nav_menu_item: 50
page: 42
polylang_mo: 2
post: 1
product: 128
product_variation: 151
revision: 406
scheduled-action: 6
shop_order: 2
size-chart: 3
wpcf7_contact_form: 2
yith-wcpsc-wc-chart: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (21) ###

Polylang: от WP SYNTEX – 2.6
Autoptimize: от Frank Goossens (futtta) – 2.5.1
Contact Form 7: от Takayuki Miyoshi – 5.1.3
WPBakery Page Builder: от Michael M - WPBakery.com – 6.0.2
Savoy Theme - Instagram Gallery: от NordicMade – 1.0
Savoy Theme - Wishlist: от NordicMade – 2.0.4
Polylang Slug: от Ulrich Pogson – 0.2.2
NC Size Chart for Woocommerce: от Nabaraj Chapagain – 1.0.6 – Не тестировалось с активной версией WooCommerce
Slider Revolution: от ThemePunch – 5.4.8.3
Shortcode in Menus: от Gagan Deep Singh – 3.5
WC Hide Shipping Methods: от Rynaldo Stoltz – 1.3
WooCommerce Bank Card Gateway: от DK – 1.1.0 – Не тестировалось с активной версией WooCommerce
WooCommerce MoneyGram Gateway: от DK – 1.1.0 – Не тестировалось с активной версией WooCommerce
Hyyan WooCommerce Polylang Integration: от Hyyan Abo Fakher – 1.4.2
Woo Shipping for Nova Poshta: от Sergey Nezbritskiy – 2.1.5 – Не тестировалось с активной версией WooCommerce
WooCommerce Western Union Gateway: от DK – 1.1.0 – Не тестировалось с активной версией WooCommerce
Woo Category Base Permalink Fixer: от MasterNs – 2.3 – Не тестировалось с активной версией WooCommerce
WOOCS - WooCommerce Currency Switcher: от realmag777 – 2.2.8
Woocommerce Mailchimp Discount: от Magnigenie – 3.3 – Не тестировалось с активной версией WooCommerce
WooCommerce Table Rate Shipping: от Bolder Elements – 4.1.3 – Не тестировалось с активной версией WooCommerce
WooCommerce: от Automattic – 3.6.4

### Inactive Plugins (6) ###

Akismet Anti-Spam: от Automattic – 4.1.2
Lingotek Translation: от Lingotek and Frédéric Demarle – 1.4.2
Savoy Theme - Custom Code: от NordicMade – 1.0
WooCommerce Liqpay Gateway: от Denis Pavlenko – 2.01 – Не тестировалось с активной версией WooCommerce
WooCommerce Privat24 Gateway: от Denis Pavlenko – 1.01 – Не тестировалось с активной версией WooCommerce
WooCommerce Simple LiqPay: от Alex Shandor – 1.7 – Не тестировалось с активной версией WooCommerce

### Settings ###

API Enabled: –
Force SSL: –
Currency: UAH (грн)
Currency Position: right_space
Thousand Separator: 
Decimal Separator: .
Number of Decimals: 0
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Ссылка магазина: #5 - /shop/
Корзина: #6 - /cart/
Оформление заказа: #7 - /checkout/
Мой аккаунт: #8 - /my-account/
Правила и условия: ❌ Страница не задана

### Theme ###

Name: Savoy
Version: 2.1.7
Author URL: http://www.nordicmade.com
Child Theme: ❌ – Если вы хотите оформить WooCommerce родительской темой
которую создал кто-то другой
мы рекомендуем воспользоваться дочерней темой. См. "Как создать дочернюю тему"

WooCommerce Support: ✔

### Templates ###

Overrides: dk/woocommerce/archive-product.php
dk/woocommerce/cart/cart-empty.php
dk/woocommerce/cart/cart-item-data.php
dk/woocommerce/cart/cart-shipping.php
dk/woocommerce/cart/cart-totals.php
dk/woocommerce/cart/cart.php
dk/woocommerce/cart/cross-sells.php
dk/woocommerce/cart/mini-cart.php
dk/woocommerce/cart/proceed-to-checkout-button.php
dk/woocommerce/cart/shipping-calculator.php
dk/woocommerce/checkout/cart-errors.php
dk/woocommerce/checkout/form-billing.php
dk/woocommerce/checkout/form-checkout.php
dk/woocommerce/checkout/form-coupon.php
dk/woocommerce/checkout/form-login.php
dk/woocommerce/checkout/form-pay.php
dk/woocommerce/checkout/form-shipping.php
dk/woocommerce/checkout/payment-method.php
dk/woocommerce/checkout/payment.php
dk/woocommerce/checkout/review-order.php
dk/woocommerce/checkout/terms.php
dk/woocommerce/checkout/thankyou.php
dk/woocommerce/content-product.php
dk/woocommerce/content-product_cat.php
dk/woocommerce/content-single-product.php
dk/woocommerce/content-widget-product.php
dk/woocommerce/content-widget-reviews.php
dk/woocommerce/emails/email-header.php
dk/woocommerce/emails/email-styles.php
dk/woocommerce/global/breadcrumb.php
dk/woocommerce/global/form-login.php
dk/woocommerce/global/quantity-input.php
dk/woocommerce/global/sidebar.php
dk/woocommerce/global/wrapper-end.php
dk/woocommerce/global/wrapper-start.php
dk/woocommerce/loop/add-to-cart.php
dk/woocommerce/loop/loop-end.php
dk/woocommerce/loop/loop-start.php
dk/woocommerce/loop/no-products-found.php
dk/woocommerce/loop/pagination.php
dk/woocommerce/loop/price.php
dk/woocommerce/loop/rating.php
dk/woocommerce/loop/sale-flash.php
dk/woocommerce/myaccount/dashboard.php
dk/woocommerce/myaccount/downloads.php
dk/woocommerce/myaccount/form-add-payment-method.php
dk/woocommerce/myaccount/form-edit-account.php
dk/woocommerce/myaccount/form-edit-address.php
dk/woocommerce/myaccount/form-login.php
dk/woocommerce/myaccount/form-lost-password.php
dk/woocommerce/myaccount/form-reset-password.php
dk/woocommerce/myaccount/lost-password-confirmation.php
dk/woocommerce/myaccount/my-account.php
dk/woocommerce/myaccount/my-address.php
dk/woocommerce/myaccount/navigation.php
dk/woocommerce/myaccount/orders.php
dk/woocommerce/myaccount/payment-methods.php
dk/woocommerce/myaccount/view-order.php
dk/woocommerce/notices/error.php
dk/woocommerce/notices/notice.php
dk/woocommerce/notices/success.php
dk/woocommerce/order/form-tracking.php
dk/woocommerce/order/order-again.php
dk/woocommerce/order/order-details-customer.php
dk/woocommerce/order/order-details-item.php
dk/woocommerce/order/order-details.php
dk/woocommerce/order/tracking.php
dk/woocommerce/product-searchform.php
dk/woocommerce/single-product/add-to-cart/external.php
dk/woocommerce/single-product/add-to-cart/grouped.php
dk/woocommerce/single-product/add-to-cart/simple.php
dk/woocommerce/single-product/add-to-cart/variable.php
dk/woocommerce/single-product/add-to-cart/variation-add-to-cart-button.php
dk/woocommerce/single-product/add-to-cart/variation.php
dk/woocommerce/single-product/meta.php
dk/woocommerce/single-product/photoswipe.php
dk/woocommerce/single-product/price.php
dk/woocommerce/single-product/product-attributes.php
dk/woocommerce/single-product/product-image.php
dk/woocommerce/single-product/product-thumbnails.php
dk/woocommerce/single-product/rating.php
dk/woocommerce/single-product/related.php
dk/woocommerce/single-product/review-meta.php
dk/woocommerce/single-product/review-rating.php
dk/woocommerce/single-product/review.php
dk/woocommerce/single-product/sale-flash.php
dk/woocommerce/single-product/share.php
dk/woocommerce/single-product/short-description.php
dk/woocommerce/single-product/stock.php
dk/woocommerce/single-product/tabs/additional-information.php
dk/woocommerce/single-product/tabs/description.php
dk/woocommerce/single-product/tabs/tabs.php
dk/woocommerce/single-product/title.php
dk/woocommerce/single-product/up-sells.php
dk/woocommerce/single-product-reviews.php
dk/woocommerce/single-product.php
dk/woocommerce/taxonomy-product_cat.php
dk/woocommerce/taxonomy-product_tag.php

### Action Scheduler ###

Complete: 5
Oldest: 2019-05-29 17:04:21 +0000
Newest: 2019-06-26 19:45:54 +0000

Pending: 1
Oldest: 2019-07-03 19:45:54 +0000
Newest: 2019-07-03 19:45:54 +0000

Canceled: 0
Oldest: –
Newest: –

In-progress: 0
Oldest: –
Newest: –

Failed: 0
Oldest: –
Newest: –

`
</details>

**Comment by Jon007** [comment]
@dmytro-kindrat  yes, that is nuts - it was working before!!

until we work out what has happened, please try turning off Settings, WooPoly, Features, Check WooCommerce Pages

Also try eg:
UPDATE `wp_options` SET `option_value` = '1' WHERE `wp_options`.`option_name` = 'wpi_wcpagecheck_passed';
to set the check to passed to try to avoid future checks.

**Comment by Jojo56** [comment]
I also have the same problem. Unfortunately setting check WooCommerce Pages Off or updating "wpi_wcpagecheck_passed" doesn't work.

**Comment by dmytro-kindrat** [comment]
I turning off WooCommerce Pages and update "wpi_wcpagecheck_passed" to 1.
The situation has not changed.

I also tried to just create a EN language version of the product. 
After save product I go to pages and saw a lot of duplicate pages.

**Comment by Jon007** [comment]
Hi, please put a 
return;
statement at the top of plugin.php wpi_ensure_woocommerce_pages_translated() 
until a fix is released

**Comment by dmytro-kindrat** [comment]
Ok.
I understand how the error comes out.

1. Go to Pages.
2. Switch to the language of EN.
3. Refresh the page.
4. Saw a lot of duplicate pages.

**Comment by saqui3001** [comment]
Hi I have the same issue and site is giving this warnings in the frontend and backend: 
Warning:  Illegal string offset 'wpi-support' in /home/theglob4/public_html/wp-content/plugins/woo-poly-integration/src/Hyyan/WPI/Tools/FlashMessages.php on line 52

Notice:  Array to string conversion in /home/theglob4/public_html/wp-content/plugins/woo-poly-integration/src/Hyyan/WPI/Tools/FlashMessages.php on line 52

Warning: Invalid argument supplied for foreach() in /home/theglob4/public_html/wp-content/plugins/woo-poly-integration/src/Hyyan/WPI/Tools/FlashMessages.php on line 85

**Comment by saqui3001** [comment]
Hi I have the same issue and site is giving this warnings in the frontend and backend:
Warning: Illegal string offset 'wpi-support' in /public_html/wp-content/plugins/woo-poly-integration/src/Hyyan/WPI/Tools/FlashMessages.php on line 52

Notice: Array to string conversion in /public_html/wp-content/plugins/woo-poly-integration/src/Hyyan/WPI/Tools/FlashMessages.php on line 52

Warning: Invalid argument supplied for foreach() in /public_html/wp-content/plugins/woo-poly-integration/src/Hyyan/WPI/Tools/FlashMessages.php on line 85

**Comment by Jon007** [comment]
@saqui3001 warnings issue is #436

**Comment by saqui3001** [comment]
can I get the previous version of the  plugin, it was cool. Thanx in advance.

**Comment by Jon007** [comment]
@saqui3001 previous versions of plugin are always available at https://wordpress.org/plugins/woo-poly-integration/advanced/
(same goes for about any other plugin, just go to the advanced tab)

**Comment by Jon007** [comment]
@saqui3001, @dmytro-kindrat, @Jojo56, @hyyan 
release prepared on:
https://github.com/hyyan/woo-poly-integration/releases/tag/v1.4.3
please check this one and let me know any issues

**Comment by dmytro-kindrat** [comment]
Thank! Good job. Everything works perfectly.

**Comment by Jojo56** [comment]
Its working perfectly. Thank you!

**Comment by saqui3001** [comment]
It works perfectly. Thanx a lot.

**Comment by crysx** [comment]
Had the same problem on new site with latest polylang. 1.4.3 fixed this.
