### ISSUE TITLE
1.4.2 some users had a FlashMessages error on upgrade

### ISSUE THREAD

**Issue by Jon007** [hyyan/woo-poly-integration#436]
reported on: https://wordpress.org/support/topic/bugs-on-latest-updates/

Warning: Illegal string offset ‘wpi-support’ in /wp-content/plugins/woo-poly-integration/src/Hyyan/WPI/Tools/FlashMessages.php on line 52
Warning: Invalid argument supplied for foreach() in /wp-content/plugins/woo-poly-integration/src/Hyyan/WPI/Tools/FlashMessages.php on line 85

Unable to reproduce but it appears that in php 7.1 previously working code such as:

```
if(!isset($array['id']) ) {
    $array['id'] = '';
}
```
does not work if the $array is not already initialised to an array variable - a fix in FlashMessages might be to ensure that the messages is definitely initialised to an array even if the saved value is a string, eg:

```
	private static function getMessages() {
		$messages = get_option( static::getOptionName(), array() );
		if ( ! is_array( $messages ) ) {
			$messages = array();
		}
		return $messages;
	}
```

However, I could not reproduce the problem, and the wordpress.org commenters have not reported the issue on github as requested so have not captured their php version etc ..

**Comment by Pechyopava** [comment]
Hello, I have the same problem. What information you want from me? I can share it. The url is: martinpechacek.cz/vaskentshop/

Thank you for reply!

**Comment by Pechyopava** [comment]
This appeared when i adding translation to new categories:
Warning: Illegal string offset 'wpi-support' in /data/web/virtuals/140619/virtual/www/domains/martinpechacek.cz/vaskentshop/wp-content/plugins/woo-poly-integration/src/Hyyan/WPI/Tools/FlashMessages.php on line 52

Warning: Cannot modify header information - headers already sent by (output started at /data/web/virtuals/140619/virtual/www/domains/martinpechacek.cz/vaskentshop/wp-content/plugins/woo-poly-integration/src/Hyyan/WPI/Tools/FlashMessages.php:52) in /data/web/virtuals/140619/virtual/www/domains/martinpechacek.cz/vaskentshop/wp-admin/includes/misc.php on line 1196

Warning: Cannot modify header information - headers already sent by (output started at /data/web/virtuals/140619/virtual/www/domains/martinpechacek.cz/vaskentshop/wp-content/plugins/woo-poly-integration/src/Hyyan/WPI/Tools/FlashMessages.php:52) in /data/web/virtuals/140619/virtual/www/domains/martinpechacek.cz/vaskentshop/wp-includes/pluggable.php on line 1251

Warning: Cannot modify header information - headers already sent by (output started at /data/web/virtuals/140619/virtual/www/domains/martinpechacek.cz/vaskentshop/wp-content/plugins/woo-poly-integration/src/Hyyan/WPI/Tools/FlashMessages.php:52) in /data/web/virtuals/140619/virtual/www/domains/martinpechacek.cz/vaskentshop/wp-includes/pluggable.php on line 1254

**Comment by Jon007** [comment]
@Pechyopava  the information needed is the value you have in the options table in the database for:
`select option_value from wp_options where option_name like 'hyyan-wpi-flash-messages'`

**Comment by Jon007** [comment]
also which version of php the site is running under..

**Comment by edwinhuish** [comment]
It seems 'hyyan-wpi-flash-messages' return just string "A", non array. I submit a PR #437

**Comment by Jon007** [comment]
@edwinhuish it is already fixed in 1.4.3 on the first commit in this thread..
https://github.com/hyyan/woo-poly-integration/commit/feedc68431bcd26c8d9bd2b4afacf4d7a86a62a1

**Comment by edwinhuish** [comment]
Yes, I saw it after view #434

**Comment by Pechyopava** [comment]
> @Pechyopava the information needed is the value you have in the options table in the database for:
> `select option_value from wp_options where option_name like 'hyyan-wpi-flash-messages'`


Hello, thank you for your reply. My option value is "A" and I´am running on PHP v. 7.1.

**Comment by edwinhuish** [comment]
@Pechyopava  pls check #434, 

this problem was fixed, you can download the releases https://github.com/hyyan/woo-poly-integration/releases/tag/v1.4.3
