### ISSUE TITLE
Sale Price Labels from Germanized plugin

### ISSUE THREAD

**Issue by ecowebdesign** [hyyan/woo-poly-integration#439]
Hi,
The Germanized plugin have some support for woo-poly , in particular translation of custom taxonomy. 
But it does not work for me.
Does anyone can tell , if this still working or there have been changes ?

`                $metas[ 'sale_price_labels' ] = array(
                        'name' => _x( 'Sale Price Labels', 'polylang', 'woocommerce-germanized' ),
                        'desc' => _x( 'Sale price labels used to mark old prices (e.g. Recommended Retail Price)', 'polylang', 'woocommerce-germanized' ),
                        'metas' => array(
                                '_sale_price_label',
                                '_sale_price_regular_label',
                        ),
                );
`

**Comment by ecowebdesign** [comment]
UPDATE: I enabled WPMP compatibility and things changed , after testing I will post results.

**Comment by ecowebdesign** [comment]
After enabling WPML compatibility , I can create translated Price labels, but I cant save them into product.
How does one properly register custom taxonomy metas ?

**Comment by Jon007** [comment]
@ecowebdesign  taxonomy and meta are two different things ...
custom taxonomies can be translated by apply the Polylang setting in Languages, Settings, Custom Taxonomies, see eg:
https://github.com/hyyan/woo-poly-integration/wiki/Product-Attributes

**Comment by ecowebdesign** [comment]
Hi Jon007,
in options-general.php?page=hyyan-wpi I do have checked list of Custom taxonomies from Germanized
but in Polylang settings ( admin.php?page=mlang_settings ) they do not appear

**Comment by ecowebdesign** [comment]
In Polylang settings only this is registered 
It appears brand| Marke is from Germanized. But is not what I need.

mysql> select * from wp_woocommerce_attribute_taxonomies;
+--------------+----------------+-----------------+----------------+-------------------+------------------+
| attribute_id | attribute_name | attribute_label | attribute_type | attribute_orderby | attribute_public |
+--------------+----------------+-----------------+----------------+-------------------+------------------+
|            1 | color          | color           | select         | menu_order        |                0 |
|            2 | size           | size            | select         | menu_order        |                0 |
|            3 | brand          | Marke           | text           | menu_order        |                0 |
+--------------+----------------+-----------------+----------------+-------------------+------------------+

Meta settings : 
https://imgur.com/hVfczQr

Polylang Custom taxonomy settings:
https://imgur.com/cETrRnZ

**Comment by Jon007** [comment]
Sorry I do not know how WooCommerce Germanized works... this plugin only bridges polylang and woocommerce, other plugins may have their own compatibility layer.. the wp_woocommerce_attribute_taxonomies may not be the most relevant table here, the taxonomies actually go through the wordpress taxonomy tables.

Also check Polylang string translations (Languages, String Translations) - this is WPML api compatible, it may be that germanized uses this.

**Comment by ecowebdesign** [comment]
I modified wpml-config.xml in Germanized plugin and is working now. I have contacted author about this issue.
