### ISSUE TITLE
After changing the product another language version becomes uncategorized.

### ISSUE THREAD

**Issue by dmytro-kindrat** [hyyan/woo-poly-integration#441]
**Can you reproduce this issue on default Wordpress theme (eg Storefront)?**
Yes

**Can you reproduce this issue when all other plugins are disabled except WooCommerce, Polylang and Hyyan WooCommerce Polylang Integration?**
Yes

**What product versions and settings are you using when this issue occurs?**

- PHP: 7.3.0
- WordPress: 5.2.2
- WooCommerce: 3.6.5
- Polylang
- Hyyan WooCommerce Polylang Integration: 1.4.3
- Browser: Firefox 67.0.4

**Steps to Reproduce**

1. Go to the Products
2. Edit product RU
3. Save product RU
4. Go to Products and saw an EN version of the product has become uncategorized.

**Comment by dmytro-kindrat** [comment]
After saving product RU, the category is not synchronized on EN language, but changed to the category on RU language.

**Comment by Jon007** [comment]
this type of behaviour sounds like your category translations are not linked.
For example, when you save a product in RU, if there is not linked category translation in EN, a copy of the RU will be created in EN and linked, and you may then go and edit the EN translation.
Check in Products, Categories, it is possible to relink categories by opening a category and using the Translations section to link the correct translation.

**Comment by dmytro-kindrat** [comment]
I have already tried re-creating the category link, but this did not help.

![1s](https://user-images.githubusercontent.com/51969083/61182342-2c1e2d80-a63a-11e9-9e81-c68ef2b36213.png)

![2](https://user-images.githubusercontent.com/51969083/61182343-2c1e2d80-a63a-11e9-9f2a-d13bc9ca30ce.png)

![3](https://user-images.githubusercontent.com/51969083/61182358-71daf600-a63a-11e9-9755-96065804572a.png)

![4s](https://user-images.githubusercontent.com/51969083/61182345-2cb6c400-a63a-11e9-81ca-53061d55f7e0.png)

![5s](https://user-images.githubusercontent.com/51969083/61182346-2cb6c400-a63a-11e9-974d-744f5f754f6b.png)

![6s](https://user-images.githubusercontent.com/51969083/61182347-2cb6c400-a63a-11e9-94f2-f5331e35233e.png)

![7s](https://user-images.githubusercontent.com/51969083/61182348-2d4f5a80-a63a-11e9-93df-4a2a500486a8.png)

**Comment by dmytro-kindrat** [comment]
If I create a product in the EN language, the category is synchronized well. The bug occurs only if I EDIT the product in the default language (RU) and if exist translated version.

**Comment by Jon007** [comment]
I cannot reproduce this, if the categories are set up correctly it normally works fine in whichever language you edit the product.

either the categories are not linked or some of them do not have language set properly.
go to Polylang languages /wp-admin/admin.php?page=mlang  and see if there is a notice about some items not have language set, with a link to set them to default language if not set.

**Comment by dmytro-kindrat** [comment]
Sorry, I found the reason for this behavior.
I use the Polylang Slug plugin (https://github.com/grappler/polylang-slug).
And the categories in two languages have the same slugs.

For example:
On RU - panties
On EN - panties

If I make slug different, example "panties-ru" and "panties", the  synchronisation of categories works fine.

I understand that the categories are synchronized not by the category ID, but by the slugs?

**Comment by Jon007** [comment]
yes, copyTerms in meta.php is currently calling wp_set_object_terms with an array of slugs.
This should be relatively easy to change as wp_set_object_terms should accept an array of ids and the ids are available.

**Comment by dmytro-kindrat** [comment]
Thank's!
I edit 409 line meta.php
`$new_terms[] = get_term_by('id', $translated_term, $tax)->slug;`
to
`$new_terms[] = get_term_by('id', $translated_term, $tax)->term_id;`

And it worked fine!
