### ISSUE TITLE
Translated product gives error 404

### ISSUE THREAD

**Issue by Niickp** [hyyan/woo-poly-integration#444]
Hi, I created a product in both languages, the base language works but the translated page gives a error 404 page not found. 

* PHP:  7.1.30
* WordPress: i have to update to latest version, but I have the one right before
* WooCommerce: 3.6.4
* Polylang: 2.5.4 (free version)
* Hyyan WooCommerce Polylang Integration: 1.4.3

**Comment by Jon007** [comment]
Sounds like something wrong with your permalinks, go to Settings, Permalinks, make sure permalinks bases are set for shop and products etc and press save

**Comment by Niickp** [comment]
Hi Jonathan, that worked, thank you very much.
