### ISSUE TITLE
translate extra field in variation product

### ISSUE THREAD

**Issue by caroletag** [hyyan/woo-poly-integration#448]
Hi,
I'm looking to desynchronize an extra field in variation product, you told me to use the filter woo-poly.product.disabledMetaSync, but I don't know how to integrate it and can't find any information about it. 
Could you give me the solution?
Thanks

**Comment by Jon007** [comment]
actually there are several filters to consider
'woo-poly.fieldsLockerSelectors' 
'woo-poly.fieldsLockerVariableExcludeSelectors'
I'll check them out a bit more and write it up here.

to get an idea though they all work along the lines of:
```

add_filter('woo-poly.product.disabledMetaSync', 'dontSyncMyCustomField');
function dontSyncMyCustomField($fieldsNotToSync){
	$fieldsNotToSync[] = 'MyCustomField';
}
```

**Comment by caroletag** [comment]
Thanks for your feedback, but it still doesn't work. The field is still blocked.... (see screenshot, I've set the transmitted function for the "Vinification" field).
Any other ideas?
Thanks
![Capture d’écran 2019-08-01 à 09 24 59](https://user-images.githubusercontent.com/40384656/62273738-8db60880-b43e-11e9-98f7-d455f83d85e5.png)

**Comment by Jon007** [comment]
sorry I did not have time to look at this yet - the example I gave was to remove the field from synchronisation, the other filter is needed to also remove from the fields locker, I'll test it out by tomorrow.

**Comment by Jon007** [comment]
Hi, sorry I didn't have time to check this earlier, the correct code should be eg:

```
/*
 * stop synchronisation of field
 */
add_filter( 'woo-poly.product.disabledMetaSync', 'dontSyncMyCustomField', 10, 1 );
function dontSyncMyCustomField( $fieldsNotToSync ) {
	$fieldsNotToSync[] = 'my_field';
	return $fieldsNotToSync;
}
/*
 * stop locking of field
 */
add_filter( 'woo-poly.fieldsLockerVariableExcludeSelectors', 'dontLockMyCustomField', 10, 1 );
function dontLockMyCustomField( $selectorsNotToLock ) {
	$selectorsNotToLock[] = '[name^="my_field"]';
	return $selectorsNotToLock;
}

```

there are two separate concepts here, whether the field is locked or not, and whether the field is synchronized or not.

just change my_field with the real name of your field, and let me know if that sorts it for you

**Comment by caroletag** [comment]
Hi Jon,
Thank you very much for your precious help! Everything works like a charm!!!
Many thanks again

**Comment by Jon007** [comment]
ok good thanks for confirming.
I have slightly improved the documentation note on:
https://github.com/hyyan/woo-poly-integration/wiki/Product-Meta-and-Custom-Fields
and with that will close this issue
