### ISSUE TITLE
Products Pricing List / Pricing Markup not being replicated to Translated Products Pages

### ISSUE THREAD

**Issue by raz0r7** [hyyan/woo-poly-integration#451]
#### Can you reproduce this issue on default Wordpress theme (eg Storefront)?
No

#### Can you reproduce this issue when all other plugins are disabled except WooCommerce, Polylang and Hyyan WooCommerce Polylang Integration?

Yes, done.

#### What product versions and settings are you using when this issue occurs?
* PHP: : 7.2.20
* WordPress: 5.2.2
* WooCommerce: Version 3.6.5 
* Polylang: Version 2.6.3 
* Hyyan WooCommerce Polylang Integration: 1.4.3
* Browser: Chrome  76.0.3809.100

#### Steps to Reproduce
1. Updating products price list.
1. Example: Default Language: English
1. More languages: Spanish and Portuguese

#### What I Expected
Update the Products Price List / Pricing Markup in multilingual, replicates the new pricing to all products in all laguages.

#### What Happened Instead

It updates only the default language in English(parent). Others products pages in Spanish and Portuguese(child) linked to the same product are not updated automatically.

Workaround:

Once I go to the default(parent) product page, click only on "Update" button, the new price is replicated to others product pages in Spanish and Portuguese. Its a tough work to update it manually one by one.

## WordPress Environment

<details>
```
`
### WordPress Environment ###

WordPress address (URL): https://shopflixstore.com
Site address (URL): https://shopflixstore.com
WC Version: 3.6.5
Log Directory Writable: ✔
WP Version: 5.2.2
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: LiteSpeed
PHP Version: 7.2.20
PHP Post Max Size: 256 MB
PHP Time Limit: 240
PHP Max Input Vars: 5000
cURL Version: 7.62.0
OpenSSL/1.0.2k

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.2.25-MariaDB
Max Upload Size: 256 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.6.5
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
Total Database Size: 34.07MB
Database Data Size: 22.32MB
Database Index Size: 11.75MB
wp_woocommerce_sessions: Data: 0.06MB + Index: 0.02MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_adsw_activities: Data: 0.27MB + Index: 0.00MB
wp_adsw_ali_meta: Data: 0.31MB + Index: 0.03MB
wp_adsw_search_analytics: Data: 0.02MB + Index: 0.02MB
wp_ads_activities: Data: 0.02MB + Index: 0.00MB
wp_ads_ali_meta: Data: 0.02MB + Index: 0.03MB
wp_ads_attributes: Data: 0.02MB + Index: 0.03MB
wp_ads_orders_item: Data: 0.02MB + Index: 0.03MB
wp_ads_products: Data: 0.02MB + Index: 0.03MB
wp_ads_products_meta: Data: 0.02MB + Index: 0.02MB
wp_ads_search_analytics: Data: 0.02MB + Index: 0.02MB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB
wp_comments: Data: 0.30MB + Index: 0.38MB
wp_duplicator_packages: Data: 0.02MB + Index: 0.02MB
wp_links: Data: 0.02MB + Index: 0.02MB
wp_options: Data: 2.16MB + Index: 0.14MB
wp_payment_discount: Data: 0.02MB + Index: 0.00MB
wp_payment_transaction: Data: 0.02MB + Index: 0.06MB
wp_postmeta: Data: 12.52MB + Index: 7.56MB
wp_posts: Data: 3.52MB + Index: 0.81MB
wp_termmeta: Data: 0.19MB + Index: 0.27MB
wp_terms: Data: 0.22MB + Index: 0.22MB
wp_term_relationships: Data: 1.34MB + Index: 0.41MB
wp_term_taxonomy: Data: 0.31MB + Index: 0.31MB
wp_tinvwl_analytics: Data: 0.02MB + Index: 0.02MB
wp_tinvwl_items: Data: 0.02MB + Index: 0.00MB
wp_tinvwl_lists: Data: 0.02MB + Index: 0.00MB
wp_tm_taskmeta: Data: 0.02MB + Index: 0.03MB
wp_tm_tasks: Data: 0.02MB + Index: 0.02MB
wp_usermeta: Data: 0.02MB + Index: 0.03MB
wp_users: Data: 0.02MB + Index: 0.05MB
wp_wcpdf_invoice_number: Data: 0.02MB + Index: 0.00MB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB
wp_wc_product_meta_lookup: Data: 0.22MB + Index: 0.47MB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB
wp_yith_wcwl: Data: 0.02MB + Index: 0.02MB
wp_yith_wcwl_lists: Data: 0.02MB + Index: 0.03MB

### Post Type Counts ###

attachment: 1011
custom_css: 1
customize_changeset: 5
elementor_library: 7
jp_img_sitemap: 1
jp_sitemap: 1
jp_sitemap_master: 1
nav_menu_item: 100
page: 60
polylang_mo: 3
post: 3
product: 186
product_variation: 1964
revision: 16
scheduled-action: 698
wpcf7_contact_form: 2
wpforms: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (36) ###

Polylang: by WP SYNTEX – 2.6.3
Livemesh Addons for Elementor: by Livemesh – 2.7.4
AliDropship Woo Plugin: by Vitaly Kukin & Yaroslav Nevskiy & Pavel Shishkin & Denis Zharov – 1.5.8
All In One SEO Pack: by Michael Torbert – 3.2.3
All-in-One WP Migration File Extension: by ServMask
Inc. – 1.5

All-in-One WP Migration: by ServMask – 7.4
WooCommerce MercadoPago: by Mercado Pago – 3.1.0 – Not tested with the active version of WooCommerce
Classic Editor: by WordPress Contributors – 1.5
Polylang Connect for Elementor: by David Decker - DECKERWEB – 1.0.0
Contact Form 7: by Takayuki Miyoshi – 5.1.4
Display PHP Version: by David Gwyer – 1.5
Elementor: by Elementor.com – 2.6.8
Envato Elements: by Envato – 1.1.1
Essential Addons for Elementor: by WPDeveloper – 3.1.5
Site Kit by Google: by Google – 1.0.0-beta.1.0.3
My Custom Functions: by Space X-Chimp – 4.38.1
Ocean Custom Sidebar: by OceanWP – 1.0.4
Ocean Extra: by OceanWP – 1.5.10
Ocean Product Sharing: by OceanWP – 1.0.7 – Not tested with the active version of WooCommerce
Ocean Social Sharing: by OceanWP – 1.0.14
Ocean Stick Anything: by OceanWP – 1.0.2
One Click Demo Import: by ProteusThemes – 2.5.2
PowerPack Lite for Elementor: by IdeaBox Creations – 1.2.5
Premium Addons for Elementor: by Leap13 – 3.6.4
Shortcode in Menus: by Gagan Deep Singh – 3.5
Sticky Header OceanWP: by Oren Hahiashvili – 1.0.5
TI WooCommerce Wishlist Plugin: by TemplateInvaders – 1.13.2
Toolbar Extras: by David Decker - DECKERWEB – 1.4.4
Hyyan WooCommerce Polylang Integration: by Hyyan Abo Fakher – 1.4.3
WooCommerce Refund and Exchange Lite: by MakeWebBetter – 1.0.5
WooCommerce Admin: by WooCommerce – 0.16.0
WooCommerce PayPal Checkout Gateway: by WooCommerce – 1.6.17
WooCommerce Services: by Automattic – 1.21.0
WooCommerce: by Automattic – 3.6.5
WP-Optimize - Clean, Compress, Cache: by David Anderson
Ruhani Rabin
Team Updraft – 3.0.11

WPForms Lite: by WPForms – 1.5.4.2

### Inactive Plugins (4) ###

Cloudflare: by John Wineman
Furkan Yilmaz
Junade Ali (Cloudflare Team) – 3.3.3

Duplicator: by Snap Creek – 1.3.18
Jetpack by WordPress.com: by Automattic – 7.6
WooCommerce Quick Buy: by Varun Sridharan – 1.9 – Not tested with the active version of WooCommerce

### Settings ###

API Enabled: –
Force SSL: –
Currency: BRL (R$)
Currency Position: left
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop base: #6 - /shop/
Cart: #7 - /cart/
Checkout: #8 - /checkout/
My account: #9 - /my-account/
Terms and conditions: #1573 - /terms-of-service/

### Theme ###

Name: OceanWP
Version: 1.6.10
Author URL: https://oceanwp.org/about-me/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: oceanwp/woocommerce/cart/mini-cart.php
oceanwp/woocommerce/content-single-product.php
oceanwp/woocommerce/loop/loop-start.php
oceanwp/woocommerce/single-product/title.php


### TI WooCommerce Wishlist Templates ###

Overrides: –

### Action Scheduler ###

Complete: 697
Oldest: 2019-07-08 23:50:42 -0300
Newest: 2019-08-08 23:21:55 -0300

Pending: 1
Oldest: 2019-08-09 00:21:55 -0300
Newest: 2019-08-09 00:21:55 -0300

Canceled: 0
Oldest: –
Newest: –

In-progress: 0
Oldest: –
Newest: –

Failed: 0
Oldest: –
Newest: –

````
</details>

**Comment by Jon007** [comment]
@raz0r7 what do you mean by "Products Price List / Pricing Markup"

**Comment by raz0r7** [comment]
Hi Jon,

First of all, thank you for trying to help. 
In my site I use AliDropShip to import that products from AliExpress.

Products Price List / Pricing Markup is the section where we setup rules for pricing to be rolled out to the entire site.
What happens is that once the rules are set in this section, it applies only to the default language. Translated pages derived from this are not getting the pricing rules.

I sent the following message to AliDropShip plugin support team:

quote

Hi AliDrop Support team,

I have already reported some issues involving translated products, but I could find a workaround for those, however this time, something must be done at your side, otherwise it will compromise my whole work and website.

The question involves Pricing Markup rules for translated products as well as pricing replications to these products.

Plugins:

AliDropShip
Plugin Translator – Polylang
Integrator - Hyyan WooCommerce Polylang Integration

I noted something odd when I was translating the products and after setting up a rule in Pricing Markup, it was not replicating the prices for these languages. To make it work, I had to go the each translated product and just click on “update” button to make it work. It was not a problem If I had to make it once on the moment that product was being translated, however it got worst.

AlidropShip settings updates on daily basis the prices from AliExpress in USD. It automatically updates all products in the site, but only in English, the default site language. 

Now, translated products pages in others languages such as Portuguese and Spanish are not being updated automatically from AliDropShip, and it will impact severely all work Ive done since I bought the Plugin, because the site is multilingual. Can´t have only the default language being updated, AliDropship must replicate pricing updates to them all.

It doesn’t matter If I set a rule to cover translated categories for example, the “main” pricing rules are not being replicated to translated pages.


Please see below some print shots :

Currency settings ( no matter the default currency, USD, BRL,EUR, the issues happens anyway, I have already tested it).

[sent some prints and adm credentials to them ]

And Spanish is the same as above in Portuguese.

Another similar issue that is happenings was reported and it’s attached to this message, the moment a products is translated, the default product page loses the variations settings and then I must set it manually which give me a lot of unnecessary work. Its someway related to the problem reported in this email, involving translated products. I believe its 2 issues with 1 root cause.

Please get your developers to investigate into this issue, and fix the problem, its jeopardizing all my work.

Thank you for your usual assistance.

Best Regards,

Rafael Pereira

unquote

So, this is the msg sent to them and I'm waiting for a solution,  believe now its on their end the real solution but if you can somehow contribute with any knowledge, its a plus. 

Thank you Jon.

Rafael

**Comment by raz0r7** [comment]
Hi Jon,

I received a feedback from their customer service.
Actually their support for the plugin is terrible.

They will not provide any support for my issue, they just suggested me to use another platform where translations must be done manually. Can´t be believe that. And also supported only from few themes, not the one I use, which is Ocean View.

Can´t believe they will not give me a hand by solving this issue, which is to force the pricing rules to be rolled about to all product pages, no matter the language.

I don't know where to ask help anymore.

**Comment by Jon007** [comment]
Hi @raz0r7 I’m not familiar with the plugin but the normal thing is to identify what additional metadata they are using and use the appropriate filters to control which of these fields are synchronised.
See https://github.com/hyyan/woo-poly-integration/wiki/Product-Meta-and-Custom-Fields
- it’s not great but may give you some ideas

**Comment by raz0r7** [comment]
I sent this article to them. With a lots of complains, of course.
Its unacceptable this plugin conflicts with Polylang, widely used worldwide.

Let's see what they will answer back. I will keep you posted.

Thank you Jon!

Rafael

**Comment by raz0r7** [comment]
Hi Jon, look I what found:

https://wpml.org/forums/topic/how-to-update-price-of-the-product/

Its exactly the problem I'm having. Until now, no response from them after my last message. 
Honestly, I don't think they will help after last exchanged messages, so I'm ready to set the site to one single language if indeed they don't provide any help. Unfortunately, because I designed the site to be multilingual. Lets see what happens until the end of this week.

**Comment by Jon007** [comment]
Right yes the thread refers to
“the use of custom tables that hold the information that you want to synchronise that lie outside of the normal Woocommerce solution”
So a custom solution would be needed,
Which also has to be outside of the scope of this plugin.

**Comment by raz0r7** [comment]
Thank you Jon for your attention on this matter and for trying to help me.

Best regards,
Rafael

**Comment by Jon007** [comment]
no problem.
for reference, what is the url for this AliDropShip and is it open source?

**Comment by raz0r7** [comment]
Hi Jon,

URL - https://alidropship.com/

I'm not sure it's open source, it's a paid plugin, 89 USD, but you can get more info by contacting them.
