### ISSUE TITLE
Translate order products

### ISSUE THREAD

**Issue by GotyMetal** [hyyan/woo-poly-integration#454]
Hi there, first of all, excellent plugin and support :)
My only issue is that i have the page in 2 languages (spanish and english), but i'd like to see the order items in the same lang (spanish), so even if a customer uses the english version and makes the order in english i can still "change", "switch" or "see" the list of purchased items in the order in spanish so it's easier for my employees to fill the order, thanks!

**Comment by Jon007** [comment]
oh, you mean in the order admin screen?
That might not be possible, an order is a post in a language and is not translated, translating it would have all sorts of side effects.

However you can normally view in the front end eg, depending on how your shop is set up:
/es/mi-cuenta/ver-pedido/12345/

On unpaid orders the Order admin gives you a link for this, the "Customer payment page" link, but if you are admin you can view any order by replacing 12345 on the url above with the order number..

As another example I've also done this in emails, implemented a separate email which is always in a particular language, but that is custom coding.

**Comment by Jon007** [comment]
Closing as not actually an error and no further problem report in last 10 months.
