### ISSUE TITLE
Translation Group and Language column missing by Woo prod import

### ISSUE THREAD

**Issue by madmin123** [hyyan/woo-poly-integration#455]
Hello,

have set up Wordpress with WooCommerce and Polylang.
Now I want to import products with the default Woo importer. As I followed the Polylang tutorial I created a simple testimport CSV wit columns "Language" and "Translation group" but when I want to map these fields during import process, there are no fields to map!

Please help, this problem needs to be fixed as soon as possible.

Used this tutorial:
https://polylang.pro/doc/product-csv-importer-and-exporter/

Set up the languages English and German within Polylang.

My Versions:
Wordpress with multisite installation: Version 5.2.2
WooCommerce 3.7.0 (upgraded because the previous showed the same problems)
Polylang Version 2.6.3

BR
madmin123

**Comment by Jon007** [comment]
wrong plugin.
That's Polylang Pro paid plugin.
https://polylang.pro/doc/product-csv-importer-and-exporter/

Importing with this plugin is discussed here:
https://github.com/hyyan/woo-poly-integration/issues/208
