### ISSUE TITLE
Polylang/Woocommerce integration problem on Cart and Checkout pages

### ISSUE THREAD

**Issue by mekoome** [hyyan/woo-poly-integration#456]
Hello! After updating Woocommerce and Polylang I found that integration between Polylang and WC stopped working. My site has 3 language versions - English, Estonian and Russian and now, when I put something to shopping cart in English or Russian versions always opens Estonian version of Shopping cart. 
Page setup in Woocommerce options is correct: different language versions of cart and checkout pages submitted  for different languages:
![image](https://user-images.githubusercontent.com/54332931/63406899-e3edea00-c3f3-11e9-9bde-d9c1230ad335.png)
![image](https://user-images.githubusercontent.com/54332931/63406921-f49e6000-c3f3-11e9-89df-f40c9f4b2fc5.png)
![image](https://user-images.githubusercontent.com/54332931/63406952-03851280-c3f4-11e9-960e-7c0ddb4b3edd.png)

**Is this resolveable issue or we should now buy another plugin for multilingual woocommerce?**

Here is completed checklist:

#### Can you reproduce this issue on default Wordpress theme (eg Storefront)?
Yes, checked on several default themes

#### Can you reproduce this issue when all other plugins are disabled except WooCommerce, Polylang and Hyyan WooCommerce Polylang Integration?
Yes, turned off all the plugins - no luck

#### What product versions and settings are you using when this issue occurs?
* PHP: **7.2.4**
* WordPress: **version 5.2.2**
* WooCommerce: **Version 3.7.0**
* Polylang: **Version 2.6.3**
* Hyyan WooCommerce Polylang Integration: **Version 1.4.3**
* Browser: **Google chrome**

#### Steps to Reproduce
1. Open English version of any product, like this: https://mekoome.com/knit-handmade/woolen-sweater-no-exit-yellow-top/
2. Try to add available variation to the Cart

#### What I Expected

English Cart page should open - like this: https://mekoome.com/shopping-cart/

#### What Happened Instead

Estonian version of cart opened instead: https://mekoome.com/ostukorv/

## WordPress Environment

<details>
```

WordPress environment
--
WordPress address (URL): |   | https://mekoome.com
Site address (URL): |   | https://mekoome.com
WooCommerce version: |   | 3.7.0
WooCommerce REST API package: |   | 1.0.2 /www/apache/domains/www.mekoome.com/htdocs/wp-content/plugins/woocommerce/packages/woocommerce-rest-api
Log directory writable: |   | /www/apache/domains/www.mekoome.com/htdocs/wp-content/uploads/wc-logs/
WordPress version: |   | 5.2.2
WordPress multisite: |   | –
WordPress memory limit: |   | 350 MB
WordPress debug mode: |   | –
WordPress cron: |   |  
Language: |   | en_US
External object cache: |   | –


```
</details>

**Comment by Jon007** [comment]
@mekoome  For me it is working, when I add the English version to cart it goes to English cart

Do note that WooCommerce 3.7 isn't officially supported yet, see pinned post on https://wordpress.org/support/plugin/woo-poly-integration/ and our thread for this #453 

Having said that I haven't seen any serious problem..

**Comment by mekoome** [comment]
Hello. It is working now because I purchased and installed Polylang for woocommerce plugin - I just could not wait. So, keep in mind that this problem can still resist if you plan to update plugin in the future.

**Comment by Jon007** [comment]
Well this is the first report of this in thousands of installations over the last few years so it was most likely your setup issue but we will keep an eye out for any possible WooCommerce3.7 compatibility
