### ISSUE TITLE
Cart.min.js fails

### ISSUE THREAD

**Issue by godofdream** [hyyan/woo-poly-integration#457]
I'm getting this error in the console on Pages where no woocommerce products are addable to cart. (Impressum pages etc.). Can we add a check if Cookies is loaded, before using them?
```
Cart.min.js?ver=1.4.3:1 Uncaught ReferenceError: Cookies is not defined
    at HTMLDocument.<anonymous> (Cart.min.js?ver=1.4.3:1)
    at i (jquery.js?ver=1.12.4-wp:2)
    at Object.fireWith [as resolveWith] (jquery.js?ver=1.12.4-wp:2)
    at Function.ready (jquery.js?ver=1.12.4-wp:2)
    at HTMLDocument.J (jquery.js?ver=1.12.4-wp:2)
```

**Comment by Jon007** [comment]
oh that's curious, 
- can you get more detail from the chrome debugging tools, which actual line in Cart.min.js?
you could enable SCRIPT_DEBUG to get the unminified version or replace the contents of Cart.min.js with Cart.js if that helps
- what's the simplest way to reproduce the issue?
- which version of woocommerce are you running?
Cart.js or Cart.min.js is a version of WooCommerce 3.6.3 cart-fragments.js with an additional language switch check

**Comment by godofdream** [comment]
I found the reason for the error.
I'm using the "WC Speed Drain Repair" Plugin.
Woocommerce: 3.7
