### ISSUE TITLE
Cannot translate woocommerce product category

### ISSUE THREAD

**Issue by marcololetti** [hyyan/woo-poly-integration#458]
I have to translate the woocommerce product category but when i click on the plus for adding a new translation, wordpress create a separate category. So when i try to change the language on the switcher, it redirects me on the homepage.
Furthermore, the products, which have a certain category, cannot be found on the translated one

**Comment by Jon007** [comment]
@marcololetti  are category translations working for Post Categories ?
are product category translations turned on in Settings, WooPoly, Features?

**Comment by wajdijurry** [comment]
I have the same issue, when I try to add new language to the category, it does nothing and the translation is not being saved!

**Comment by Jon007** [comment]
I have tested this is working ok in WP5.4.2 woo4.2.2 polylang 2.7.3 php7.4.2
Just check Category translation is turned on at:

- Settings\WooPoly (normally at /wp-admin/options-general.php?page=hyyan-wpi): 
- Polylang settings (Languages, Settings, Custom post types and Taxonomies) 

and check Settings, Permalinks and Save Changes

If still experiencing problems please raise a new issue with full details.
