### ISSUE TITLE
Product main image is not translating

### ISSUE THREAD

**Issue by colorgreen** [hyyan/woo-poly-integration#459]
I changed main image of product and it is changing on all translated versions. How to do it? I can't find any setting for this behaviour

**Comment by Jon007** [comment]
@colorgreen Yes, this is what most people want, what is it that you are expecting?

1. To avoid synchronising the main image try using Polylang settings under Languages, Settings, Synchronisation, Featured image.
1. Or, you can set Polylang to translate all images using Languages, Settings, Media - I dont recommend this
1. Or, you can do custom meta handling as indicated here: https://github.com/hyyan/woo-poly-integration/wiki/Product-Meta-and-Custom-Fields
