### ISSUE TITLE
Translate Cart and Checkout Pages

### ISSUE THREAD

**Issue by mindrunner** [hyyan/woo-poly-integration#461]
#### What product versions and settings are you using when this issue occurs?
* PHP: 7.2
* WordPress: latest
* WooCommerce: latest
* Polylang: latest
* Hyyan WooCommerce Polylang Integration: latest
* Browser: not relevant

#### Steps to Reproduce
1. visit my site
1. switch to spanish
1. go to checkout

#### What I Expected
All test is on spanish

#### What Happened Instead
Lots of text is on english

## WordPress Environment

<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.
```
</details>

![screenshot_20190914_152045](https://user-images.githubusercontent.com/1413542/64913774-b3a01f80-d703-11e9-937f-cd57d4088bbb.png)
![screenshot_20190914_152040](https://user-images.githubusercontent.com/1413542/64913775-b3a01f80-d703-11e9-9e96-a0c9a2212228.png)
![screenshot_20190914_151934](https://user-images.githubusercontent.com/1413542/64913776-b3a01f80-d703-11e9-8410-358f40153b96.png)
![screenshot_20190914_151925](https://user-images.githubusercontent.com/1413542/64913777-b3a01f80-d703-11e9-9928-5cd4d43aa731.png)

**Comment by Jon007** [comment]
Please include the version numbers and the WooCommerce status report.
Please answer the first two questions

**Comment by mindrunner** [comment]
Actually, the problem was solved by itself. It is working now. I do not know, what did the trick.
