### ISSUE TITLE
undefined index in Cart.php on line 188

### ISSUE THREAD

**Issue by nicmare** [hyyan/woo-poly-integration#466]
Notice: Undefined index: value in …r/wp-content/plugins/woo-poly-integration/src/Hyyan/WPI/Cart.php on line 188

change this:
if ($term && $term->name === $data['value']) {

to that:
if ($term && isset($data['value']) && $term->name === $data['value']) {

seems to fix the notice!

**Comment by Jon007** [comment]
that looks like a good candidate for a pull request!
