### ISSUE TITLE
Cart Subtotal does not change the currency

### ISSUE THREAD

**Issue by Dagsonmedia** [hyyan/woo-poly-integration#468]
Hi, I have two languages ​​and two currencies in the store. In the basket, the currency and price change correctly, but in Subtotal after changing the language the value remains from the previous one, and only the currency changes ... Everything updated and checked. Link to store:
https://zuaworld.com
Can anyone help?
Thank You!

**Comment by bpotocnak96** [comment]
Hi, is it open and actual?

**Comment by Dagsonmedia** [comment]
Yes, i still waiting for response or any help...

**Comment by bpotocnak96** [comment]
Could you assign me this issue? I'll try to solve it.

**Comment by Dagsonmedia** [comment]
How can I assign You?

**Comment by bpotocnak96** [comment]
Try this https://help.github.com/en/articles/assigning-issues-and-pull-requests-to-other-github-users

**Comment by Jon007** [comment]
this plugin does not do currency switching.
Currency and language are two separate concepts - this plugin can be used with currency switchers and there is some example about it in the documentation on the wiki.

This issues list is for issues about woo-poly-integration and when reporting issues the details requested on the issue template must be completed
