### ISSUE TITLE
Cart does not show variation image for variation products

### ISSUE THREAD

**Issue by Jon007** [hyyan/woo-poly-integration#47]
When a customer chooses a product variation, woocommerce shows the variation image (if exists) in the cart, to remind the customer what they chose.
This stops working if Hyyan woo-poly-integration 0.27 is activated.

Scenario:
1. On Woocommerce 2.6.4, Hyyan 0.27, Polylang  set up a product with variations and variation image 
2. Visit the site and select a product variation and add to cart
3. Visit cart page:  in the cart you see the product image not the product variation image
4. Deactivate Hyyan plugin and refresh cart:  product variation image is correctly shown
5. activate decarvalhoaa version from https://github.com/decarvalhoaa/woopoly/releases/tag/1.0.1
   - product variation image is also correctly shown
 
Similarly, if you do switch languages on the cart page, decarvalhoaa 1.01 shows correct variation image, Hyyan 0.27 does not.

**Comment by Jon007** [comment]
this may be linked with issue 15:
https://github.com/hyyan/woo-poly-integration/issues/15

there is some discussion and suggested variation fixes there and link to:
https://gist.github.com/mister/2e58e64a2c43b5a130d9/revisions
as well as a number of variation product issues fixed on decarvalhoaa branch

**Comment by decarvalhoaa** [comment]
@Jon007 I am in the process of porting my fix to Hyyan plugin. 

@hyyan You can assigned this to me, if you want.

**Comment by decarvalhoaa** [comment]
This is now fixed in the #67 new release 0.29 that I prepare for @hyyan with the bug-fixes I ported from my fork.
