### ISSUE TITLE
after uninstalling this plugin: 404 on checkout confirmation page

### ISSUE THREAD

**Issue by nicmare** [hyyan/woo-poly-integration#471]
`
### WordPress Environment ###

WordPress address (URL): http://help2buy.de
Site address (URL): http://help2buy.de
WC Version: 3.7.1
REST API Version: ✔ 1.0.2
Log Directory Writable: ✔
WP Version: 5.2.4
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: de_DE
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.2.20
PHP Post Max Size: 51 MB
PHP Time Limit: 180
PHP Max Input Vars: 1000
cURL Version: 7.29.0
NSS/3.36

SUHOSIN Installed: –
MySQL Version: 5.5.60-MariaDB
Max Upload Size: 50 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Dein Server verfügt nicht über eine lauffähige Version der SoapClient Klasse - einige Zahlungsschnittstellen
welche SOAP nutzen
funktionieren unter Umständen nicht korrekt.

DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.7.1
WC Database Prefix: yc_
Datenbank-Gesamtgröße: 8.60MB
Datenbank-Datengröße: 6.59MB
Datenbank-Indexgröße: 2.01MB
yc_woocommerce_sessions: Daten: 0.05MB + Index: 0.02MB + Engine InnoDB
yc_woocommerce_api_keys: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
yc_woocommerce_attribute_taxonomies: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
yc_woocommerce_downloadable_product_permissions: Daten: 0.02MB + Index: 0.06MB + Engine InnoDB
yc_woocommerce_order_items: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
yc_woocommerce_order_itemmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
yc_woocommerce_tax_rates: Daten: 0.02MB + Index: 0.06MB + Engine InnoDB
yc_woocommerce_tax_rate_locations: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
yc_woocommerce_shipping_zones: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
yc_woocommerce_shipping_zone_locations: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
yc_woocommerce_shipping_zone_methods: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
yc_woocommerce_payment_tokens: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
yc_woocommerce_payment_tokenmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
yc_woocommerce_log: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
yc_commentmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
yc_comments: Daten: 0.14MB + Index: 0.25MB + Engine InnoDB
yc_jckpc_inventory: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
yc_links: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
yc_options: Daten: 3.47MB + Index: 0.09MB + Engine InnoDB
yc_postmeta: Daten: 1.52MB + Index: 0.31MB + Engine InnoDB
yc_posts: Daten: 0.41MB + Index: 0.19MB + Engine InnoDB
yc_simple_history: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
yc_simple_history_contexts: Daten: 0.05MB + Index: 0.03MB + Engine InnoDB
yc_termmeta: Daten: 0.06MB + Index: 0.06MB + Engine InnoDB
yc_terms: Daten: 0.06MB + Index: 0.03MB + Engine InnoDB
yc_term_relationships: Daten: 0.09MB + Index: 0.08MB + Engine InnoDB
yc_term_taxonomy: Daten: 0.08MB + Index: 0.06MB + Engine InnoDB
yc_usermeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
yc_users: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
yc_wc_admin_notes: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
yc_wc_admin_note_actions: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
yc_wc_category_lookup: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
yc_wc_customer_lookup: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
yc_wc_download_log: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
yc_wc_order_coupon_lookup: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
yc_wc_order_product_lookup: Daten: 0.02MB + Index: 0.06MB + Engine InnoDB
yc_wc_order_stats: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
yc_wc_order_tax_lookup: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
yc_wc_product_meta_lookup: Daten: 0.02MB + Index: 0.09MB + Engine InnoDB
yc_wc_tax_rate_classes: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
yc_wc_webhooks: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
yc_yith_wapo_groups: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
yc_yith_wapo_types: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB

### Security ###

Secure connection (HTTPS): ❌
					Dein Shop benutzt kein HTTPS. Erfahre mehr über HTTPS und SSL-Zertifikate.
Hide errors from visitors: ❌Fehlermeldungen sollten Besuchern nicht angezeigt werden.

### Active Plugins (27) ###

Polylang Pro: von WP SYNTEX – 2.6.5
Admin Menu Editor Pro: von Janis Elsts – 2.6.4
Advanced Custom Fields PRO: von Elliot Condon – 5.8.5
Custom Order Numbers for WooCommerce: von Tyche Softwares – 1.2.9
Enable Media Replace: von ShortPixel – 3.3.6
Webcraftic Assets manager: von Webcraftic  – 1.0.7
WooCommerce Product Configurator by Iconic: von Iconic – 1.3.6 – Nicht getestest mit der aktiven WooCommerce-Version
Imsanity: von Exactly WWW – 2.4.3
Klarna Order Management for WooCommerce: von klarna
krokedil – 1.4.0

Klarna Payments for WooCommerce: von krokedil
klarna
automattic – 1.9.2

Password Protected: von Ben Huson – 2.2.5
Polylang for WooCommerce: von Frédéric Demarle – 1.2.2
Simple Custom Post Order: von Colorlib – 2.4.7
User Switching: von John Blackbourn und Mitwirkende – 1.5.2
WC Fields Factory: von Saravana Kumar K – 3.0.3 – Nicht getestest mit der aktiven WooCommerce-Version
Hyyan WooCommerce Polylang Integration: von Hyyan Abo Fakher – 1.4.3 – Nicht getestest mit der aktiven WooCommerce-Version
WPC Smart Quick View for WooCommerce: von WPclever.net – 1.2.9
Variation Swatches for WooCommerce: von Emran Ahmed – 1.0.63
WooCommerce Admin: von WooCommerce – 0.20.1
WooCommerce Expand Tabs: von Diana Burduja – 1.10
WooCommerce PayPal Checkout Gateway: von WooCommerce – 1.6.17
Germanized für WooCommerce: von Vendidero – 2.3.4
WooCommerce: von Automattic – 3.7.1
WP Filters Extras: von BeAPI – 1.0.2
WP Migrate DB Pro Theme & Plugin Files: von Delicious Brains – 1.0.5
WP Migrate DB Pro: von Delicious Brains – 1.9.8
Custom Product Tabs for WooCommerce: von YIKES
Inc. – 1.6.11 – Nicht getestest mit der aktiven WooCommerce-Version

### Inactive Plugins (14) ###

Akismet Anti-Spam: von Automattic – 4.1.2
Amazon Pay WooCommerce payment gateway: von Subhadeep Mondal – 2.7
Crop Thumbnails: von Volkmar Kantor – 1.2.5
Force Regenerate Thumbnails: von Pedro Elsner – 2.0.6
Image optimization service by Optimole: von Optimole – 2.2.1
PayPal PLUS for WooCommerce: von Inpsyde GmbH – 2.0.4 – Nicht getestest mit der aktiven WooCommerce-Version
Polylang: von WP SYNTEX – 2.6.5
Query Monitor: von John Blackbourn – 3.4.0
Simple History: von Pär Thernström – 2.32
Simply Show Hooks: von Stuart O'Brien
cxThemes – 1.2.1

WooCommerce Advanced Free Shipping: von Jeroen Sormani – 1.1.4 – Nicht getestest mit der aktiven WooCommerce-Version
WooCommerce Amazon Pay Gateway: von WooCommerce – 1.10.2
WooCommerce Services: von Automattic – 1.21.1
WP Migrate DB Pro Media Files: von Delicious Brains – 1.4.14

### Must Use Plugins (1) ###

WP Migrate DB Pro Compatibility: von Delicious Brains – 1.2

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: right_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop-Basis: #6 - /shop/
Warenkorb: #7 - /cart/
Kasse: #8 - /checkout/
Mein Konto: #9 - /my-account/
Allgemeine Geschäftsbedingungen: #22 - /agb/

### Theme ###

Name: 
Version: – 0 ist verfügbar
Author URL: 
Child Theme: ❌ – Wenn du WooCommerce mit einem Theme
das du nicht selbst entwickelt hast
an eigene Bedürfnisse anpasst
dann empfehlen wir die Verwendung eines Child-Themes. Siehe Wie du ein Child-Theme erstellst (engl.)

WooCommerce Support: ✔

### Templates ###

Overrides: –

### WC Pages Translations ###

Shop-Basis: ✔
Warenkorb: ✔
Kasse: ✔
Mein Konto: ✔

### Action Scheduler ###

Complete: 255
Oldest: 2019-09-30 09:14:10 +0200
Newest: 2019-10-30 16:16:34 +0100

Pending: 2
Oldest: 2019-10-30 17:16:34 +0100
Newest: 2019-10-30 17:16:34 +0100

Canceled: 0
Oldest: –
Newest: –

In-progress: 0
Oldest: –
Newest: –

Failed: 0
Oldest: –
Newest: –

`
as soon as i uninstall your plugin, i get a 404 error on last checkout page when success message should appear! what else you need from me to solve this issue? i uninstalled your plugin because i purchased polylang pro

**Comment by Jon007** [comment]
I assume this is fixed for you, as you commented on https://wordpress.org/support/topic/404-order-received-page-when-disabling-the-plugin/
"i enabled the plugin again and voila – 404 error is gone. Strange behaviour! i disabled it again and uninstalled. seems the error is gone forever. no 404"

nevertheless I'll leave this open - it may be that the plugin could hook some uninstall event and force refresh of permalinks

**Comment by Jon007** [comment]
closing as no further interest raised in this issue in last 8 months
