### ISSUE TITLE
woocommerce shop - product language assignment

### ISSUE THREAD

**Issue by plxmas** [hyyan/woo-poly-integration#472]
#### Can you reproduce this issue on default Wordpress theme (eg Storefront)?

yes.

#### Can you reproduce this issue when all other plugins are disabled except WooCommerce, Polylang and Hyyan WooCommerce Polylang Integration?

yes, the issue is here.

#### What product versions and settings are you using when this issue occurs?
* PHP: 7.3.10
* WordPress: 5.2.4
* WooCommerce: 3.7.1
* Polylang: 2.6.5, free
* Hyyan WooCommerce Polylang Integration: 1.4.3
* Browser: safari-firefox-chrome

#### Steps to Reproduce
1. I create a product in my shop, and I assign it to a primary language
2. I create a secondo, and assign it to a secondary language

#### What I Expected

I expect the product to be shown in the language of the correctly assigned store

#### What Happened Instead

 I see this two products in shop for primary language and none in secondary language

## WordPress Environment

<details>
```

Ambiente WordPress
--
Indirizzo WordPress (URL): |   | https://www.tigmaniac.com
Indirizzo sito (URL): |   | https://www.tigmaniac.com
Versione di WooCommerce: |   | 3.7.1
Pacchetto REST API di WooCommerce: |   | 1.0.2 /home/ttigmanz/public_html/wp-content/plugins/woocommerce/packages/woocommerce-rest-api
Cartella dei log scrivibile: |   | /home/ttigmanz/public_html/wp-content/uploads/wc-logs/
Versione di WordPress: |   | 5.2.4
Multisito WordPress: |   | –
Limite di memoria per WordPress: |   | 1 GB
Modalità di debug WordPress: |   | –
Cron WordPress: |   |  
Lingua: |   | it_IT
Cache esterna per gli oggetti: |   | –


```
</details>

**Comment by Jon007** [comment]
There isn't enough detail on this issue to be able to tell what is happening, but in general, create the product in primary language and translate the product using the plus symbols in the polylang box in the same way as you translate a post in polylang.
I see the site seems to be working now so I'll close this for now.
