### ISSUE TITLE
The Variation buttons are not translated, and my translated catagory doesn't work

### ISSUE THREAD

**Issue by custers-photography** [hyyan/woo-poly-integration#474]
Hello,
I made a website in Dutch and English. Later I installed Woocommerce for the sale pages.
I Installed yyan woocommerce polylang integration to get my sales pages translated to English.

But the Variation texts (like: sizes), doesn't translate. And the translated catagory page doesn't work.
I hope someone can help me please.

https://custers-photography.com/en/product/mother-earth-stop-digging-en

**Comment by Jon007** [comment]
use product attributes for translating the variations, see:
https://github.com/hyyan/woo-poly-integration/wiki/Product-Attributes

looks like you have already done it
