### ISSUE TITLE
Adding aditional Content to Email String translation

### ISSUE THREAD

**Issue by MELindley** [hyyan/woo-poly-integration#476]
Can you reproduce this issue on default Wordpress theme (eg Storefront)?

Yes: 
The additional content for emails is not added to string translations

#### Can you reproduce this issue when all other plugins are disabled except WooCommerce, Polylang and Hyyan WooCommerce Polylang Integration?
Yes

#### What product versions and settings are you using when this issue occurs?
* PHP: 7.2
* WordPress: 5.2.3
* WooCommerce: 3.7
* Polylang: free
* Hyyan WooCommerce Polylang Integration: 1.4.3
* Browser: All

I have added the additional_content field to the string translation by rewritting
 ```PHP
public function registerString($email_type, $sufix = '') 
 ```

and adding 
  ```PHP 
if (isset($settings['additional_content' . $sufix])) {
      pll_register_string('woocommerce_' . $email_type . '_additional_content' . $sufix, $settings['additional_content' . $sufix], __('WooCommerce Emails', 'woo-poly-integration'));
} 
```
 after the recipient field

It's a pretty easy fix, let me know if I should submit a pull request to add the feature :)

**Comment by Jon007** [comment]
yes you are correct there are some email related enhancements in recent woo commerce releases which are not yet added to the plugin, you are welcome to submit pull request

**Comment by Jon007** [comment]
I've added this in development and will check in after fixing a few related issues.
It's a complex subject so adding a note on it here: https://github.com/hyyan/woo-poly-integration/wiki/Email-Languages
