### ISSUE TITLE
Product arrtibutes and variations all grey and not editable in second language.

### ISSUE THREAD

**Issue by Niickp** [hyyan/woo-poly-integration#477]
Hi

I set product attribute and variation in the product page in main language. When I add the translated version of the product page, the attributes and variations section is grey and not clickable / editable, not allowing me to insert the variations in second language. What could I do?

PHP: 7.1.30
WordPress: i have to update to latest version, but I have the one right before
WooCommerce: 3.6.4
Polylang: 2.5.4 (free version)
Hyyan WooCommerce Polylang Integration: 1.4.3

**Comment by Jon007** [comment]
that's by design - variations must be added in the main language only, and when you save in main language they will be synchronised to the other languages.  If this is not happening, check if you have some error in the logs

**Comment by Niickp** [comment]
Hi, 
for some reason I couldn't see the flags of the languages in the attributes, so I thought I was doing something wrong, tried to refresh everything and now I see them, thank you for your response.

Kind regards,
Nick
