### ISSUE TITLE
Translated cart pages do not set DONOTCACHEPAGE

### ISSUE THREAD

**Issue by Jon007** [hyyan/woo-poly-integration#48]
Woocommerce currently sets:

```
                define( "DONOTCACHEPAGE", true );
```

for all dynamic pages such as cart, account etc.

This means that woocommerce dynamic pages are automatically excluded from WP Super Cache and any other tools that implement this.

However with woo-poly-integration activated this is not set on the translated versions of these pages, so the out-of-the-box behaviour is that translated cart pages get cached.

see:

```
    public static function prevent_caching() {
        if ( false === ( $wc_page_uris = get_transient( 'woocommerce_cache_excluded_uris' ) ) ) {
            $wc_page_uris   = array_filter( array_merge( self::get_page_uris( 'cart' ), self::get_page_uris( 'checkout' ), 
...
```

Testing suggests this may only apply to the Cart page - the Account page in different languages does not appear to get cached.

Apart from code fixes, the alternatives for WP Super Cache are:
- disable ALL page caching
- make sure you add ALL the slugs for all the translations to the exclude list (fragile to adding languages / changing slugs)

Also note that response headers are correctly set for translated cart page:

```
Cache-Control: no-cache, must-revalidate, max-age=0
Pragma: no-cache
```

it is just the DONOTCACHEPAGE which is missing.

Also tested, this is not fixed in fork decarvalhoaa 1.01.

**Comment by hyyan** [comment]
@Jon007 It will be a good idea to add support for WP Super Cache  plugin , I will add it to the my todo list

**Comment by hyyan** [comment]
@Jon007 would you like to work on this one?

**Comment by Jon007** [comment]
I think I did enough already :)
but yes I can look if it can wait until next week.

**Comment by hyyan** [comment]
Sure, thanks @Jon007 for your help  :), I will take a look at this

**Comment by Jon007** [comment]
retested and closed, this is a non-issue at least as far as WP Super Cache is concerned..
