### ISSUE TITLE
Problem with cart page

### ISSUE THREAD

**Issue by brigo92** [hyyan/woo-poly-integration#480]
Hi, I have a problem with the cart page.
My website is in Italian but when I switch to the English version and I add a product to the cart, the cart where I redirect is in the Italian version. I how I solve it?

**Comment by elidesign** [comment]
Hello! Did you fix the problem? The woocommerce endpoints are also displayed in English by me and I'm looking for a solution. Have you find a solution?

lg Elen

**Comment by Jon007** [comment]
1. check Endpoint settings in WooCommerce, Settings, Advanced /wp-admin/admin.php?page=wc-settings&tab=advanced
2. check Endpoint translations in Languages, Strings translations, WooCommerce Endpoints /wp-admin/admin.php?page=mlang_strings&s&group=WooCommerce+Endpoints&paged=1
3. go to Settings, Permalinks and Save Changes (even if there were no changes this will ensure the Permalinks are rebuilt and saved correctly)

then if there are further issues, please report with full details on the issue templates.
