### ISSUE TITLE
WooCommerce endpoints translation

### ISSUE THREAD

**Issue by elidesign** [hyyan/woo-poly-integration#481]
Thank you for the first time for the great plugin. It works great.

I have a question and hope someone ca help me.

How can the content of the Woocommerce pages, shopping cart, checkout, my account, ... be translated? For me, the via shortcode (example [woocommerce_cart]) integrated text is displayed in English.

lg Elena

**Comment by fkoomek** [comment]
Hi.
You have to make a translation of the Woocommerce pages in your desired language:
https://polylang.pro/doc/translating-pages-posts-categories-and-tags/
