### ISSUE TITLE
when i activate Hyyan WooCommerce Polylang Integration, admin panel menu goes to right , and all elements mess up in dashboard,please help me !!! i'm so confused.

### ISSUE THREAD

**Issue by kimiamousavi1995** [hyyan/woo-poly-integration#482]
#### What product versions and settings are you using when this issue occurs?
* PHP: 
* WordPress: 
* WooCommerce: 
* Polylang: [state if using Polylang PRO]
* Hyyan WooCommerce Polylang Integration: 
* Browser: 

#### Steps to Reproduce
1. 
1. 
1. 

## WordPress Environment

<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.
```
</details>

**Comment by kimiamousavi1995** [comment]
i deactivated all other plugins, but it has nothing to do with other plugins,also i dont have any console error!!!!!
i even tried it on other wordpress site with the same plugins installed but this only happens on my site

**Comment by Jon007** [comment]
Never seen that - try refreshing the screen.
When reporting issue please answer all the questions and provide the environment details requested as this is valuable information to understand possible compatibility issues etc.
