### ISSUE TITLE
Missing orders in Woocommerce back-office

### ISSUE THREAD

**Issue by adriensosa** [hyyan/woo-poly-integration#483]
Hi,

I’m using Hyyan WooCommerce Polylang Integration and I’m facing an issue with the plugin.
I have basically orders that don’t show up in the order section of the back-office. The total number in the status tab is correct but there isn’t as many order in the table below.
The reason is that the table is only displaying orders that have been placed in the store main language (can’t see FR and EN).

Any idea of how that could be fixed ?

Your help would be highly appreciated

Adrien

`
### WordPress Environment ###

WordPress address (URL): http://test.adriensosa.fr
Site address (URL): http://test.adriensosa.fr
WC Version: 3.9.0
REST API Version: ✔ 1.0.6
Log Directory Writable: ✔
WP Version: 5.3.2
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: es_ES
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.0.33 - Recomendamos usar la versión 7.2 o superior de PHP para un mayor rendimiento y seguridad. Cómo actualizar tu versión de PHP
PHP Post Max Size: 800 MB
PHP Time Limit: 1200
PHP Max Input Vars: 18000
cURL Version: 7.62.0
OpenSSL/1.0.2k

SUHOSIN Installed: –
MySQL Version: 5.6.47-cll-lve
Max Upload Size: 200 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Tu servidor no tiene la clase SoapClient activada - puede que algunos plugins de pasarela de pago que utilizan SOAP no funcionen como se espera.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.9.0
WC Database Prefix: wpeg_
Tamaño total de la base de datos: 45.42MB
Tamaño de los datos de la base de datos: 36.03MB
Tamaño del índice de la base de datos: 9.39MB
wpeg_woocommerce_sessions: Datos: 1.03MB + Índice: 0.05MB + Motor InnoDB
wpeg_woocommerce_api_keys: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wpeg_woocommerce_attribute_taxonomies: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wpeg_woocommerce_downloadable_product_permissions: Datos: 0.02MB + Índice: 0.06MB + Motor InnoDB
wpeg_woocommerce_order_items: Datos: 0.06MB + Índice: 0.02MB + Motor InnoDB
wpeg_woocommerce_order_itemmeta: Datos: 0.27MB + Índice: 0.27MB + Motor InnoDB
wpeg_woocommerce_tax_rates: Datos: 0.02MB + Índice: 0.06MB + Motor InnoDB
wpeg_woocommerce_tax_rate_locations: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wpeg_woocommerce_shipping_zones: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wpeg_woocommerce_shipping_zone_locations: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wpeg_woocommerce_shipping_zone_methods: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wpeg_woocommerce_payment_tokens: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wpeg_woocommerce_payment_tokenmeta: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wpeg_woocommerce_log: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wpeg_commentmeta: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wpeg_comments: Datos: 0.16MB + Índice: 0.09MB + Motor InnoDB
wpeg_duplicator_pro_entities: Datos: 0.01MB + Índice: 0.01MB + Motor MyISAM
wpeg_duplicator_pro_packages: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wpeg_elfsight_instagram_feed_widgets: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wpeg_ewwwio_images: Datos: 0.18MB + Índice: 0.13MB + Motor MyISAM
wpeg_ewwwio_queue: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wpeg_gp_glossaries: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wpeg_gp_glossary_entries: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wpeg_gp_meta: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wpeg_gp_originals: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wpeg_gp_permissions: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wpeg_gp_projects: Datos: 0.00MB + Índice: 0.01MB + Motor MyISAM
wpeg_gp_translations: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wpeg_gp_translation_sets: Datos: 0.00MB + Índice: 0.01MB + Motor MyISAM
wpeg_links: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wpeg_options: Datos: 3.06MB + Índice: 0.14MB + Motor InnoDB
wpeg_postmeta: Datos: 26.45MB + Índice: 7.03MB + Motor InnoDB
wpeg_posts: Datos: 3.48MB + Índice: 0.53MB + Motor InnoDB
wpeg_stock_log: Datos: 0.04MB + Índice: 0.02MB + Motor MyISAM
wpeg_termmeta: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wpeg_terms: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wpeg_term_relationships: Datos: 0.11MB + Índice: 0.08MB + Motor InnoDB
wpeg_term_taxonomy: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wpeg_toolset_associations: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wpeg_toolset_post_guid_id: Datos: 0.01MB + Índice: 0.03MB + Motor MyISAM
wpeg_toolset_relationships: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wpeg_toolset_type_sets: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wpeg_trp_gettext_es_es: Datos: 0.01MB + Índice: 0.02MB + Motor MyISAM
wpeg_ulp_campaigns: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wpeg_ulp_campaign_items: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wpeg_ulp_layers: Datos: 0.29MB + Índice: 0.00MB + Motor MyISAM
wpeg_ulp_popups: Datos: 0.05MB + Índice: 0.00MB + Motor MyISAM
wpeg_ulp_subscribers: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wpeg_ulp_targets: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wpeg_ulp_webfonts: Datos: 0.05MB + Índice: 0.01MB + Motor MyISAM
wpeg_usermeta: Datos: 0.16MB + Índice: 0.16MB + Motor InnoDB
wpeg_users: Datos: 0.02MB + Índice: 0.05MB + Motor InnoDB
wpeg_wc_download_log: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wpeg_wc_product_meta_lookup: Datos: 0.11MB + Índice: 0.20MB + Motor InnoDB
wpeg_wc_tax_rate_classes: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wpeg_wc_webhooks: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wpeg_wpml_mails: Datos: 0.05MB + Índice: 0.00MB + Motor MyISAM
wpeg_yoast_seo_links: Datos: 0.02MB + Índice: 0.01MB + Motor MyISAM
wpeg_yoast_seo_meta: Datos: 0.01MB + Índice: 0.01MB + Motor MyISAM

### Post Type Counts ###

attachment: 356
elementor_library: 6
nav_menu_item: 28
oembed_cache: 2
page: 46
polylang_mo: 3
post: 4
product: 99
product_variation: 895
revision: 744
scheduled-action: 3
shop_order: 166
shop_order_refund: 1
view: 1
view-template: 5
wp-types-group: 1

### Security ###

Secure connection (HTTPS): ❌
					Tu tienda no está usando HTTPS. Aprende más sobre HTTPS y los certificados SSL.
Hide errors from visitors: ✔

### Active Plugins (3) ###

Polylang: por WP SYNTEX – 2.6.9
Hyyan WooCommerce Polylang Integration: por Hyyan Abo Fakher – 1.4.3 – No probado con la versión activa de WooCommerce
WooCommerce: por Automattic – 3.9.0

### Inactive Plugins (34) ###

Astra Starter Sites: por Brainstorm Force – 1.4.5
Autoptimize: por Frank Goossens (futtta) – 2.6.1
Classic Editor: por WordPress Contributors – 1.5
Cookie Notice: por dFactory – 1.2.50
Duplicator Pro: por Snap Creek – 3.8.5
Elementor: por Elementor.com – 2.8.4
Elementor Pro: por Elementor.com – 2.5.9
Elfsight Instagram Feed CC: por Elfsight – 3.8.4
Enhanced E-commerce for Woocommerce store: por Tatvic – 2.3.0 – No probado con la versión activa de WooCommerce
Facebook for WooCommerce: por Facebook – 1.9.15 – No probado con la versión activa de WooCommerce
Jetpack by WordPress.com: por Automattic – 8.1
Kadence WooCommerce Email Designer: por Kadence WP – 1.3.11 – No probado con la versión activa de WooCommerce
Layered Popups: por Halfdata
Inc. – 6.60

Password Protected: por Ben Huson – 2.2.5
Really Simple SSL: por Rogier Lankhorst
Mark Wolters – 3.2.8

Redsys WooCommerce: por Redsys – 3.0.1 – No probado con la versión activa de WooCommerce
Toolset Types: por OnTheGoSystems – 3.3.4
Toolset Views: por OnTheGoSystems – 2.9.1
Toolset WooCommerce Views: por OnTheGoSystems – 2.7.10 – No probado con la versión activa de WooCommerce
UPS WooCommerce Shipping: por PluginHive – 3.13.1 – No probado con la versión activa de WooCommerce
Webcraftic Updates manager: por Webcraftic <wordpress.webraftic@gmail.com> – 1.1.1
WooCommerce Additional Variation Images: por WooCommerce – 1.7.16 – No probado con la versión activa de WooCommerce
WooCommerce Dynamic Pricing & Discounts: por RightPress – 2.3.3 – No probado con la versión activa de WooCommerce
WooCommerce Google Ads Conversion Tracking: por Wolf+Bär Agency – 1.6.2 – No probado con la versión activa de WooCommerce
WooCommerce Google Analytics Integration: por WooCommerce – 1.4.17
WooCommerce PayPal Checkout Gateway: por WooCommerce – 1.6.18 – No probado con la versión activa de WooCommerce
WooCommerce Price Based on Country (Basic): por Oscar Gare – 1.8.19 – No probado con la versión activa de WooCommerce
WooCommerce Services: por Automattic – 1.22.3
WooCommerce Stock Manager: por Vladislav Musílek – 2.0.2 – No probado con la versión activa de WooCommerce
WooCommerce Stripe Gateway: por WooCommerce – 4.3.1 – No probado con la versión activa de WooCommerce
WooSwatches - Woocommerce Color or Image Variation Swatches |  VestaThemes.com: por woomatrix – 2.5.0 – No probado con la versión activa de WooCommerce
WP Add Custom CSS: por Daniele De Santis – 1.1.5
WP Mail Logging: por MailPoet – 1.9.5
Yoast SEO: por Team Yoast – 12.9.1

### Must Use Plugins (1) ###

1&1 Product Subdomain: por 1&1 – 1.1.0

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: right
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Base de la tienda: #837 - /tienda
Carrito: #10 - /carrito
Finalizar compra: #11 - /finalizar-compra
Mi cuenta: #12 - /mi-cuenta
Términos y condiciones: #540 - /condiciones-generales-ventas

### Theme ###

Name: Twenty Twenty
Version: 1.1
Author URL: https://es.wordpress.org/
Child Theme: ❌ – Si estás modificando WooCommerce en un tema padre que no has creado personalmente
te recomendamos utilizar un tema hijo. Ver: Cómo crear un tema hijo

WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Completar: 3
Oldest: 2020-01-22 19:42:36 +0000
Newest: 2020-01-22 19:42:37 +0000

Pendiente: 0
Oldest: –
Newest: –

Cancelada: 0
Oldest: –
Newest: –

En curso: 0
Oldest: –
Newest: –

Fallida: 0
Oldest: –
Newest: –

**Comment by Jon007** [comment]
Hi, I assume you are referring to the Shop Orders screen in wp-admin.
This screen is filtered by Polylang language, same as the Posts, Pages, and Products screens.
To show all languages, use the language filter at the top of the screen or go to eg:
/wp-admin/edit.php?post_type=shop_order&lang=all

If you are referring to a different screen please reopen with more details/
