### ISSUE TITLE
Wholesale prices not translated/copied 

### ISSUE THREAD

**Issue by mhv75** [hyyan/woo-poly-integration#484]
I reproduced this issue on Storefront theme

Issue reproduced when Woocommerce, Polylang, Hyyan woocommerce Polylang integration and Woocommerce wholesale prices are activated

* PHP: 7.1
* WordPress: 5.3.2
* WooCommerce: 3.9.1
* Polylang: 2.6.9
* Hyyan WooCommerce Polylang Integration: 1.4.3
* Browser: Chrome and Safari

1. Updated all related plug ins after wordpress update produced this error
1. 
1. 

#### What I Expected

I expected updates to plugins to fix this issue and translate wholesale prices. Not the case

#### What Happened Instead
Translation failed

## WordPress Environment

<details>
`
### WordPress Environment ###

WordPress address (URL): https://homebydoor.com
Site address (URL): https://homebydoor.com
WC Version: 3.9.1
REST API Version: ✔ 1.0.7
Log Directory Writable: ✔
WP Version: 5.3.2
WP Multisite: –
WP Memory Limit: 768 MB
WP Debug Mode: –
WP Cron: ✔
Language: nl_NL
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.1.33 - We raden je aan om PHP-versie 7.2 of hoger te gebruiken voor betere prestaties en beveiliging. Hoe je PHP-versie bijwerken
PHP Post Max Size: 128 MB
PHP Time Limit: 120
PHP Max Input Vars: 3000
cURL Version: 7.59.0
OpenSSL/1.0.2r

SUHOSIN Installed: –
MySQL Version: 5.6.40-84.0-log
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.9.1
WC Database Prefix: wpy5_
Totale databasegrootte: 133.53MB
Database datagrootte: 85.55MB
Database index grootte: 47.98MB
wpy5_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpy5_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpy5_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpy5_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wpy5_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpy5_woocommerce_order_itemmeta: Data: 0.09MB + Index: 0.09MB + Engine InnoDB
wpy5_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wpy5_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpy5_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpy5_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpy5_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpy5_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpy5_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpy5_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpy5_berocket_termmeta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpy5_cartflows_ca_cart_abandonment: Data: 0.08MB + Index: 0.02MB + Engine InnoDB
wpy5_cartflows_ca_email_history: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpy5_cartflows_ca_email_templates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpy5_cartflows_ca_email_templates_meta: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpy5_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpy5_comments: Data: 0.13MB + Index: 0.09MB + Engine InnoDB
wpy5_crm_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpy5_crm_log_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpy5_erp_ac_banks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpy5_erp_ac_chart_classes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpy5_erp_ac_chart_types: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpy5_erp_ac_journals: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpy5_erp_ac_ledger: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpy5_erp_ac_payments: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpy5_erp_ac_tax: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpy5_erp_ac_tax_items: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpy5_erp_ac_transactions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wpy5_erp_ac_transaction_items: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpy5_erp_audit_log: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wpy5_erp_company_locations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpy5_erp_crm_activities_task: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpy5_erp_crm_contact_group: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpy5_erp_crm_contact_subscriber: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpy5_erp_crm_customer_activities: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wpy5_erp_crm_customer_companies: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpy5_erp_crm_save_email_replies: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpy5_erp_crm_save_search: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpy5_erp_hr_announcement: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpy5_erp_hr_dependents: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpy5_erp_hr_depts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpy5_erp_hr_designations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpy5_erp_hr_education: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpy5_erp_hr_employees: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wpy5_erp_hr_employee_history: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpy5_erp_hr_employee_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpy5_erp_hr_employee_performance: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpy5_erp_hr_holiday: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpy5_erp_hr_leaves: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpy5_erp_hr_leave_entitlements: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpy5_erp_hr_leave_policies: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpy5_erp_hr_leave_requests: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wpy5_erp_hr_work_exp: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpy5_erp_peoplemeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpy5_erp_peoples: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wpy5_erp_people_types: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpy5_erp_people_type_relations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpy5_failed_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpy5_icl_cms_nav_cache: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpy5_icl_content_status: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpy5_icl_core_status: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpy5_icl_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpy5_icl_languages: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpy5_icl_languages_translations: Data: 0.20MB + Index: 0.13MB + Engine InnoDB
wpy5_icl_locale_map: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpy5_icl_message_status: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpy5_icl_mo_files_domains: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpy5_icl_node: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpy5_icl_reminders: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpy5_icl_strings: Data: 5.52MB + Index: 8.98MB + Engine InnoDB
wpy5_icl_string_packages: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpy5_icl_string_pages: Data: 16.55MB + Index: 24.06MB + Engine InnoDB
wpy5_icl_string_positions: Data: 0.27MB + Index: 0.11MB + Engine InnoDB
wpy5_icl_string_status: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpy5_icl_string_translations: Data: 2.52MB + Index: 1.91MB + Engine InnoDB
wpy5_icl_string_urls: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wpy5_icl_translate: Data: 1.52MB + Index: 0.08MB + Engine InnoDB
wpy5_icl_translate_job: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpy5_icl_translations: Data: 0.28MB + Index: 0.78MB + Engine InnoDB
wpy5_icl_translation_batches: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpy5_icl_translation_status: Data: 1.52MB + Index: 0.05MB + Engine InnoDB
wpy5_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpy5_loginizer_logs: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpy5_mailchimp_carts: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wpy5_mailchimp_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpy5_options: Data: 5.14MB + Index: 0.25MB + Engine InnoDB
wpy5_podsrel: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wpy5_postmeta: Data: 41.55MB + Index: 7.03MB + Engine InnoDB
wpy5_posts: Data: 6.52MB + Index: 1.00MB + Engine InnoDB
wpy5_queue: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpy5_sbi_instagram_feeds_posts: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpy5_sbi_instagram_posts: Data: 0.14MB + Index: 0.00MB + Engine InnoDB
wpy5_termmeta: Data: 0.08MB + Index: 0.06MB + Engine InnoDB
wpy5_terms: Data: 0.09MB + Index: 0.11MB + Engine InnoDB
wpy5_term_relationships: Data: 0.39MB + Index: 0.34MB + Engine InnoDB
wpy5_term_taxonomy: Data: 0.13MB + Index: 0.11MB + Engine InnoDB
wpy5_tinvwl_analytics: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpy5_tinvwl_items: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpy5_tinvwl_lists: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpy5_usermeta: Data: 0.27MB + Index: 0.30MB + Engine InnoDB
wpy5_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpy5_wcpdf_invoice_number: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpy5_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpy5_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpy5_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpy5_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpy5_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpy5_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpy5_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wpy5_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpy5_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpy5_wc_product_meta_lookup: Data: 0.14MB + Index: 0.33MB + Engine InnoDB
wpy5_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpy5_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpy5_woof_query_cache: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpy5_wtbp_tables: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpy5_yoast_seo_links: Data: 0.09MB + Index: 0.05MB + Engine InnoDB
wpy5_yoast_seo_meta: Data: 0.31MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

acf-field: 154
acf-field-group: 37
attachment: 1851
block: 2
br_product_filter: 1
cartflows_flow: 1
cartflows_step: 1
custom_css: 5
elementor_font: 2
elementor_icons: 1
elementor_library: 24
et_pb_layout: 22
hbd: 2
homebyd: 19
howto: 1
jetpack_migration: 2
jp_img_sitemap: 3
jp_sitemap: 3
jp_sitemap_master: 3
nav_menu_item: 171
oembed_cache: 8
page: 88
polylang_mo: 4
post: 23
product: 270
product_variation: 636
revision: 2486
scheduled-action: 93
shop_order: 48
shop_order_refund: 1
wpforms: 1
wp_block: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (32) ###

Polylang: door WP SYNTEX – 2.6.9
ACF Content Analysis for Yoast SEO: door Thomas Kräftner
ViktorFroberg
marol87
pekz0r
angrycreative
Team Yoast – 2.3.0

Adminimize: door Frank Bültge – 1.11.6
Advanced Custom Fields: door Elliot Condon – 5.8.7
PublishPress Capabilities: door PublishPress – 1.9
Polylang Connect for Elementor: door David Decker - DECKERWEB – 1.0.0
Custom Icons for Elementor: door Michael Bourne – 0.3.1
Elementor Addons & Templates - Sizzify Lite: door ThemeIsle – 1.3.2
Elementor Pro: door Elementor.com – 2.8.3
Elementor: door Elementor.com – 2.8.5
EMS payments for WooCommerce: door emspay – 1.1.8 – Niet getest met de actieve versie van WooCommerce
EU Cookie Law: door Alex Moss
Marco Milesi – 3.1

Google Analytics for WordPress by MonsterInsights: door MonsterInsights – 7.10.4
Granular Controls Elementor: door Zulfikar Nore – 1.0.5
Jetpack door WordPress.com: door Automattic – 8.1.1
Loginizer: door Raj Kothari – 1.4.3
Mailchimp for WooCommerce: door Mailchimp – 2.3.1 – Niet getest met de actieve versie van WooCommerce
Nav Menu Roles: door Kathy Darling – 1.9.5
NavMenu Addon For Elementor: door ThemeIsle – 1.1.6
SG Optimizer: door SiteGround – 5.4.3
Orbit Fox Companion: door Themeisle – 2.9.1
TI WooCommerce Wishlist Plugin: door TemplateInvaders – 1.16.2
WooCommerce Cart Abandonment Recovery: door CartFlows Inc – 1.2.3 – Niet getest met de actieve versie van WooCommerce
Hyyan WooCommerce Polylang Integration: door Hyyan Abo Fakher – 1.4.3 – Niet getest met de actieve versie van WooCommerce
WooCommerce Admin: door WooCommerce – 0.25.0
WooCommerce PDF Invoices & Packing Slips: door Ewout Fernhout – 2.4.5
WooCommerce Services: door Automattic – 1.22.3
WooCommerce Wholesale Prices: door Rymera Web Co – 1.10 – Niet getest met de actieve versie van WooCommerce
WooCommerce: door Automattic – 3.9.1
Yoast SEO: door Team Yoast – 13.0
Category and Taxonomy Image: door Aftab Husain – 1.0.0
WPForms Lite: door WPForms – 1.5.8.2

### Inactive Plugins (27) ###

Admin Columns: door AdminColumns.com – 3.4.8
Advanced AJAX Product Filters for WooCommerce: door BeRocket – 1.4.1.5
Advanced Custom Fields Multilingual: door OnTheGoSystems – 1.4.0
Advanced Woo Search: door ILLID – 1.93
CartFlows: door CartFlows Inc – 1.3.5 – Niet getest met de actieve versie van WooCommerce
Check Email: door Chris Taylor – 0.5.6
Clean Login: door codection – 1.10
Custom Post Type UI: door WebDevStudios – 1.7.3
Dashboard Welcome for Elementor: door IdeaBox Creations – 1.0.4
Disable Gutenberg: door Jeff Starr – 2.0
Dynamic Visibility for Elementor: door Dynamic.ooo – 3.0.1
e-Boekhouden.nl: door e-Boekhouden.nl – 3.0.0
Elementor - Header, Footer & Blocks: door Brainstorm Force
Nikhil Chavan – 1.2.2

ElementsKit Lite: door Wpmet – 1.4.2
GDPR: door Trew Knowledge – 2.1.0
Image optimization service by Optimole: door Optimole – 2.2.8
Insert Headers and Footers: door WPBeginner – 1.4.4
MailChimp for WordPress Multilingual: door OnTheGoSystems – 0.0.3
Media Cleaner: door Jordy Meow – 5.5.4
Smash Balloon Instagram Feed: door Smash Balloon – 2.1.5
WooCommerce Login Popup and Shortcodes: door Phpbits Creative Studio – 1.0.2 – Niet getest met de actieve versie van WooCommerce
WooCommerce Show Single Variations by Iconic: door Iconic – 1.1.16 – Niet getest met de actieve versie van WooCommerce
WOOF - WooCommerce Products Filter: door realmag777 – 1.2.3 – Niet getest met de actieve versie van WooCommerce
WP-CRM: door Usability Dynamics
Inc. – 1.1.10

WP ERP: door weDevs – 1.5.12
WP ERP - PDF Invoice: door weDevs – 1.1.3
Yoast SEO Multilingual: door OnTheGoSystems – 1.0.2

### Must Use Plugins (1) ###

ET Support Center :: Must-Use Plugins Autoloader: door Elegant Themes –

### Settings ###

API Enabled: –
Force SSL: ✔
Currency: EUR (€)
Currency Position: left
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-catalog (exclude-from-catalog-en)
exclude-from-filtered (exclude-from-filtered)
exclude-from-search (exclude-from-search)
exclude-from-search (exclude-from-search-en)
featured (featured)
featured (featured-en)
outofstock (outofstock)
outofstock (outofstock-en)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Winkelbasis: #2557 - /en/all-products/
Winkelmand: #3067 - /winkelmandje/
Afrekenen: #3070 - /afrekenen/
Mijn account: #3033 - /mijn-account/
Algemene voorwaarden: #1624 - /algemene-voorwaarden/

### Theme ###

Name: GeneratePress Child
Version: 0.1
Author URL: https://tomusborne.com
Child Theme: ✔
Parent Theme Name: GeneratePress
Parent Theme Version: 2.4.1
Parent Theme Author URL: https://tomusborne.com
WooCommerce Support: ✔

### Templates ###

Overrides: generatepress_child/woocommerce/emails/admin-cancelled-order.php

### TI WooCommerce Wishlist Templates ###

Overrides: –

### Action Scheduler ###

Afgerond: 67
Oldest: 2020-01-07 16:15:04 +0100
Newest: 2020-02-06 11:20:17 +0100

In afwachting: 2
Oldest: 2020-02-06 12:20:17 +0100
Newest: 2020-02-11 16:27:01 +0100

Geannuleerd: 24
Oldest: 2020-01-08 00:30:50 +0100
Newest: 2020-01-29 17:50:13 +0100

In behandeling: 0
Oldest: –
Newest: –

Mislukt: 0
Oldest: –
Newest: –

`
</details>

**Comment by Jon007** [comment]
This plugin only provides a compatibility layer between the WooCommerce plugin itself and the Polylang plugin.
Other plugins like WooCommerce wholesale prices might need their own compatibility layer with Polylang and translations.

If it is just an extra field for wholesale prices, it is actually quite easy to control whether the additional field is synchronised to translations, there is some documentation with an example here: https://github.com/hyyan/woo-poly-integration/wiki/Product-Meta-and-Custom-Fields
