### ISSUE TITLE
Products block on multilanguage products modifications 

### ISSUE THREAD

**Issue by mabeleira** [hyyan/woo-poly-integration#485]
I'm having an issue when adding or modifying products, if i don't remove the field block during the modifications products appear blocked, don't know if this is an issue or me doing something wrong.

Thanks in advance.

#### What product versions and settings are you using when this issue occurs?
* PHP: 
* WordPress: 
* WooCommerce: 
* Polylang: [state if using Polylang PRO]
* Hyyan WooCommerce Polylang Integration: 
* Browser: 

#### Steps to Reproduce
1. 
1. 
1. 

## WordPress Environment

<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.
```
</details>

**Comment by Jon007** [comment]
No work has been done to support the Products block, however this Issue report does not contain the necessary details about the environment and issue to be able to action.
