### ISSUE TITLE
URL Product category 404 

### ISSUE THREAD

**Issue by cicileu** [hyyan/woo-poly-integration#486]
Hello, I have a problem with the Product category URL.
I switch on the product category translation in the WooPoly Settings, than I created 3 categories, one for each supported language (en, it, es). The categories are correctly show in the menu.
But when I click a category menu, it redirect to an URL like this: "/en/product-category/pies/" receiving a 404 error.
What I miss? Thanks

**Comment by Jon007** [comment]
Hi, check the category translations are linked and go to Settings, Permalink and Save Changes.
Can't suggest more than that from report but if that doesn't work  open issue with more details

**Comment by 01202581905** [comment]
> Hi, check the category translations are linked and go to Settings, Permalink and Save Changes.
> Can't suggest more than that from report but if that doesn't work open issue with more details

Thanks for support 🥉
