### ISSUE TITLE
WordPress Dashboard Direction Switched

### ISSUE THREAD

**Issue by hassandayem** [hyyan/woo-poly-integration#487]
#### What product versions and settings are you using when this issue occurs?
* PHP: 7.3
* WordPress: 5.3
* WooCommerce: 3.9
* Polylang: [state if using Polylang PRO] free version 2.6.10
* Hyyan WooCommerce Polylang Integration: 1.4.3
* Browser: Brave Version 1.4.96 Chromium: 80.0.3987.132 (Official Build) (64-bit)

#### Steps to Reproduce

1. Install Polylang
2. add 3 languages (Arabic, English, German)
3. Make Arabic default website's language
4. Install Woocommerce
5. Install WooPoly
6. Navigate to plugins or settings

#### What I Expected
Wordpress dashboard still as normal

#### What Happened Instead
WordPress Dashboard Direction Switched
please have a look at this [screenshot](https://prnt.sc/rcvbsh)
And sometimes this [what happens](https://prnt.sc/rcvc7w)
And it still even if we make website's default language LTR like English

## WordPress Environment
<details>

- I have 3 different languages, 2 LTR (English and German) and 1 RTL (Arabic).
- The website’s default language is English.
- Admin language is English.

```
WooCommerce version: |   | 3.9.3
WordPress version: |   | 5.3.2
WordPress memory limit: |   | 768 MB
Language: |   | en_US

##Server environment
Server info: |   | Apache
PHP version: |   | 7.3.15
PHP post max size: |   | 128 MB
PHP time limit: |   | 120
PHP max input vars: |   | 3000
cURL version: |   | 7.66.0, OpenSSL/1.1.1d-fips
SUHOSIN installed: |   | –
MySQL version: |   | 5.7.25-28-log
Max upload size: |   | 128 MB

WooCommerce database version: |   | 3.9.3
-- | -- | --
Active plugins (17)
--
Polylang |   | by WP SYNTEX – 2.6.10
Advanced Custom Fields PRO |   | by Elliot Condon – 5.8.8
Advanced Custom Fields |   | by Elliot Condon – 5.8.8
CMP - Coming Soon & Maintenance Plugin |   | by NiteoThemes – 3.7.0
Custom Post Type UI |   | by WebDevStudios – 1.7.3
Easy Theme and Plugin Upgrades |   | by Chris Jean – 2.0.1
Editor Enhancer for Oxygen |   | by Ukuwi – 1.1.2
Frontend Gallery Slider For Advanced Custom Field |   | by WP OnlineSupport – 1.4
Insert Headers and Footers |   | by WPBeginner – 1.4.5
LTR RTL Admin content |   | by Ronny Sherer – 0.5.1
Oxygen Repeater Fix (Duplicated IDs) |   | by Fadlul Alim – 1.3.2
Oxygen Elements for WooCommerce |   | by Soflyy – 1.2 – Not tested with the active version of WooCommerce
Oxygen |   | by Soflyy – 3.2
OxyPowerPack |   | by Emmanuel Laborin – 1.0.8.2
SG Optimizer |   | by SiteGround – 5.4.4
Hyyan WooCommerce Polylang Integration |   | by Hyyan Abo Fakher – 1.4.3 – Not tested with the active version of WooCommerce
WooCommerce |   | by Automattic – 3.9.3
```
</details>

**Comment by Jon007** [comment]
Noting also:
https://wordpress.org/support/topic/wordpress-dashboard-direction-switched/
It sounds like switching languages does not always switch the text direction properly.
If you can find any particular evidence of when this happens, any trace from the php error logs please reopen on github.

**Comment by Jon007** [comment]
On reflection, the admin language switching is a WordPress native function, not related to this plugin or Polylang, though it may be worth asking Polylang if this problem still exists.
This plugin itself only handles the compatibility between Polylang and WooCommerce, these and WordPress itself already provide the language files and basis for language switching.
