### ISSUE TITLE
Message about the plugin

### ISSUE THREAD

**Issue by mstudioIL** [hyyan/woo-poly-integration#488]
I got this message:
"shop page in language en_US was not found and must be created for the shop to work in this language: this will be done automatically if Check WooCommerce Pages option is enabled in Settings"

what it is mean?
I using other page for the shop, because I  have different layout
I the plugin works with Elementor?

**Comment by Jon007** [comment]
It is advisable that the standard WooCommerce pages should exist because other plugins may refer to them.
Whatever page you are using to handle the shop etc must also be translated with Polylang.

We will reduce the number of messages, this is already being tracked under a separate issue #462
