### ISSUE TITLE
WooCommerce 4.0

### ISSUE THREAD

**Issue by mstudioIL** [hyyan/woo-poly-integration#489]
Will the plugin work with WooCommerce 4.0?

**Comment by Jon007** [comment]
as per https://wordpress.org/support/topic/compatible-with-woocommerce-4-0-3/
No major upgrade compatibility issues have been reported, but of course no specific translation support has been added for any new features such WooCommerce blocks, Analytics, Marketing or other new developments.
If you have a specific issue to raise please raise it with full details, there is no advantage in keeping multiple unspecific woo 4.x issues open..
