### ISSUE TITLE
Woocommerce 4.0

### ISSUE THREAD

**Issue by amertre** [hyyan/woo-poly-integration#490]
hi, update to WooCommerce 4.0,  I have problems with my website, it takes a long time to load and it doesn't work correctly, today wordpress sent me an email "WordPress has detected an error with one of your plugins: Hyyan WooCommerce Polylang Integration" please i need your help with updating this plugin to solve the problem.
thanks

**Comment by joakimif** [comment]
Is there any progress on the compatibility? It has been a long time since WooCommerce 4.0 was released now, and the newest version is 4.1.0 at the time of writing. Versions < 4.1.0 are also vulnerable to XSS (https://wpvulndb.com/vulnerabilities/10220).

**Comment by Jon007** [comment]
as per https://wordpress.org/support/topic/compatible-with-woocommerce-4-0-3/
No major upgrade compatibility issues have been reported, but of course no specific translation support has been added for any new features such WooCommerce blocks, Analytics, Marketing or other new developments.
If you have a specific issue to raise please raise it with full details, there is no advantage in keeping multiple unspecific woo 4.x issues open..
