### ISSUE TITLE
Can't change product properties if product is not available in the default language

### ISSUE THREAD

**Issue by stentibbing** [hyyan/woo-poly-integration#491]
Hi

Product properties can only be changed for products in default languages which is a problem since in my customer's shop some products or services are for foreign customers only. And vice versa, some products or services are only for domestic customers. So my customer can not change products' properties if the product does not exist in the default language.

Thanks!

**Comment by stentibbing** [comment]
Hi!

Solved by enabling synced settings for each language. Turned out the problem is that menu order is not syncing between languages.

Thanks!

**Comment by mklusak** [comment]
Hi @stentibbing, could you please elaborate a little bit more about  "enabling synced settings for each language" ? I am dealing with the excact same problem like you and can't get it to work.
