### ISSUE TITLE
How to change order of products in translated page?

### ISSUE THREAD

**Issue by cinnig** [hyyan/woo-poly-integration#494]
Hi,

I love the plugin and it's working very well. I do have one issue, I would like to change the order of the products on the translated page but this is not possible. I can change it for the original language in Woocommerce/Products/Product data/Advanced/Menu order but this Product data field can't be changed in the translated page and it is not automatically following the order of products on the original language page. 

I have Storefront childs theme, Woocommerce 4.0.1 and Hyyan WooCommerce Polylang Integration 1.4.3. (not using Polylang Pro).

https://www.cinnig.com/product-category/men/  (original language)
https://www.cinnig.com/nl/product-category/heren/  (translated page)

I would like to start on the dutch page with 'Rookie Dad' tee as well. Hope you can help me out.

#### What product versions and settings are you using when this issue occurs?
* PHP: 
* WordPress: 
* WooCommerce: 
* Polylang: [state if using Polylang PRO]
* Hyyan WooCommerce Polylang Integration: 
* Browser: 

#### Steps to Reproduce
1. 
1. 
1. 

## WordPress Environment

<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.
```
</details>

**Comment by Jon007** [comment]
Hi, you haven't provided all the details, however if you want the ordering to be different in each language, please turn off the synchronisation of the Order meta in both Polylang and WooPoly, see the wiki here:: https://github.com/hyyan/woo-poly-integration/wiki/Settings-Metas

it may be necessary to turn off both:
- Settings, WooPoly, Menu Order
- Languages, Settings, Synchronisation, Page Order

then the order is editable on the translations without affecting the other languages
