### ISSUE TITLE
Problem multiple languages in Estore from themegrill

### ISSUE THREAD

**Issue by MarcoM06** [hyyan/woo-poly-integration#496]
Hello
Our website is multiple languages.
Now I don’t get the text in the Header Top Bar bilingual. 
(I use Polylang and Hyyan WooCommerce Polylang)

regards
Marco

**Comment by Jon007** [comment]
Hi, I do not know what you mean by "don’t get the text in the Header Top Bar bilingual"
when reporting the problem please provide more details including all the details requested in the issue template.
This plugin is only supported by unpaid volunteers in their spare time so please provide all information which might be needed.
