### ISSUE TITLE
🚨Product attributes keep disappearing randomly

### ISSUE THREAD

**Issue by brmdbr** [hyyan/woo-poly-integration#498]
#### Can you reproduce this issue on default Wordpress theme (eg Storefront)?
Yes
#### Can you reproduce this issue when all other plugins are disabled except WooCommerce, Polylang and Hyyan WooCommerce Polylang Integration?
Don't know
#### What product versions and settings are you using when this issue occurs?
* PHP: 7.0.33
* WordPress: 5.2.6
* WooCommerce: 3.7.0
* Polylang: latest
* Hyyan WooCommerce Polylang Integration: latest
* Browser: not browser related

#### What Happened Instead
Product attributes keep disappearing randomly. Once in awhile product attributes of the original product disappear. Its like something goes wrong in a sync and products disappear.  Sometimes it takes months, sometimes a few days.

The attributes can't be chosen in the product page so we can't sell these products.. And there is no way for us to find out when it happens .

It has happened at least 5 times now, the click fix is to open a product and just click update without changing anything.

**Comment by Jon007** [comment]
I haven't seen this happen (running for thousands of products across three languages) so we need a specific example.
Most likely there is a bad update in the admin interface by one of the shop managers, I would suggest to turn debug logging on ie in wp-config.php

```
define( 'WP_DEBUG', true );
define( 'WP_DEBUG_LOG', true );
define( 'WP_DEBUG_DISPLAY', false );
```

check what is happening in the error logs, and when you find specific related error open an new issue with the debug stack trace and your WooCommerce status report (which is also missing from this issue)
