### ISSUE TITLE
Custom Taxonomy, unit problem

### ISSUE THREAD

**Issue by MarcoM06** [hyyan/woo-poly-integration#499]
Hello
I use Germanized and  we have the Custom Taxonomy option Unit (€ 3,50/ 100 ml).
This has always worked well, Till know.
On the dutch version i select ml but dont show up, but on the gernam version its works well and show ML
Germanized thinks the problem is the translation.

Who have a solution?

Thanks
Marco

 

#### What product versions and settings are you using when this issue occurs?
* PHP: 
* WordPress: 
* WooCommerce: 
* Polylang: [state if using Polylang PRO]
* Hyyan WooCommerce Polylang Integration: 
* Browser: 

#### Steps to Reproduce
1. 
1. 
1. 

## WordPress Environment

<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.
```
</details>

**Comment by Jon007** [comment]
This report is missing plugin versions, WooCommerce System Status etc
Also this plugin only directly addresses Polylang compatibility layer for the WooCommerce plugin layer itself. As a free plugin it cannot offer support for any and all WooCommerce extensions.
Other plugins may need their own compatibility layer.  The authors of WooCommerce Germanized are aware of this and have contributed to this plugin previously so I would suggest referring back to them.

Apart from that, check that you have attribute translation turned on and enabled for the specific product category as per https://github.com/hyyan/woo-poly-integration/wiki/Product-Attributes
