### ISSUE TITLE
Variation Attribute not synced

### ISSUE THREAD

**Issue by phoenix4rmhell** [hyyan/woo-poly-integration#5]
Hello Hyyan,

Thanks for the awesome plugin. 
There is a problem with variable product attribute when creating the copy of the product variations for another language. The meta 'attribute_' is not synced. All the other metas are being copied except the main attribute. 
I'm a new developer and as far as I've looked into it the problem seems to be in
File: src/Hyyan/WPI/product/variation.php
Function: protected function copyVariationMetas($from, $to){...}

the array $translated is always empty so the value is not getting copied. I'm not sure if that is the problem or I'm doing something wrong. Can you check that please?

Regards,
Akash Kanojia

**Comment by hyyan** [comment]
@phoenix4rmhell I don't think the problem is in the function logic here ,  you an do two things to make sure :

After disabling all plugin in your site except for `this one` and `(ploylang , WooCommerce)` : 

*  Make sure the attribute sync is enabled in the plugin settings page / Meta tab , 
*  Enable the Synchronization for taxonomies in polylang settings page

If non of that worked for you and that might be strange , add this function somewhere in your theme funciton file then navigate to your post in default language in the wp admin and paste the result you see here please .


```php
add_action('admin_ini', function() {

    var_dump(@$_GET['post']);
});
```

**Comment by phoenix4rmhell** [comment]
Hello Hyyan!

Thanks for the quick reply.

I've tried the solutions you mentioned above
1) disable all plugins then check
2) enabled Sync for all attributes on woo-poly metas list
2) Enabled Synchronization fro taxonomies

Still its not working.
After that I tried the same with a fresh WP install
installed only the required plugins (Used Storefront Theme)

Still the same issue.
I even checked the DB (wp_postmeta table)
only the original post (post in default language that I create) has the meta_key = attribute_size attached with it. The variations created by woo-poly has other meta_key(s) but not attribute_size key.

Product Variation Tabs for Default Language:
![default](https://cloud.githubusercontent.com/assets/1804872/8242101/ae62715e-15b9-11e5-99ef-a4da1722cd0d.png)

Product Variation Tabs for Second Language:
![second](https://cloud.githubusercontent.com/assets/1804872/8242104/b1fa77d0-15b9-11e5-8cef-01ccd273dc33.png)


You can reproduce the problem easily. I've tried my best to explain the issue. Still I don't know if I'm doing something wrong. And yes I selected default language before adding variable product (any product).

Can you check if the issue is in plugin or I'm making any mistake?

Thanks for the help!
Regards,
Akash Kanojia

**Comment by phoenix4rmhell** [comment]
Just for the test I tried adding some code in 
`src\Hyyan\WPI\Product\Variation.php`

in function 
```php
    protected function copyVariationMetas($from, $to){...}
```
if I change this code
```php
    foreach ($metas[$key] as $termSlug) {
        $term = get_term_by('slug', $termSlug, $tax);
        if ($term) {
            $lang = isset($_GET['new_lang']) ? esc_attr($_GET['new_lang']) : pll_get_post_language($this->to->id);
            $translated[] = get_term_by('id', pll_get_term($term->term_id, $lang), $tax)->slug;
        }
    }
```

to:

```php
    foreach ($metas[$key] as $termSlug) {
        $term = get_term_by('slug', $termSlug, $tax);
        if ($term) {
            $lang = isset($_GET['new_lang']) ? esc_attr($_GET['new_lang']) : pll_get_post_language($this->to->id);
            $translated[] = get_term_by('id', pll_get_term($term->term_id, $lang), $tax)->slug;
        }else{
            $translated[] = $termSlug;
        }
    }
```

then it starts working fine.

**Comment by hyyan** [comment]
@phoenix4rmhell thank you for the great effort in explaining the issue , but I have to ask you this question to make sure before I go any deeper in this issue , have you translated the attributes you are using to generate the variations ? as it seems in the photos , you did not ? am I right ?

**Comment by phoenix4rmhell** [comment]
@hyyan I'm not sure how to translate the attributes. Is there any interface to translate the attributes on admin section or do I have to add the translation for attributes in translation files?
I've checked the woo-poly settings and polylang settings and I can't find the interface to translate the attributes. Can you guide me how to do that?

**Comment by hyyan** [comment]
phoenix4rmhell  The plugin does not create any new interface , but it uses the current avaliable woocommere and polylang interface. 

To translate you interface follow this steps in the images below : 

![fireshot capture - attributes woo wordpress_ - http___woo localhost com_wp-admin_edit php](https://cloud.githubusercontent.com/assets/4313420/8249020/bef37b74-161a-11e5-8247-b7d284acd23e.png)

![fireshot capture - attributes woo wordpress_ - http___woo localhost com_wp-admin_edit php](https://cloud.githubusercontent.com/assets/4313420/8249062/472e11fc-161b-11e5-9f23-80c6ee50dad6.png)

![ds](https://cloud.githubusercontent.com/assets/4313420/8249143/fbeaf09c-161b-11e5-8c5f-a89c85b7fc64.png)

![fireshot capture - add attribute name here woo _ - http___woo localhost com_wp-admin_edit-tags php](https://cloud.githubusercontent.com/assets/4313420/8249145/072ea174-161c-11e5-98ce-866210cd4f35.png)

if you have created attributes when you created your product in the default language , then go on and translate you created attributes in the same interface before you start creating translation for your product .

Hope that helps !

**Comment by phoenix4rmhell** [comment]
@hyyan Thank you very much for the support. I didn't know about attribute translation. Everything seems to be working fine now.
Thanks again for the plugin.

**Comment by hyyan** [comment]
@phoenix4rmhell  you are more than welcome , and please do not hesitate to ask more questions , I always be here to help .

**Comment by dharamgoyal** [comment]
Hello,
Not getting woocommerce product attribute in hindi while use hinidi code(hi) with REST API also using polylang and your plugin

**Comment by raynov** [comment]
Hi guys,
The above code didn't do it for me either. I figured must be because the attributes names and slugs are in cyrillic. So I changed the code in 
`protected function copyVariationMetas($from, $to) {..} `
as follows:
`$tax = str_replace('attribute_', '', $key); `
to
`$tax = urldecode(str_replace('attribute_', '', $key));`
and
`$term = get_term_by('slug', $termSlug, $tax);`
to
`$term = get_term_by('slug', urldecode($termSlug), $tax);`

@dharamgoyal  suppose this helps with hindi too

**Comment by bgmeet** [comment]
Hello Hyyan,
Hello,

everything work perfect except that when translate product the new translated product come absolute empty. Only the name and product description is translated. Noting more. Noting more inside.

Price, attributes, Taxes, even image is empty.

I have about 1900 products if i must add those attributes manual will cost me months.

Look examle:

Upload photos.

Any advice will be most welcome:

Thx in advanced:

Kind Regards:

Venetta


![original product](https://cloud.githubusercontent.com/assets/12895037/22404650/0bde4028-e63e-11e6-83f6-73aed23c2b86.jpg)
![original product2](https://cloud.githubusercontent.com/assets/12895037/22404649/0bde1314-e63e-11e6-85d7-e44847a2bd6d.jpg)
![translated product](https://cloud.githubusercontent.com/assets/12895037/22404651/0bdfe91e-e63e-11e6-9324-d9f7d9b4c3b4.jpg)
![translated product1](https://cloud.githubusercontent.com/assets/12895037/22404648/0bddadc0-e63e-11e6-84fe-43a4c03c75e2.jpg)
![translated product2](https://cloud.githubusercontent.com/assets/12895037/22404647/0bdd9704-e63e-11e6-824b-d6a1dcef3450.jpg)
