### ISSUE TITLE
When I create the translation of a product, an error 500 is generated

### ISSUE THREAD

**Issue by gorkatolosa** [hyyan/woo-poly-integration#500]
When I am going to create the translation of a product, an error 500 is generated. From my hosting provider they indicate that it is a Woocommerce compatibility problem with the language plugin- The website is from a client and you need to be able to solve the error to continue introducing the translations of the products. When trying to create a new product in the default language of the website (in this case Spanish) the error does not occur.

As a wordpress theme I am using Avada 6.2.3

#### What product versions and settings are you using when this issue occurs?
* PHP: 7.2.15
* WordPress: 5.4.2
* WooCommerce: 4.2.0
* Polylang: 2.7.3
* Hyyan WooCommerce Polylang Integration: 1.4.3
* Browser: Mozilla Firefox 77.0.1 (64-bit)

#### Steps to Reproduce
1. Products > All Products 
2. Press the button with the + symbol in the column with the flag of the language you want to add or edit 

#### What I Expected
Edit or create a new translation of a product

#### What Happened Instead
Error 500 Internal Server Error

## WordPress Environment

<details>
`
### WordPress Environment ###

WordPress address (URL): https://www.monopensador.com
Site address (URL): https://www.monopensador.com
WC Version: 4.2.0
REST API Version: ✔ 1.0.8
WC Blocks Version: ✔ 2.5.16
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 1.2.3
Log Directory Writable: ✔
WP Version: 5.4.2
WP Multisite: –
WP Memory Limit: 1 GB
WP Debug Mode: –
WP Cron: ✔
Language: es_ES
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.2.15
PHP Post Max Size: 256 MB
PHP Time Limit: 300
PHP Max Input Vars: 8000
cURL Version: 7.26.0
OpenSSL/1.0.1t

SUHOSIN Installed: –
MySQL Version: ❌ 5.5.60-0+deb7u1-log - Recomendamos como versión mínima de MySQL la 5.6. Ver: Requisitos de WordPress
Max Upload Size: 256 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.2.0
WC Database Prefix: tmonkey_
Tamaño total de la base de datos: 162.57MB
Tamaño de los datos de la base de datos: 105.18MB
Tamaño del índice de la base de datos: 57.39MB
tmonkey_woocommerce_sessions: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
tmonkey_woocommerce_api_keys: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
tmonkey_woocommerce_attribute_taxonomies: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
tmonkey_woocommerce_downloadable_product_permissions: Datos: 0.02MB + Índice: 0.06MB + Motor InnoDB
tmonkey_woocommerce_order_items: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
tmonkey_woocommerce_order_itemmeta: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
tmonkey_woocommerce_tax_rates: Datos: 0.02MB + Índice: 0.06MB + Motor InnoDB
tmonkey_woocommerce_tax_rate_locations: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
tmonkey_woocommerce_shipping_zones: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
tmonkey_woocommerce_shipping_zone_locations: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
tmonkey_woocommerce_shipping_zone_methods: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
tmonkey_woocommerce_payment_tokens: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
tmonkey_woocommerce_payment_tokenmeta: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
tmonkey_woocommerce_log: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
tmonkey_actionscheduler_actions: Datos: 0.02MB + Índice: 0.11MB + Motor InnoDB
tmonkey_actionscheduler_claims: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
tmonkey_actionscheduler_groups: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
tmonkey_actionscheduler_logs: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
tmonkey_aws_index: Datos: 4.14MB + Índice: 2.61MB + Motor InnoDB
tmonkey_commentmeta: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
tmonkey_comments: Datos: 0.02MB + Índice: 0.09MB + Motor InnoDB
tmonkey_links: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
tmonkey_options: Datos: 13.02MB + Índice: 2.16MB + Motor InnoDB
tmonkey_page_visit_history: Datos: 4.52MB + Índice: 0.00MB + Motor InnoDB
tmonkey_page_visit_referer: Datos: 0.09MB + Índice: 0.00MB + Motor InnoDB
tmonkey_page_visit_wizard: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
tmonkey_postmeta: Datos: 48.39MB + Índice: 37.70MB + Motor InnoDB
tmonkey_posts: Datos: 10.11MB + Índice: 4.56MB + Motor InnoDB
tmonkey_revslider_css: Datos: 0.14MB + Índice: 0.00MB + Motor InnoDB
tmonkey_revslider_css_bkp: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
tmonkey_revslider_layer_animations: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
tmonkey_revslider_layer_animations_bkp: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
tmonkey_revslider_navigations: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
tmonkey_revslider_navigations_bkp: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
tmonkey_revslider_sliders: Datos: 0.06MB + Índice: 0.00MB + Motor InnoDB
tmonkey_revslider_sliders_bkp: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
tmonkey_revslider_slides: Datos: 0.23MB + Índice: 0.00MB + Motor InnoDB
tmonkey_revslider_slides_bkp: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
tmonkey_revslider_static_slides: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
tmonkey_revslider_static_slides_bkp: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
tmonkey_smush_dir_images: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
tmonkey_termmeta: Datos: 0.09MB + Índice: 0.03MB + Motor InnoDB
tmonkey_terms: Datos: 0.06MB + Índice: 0.03MB + Motor InnoDB
tmonkey_term_relationships: Datos: 3.03MB + Índice: 2.05MB + Motor InnoDB
tmonkey_term_taxonomy: Datos: 0.08MB + Índice: 0.03MB + Motor InnoDB
tmonkey_usermeta: Datos: 0.05MB + Índice: 0.03MB + Motor InnoDB
tmonkey_users: Datos: 0.02MB + Índice: 0.05MB + Motor InnoDB
tmonkey_wcpdf_invoice_number: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
tmonkey_wc_admin_notes: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
tmonkey_wc_admin_note_actions: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
tmonkey_wc_category_lookup: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
tmonkey_wc_customer_lookup: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
tmonkey_wc_download_log: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
tmonkey_wc_order_coupon_lookup: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
tmonkey_wc_order_product_lookup: Datos: 0.02MB + Índice: 0.06MB + Motor InnoDB
tmonkey_wc_order_stats: Datos: 0.02MB + Índice: 0.05MB + Motor InnoDB
tmonkey_wc_order_tax_lookup: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
tmonkey_wc_product_meta_lookup: Datos: 2.52MB + Índice: 3.44MB + Motor InnoDB
tmonkey_wc_tax_rate_classes: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
tmonkey_wc_webhooks: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
tmonkey_wfblockediplog: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
tmonkey_wfblocks7: Datos: 0.02MB + Índice: 0.05MB + Motor InnoDB
tmonkey_wfconfig: Datos: 1.52MB + Índice: 0.00MB + Motor InnoDB
tmonkey_wfcrawlers: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
tmonkey_wffilechanges: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
tmonkey_wffilemods: Datos: 7.52MB + Índice: 0.00MB + Motor InnoDB
tmonkey_wfhits: Datos: 0.06MB + Índice: 0.05MB + Motor InnoDB
tmonkey_wfhoover: Datos: 0.06MB + Índice: 0.02MB + Motor InnoDB
tmonkey_wfissues: Datos: 0.02MB + Índice: 0.06MB + Motor InnoDB
tmonkey_wfknownfilelist: Datos: 2.52MB + Índice: 0.00MB + Motor InnoDB
tmonkey_wflivetraffichuman: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
tmonkey_wflocs: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
tmonkey_wflogins: Datos: 0.05MB + Índice: 0.03MB + Motor InnoDB
tmonkey_wfls_2fa_secrets: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
tmonkey_wfls_settings: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
tmonkey_wfnotifications: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
tmonkey_wfpendingissues: Datos: 0.02MB + Índice: 0.06MB + Motor InnoDB
tmonkey_wfreversecache: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
tmonkey_wfsnipcache: Datos: 0.02MB + Índice: 0.05MB + Motor InnoDB
tmonkey_wfstatus: Datos: 0.14MB + Índice: 0.09MB + Motor InnoDB
tmonkey_wftrafficrates: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
tmonkey_woobe_history: Datos: 0.16MB + Índice: 0.20MB + Motor InnoDB
tmonkey_woobe_history_bulk: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
tmonkey_yoast_indexable: Datos: 4.52MB + Índice: 2.39MB + Motor InnoDB
tmonkey_yoast_indexable_hierarchy: Datos: 0.44MB + Índice: 0.55MB + Motor InnoDB
tmonkey_yoast_migrations: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
tmonkey_yoast_primary_term: Datos: 0.06MB + Índice: 0.03MB + Motor InnoDB
tmonkey_yoast_seo_links: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
tmonkey_yoast_seo_meta: Datos: 0.36MB + Índice: 0.00MB + Motor InnoDB

### Post Type Counts ###

attachment: 459
forum: 9
fusion_element: 9
nav_menu_item: 116
page: 29
polylang_mo: 4
post: 18
product: 662
product_variation: 15494
revision: 433
shop_order: 3
topic: 1
tribe_events: 6
tribe_organizer: 1
tribe_venue: 1
wpcf7_contact_form: 8

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (21) ###

Polylang: por WP SYNTEX – 2.7.3
Advanced Access Manager: por Vasyl Martyniuk <vasyl@vasyltech.com> – 6.5.4
Asesor de Cookies RGPD: por Carlos Doral Pérez – 0.31
Autoptimize: por Frank Goossens (futtta) – 2.7.3
Contact Form 7: por Takayuki Miyoshi – 5.1.9
Fusion Builder: por ThemeFusion – 2.2.3
Fusion Core: por ThemeFusion – 4.2.3
Google Analytics para WordPress por MonsterInsights: por MonsterInsights – 7.10.4
Really Simple CAPTCHA: por Takayuki Miyoshi – 2.0.2
Slider Revolution: por ThemePunch – 6.2.8
Mostrar IP del servidor y uso de memoria: por Apasionados
Apasionados del Marketing – 2.1.0

WooCommerce Bulk Editor: por realmag777 – 1.0.5.1 – Versión instalada no está probada con la versión activa de WooCommerce 4.2.0
Hyyan WooCommerce Polylang Integration: por Hyyan Abo Fakher – 1.4.3 – Versión instalada no está probada con la versión activa de WooCommerce 4.2.0
WooCommerce Google Analytics Integration: por WooCommerce – 1.4.22
WooCommerce: por Automattic – 4.2.0
Wordfence Security: por Wordfence – 7.4.8
Yoast SEO: por Equipo Yoast – 14.3
Smush: por WPMU DEV – 3.6.3
WP Super Cache: por Automattic – 1.7.1
ReCaptcha v2 for Contact Form 7: por IQComputing – 1.2.7
YITH Color and Label Variations for WooCommerce: por YITH – 1.9.2

### Inactive Plugins (3) ###

Advanced Woo Search: por ILLID – 2.03
Maintenance: por WP Maintenance – 3.90
Page Visit Counter: por theDotstore – 6.0.4 – Versión instalada no está probada con la versión activa de WooCommerce 4.2.0

### Dropin Plugins (1) ###

advanced-cache.php: advanced-cache.php

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: right
Thousand Separator: 
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Base de la tienda: #1322 - /shop/
Carrito: ❌ La página no contiene el shortcode.
Finalizar compra: ❌ La página no contiene el shortcode.
Mi cuenta: ❌ La página no contiene el shortcode.
Términos y condiciones: ❌ Página sin definir

### Theme ###

Name: Avada
Version: 6.2.3
Author URL: http://themeforest.net/user/ThemeFusion
Child Theme: ❌ – Si estás modificando WooCommerce en un tema padre que no has creado personalmente
te recomendamos utilizar un tema hijo. Ver: Cómo crear un tema hijo

WooCommerce Support: ✔

### Templates ###

Overrides: Avada/woocommerce/cart/cart.php
Avada/woocommerce/checkout/form-pay.php
Avada/woocommerce/checkout/review-order.php
Avada/woocommerce/checkout/thankyou.php
Avada/woocommerce/loop/loop-start.php
Avada/woocommerce/single-product/add-to-cart/variable.php
Avada/woocommerce/single-product/short-description.php
Avada/woocommerce/single-product/tabs/additional-information.php
Avada/woocommerce/single-product/tabs/description.php

### Action Scheduler ###

Completo: 7
Oldest: 2020-06-12 15:32:31 +0000
Newest: 2020-06-17 11:32:37 +0000

`
</details>

**Comment by Jon007** [comment]
This does not happen out of the box so should be a compatibility issue with one of the other plugins.
Check also your WooCommerce status report is indicating other problems such as that the core WooCommerce pages may not be created.
To understand further where the error might be, turn on WP debugging by enabling define( 'WP_DEBUG', true ); in wp-config.php and check the detailed error which appears in the php error logs.

**Comment by gorkatolosa** [comment]
Sorry for not indicating that I had already solved the problem, in my case it was a compatibility error with the Wordpress version, when returning to an earlier version, in my case version 5.2.4 of Wordpress, the problem was solved.

Anyway thank you for responding by proposing a solution.
