### ISSUE TITLE
Combatibility issues between WooCommerce Product Add-ons plugin and Polylang

### ISSUE THREAD

**Issue by AdrianMoise009** [hyyan/woo-poly-integration#501]
Hello, i am having a strange bug when i use woocomerce product addon plugin to add a price field to modify the Subtotal of a product.

1)First in the product page the addition of the price is included in the subtotal like it should be (Screenshot bellow).
![product-page-screenshot](https://user-images.githubusercontent.com/67193199/85202331-5b3f2380-b30e-11ea-8715-baffa8e6e887.PNG)

2)The problem is that when the product have been added to the cart, the subtotal is wrong. (it shows the price without the addition) (Screenshot bellow).
![cart-screenshot](https://user-images.githubusercontent.com/67193199/85202434-1bc50700-b30f-11ea-901e-50f6334a022d.PNG)

I have tried to find the case for this issue, by activating the default theme of wordpress and by deactivating all plugins, and activating step by step to find if it is a compatibility issue between some plugins.
Doing that i find that by deactivating the polylang and hyyan woo-poly-integration plugin that the issue have been removed.

Can you please help me fix this issue?

Bellow you will find my website settings:
PHP: 5.3.3
Wordpress: 5.3.4
WooCommerce: 4.2.0
Polylang: 2.7.3
Hyyan WooCommerce Polylang Integration: 1.4.3
Browser: Chrome and Firefox

**Comment by Jon007** [comment]
This plugin only provides compatibility with WooCommerce itself, other WooCommerce extensions may need additional translation compatibility layer.  There are some notes about this on the wiki.

When reporting an issue you must provide the environment details from WooCommerce System Status, in particular when reporting compatibility issue with another plugin it is necessary to know exactly which the other plugins are.
If the other plugins are paid plugins it would be advisable to report the Polylang compatibility issue to them as this is only a free plugin maintained by volunteers.
