### ISSUE TITLE
You cannot add that amount to the cart — we have 1 in stock and you already have 1 in your cart - Redirection issue

### ISSUE THREAD

**Issue by fkoomek** [hyyan/woo-poly-integration#506]
#### Can you reproduce this issue on default Wordpress theme (eg Storefront)?
Yes

#### Can you reproduce this issue when all other plugins are disabled except WooCommerce, Polylang and Hyyan WooCommerce Polylang Integration?
Yes

#### Steps to Reproduce
1. Set up two languages
2. Create a product in both languages
3. Set stock quantity to 1
4. Switch to the language that is not default
5. Go to the shop page and add the product to the cart
6. After that add it to the cart once again

#### What I Expected
To land on a single product page saying "You cannot add that amount to the cart — we have 1 in stock and you already have 1 in your cart. " And the page is in the appropriate language.

#### What Happened Instead
I land on a single product page in the default language.

<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.
```
</details>

**Comment by Jon007** [comment]
a number of stock handling issues are fixed on #475 and I can't now reproduce on latest source and latest plugin versions, so I'll close here but please reopen if you find a scenario with the latest code that isn't fixed
