### ISSUE TITLE
Woocommerce Widget product category. Error 404 

### ISSUE THREAD

**Issue by Fravit6** [hyyan/woo-poly-integration#508]
#### Can you reproduce this issue on default Wordpress theme (eg Storefront)?

Yes

#### Can you reproduce this issue when all other plugins are disabled except WooCommerce, Polylang and Hyyan WooCommerce Polylang Integration?

Yes

#### What product versions and settings are you using when this issue occurs?
* PHP: 7.2.32
* WordPress: 5.3.4
* WooCommerce: 3.6.4
* Polylang: 2.7.1 free
* Hyyan WooCommerce Polylang Integration: 1.4.3
* Browser: all

#### Steps to Reproduce
1. Go to page: https://transafrica.biz/en/i-nostri-viaggi/
2. Select a country in the widget dropdow menu (where do you read: "select a destination:")

#### What I Expected
To go on https://transafrica.biz/ **en/**  ?product_cat=ghana-en page 

#### What Happened Instead
Error 404: because the url doesn't have /en/

This problem is only for second language (en). For the main language (it) all works perfectly.

**Comment by Jon007** [comment]
This sounds like a permalinks issue, save your Polylang settings at /wp-admin/admin.php?page=mlang_settings
then check and save /wp-admin/options-permalink.php
which should solve this issue
If not please raise issue with more details
