### ISSUE TITLE
Woocommerce shipping method does not show when switching to secondary language

### ISSUE THREAD

**Issue by calwine** [hyyan/woo-poly-integration#509]
Hello,
I run a webshop in Danish with Polylang and WooPoly for the English integration. I've been very happy with it so far, but I was just alerted to this issue by a customer:

When using the native Danish version, local delivery is activated. However, when switching to English, that option is taken away, even though it matches and I have translated the string. I have shipping set for delivery address. I will attach two screenshots.

![WooPoly Danish](https://user-images.githubusercontent.com/70708533/92129339-3bb98200-edb8-11ea-9540-5870fa0e84f1.jpg)
![WooPoly English](https://user-images.githubusercontent.com/70708533/92129351-3fe59f80-edb8-11ea-9efb-84c9f606e207.jpg)

Looking for any help on this.

Thank you in advance.

Best regards,

Anja Clarke

#### What product versions and settings are you using when this issue occurs?
* PHP: 
* WordPress: 
* WooCommerce: 
* Polylang: [state if using Polylang PRO]
* Hyyan WooCommerce Polylang Integration: 
* Browser: 

#### Steps to Reproduce
1. 
1. 
1. 

## WordPress Environment

<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.
```
</details>

**Comment by krohmalny** [comment]
I have similar issue in one of the shops. When you add something to cart in English everything works, but in Polish cart doesn't work at all, returns page without any content cart related. Funny thing is, that when you log in, everything works fine.

**Comment by BigthorDev** [comment]
I think I have the same issue, 
when the product is selected in English everything works properly, Then I switch to French, and the shipping price changes completely. I have no idea where this value is coming from. Any Ideas?

**Comment by Jon007** [comment]
Hi, it works fine on a basic installation, but note the options only come up when you have put in a full address or if you are logged in as a user with address.
If possible please try with the latest pre-release https://github.com/hyyan/woo-poly-integration/releases/tag/1.4.5
and if you are still having trouble please test disabling other plugins and with a standard theme like Storefront to rule out conflict with other plugin, and if still a problem please report including the status report with the plugin versions
