### ISSUE TITLE
Metas list checkbox values not saving

### ISSUE THREAD

**Issue by bobby-joeaudet** [hyyan/woo-poly-integration#51]
Hello!
Every time I try to uncheck 2 check boxes from the Meta List (Product Attributes, Default Attributes) and submit to save, the values are not saved on the refresh.

Thanks

**Comment by hyyan** [comment]
Please try the master branch https://github.com/hyyan/woo-poly-integration

**Comment by decarvalhoaa** [comment]
Solve in 0.29 candidate
