### ISSUE TITLE
Variable Product Issue

### ISSUE THREAD

**Issue by dgulias** [hyyan/woo-poly-integration#512]
#### Can you reproduce this issue on default Wordpress theme (eg Storefront)?

Yes.

#### Can you reproduce this issue when all other plugins are disabled except WooCommerce, Polylang and Hyyan WooCommerce Polylang Integration?

Yes.

#### What product versions and settings are you using when this issue occurs?
* PHP: 7.3.21
* WordPress: Versión 5.5.1–es_ES
* WooCommerce: Versión 4.4.1
* Polylang: [state if using Polylang PRO] -> Free Versión 2.8.1
* Hyyan WooCommerce Polylang Integration: Versión 1.4.3
* Browser: Firefox 80.0.1 (64-bit)

#### Steps to Reproduce

Hello everybody.

Since this last wordpress + woocommerce + polylang update, I see a variable products issue, where everytime we save a product as variable product it back to simple product again. ------> OK: It was FIXED on this issue ( https://github.com/hyyan/woo-poly-integration/issues/510#issuecomment-687156776 ) **but all the following issues keep the same**:

**Because of this issue, on backend, when I choose again “variable product” I can’t see anymore the variation options detail (just the number of variations but I can’t click on it – it is stuck). When I disable “polylang + hyyan” plugins I can see variations options again in backend.**

If you edit the product without pay attention, there is a risk to save it as a simple product, so the product price will just disappear on frontend. To fix that (price disappearing), you have to edit the product, select again “variable product” and save it, so the price shows up again. -----> This part was fixed as well with the fix mentioned above.

**But I still having problem to see the Variatons, and the “select options” button became “read more” on frontend for variable products.**

Is there something I can do to fix that? Thanks.

#### What I Expected

After fix the forced simple product problem, I expected to back to see the variation options again. 

#### What Happened Instead

I can't see any variation options I created before. Only when I disable Polylang + Hyyan plugin, so I can see variable products again. (This happened before this mentioned fix above - and so, it is not the fix problem, actually, it happend just after the last Polylang + Woocommerce updates)

## WordPress Environment

<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.
```

`
### WordPress Environment ###

WordPress address (URL): https://filtroshop.com
Site address (URL): https://filtroshop.com
WC Version: 4.4.1
REST API Version: ✔ 1.0.15
WC Blocks Version: ✔ 3.3.0
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 1.4.0
Log Directory Writable: ✔
WP Version: 5.5.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: –
Language: es_ES
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.3.21
PHP Post Max Size: 260 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.72.0
OpenSSL/1.1.1g

SUHOSIN Installed: –
MySQL Version: 5.6.41-84.1
Max Upload Size: 256 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.4.1
WC Database Prefix: wpfseu_
Tamaño total de la base de datos: 12.45MB
Tamaño de los datos de la base de datos: 10.71MB
Tamaño del índice de la base de datos: 1.74MB
wpfseu_woocommerce_sessions: Datos: 0.03MB + Índice: 0.00MB + Motor MyISAM
wpfseu_woocommerce_api_keys: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wpfseu_woocommerce_attribute_taxonomies: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wpfseu_woocommerce_downloadable_product_permissions: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wpfseu_woocommerce_order_items: Datos: 0.01MB + Índice: 0.01MB + Motor MyISAM
wpfseu_woocommerce_order_itemmeta: Datos: 0.04MB + Índice: 0.03MB + Motor MyISAM
wpfseu_woocommerce_tax_rates: Datos: 0.00MB + Índice: 0.01MB + Motor MyISAM
wpfseu_woocommerce_tax_rate_locations: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wpfseu_woocommerce_shipping_zones: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wpfseu_woocommerce_shipping_zone_locations: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wpfseu_woocommerce_shipping_zone_methods: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wpfseu_woocommerce_payment_tokens: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wpfseu_woocommerce_payment_tokenmeta: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wpfseu_woocommerce_log: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wpfseu_actionscheduler_actions: Datos: 0.15MB + Índice: 0.05MB + Motor MyISAM
wpfseu_actionscheduler_claims: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wpfseu_actionscheduler_groups: Datos: 0.00MB + Índice: 0.01MB + Motor MyISAM
wpfseu_actionscheduler_logs: Datos: 0.07MB + Índice: 0.05MB + Motor MyISAM
wpfseu_ac_abandoned_cart_history_lite: Datos: 1.09MB + Índice: 0.02MB + Motor MyISAM
wpfseu_ac_email_templates_lite: Datos: 0.01MB + Índice: 0.00MB + Motor MyISAM
wpfseu_ac_guest_abandoned_cart_history_lite: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wpfseu_ac_sent_history_lite: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wpfseu_clickbar: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wpfseu_clickbar_clicks: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wpfseu_clickbar_hits: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wpfseu_commentmeta: Datos: 0.00MB + Índice: 0.01MB + Motor MyISAM
wpfseu_comments: Datos: 0.02MB + Índice: 0.02MB + Motor MyISAM
wpfseu_jack_jacker_pages: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wpfseu_links: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wpfseu_options: Datos: 1.95MB + Índice: 0.11MB + Motor MyISAM
wpfseu_postmeta: Datos: 0.64MB + Índice: 0.32MB + Motor MyISAM
wpfseu_posts: Datos: 0.44MB + Índice: 0.06MB + Motor MyISAM
wpfseu_termmeta: Datos: 0.01MB + Índice: 0.02MB + Motor MyISAM
wpfseu_terms: Datos: 0.01MB + Índice: 0.03MB + Motor MyISAM
wpfseu_term_relationships: Datos: 0.03MB + Índice: 0.05MB + Motor MyISAM
wpfseu_term_taxonomy: Datos: 0.02MB + Índice: 0.01MB + Motor MyISAM
wpfseu_tm_taskmeta: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wpfseu_tm_tasks: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wpfseu_usermeta: Datos: 0.11MB + Índice: 0.05MB + Motor MyISAM
wpfseu_users: Datos: 0.00MB + Índice: 0.01MB + Motor MyISAM
wpfseu_wc_admin_notes: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wpfseu_wc_admin_note_actions: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wpfseu_wc_category_lookup: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wpfseu_wc_customer_lookup: Datos: 0.00MB + Índice: 0.01MB + Motor MyISAM
wpfseu_wc_download_log: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wpfseu_wc_order_coupon_lookup: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wpfseu_wc_order_product_lookup: Datos: 0.00MB + Índice: 0.01MB + Motor MyISAM
wpfseu_wc_order_stats: Datos: 0.00MB + Índice: 0.01MB + Motor MyISAM
wpfseu_wc_order_tax_lookup: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wpfseu_wc_product_meta_lookup: Datos: 0.01MB + Índice: 0.02MB + Motor MyISAM
wpfseu_wc_reserved_stock: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wpfseu_wc_tax_rate_classes: Datos: 0.00MB + Índice: 0.01MB + Motor MyISAM
wpfseu_wc_webhooks: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wpfseu_wfblockediplog: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wpfseu_wfblocks7: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wpfseu_wfconfig: Datos: 2.12MB + Índice: 0.01MB + Motor MyISAM
wpfseu_wfcrawlers: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wpfseu_wffilechanges: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wpfseu_wffilemods: Datos: 2.32MB + Índice: 0.47MB + Motor MyISAM
wpfseu_wfhits: Datos: 0.01MB + Índice: 0.00MB + Motor MyISAM
wpfseu_wfhoover: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wpfseu_wfissues: Datos: 0.00MB + Índice: 0.01MB + Motor MyISAM
wpfseu_wfknownfilelist: Datos: 1.22MB + Índice: 0.14MB + Motor MyISAM
wpfseu_wflivetraffichuman: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wpfseu_wflocs: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wpfseu_wflogins: Datos: 0.04MB + Índice: 0.01MB + Motor MyISAM
wpfseu_wfls_2fa_secrets: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wpfseu_wfls_settings: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wpfseu_wfnotifications: Datos: 0.02MB + Índice: 0.00MB + Motor MyISAM
wpfseu_wfpendingissues: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wpfseu_wfreversecache: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wpfseu_wfsnipcache: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wpfseu_wfstatus: Datos: 0.09MB + Índice: 0.04MB + Motor MyISAM
wpfseu_wftrafficrates: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wpfseu_wpmm_subscribers: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wpfseu_yoast_indexable: Datos: 0.16MB + Índice: 0.04MB + Motor MyISAM
wpfseu_yoast_indexable_hierarchy: Datos: 0.00MB + Índice: 0.01MB + Motor MyISAM
wpfseu_yoast_migrations: Datos: 0.00MB + Índice: 0.01MB + Motor MyISAM
wpfseu_yoast_primary_term: Datos: 0.00MB + Índice: 0.01MB + Motor MyISAM
wpfseu_yoast_seo_links: Datos: 0.02MB + Índice: 0.01MB + Motor MyISAM
wpfseu_yoast_seo_meta: Datos: 0.03MB + Índice: 0.03MB + Motor MyISAM

### Post Type Counts ###

attachment: 54
feedback: 48
jetpack_migration: 2
jp_img_sitemap: 1
jp_sitemap: 1
jp_sitemap_master: 1
mc4wp-form: 1
nav_menu_item: 66
page: 33
polylang_mo: 3
post: 6
product: 60
product_variation: 152
shop_coupon: 2
shop_order: 36
ywcm_message: 3

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (34) ###

Polylang: por WP SYNTEX – 2.8.1
Akismet Anti-Spam: por Automattic – 4.1.6
Brave Payments Verification: por Brave Software Intl – 1.0.4
Cookie Notice: por dFactory – 1.3.2
Easy WP SMTP: por wpecommerce
alexanderfoxc – 1.4.1

Flexible Checkout Fields: por WP Desk – 2.5.3
Jetpack by WordPress.com: por Automattic – 8.9
Kadence Blocks – Gutenberg Blocks for Page Builder Features: por Kadence WP – 1.8.13
Loco Translate: por Tim Whitlock – 2.4.3
MC4WP: Mailchimp for WordPress: por ibericode – 4.8.1
WooCommerce Payment Gateway - OpenNode: por OpenNode – 1.4.1 – Versión instalada no está probada con la versión activa de WooCommerce 4.4.1
Recently Registered: por Mika Epstein – 3.4.3
Sucuri Security - Auditing, Malware Scanner and Hardening: por Sucuri Inc. – 1.8.24
Tracking Code Manager: por IntellyWP – 1.12.3
Virtue/Ascend/Pinnacle Toolkit: por Kadence WP – 4.9.6
WC - APG Campo NIF/CIF/NIE: por Art Project Group – 1.4.1 – Versión instalada no está probada con la versión activa de WooCommerce 4.4.1
WooCommerce Blocks: por Automattic – 3.3.0
Hyyan WooCommerce Polylang Integration: por Hyyan Abo Fakher – 1.4.3 – Versión instalada no está probada con la versión activa de WooCommerce 4.4.1
Abandoned Cart Lite for WooCommerce: por Tyche Softwares – 5.8.1
WC - APG Envío Gratuito: por Art Project Group – 2.4.0.6
WC - APG Notificaciones SMS: por Art Project Group – 2.21 – Versión instalada no está probada con la versión activa de WooCommerce 4.4.1
WC - APG Envío por peso: por Art Project Group – 2.3.1.5
WooCommerce PayPal Checkout Gateway: por WooCommerce – 2.0.3 – Versión instalada no está probada con la versión activa de WooCommerce 4.4.1
WooCommerce Stripe Gateway: por WooCommerce – 4.5.2 – Versión instalada no está probada con la versión activa de WooCommerce 4.4.1
WooCommerce Services: por Automattic – 1.24.2 – Versión instalada no está probada con la versión activa de WooCommerce 4.4.1
WooCommerce: por Automattic – 4.4.1
Wordfence Security: por Wordfence – 7.4.11
Yoast SEO: por Equipo Yoast – 14.9
WP Fastest Cache: por Emre Vona – 0.9.1.0
WP Maintenance Mode: por Designmodo – 2.2.4
WP-Optimize - Clean, Compress, Cache: por David Anderson
Ruhani Rabin
Team Updraft – 3.1.2

YITH Color and Label Variations for WooCommerce: por YITH – 1.9.3
YITH Essential Kit for WooCommerce #1: por YITH – 2.1.4 – Versión instalada no está probada con la versión activa de WooCommerce 4.4.1
YITH WooCommerce Cart Messages: por YITH – 1.5.4

### Inactive Plugins (2) ###

Multiple Packages for WooCommerce: por Erica Dion – 1.1 – Versión instalada no está probada con la versión activa de WooCommerce 4.4.1
YITH WooCommerce Catalog Mode: por YITH – 2.0.3

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: right_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Base de la tienda: #10 - /tienda/
Carrito: #11 - /carrito/
Finalizar compra: #12 - /finalizar-compra/
Mi cuenta: #13 - /mi-cuenta/
Términos y condiciones: ❌ Página sin definir

### Theme ###

Name: Pinnacle
Version: 1.7.12
Author URL: https://www.kadencewp.com/
Child Theme: ❌ – Si estás modificando WooCommerce en un tema padre que no has creado personalmente
te recomendamos utilizar un tema hijo. Ver: Cómo crear un tema hijo

WooCommerce Support: ✔

### Templates ###

Overrides: pinnacle/woocommerce/archive-product.php
pinnacle/woocommerce/content-product.php
pinnacle/woocommerce/content-product_cat.php
pinnacle/woocommerce/content-single-product.php
pinnacle/woocommerce/loop/loop-end.php
pinnacle/woocommerce/loop/loop-start.php
pinnacle/woocommerce/loop/rating.php
pinnacle/woocommerce/loop/sale-flash.php
pinnacle/product-searchform.php
pinnacle/woocommerce/single-product/add-to-cart/variable.php
pinnacle/woocommerce/single-product/product-image.php
pinnacle/woocommerce/single-product/product-thumbnails.php
pinnacle/woocommerce/single-product.php
pinnacle/woocommerce/taxonomy-product_cat.php
pinnacle/woocommerce/taxonomy-product_tag.php

### Action Scheduler ###

Completo: 403
Oldest: 2020-08-08 05:18:06 +0200
Newest: 2020-09-08 02:06:29 +0200

Fallida: 2
Oldest: 2020-04-08 23:54:38 +0200
Newest: 2020-04-08 23:54:38 +0200

Pendiente: 3
Oldest: 2020-09-08 02:21:29 +0200
Newest: 2020-09-09 23:18:20 +0200

`

</details>

**Comment by janis-ps** [comment]
> Because of this issue, on backend, when I choose again “variable product” I can’t see anymore the variation options detail (just the number of variations but I can’t click on it – it is stuck). When I disable “polylang + hyyan” plugins I can see variations options again in backend.

We also had this problem. I discovered that variations disappear **unless** the `product_variation` posts (WooCommerce custom post type) posts have a "language" taxonomy term. I automated the fix with wp-cli, but it was a very complicated fix. As an example, `wp post term set 1234 language en` sets the "language" taxonomy term for product_variation with ID 1234. That is only one variation, I had to do it for 5000+.

Has anyone tried a WP downgrade?

**Comment by dgulias** [comment]
> 
> 
> > Because of this issue, on backend, when I choose again “variable product” I can’t see anymore the variation options detail (just the number of variations but I can’t click on it – it is stuck). When I disable “polylang + hyyan” plugins I can see variations options again in backend.
> 
> We also had this problem. I discovered that variations disappear **unless** the `product_variation` posts (WooCommerce custom post type) posts have a "language" taxonomy term. I automated the fix with wp-cli, but it was a very complicated fix. As an example, `wp post term set 1234 language en` sets the "language" taxonomy term for product_variation with ID 1234. That is only one variation, I had to do it for 5000+.
> 
> Has anyone tried a WP downgrade?

OMG, this is really difficult to fix.

Has anyone found a solution?

**Comment by colyz93** [comment]
same here fixed the product type with the fix but one of two languages show as out of stock

**Comment by dgulias** [comment]
> 
> 
> same here fixed the product type with the fix but one of two languages show as out of stock

Same times it happens to me. I just save again every product language page (and let the main language product page for the last) to force everything to work fine again.


But I still not seeing the variation options to edit... (only if I disable Polylang and Ryyan WooPoly)

**Comment by colyz93** [comment]
also, the second lang. page gets freezing i tried many things to fix it but no luck
for now i downgraded my wordpress till these problems get fixed

**Comment by dgulias** [comment]
Please, anyone can provide us any kind of fix?

Thanks

**Comment by gabrieljstavares** [comment]
Same problem, variations are not expandable anymore, and on the frontoffice, products show as "out of stock", anyone please help?

**Comment by flux28** [comment]
same issue. Also, products in both languages are no longer linked (variations are not updated together). can someone update the plugin Hyyan WooCommerce Polylang Integration?

**Comment by mircoraffinetti** [comment]
I just realized that the variation association is fixed fixed if all products (all languages) are saved in the same time using bulk edit from product view. 
Otherwise if I save one language at the time, only the single product (one language) id fixed but the other languages comes corrupted.

I hope that this problem will be fixed soon.

**Comment by dgulias** [comment]
The bulk save didn't work for me. I selected all the products, and click and "pubblish" options and save. Nothing changed to me.

So I did the association-fix manually as some people said above.

Follow the steps:

1) Do the variation/single product FIX before those steps.

2) disable Polylang and Hyyan (woo-polly-integration) pluggins

3) Go to the first product; go to one variation option (that will show now), go to price and change the price, then change it back, just to apper the variations SAVE button. So you save it. After save the variations, click on UPDATE button of your product.

4) Do this on every product and on every language variations. - For me was just 69 products (including the translations) - I can't imagine a shop with 10k products doing this.

5) Clean Cashe; Enable all pluggins again; Clean Cashe again. Clean your browser cache as well.

That's it.

Cheers

**Comment by gabrieljstavares** [comment]
Great!!

I'm now inclined to say this is a Polylang bug.
I've discovered a few this past week...

Ex: My products are different in each language, for a language/country the product X, is the product X but with different features, for that reason i do not associate the translations between products.
So, i have a product, in spanish, that does not have translation to any other language, in its current and correct language the variations do not show, but if i change the language of the product, i eventually find a language that shows me the variations, i can then modify them... this is a very weird bug...
The only way i can conceive this bug, is if the attributes were created when the "global" admin language was selected on a specific language, there is no other way to explain... but even with that, all my attributes are "global attributes" i do not want them and their terms translated, as i have more than 100 terms per attribute and all are like color references...

Another bug:
I have 4 languages, (PT, ES, EN, UK), after the latest updates, i can only update the product categories on the PT language, when i try to modify any of the categories in other languages, wordpress throws an error "Category not updated".

I had to manually modify the categories on the database...

Thinking twice of renovating polylang licence next year....

**Comment by cavalihno** [comment]
> 
> 
> also, the second lang. page gets freezing i tried many things to fix it but no luck
> for now i downgraded my wordpress till these problems get fixed
@colyz93 what downgraded version of woocommerce, polylang and woo-poly makes it works ?

**Comment by Jon007** [comment]
Hi, I think this is fixed in latest source and current plugin versions, see eg #430 and recent checkins and please report with detail if not.
