### ISSUE TITLE
Woo categories mutilang

### ISSUE THREAD

**Issue by BowenheWZJ** [hyyan/woo-poly-integration#520]
#### What product versions and settings are you using when this issue occurs?
* PHP: 
* WordPress: 5.5.3
* WooCommerce: 4.6.1
* Polylang: [state if using Polylang PRO]
* Hyyan WooCommerce Polylang Integration: 1.4.3
* Browser: google chorm

#### Steps to Reproduce
1. get into WordPress
1. under product
1. categorises

#### What I Expected
the language switch appear near the categorize

#### What Happened Instead
it doesnt appear

## WordPress Environment

<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.
```
</details>

**Comment by Jon007** [comment]
I can't tell exactly from the details provided but please make sure category translation is turned on in both polylang and woopoly settings, see: https://github.com/hyyan/woo-poly-integration/wiki/Product-Categories
