### ISSUE TITLE
jQuery Migrate: jQuery.parseJSON requires a valid JSON string

### ISSUE THREAD

**Issue by webappvicio** [hyyan/woo-poly-integration#522]
woo-poly-integration/public/js/Cart.min.js
**jQuery.parseJSON requires a valid JSON string**

Line 143 (Cart.js)
	var wc_fragments = $.parseJSON( sessionStorage.getItem( wc_cart_fragments_params.fragment_name ) )

How I can fix the code to avoid the deprecation warning? 

jQuery Migrate Version 2.62, WooCommerce 4.8.0, WordPress 5.6, Polylang (free) Version 2.9.1

**Comment by mrleemon** [comment]
Try replacing that line with:

`var wc_fragments = JSON.parse( sessionStorage.getItem( wc_cart_fragments_params.fragment_name ) );`

**Comment by mrleemon** [comment]
@Jon007 You forgot to make the change in the `Cart.min.js` file, which is the one that is actually used in the plugin.
