### ISSUE TITLE
Product type dropdown shows "Simple Product" after saving a variable product

### ISSUE THREAD

**Issue by mrleemon** [hyyan/woo-poly-integration#526]
I installed the plugin from master with the latest commits from February to test if issues with variable product persist, and I see that #510 is still occurring.
When I save a variable product, and the edit product page reloads, the "Single Product" option in the product type dropdown is selected. As soon as I select "Variable Product", all the previously set up attributes and variations appear again, so this data is apparently not lost when saving.

**Comment by Jon007** [comment]
ok wow, it works fine in Safari which i was using but in Chrome no, nada

**Comment by Jon007** [comment]
Hi @mrleemon try this, just replaced the JQuery with standard javascript

**Comment by mrleemon** [comment]
I tested this new version and now in the edit screen of any previously saved product (single, group, external, etc.), the "Variable Product" option is always selected in the Product Type dropdown.

**Comment by mrleemon** [comment]
I suppose this line:

`document.getElementById("product-type").value="variable";`

should be:

`document.getElementById("product-type").value="%2$s";`

to select the correct type (`$type[0]` parameter in the `sprintf`)

**Comment by Jon007** [comment]
haha yes, was already on it..

**Comment by mrleemon** [comment]
In this new patch you referenced the wrong placeholder: It's %2$s, not %1$s

**Comment by mrleemon** [comment]
Thanks!

**Comment by PauKokura** [comment]
Hi. Sorry to say that my wp is still stuck with this #526 issue. Same with the 1.4.5 zip from github and the 1.5.0 from wordpress repo.  I'm totally lost.
