### ISSUE TITLE
Product variation terms not showing in product page.

### ISSUE THREAD

**Issue by caliokapi** [hyyan/woo-poly-integration#528]
Hi, I have try everything .

I created my product in main language.
Then created an attribute 
Then created terms
 Then I created the translation for attribute and terms. (All taxonomies on)

I created my product translation to my second language.

Then when I visit my product page on main language everything is ok, when I visit the same product on secondary language the terms are not visible. I can see the attribution and in the correct language, but not any term.

[https://www.fundacionshare.org/product/amor-propio/](url)

I already tried it in original theme and deactivating plugins. Same issue.

***I try creating NEW Product Attributes and terms and still have the same issue. When I created the attributes this time I created first the second language and then the main language. Still one term not available but this time the main term. That means that the one created second is the one that wont appear.

I would really appreciate your help!

Thanks

#### What product versions and settings are you using when this issue occurs?
* PHP: 7.3.26
* WordPress: 5.6.1
* WooCommerce: 4.9.2
* Polylang: [state if using Polylang PRO]
* Hyyan WooCommerce Polylang Integration: 
* Browser: Chrome

#### Steps to Reproduce
1. 
1. 
1. 

## WordPress Environment

<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.
```
</details>

**Comment by Jon007** [comment]
Hi I can't reproduce this and some of the details are missing on the report.
Please try this pre-release:  https://github.com/hyyan/woo-poly-integration/releases/tag/1.4.5
and check the notes https://github.com/hyyan/woo-poly-integration/wiki/Product-Attributes
and please reopen with as much detail as possible if you are still finding an issue
