### ISSUE TITLE
jQuery .attr() deprecated for use with the "disabled" property

### ISSUE THREAD

**Issue by mrleemon** [hyyan/woo-poly-integration#529]
In both `/public/js/Variables.js` and `/public/js/Variables.min.js` files `.attr()` is used with the `disabled` property. jQuery has deprecated this use in its most recent versions, which WordPress is using now. jQuery now requires `.prop()` instead to set and retrieve the value of "checked", "selected" and "disabled" properties of a node.

https://github.com/hyyan/woo-poly-integration/blob/383d3aa7ab16f9811344ed84ebb42539ec9e6b60/public/js/Variables.js#L80

The line:

`this.$('#submitdiv *').attr('disabled', enable);`

should be:

`this.$('#submitdiv *').prop('disabled', enable);`

**Comment by Jon007** [comment]
do you want to check in an update for this?

**Comment by mrleemon** [comment]
Do you want me to do a PR?

**Comment by Jon007** [comment]
sure you seem to have this under control :)
I'm busy looking at synchronisation of variation default attributes and stock status

**Comment by mrleemon** [comment]
Done
