### ISSUE TITLE
translateEmailStringToOrderLanguage / translateEmailStringToObjectLanguage compatibility issue for WooCommerce Germanized

### ISSUE THREAD

**Issue by kamran1331** [hyyan/woo-poly-integration#540]
2021-02-21T00:48:24+00:00 CRITICAL Uncaught Error: Call to undefined method Hyyan\WPI\Emails::translateEmailStringToOrderLanguage() in /www/htdocs/*****/*******/wp-content/plugins/woocommerce-germanized/includes/compatibility/class-wc-gzd-compatibility-woo-poly-integration.php:135
Stack trace:
#0 /www/htdocs/*****/*******/wp-includes/class-wp-hook.php(289): WC_GZD_Compatibility_Woo_Poly_Integration->translate_order_subject('Zahlung erhalte...', Object(Automattic\WooCommerce\Admin\Overrides\Order))
#1 /www/htdocs/******/a*******/wp-includes/plugin.php(212): WP_Hook->apply_filters('Zahlung erhalte...', Array)
#2 /www/htdocs/******/a*******/wp-content/plugins/woocommerce/includes/emails/class-wc-email.php(381): apply_filters('woocommerce_ema...', 'Zahlung erhalte...', Object(Automattic\WooCommerce\Admin\Overrides\Order), Object(WC_GZD_Email_Customer_Paid_For_Order))
#3 /www/htdocs/******/a********e/wp-content/plugins/woocommerce-germanized/includes/emails/class-wc-gzd-email-customer-paid-for-order.ph in /www/htdocs/*******/********/wp-content/plugins/woocommerce-germanized/includes/compatibility/class-wc-gzd-compatibility-woo-poly-integration.php in Zeile 135

**Comment by mrleemon** [comment]
This is an error coming from the WooCommerce Germanized plugin.

In their `class-wc-gzd-compatibility-woo-poly-integration.php` file there are two references to a function that has been renamed in WooPoly.

`return $this->get_pll_email_instance()->translateEmailStringToOrderLanguage( $subject, $object, 'subject', $email_id );`

should be changed to:

`return $this->get_pll_email_instance()->translateEmailStringToObjectLanguage( $subject, $object, 'subject', $email_id );`

And:

`return $this->get_pll_email_instance()->translateEmailStringToOrderLanguage( $heading, $object, 'heading', $email_id );`

should be changed to:

`return $this->get_pll_email_instance()->translateEmailStringToObjectLanguage( $heading, $object, 'heading', $email_id );`

**Comment by kamran1331** [comment]
thanks, this is next bug for me :D

i hope the problem with Klarna can be solved.


Mit freundlichen Grüßen
Nuriyev


Am So., 21. Feb. 2021 um 22:57 Uhr schrieb mrleemon <
notifications@github.com>:

**Comment by kamran1331** [comment]
sorry false email...

ok, i will write to the Germanized Plugin. for update. Thank you.

Mit freundlichen Grüßen
Nuriyev


Am So., 21. Feb. 2021 um 23:01 Uhr schrieb Kamran Nuriyev <
nuriyev.1331@gmail.com>:

**Comment by mrleemon** [comment]
Apparently, this has been fixed in WooCommerce Germanized 3.3.7:
https://es.wordpress.org/plugins/woocommerce-germanized/#developers

**Comment by Jon007** [comment]
I see that's 8 releases ago for WooCommerce Germanized so I think we can close here then.
