### ISSUE TITLE
Uncaught Error: Call to undefined method WPSEO_Options

### ISSUE THREAD

**Issue by rdehoogen** [hyyan/woo-poly-integration#544]
#### What product versions and settings are you using when this issue occurs?
PHP: Version 7.4.15
WordPress: Version 5.6.2
WooCommerce: Version: 5.0.0
Polylang: [state if using Polylang PRO] Version 3.0
Hyyan WooCommerce Polylang Integration: Version 1.5.0 
Browser: Chrome

#### Steps to Reproduce
1. Start plugin and it crashes, deactivate in recovermode
1. deacivate and uninstall Yoast SEO end again starting Polylang plugin and it crashes, deactivate in recovermode
1. 

#### What I Expected
Start website normally

#### What Happened Instead
Site is again in recoverymode

## WordPress Environment

<details>
```
content/plugins/polylang/integrations/wpseo/wpseo.php. 
Uncaught Error: Call to undefined method WPSEO_Options::clear_cache() in /www/wp-content/plugins/polylang/integrations/wpseo/wpseo.php:87 Stack trace: #0 /www/wp-includes/class-wp-hook.php(287): PLL_WPSEO->wpseo_translate_options('') #1 /www/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters(NULL, Array) #2 /www/wp-includes/plugin.php(484): WP_Hook->do_action(Array) #3 /www/wp-settings.php(579): do_action('wp_loaded') #4 /www/wp-config.php(78): require_once('/www/wp-setting...') #5 /www/wp-load.php(37): require_once('/www/wp-config....') #6 /www/wp-login.php(12): require('/www/wp-load.ph...') #7 {main} thrown```
</details>

**Comment by Jon007** [comment]
Hi, you didn't state the the Yoast version, and the error log shows the error in the polylang plugin not this plugin.
there were Polylang fixes in 16 March 2021 release of Yoast SEO 16.0 and both Polylang and Yoast have had recent updates and should now be working.
This plugin itself doesn't interact with WPSEO.
