### ISSUE TITLE
Variable products loosing content in frontend by activating woo-poly

### ISSUE THREAD

**Issue by Bozafi** [hyyan/woo-poly-integration#546]
#### Can you reproduce this issue on default Wordpress theme (eg Storefront)?
I use Flatsome Theme
#### Can you reproduce this issue when all other plugins are disabled except WooCommerce, Polylang and Hyyan WooCommerce Polylang Integration?
Yes
#### What product versions and settings are you using when this issue occurs?
* PHP: 8.0
* WordPress: 5.7.1.
* WooCommerce: 5.2.2.
* Polylang: [state if using Polylang PRO] 3.0.3. (Free)
* Hyyan WooCommerce Polylang Integration: 1.5.0.
* Browser: Chrome + Safari

#### Steps to Reproduce
1. 
1. 
1. 

#### What I Expected
Resolving issue that i can use plugin. Variable and simple product content should be shown

#### What Happened Instead
From the moment i activated woo-poly-integration the variable product page ist loosing lots of content in front end. These are tags, buy now button, short descpription, description, ... Only the Headline, the main image and the price is shown. All simple product shown as they should be. The issue is only on variable products. 

Within the old website i use woo-poly on storefront theme. Now for the new shop i installed flatsome theme with ux builder. 

## WordPress Environment

<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.
```
</details>

**Comment by Jon007** [comment]
can you reproduce this on Storefront?
if it works on Storefront but not on the flatsome theme then it is an issue with the Flatsome theme support for the variable products.
