### ISSUE TITLE
Tax name translation not available

### ISSUE THREAD

**Issue by gorecwp** [hyyan/woo-poly-integration#547]
Can you reproduce this issue on default Wordpress theme (eg Storefront)?
This also doesn't work on the storefront theme.

Can you reproduce this issue when all other plugins are disabled except WooCommerce, Polylang, and Hyyan WooCommerce Polylang Integration?
This is the problem of Hyyan Woocommerce Polylang integration

What product versions and settings are you using when this issue occurs?
Latest

What I Expected
Resolving the issue that I can use the plugin and can also translate Tax names in different languages.

**Comment by Jon007** [comment]
How this works is that the 

Price Display Suffix under wooCommerce tax settings at: 
/wp-admin/admin.php?page=wc-settings&tab=tax
is translatable using Polylang strings translation at:
/wp-admin/admin.php?page=mlang_strings&s&group=WooCommerce+Taxes

The tax names of the different tax classes are not used on the front end as far as I know so they do not require translation.
If you think they do need to be translated you are welcome to explain why and where and submit a pull request.
