### ISSUE TITLE
Infinite loading on a 2nd lang. checkout page

### ISSUE THREAD

**Issue by shyshs** [hyyan/woo-poly-integration#551]
Hi. Can't confirm order on a second language. It is just ififnite loading on a checkout page and button procced order is not active.. 
When I disable your plugin - all works, but there is other problems appear. I need this plugin enable so please help me to resolve this problem.
Page where I need help - https://mechanika.in.ua/ru/checkout-2/
![image](https://user-images.githubusercontent.com/84450756/118807600-2f774580-b8b1-11eb-9455-2bca42289cdd.png)

**Comment by Jon007** [comment]
Hi, I'm accepting orders in three languages with this plugin however you could have a compatibility issue with a particular payment gateway plugin or theme or combination of plugin versions.

Please try with the default WooCommerce payment gateways and standard WooCommerce theme such as Storefront to confirm.

The issue template for raising a new issue at https://github.com/hyyan/woo-poly-integration/issues/new/choose explicitly asks that you confirm this, version details of key plugins and WooCommerce status report in particular for the active plugins and versions.  This information is necessary to be able to provide any advice on the issue.

If you can reproduce a problem with standard themes and WooCommerce payment gateways then please reopen with the details requested.
