### ISSUE TITLE
Can't stop synchronisation of field

### ISSUE THREAD

**Issue by snatch41** [hyyan/woo-poly-integration#553]
Hi, 

I'm using TM Extra product options plugin on my website and I have different forms set for English and French products. 
I would like Polyland not to synchronise TM Extra products fields I have in my product creation page. 

I tried adding this to my function.php but it does not work. I'm not sure my field names are correct but I struggle to get them.

`/*
 * stop synchronisation of field
 */
add_filter( 'woo-poly.product.disabledMetaSync', 'dontSyncMyCustomField', 10, 1 );
function dontSyncMyCustomField( $fieldsNotToSync ) {
	$fieldsNotToSync[] = 'tm_options_group';
    $fieldsNotToSync[] = 'tm_extra_product_options';
	return $fieldsNotToSync;
}
`

Anybody can point me what I should do ? 

Thanks a lot. 

Rémi

**Comment by Jon007** [comment]
see https://github.com/hyyan/woo-poly-integration/wiki/Product-Meta-and-Custom-Fields
by default Polylang doesn't sync meta keys starting with '_' but does sync others.

The filtering of the Polylang behaviour in this plugin is to add the specific  '_' meta for woocommerce to synchronisation according to the settings for this plugin.
to ensure the settings are not synchronised you need to use the Polylang filter 'is_protected_meta'
