### ISSUE TITLE
Custom Emails locale issue

### ISSUE THREAD

**Issue by submediax** [hyyan/woo-poly-integration#554]
Hi there,

I stuck with localization problem of custom email types e.g. `wc_transporting_order`, `wc_order_status_email_*`.

It would be great to make possible for users to add more email types themselves using hooks whatsoever.

In my case, I utilize WooCommerce Order Status Manager plugin where created some custom order statuses as well as corresponding emails for them.
Unfortunately the polylang default language used for these emails despite of order language.

Does anyone know how make them work? Any bypass way appreciated.

Thanks!

**Comment by Jon007** [comment]
This plugin is limited to translation of WooCommerce plugin, separate bridges are needed for any WooCommerce extension.
You could implement for your situation by copying the type of code in:
https://github.com/hyyan/woo-poly-integration/blob/master/src/Hyyan/WPI/Emails.php
