### ISSUE TITLE
impossible to translate the position of the $ sign

### ISSUE THREAD

**Issue by quanticconseil** [hyyan/woo-poly-integration#560]
#### What product versions and settings are you using when this issue occurs?
* PHP: 7.4
* WordPress:  5.7.2
* WooCommerce: 5.4.1
* Polylang: [state if using Polylang PRO] polylang classic
* Hyyan WooCommerce Polylang Integration: yes
* Browser:  chrome (all)

1. Hello, i've try to translate the postion of the $ sign in the price for the different languages, but without success.
For exemple : in french it's 5,00 $ and in english it's $5.00.

2. With Polylang for woocommerce, this string is added in Languages > strings transaltion > currency position

3. I can't find the string with hyyan/Poly

Could you help us please?
Thanks

**Comment by Jon007** [comment]
The locale setting does just this, turn it on in WooPoly Settings Features to have the prices displayed according to currency locale.
By all means reopen if that doesn’t work.
