### ISSUE TITLE
After uninstalling, the product categories keep the language selector

### ISSUE THREAD

**Issue by estigeweb** [hyyan/woo-poly-integration#562]
Hello,

I installed your plugin to see if it suited my needs.

As it did not meet my needs, uninstall your plugin and now in the product categories section the translation selector is still displayed.

Before installing your plugin this did not happen.

Please, how can I restore the previous state (that the product categories do not take into account the language) considering that I use polylang for the pages of my site?

Disable language in product categories.

It is important because I have the web stopped due to this problem.

Thanks!

==========================================================
### WordPress Environment ###

WordPress address (URL): https://www.xxxx.com
Site address (URL): https://www.xxxx.com
WC Version: 5.6.0
REST API Version: ✔ 5.6.0
WC Blocks Version: ✔ 5.5.1
Action Scheduler Version: ✔ 3.2.1
WC Admin Version: ✔ 2.5.1
Log Directory Writable: ✔
WP Version: 5.8.1
WP Multisite: –
WP Memory Limit: 320 MB
WP Debug Mode: –
WP Cron: ✔
Language: es_ES
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.4.11
PHP Post Max Size: 2 MB
PHP Time Limit: 120
PHP Max Input Vars: 10000
cURL Version: 7.52.1
OpenSSL/1.0.2u

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.2.39-MariaDB-10.2.39+maria~stretch-log
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 5.6.0
WC Database Prefix: wp_
Tamaño total de la base de datos: 30.22MB
Tamaño de los datos de la base de datos: 20.48MB
Tamaño del índice de la base de datos: 9.74MB
wp_woocommerce_sessions: Datos: 0.16MB + Índice: 0.02MB + Motor InnoDB
wp_woocommerce_api_keys: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_woocommerce_attribute_taxonomies: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_woocommerce_downloadable_product_permissions: Datos: 0.02MB + Índice: 0.06MB + Motor InnoDB
wp_woocommerce_order_items: Datos: 0.06MB + Índice: 0.05MB + Motor InnoDB
wp_woocommerce_order_itemmeta: Datos: 0.50MB + Índice: 0.39MB + Motor InnoDB
wp_woocommerce_tax_rates: Datos: 0.02MB + Índice: 0.06MB + Motor InnoDB
wp_woocommerce_tax_rate_locations: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_woocommerce_shipping_zones: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_woocommerce_shipping_zone_locations: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_woocommerce_shipping_zone_methods: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_woocommerce_payment_tokens: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_woocommerce_payment_tokenmeta: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_woocommerce_log: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_actionscheduler_actions: Datos: 2.50MB + Índice: 0.91MB + Motor InnoDB
wp_actionscheduler_claims: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_actionscheduler_groups: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_actionscheduler_logs: Datos: 1.52MB + Índice: 0.47MB + Motor InnoDB
wp_ce4wp_abandoned_checkout: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_cf7_vdata: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_cf7_vdata_entry: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_check_email_log: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_commentmeta: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_comments: Datos: 0.23MB + Índice: 0.28MB + Motor InnoDB
wp_erp_acct_bills: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_erp_acct_bill_account_details: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_erp_acct_bill_details: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_erp_acct_cash_at_banks: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_erp_acct_chart_of_accounts: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_erp_acct_currency_info: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_erp_acct_expenses: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_erp_acct_expense_checks: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_erp_acct_expense_details: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_erp_acct_financial_years: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_erp_acct_invoices: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_erp_acct_invoice_account_details: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_erp_acct_invoice_details: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_erp_acct_invoice_details_tax: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_erp_acct_invoice_receipts: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_erp_acct_invoice_receipts_details: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_erp_acct_journals: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_erp_acct_journal_details: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_erp_acct_ledgers: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_erp_acct_ledger_categories: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_erp_acct_ledger_details: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_erp_acct_ledger_settings: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_erp_acct_opening_balances: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_erp_acct_payment_methods: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_erp_acct_pay_bill: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_erp_acct_pay_bill_details: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_erp_acct_pay_purchase: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_erp_acct_pay_purchase_details: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_erp_acct_people_account_details: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_erp_acct_people_trn: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_erp_acct_people_trn_details: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_erp_acct_products: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_erp_acct_product_categories: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_erp_acct_product_details: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_erp_acct_product_types: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_erp_acct_purchase: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_erp_acct_purchase_account_details: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_erp_acct_purchase_details: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_erp_acct_purchase_details_tax: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_erp_acct_synced_taxes: Datos: 0.02MB + Índice: 0.08MB + Motor InnoDB
wp_erp_acct_taxes: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_erp_acct_tax_agencies: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_erp_acct_tax_agency_details: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_erp_acct_tax_categories: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_erp_acct_tax_cat_agency: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_erp_acct_tax_pay: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_erp_acct_transfer_voucher: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_erp_acct_trn_status_types: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_erp_acct_voucher_no: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_erp_audit_log: Datos: 0.02MB + Índice: 0.06MB + Motor InnoDB
wp_erp_company_locations: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_erp_crm_activities_task: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_erp_crm_contact_group: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_erp_crm_contact_subscriber: Datos: 0.02MB + Índice: 0.05MB + Motor InnoDB
wp_erp_crm_customer_activities: Datos: 0.02MB + Índice: 0.06MB + Motor InnoDB
wp_erp_crm_customer_companies: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_erp_crm_save_email_replies: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_erp_crm_save_search: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_erp_holidays_indv: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_erp_hr_announcement: Datos: 0.02MB + Índice: 0.05MB + Motor InnoDB
wp_erp_hr_dependents: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_erp_hr_depts: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_erp_hr_designations: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_erp_hr_education: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_erp_hr_employees: Datos: 0.02MB + Índice: 0.08MB + Motor InnoDB
wp_erp_hr_employee_history: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_erp_hr_employee_notes: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_erp_hr_employee_performance: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_erp_hr_financial_years: Datos: 0.02MB + Índice: 0.05MB + Motor InnoDB
wp_erp_hr_holiday: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_erp_hr_leaves: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_erp_hr_leaves_unpaid: Datos: 0.02MB + Índice: 0.08MB + Motor InnoDB
wp_erp_hr_leave_approval_status: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_erp_hr_leave_encashment_requests: Datos: 0.02MB + Índice: 0.05MB + Motor InnoDB
wp_erp_hr_leave_entitlements: Datos: 0.02MB + Índice: 0.05MB + Motor InnoDB
wp_erp_hr_leave_policies: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_erp_hr_leave_policies_segregation: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_erp_hr_leave_requests: Datos: 0.02MB + Índice: 0.08MB + Motor InnoDB
wp_erp_hr_leave_request_details: Datos: 0.02MB + Índice: 0.05MB + Motor InnoDB
wp_erp_hr_work_exp: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_erp_peoplemeta: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_erp_peoples: Datos: 0.02MB + Índice: 0.06MB + Motor InnoDB
wp_erp_people_types: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_erp_people_type_relations: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_erp_user_leaves: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_gla_budget_recommendations: Datos: 0.20MB + Índice: 0.11MB + Motor InnoDB
wp_gla_merchant_issues: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_gla_shipping_rates: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_gla_shipping_times: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_links: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_mailchimp_carts: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_mailchimp_jobs: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_mrw_cities: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_mrw_orders: Datos: 0.19MB + Índice: 0.00MB + Motor InnoDB
wp_mrw_ranges: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_mrw_taxes: Datos: 0.05MB + Índice: 0.00MB + Motor InnoDB
wp_nextend2_image_storage: Datos: 0.05MB + Índice: 0.02MB + Motor InnoDB
wp_nextend2_section_storage: Datos: 0.05MB + Índice: 0.06MB + Motor InnoDB
wp_nextend2_smartslider3_generators: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_nextend2_smartslider3_sliders: Datos: 0.09MB + Índice: 0.03MB + Motor InnoDB
wp_nextend2_smartslider3_sliders_xref: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_nextend2_smartslider3_slides: Datos: 0.09MB + Índice: 0.11MB + Motor InnoDB
wp_options: Datos: 3.47MB + Índice: 0.22MB + Motor InnoDB
wp_pimwick_gift_card: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_pimwick_gift_card_activity: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_postmeta: Datos: 4.52MB + Índice: 3.89MB + Motor InnoDB
wp_posts: Datos: 2.50MB + Índice: 0.31MB + Motor InnoDB
wp_shipment_batch_process: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_termmeta: Datos: 0.06MB + Índice: 0.06MB + Motor InnoDB
wp_terms: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_term_relationships: Datos: 0.06MB + Índice: 0.05MB + Motor InnoDB
wp_term_taxonomy: Datos: 0.05MB + Índice: 0.03MB + Motor InnoDB
wp_tm_taskmeta: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_tm_tasks: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_trackship_shipment: Datos: 0.02MB + Índice: 0.13MB + Motor InnoDB
wp_trackship_shipping_provider: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_ups_shipping_accessorial: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_ups_shipping_account: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_ups_shipping_config: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_ups_shipping_delivery_rates: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_ups_shipping_fallback_rates: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_ups_shipping_license: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_ups_shipping_logs_api: Datos: 0.17MB + Índice: 0.00MB + Motor InnoDB
wp_ups_shipping_log_frontend: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_ups_shipping_orders: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_ups_shipping_package_default: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_ups_shipping_product_dimension: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_ups_shipping_retry_api: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_ups_shipping_services: Datos: 0.05MB + Índice: 0.00MB + Motor InnoDB
wp_ups_shipping_shipments: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_ups_shipping_tracking: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_usermeta: Datos: 0.31MB + Índice: 0.25MB + Motor InnoDB
wp_users: Datos: 0.05MB + Índice: 0.05MB + Motor InnoDB
wp_vxcf_hubspot: Datos: 0.20MB + Índice: 0.02MB + Motor InnoDB
wp_vxcf_hubspot_accounts: Datos: 0.05MB + Índice: 0.00MB + Motor InnoDB
wp_vxcf_hubspot_log: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_wcpdf_invoice_number: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_wc_admin_notes: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_wc_admin_note_actions: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_wc_category_lookup: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_wc_customer_lookup: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_wc_download_log: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_wc_order_coupon_lookup: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_wc_order_product_lookup: Datos: 0.08MB + Índice: 0.06MB + Motor InnoDB
wp_wc_order_stats: Datos: 0.06MB + Índice: 0.05MB + Motor InnoDB
wp_wc_order_tax_lookup: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_wc_product_meta_lookup: Datos: 0.05MB + Índice: 0.09MB + Motor InnoDB
wp_wc_reserved_stock: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_wc_tax_rate_classes: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_wc_webhooks: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_woocommerce_bundled_itemmeta: Datos: 0.05MB + Índice: 0.03MB + Motor InnoDB
wp_woocommerce_bundled_items: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_woo_shipment_status_email: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_woo_shippment_provider: Datos: 0.06MB + Índice: 0.00MB + Motor InnoDB
wp_yith_wcwl: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_yith_wcwl_lists: Datos: 0.02MB + Índice: 0.05MB + Motor InnoDB

### Post Type Counts ###

attachment: 173
br_minmax_limitation: 2
custom_css: 3
elementor_library: 2
flamingo_contact: 126
flamingo_inbound: 66
jetpack_migration: 2
jp_img_sitemap: 1
jp_sitemap: 1
jp_sitemap_master: 1
mailpoet_page: 1
nav_menu_item: 57
o-discount: 2
o-list: 1
oembed_cache: 136
page: 82
polylang_mo: 3
post: 1
product: 68
product_variation: 74
revision: 95
shop_order: 329
shop_order_refund: 1
wafs: 1
woo_discount: 1
wp_block: 1
wpcf7_contact_form: 7

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (58) ###

Polylang: por WP SYNTEX – 3.1.1
Additional Order Filters for WooCommerce: por Anton Bond – 1.10
Advanced CF7 DB: por Vsourz Digital – 1.8.2
Akismet Anti-Spam: por Automattic – 4.1.12
Allow Multiple Accounts: por Scott Reilly – 3.0.4
Integration for Contact Form 7 and HubSpot: por CRM Perks – 1.2.0
Child Theme Configurator: por Lilaea Media – 2.5.8
Widgets clásicos: por Colaboradores de WordPress – 0.2
Contact Form 7: por Takayuki Miyoshi – 5.4.2
Cookiebot | GDPR/CCPA Compliant Cookie Consent and Control: por Cybot A/S – 3.10.1
Join.chat: por Creame – 4.1.15
Duplicate Menu: por Jonathan Christopher – 0.2.2
Yoast Duplicate Post: por Enrico Battocchi & Team Yoast – 4.1.2
Elementor: por Elementor.com – 3.4.3
WP ERP - PDF Invoice: por weDevs – 1.1.3
WP ERP: por weDevs – 1.10.0
Essential Addons for Elementor: por WPDeveloper – 4.9.0
Facebook for WooCommerce: por Facebook – 2.6.4
Health Check & Troubleshooting: por La comunidad de WordPress.org – 1.4.5
If Widget - Visibility control for Widgets: por Layered – 0.5
Insert Pages: por Paul Ryan – 3.6.1
Jetpack: por Automattic – 10.1
Loco Translate: por Tim Whitlock – 2.5.3
HubSpot for WooCommerce: por MakeWebBetter – 1.2.2
Members: por MemberPress – 3.1.5
More Visibility Rules: por Layered – 0.4
Fonts Plugin | Google Fonts Typography: por Fonts Plugin – 3.0.4
PW WooCommerce Gift Cards: por Pimwick
LLC – 1.187

Really Simple SSL: por Really Simple Plugins – 5.1.0
Shortcodes Ultimate: por Vladimir Anokhin – 5.10.2
Simple Social Icons: por StudioPress – 3.0.2
Smart Slider 3: por Nextend – 3.5.0.10
TemplatesNext ToolKit: por TemplatesNext – 3.2.4
TrackShip for WooCommerce: por TrackShip – 1.1.5
UpdraftPlus - Backup/Restore: por UpdraftPlus.Com
DavidAnderson – 1.16.61

Servicio UPS Shipping y UPS Access Point™: complemento oficial: por UPS – 2.2.1
Password Strength Settings for WooCommerce: por Daniel Santoro – 3.0.0
White Label CMS: por www.videousermanuals.com – 2.2.4
Seguimiento avanzado de envíos para WooCommerce: por zorem – 3.2.9
Woo Discount Rules: por Flycart – 2.3.8
Advanced Order Export For WooCommerce: por AlgolPlus – 3.1.9
Premmerce Permalink Manager for WooCommerce: por premmerce – 2.3.3
Country Based Restrictions for WooCommerce: por zorem – 3.1
Woo Stickers by Webline: por Weblineindia – 1.1.5
Variation Swatches for WooCommerce: por Emran Ahmed – 1.1.19
WooCommerce - Country Based Payments: por Ivan Paulin – 1.4
WooCommerce Stripe Gateway: por WooCommerce – 5.4.1
WooCommerce Geolocation Based Products: por Roy Ho – 1.5.4
WooCommerce Min and Max Quantities: por BeRocket – 3.0.6.1
MRW: por Webubi – 4.1.7
WooCommerce PDF Invoices & Packing Slips: por Ewout Fernhout – 2.9.3
WooCommerce Product Bundles - Bulk Discounts: por SomewhereWarm – 1.1.0
WooCommerce Product Bundles - Min/Max Items: por SomewhereWarm – 1.3.5
WooCommerce Product Bundles: por SomewhereWarm – 5.13.3
WooCommerce Price Based on Country (Basic): por Oscar Gare – 2.0.24
WooCommerce Shipping & Tax: por WooCommerce – 1.25.18
WooCommerce: por Automattic – 5.6.0
WP-Optimize - Clean, Compress, Cache: por David Anderson
Ruhani Rabin
Team Updraft – 3.1.12

### Inactive Plugins (2) ###

Check & Log Email: por WPChill – 1.0.2
Query Monitor: por John Blackbourn – 3.7.1

### Must Use Plugins (1) ###

Health Check Troubleshooting Mode: por  – 1.7.2

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: right
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: bundle (bundle)
pw gift card (pw-gift-card)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)

Connected to WooCommerce.com: ✔

### WC Pages ###

Base de la tienda: #12631 - /tienda/
Carrito: #8 - /carrito/
Finalizar compra: #9 - /finalizar-compra/
Mi cuenta: #10 - /mi-cuenta/
Términos y condiciones: #2514 - /terminos-y-condiciones/

### Theme ###

Name: i-craft Child
Version: 3.2.9.1573835839
Author URL: http://templatesnext.org/
Child Theme: ✔
Parent Theme Name: i-craft
Parent Theme Version: 3.5.2
Parent Theme Author URL: http://templatesnext.org/
WooCommerce Support: ✔

### Templates ###

Archive Template: Tu tema tiene un archivo woocommerce.php
no podrás sobreescribir la plantilla personalizada woocommerce/archive-product.php ya que woocommerce.php tiene prioridad sobre archive-product.php. Esto es intencionado para prevenir problemas de visualización.

Overrides: i-craft/woocommerce/content-product.php
i-craft/woocommerce/loop/loop-end.php
i-craft/woocommerce/loop/sale-flash.php
i-craft/woocommerce/single-product/sale-flash.php
i-craft/woocommerce/single-product/title.php

### Geolocation debug info ###

Default customer location: geolocation
MaxMind GeoIP database: ✔
MaxMind GeoIP license: ✔
MM_COUNTRY_CODE: ❌
GEOIP_COUNTRY_CODE: ❌
HTTP_CF_IPCOUNTRY: ❌
HTTP_X_COUNTRY_CODE: ❌
HTTP_X_REAL_IP: ❌
HTTP_X_FORWARDED_FOR: ❌
REMOTE_ADDR: 83.43.14.120
Real external IP: 83.43.14.120
WCPBC_USE_REMOTE_ADDR: –
Geolocation Test: ✔

### PBC Settings ###

Version: 2.0.24
Base location: ES:V
Base currency: EUR
Price Based On: shipping
Shipping: ✔
Test mode: –
Test country: –
Load products price in background: –
Prices entered with tax: ✔
Calculate tax based on: shipping
Display prices in the shop: incl

### Zone Pricing PENINSULA ###

zone_id: peninsula
name: PENINSULA
countries: AD | ES | PT
currency: EUR
exchange_rate: 1
auto_exchange_rate: no
disable_tax_adjustment: no

### Zone Pricing EUROPA EURO ###

zone_id: europa-euro
name: EUROPA EURO
countries: DE | BE | FR
currency: EUR
exchange_rate: 1
auto_exchange_rate: no
disable_tax_adjustment: no

### Zone Pricing SUIZA ###

zone_id: suiza
name: SUIZA
countries: CH
currency: EUR
exchange_rate: 1.092
auto_exchange_rate: no
disable_tax_adjustment: no

### Product Bundles ###

Database Version: 5.13.3
Template Overrides: –

### Action Scheduler ###

Completo: 2.658
Oldest: 2021-09-08 18:29:26 +0200
Newest: 2021-09-10 09:00:47 +0200

Pendiente: 7
Oldest: 2021-09-10 09:03:47 +0200
Newest: 2021-09-10 09:15:03 +0200

### Status report information ###

Generated at: 2021-09-10 09:01:41 +02:00
`

**Comment by Cuniq** [comment]
Hi @estigeweb 

I don't know if this problem is related to the plugin. Polylang let's you enable and disable option through the UI.

In your admin menu click on Languages -> Settings -> Custom post types and Taxonomies -> click the Settings button under the "Custom post types and Taxonomies" title -> Uncheck "Product categories"

![image](https://user-images.githubusercontent.com/10845107/132912936-f87617cf-3b64-4b3b-9b07-9ad0fadfb5d8.png)

**Comment by estigeweb** [comment]
Thank you!

Problem solved.

**Comment by Cuniq** [comment]
@estigeweb Glad that I helped. Can you close the issue please?

**Comment by estigeweb** [comment]
Just one more thing, please.

The real problem I have is that I want the products of any category to be displayed in any language.

Now, the products filtered by category, are only shown in the main language. They are not shown in the rest of the languages.

That is why I installed your plugin. But to this day I am stuck with this problem.

Only products by category are shown in the main language, in the rest of languages ​​the same category shows 0 products.

You can help?

Thanks!

**Comment by estigeweb** [comment]
My configuration:

![image](https://user-images.githubusercontent.com/53442025/132941581-9c42f092-83b7-4b03-a0f2-734c7caba3a0.png)

**Comment by estigeweb** [comment]
![image](https://user-images.githubusercontent.com/53442025/132941613-7a38d31b-10b3-442c-87f2-d78004e80c25.png)

**Comment by estigeweb** [comment]
To put it in a nutshell, I don't want language to intervene when filtering products.

Not at the level of category, or product, or labels ... or anything in my store.

It's possible?

Thanks!

**Comment by Cuniq** [comment]
Unfortunately, I don't thing this is possible with polylang. Polylang languages are completed separated. The easiest solution that comes in mind is to just duplicate each product for all languages. 

I guess maybe other multilanguage plugins are better fit for your problem, but I've never used them.

You can ask for help here https://wordpress.org/plugins/polylang/

Now, if it is possible, can you please close this issue since your problem is not related with this repository.

**Comment by estigeweb** [comment]
OK thanks!
