### ISSUE TITLE
Product Reviews not activated

### ISSUE THREAD

**Issue by orbtaz** [hyyan/woo-poly-integration#563]
#### Can you reproduce this issue on default Wordpress theme (eg Storefront)?
Yes
#### Can you reproduce this issue when all other plugins are disabled except WooCommerce, Polylang and Hyyan WooCommerce Polylang Integration?
Yes
#### What product versions and settings are you using when this issue occurs?
* PHP: 
* WordPress: 5.8.1
* WooCommerce: Version 5.9.1 
* Polylang:  3.1.1
* Hyyan WooCommerce Polylang Integration: Version 1.5.0
* Browser: Google chrome

#### Steps to Reproduce
1. Go to product
2. Go to the advance tab
3. Enable product review
4. Go to the 2nd language product
5. try enabling the product reviews using step above
#### What I Expected
The "enable review" is greyed out.

#### What Happened Instead
Nothing. 

Good day! I just wanted to point out that when we checkmark “Enable product reviews” in the advance tab in the primary language it does not enable it in the 2nd language resulting in not having reviews displayed in the 2nd language.

The only way to enable review in the other language is to disable Hyyan WooCommerce plugin. Then checkmark the “Enable review” and then the reviews will be displayed.

Screenshot: https://prnt.sc/1tzp1jm

**Comment by Jon007** [comment]
make sure Comment Status synchronisation is turned  on under Languages, Settings, Synchronisation at:
/wp-admin/admin.php?page=mlang_settings
(Reviews are a type of comment basically) 
then it should work.

Also, it's highly recommendable to use 1.5.1 as per https://github.com/hyyan/woo-poly-integration/releases
