### ISSUE TITLE
Update wordpress-settings-api-class to latest version

### ISSUE THREAD

**Issue by hyyan** [hyyan/woo-poly-integration#71]
@decarvalhoaa  we must update to latest version of `wordpress-settings-api-class to latest version` , too many changes .

**Comment by hyyan** [comment]
https://github.com/tareq1988/wordpress-settings-api-class

**Comment by hyyan** [comment]
releated to issue #51 Metas list checkbox values not saving

**Comment by decarvalhoaa** [comment]
Done and pushed to  #68 proposed new release 0.29.
