### ISSUE TITLE
How to handle Variable Product attributes with terms withtout translation

### ISSUE THREAD

**Issue by decarvalhoaa** [hyyan/woo-poly-integration#72]
**tl;tr**

I have come across the following scenario and need help figuring out what should be the behavior of the plugin in this case.

Scenario:
1. Product attribute with the name "My Attribute" is created. 
1.1. The translation is automatically added to the Polylang Strings Translations page, with the same name for all active languages.
2. The term named "terms1" is added to "My Attribute" in the default language.
3. A variable product titled "My Var Product" is created in the default language with the attribute "My Attribute" used to create variations.
4. A translation of "My Var Product" is created for a second language, named "My Translated Var Product"
4.1. The translation is created with 1 variation and all metas copied except the term slug since the term doesn't have translation. When "My Translated Var Product" is saved/published, Polylang will sync back to the product in default language "My Var Product" and remove the attribute and variation.

Althought he behaiviour is consistent with Polylang own logic, for a new user of WooPoly plugin this may be confusing and doesn't understand that the terms were not translated.

So my question: shall WooPoly create the terms translations with the same name (like for the attribute name - see point 1.1) if a translation is not found? And potentially add some inline js to alert that attribute terms need to be translated?

Alternatively, we can simple add a note to the readme file and FAQ mentioning this as a know issue?

**Comment by Jon007** [comment]
related also to #127 current behaviour is hard to understand or undesirable:

- current setting forces translation on or off for all attributes: this is unnecessary and conflict with Polylang Languages, Settings, Custom Post Types and Taxonomies, where each individual taxonomy can be selected or not.

- It should not be mandatory to translate attributes which are numeric or ids:  failing to create the variation or showing the variation unlinked to any term is confusing for the shop owner.

I don't want to mix significant changes in behaviour with the woo3 release but I would think it is safe to use base language term if no translation exists.
