### ISSUE TITLE
URL Notifiy for PayPal payment

### ISSUE THREAD

**Issue by michellotto** [hyyan/woo-poly-integration#8]
Hi there,
## http://raphaelmarchetti.ch/fr/wc-api/WC_Gateway_Paypal/

The Paypal API tell us a 404 error..
## https://wpml.org/forums/topic/rest-api-doesnt-work-with-use-directory-for-default-language/

Regards,
/Jérôme

**Comment by Jon007** [comment]
appears to be duplicated by #218 where a solution is proposed
