### ISSUE TITLE
Enabling Hyyan WooCommerce Polylang Integration causes checkout scripts to be loaded on all pages

### ISSUE THREAD

**Issue by Jon007** [hyyan/woo-poly-integration#81]
Enabling Hyyan WooCommerce Polylang Integration causes checkout scripts to be loaded on all pages, for example from the Stripe 
https://checkout.stripe.com/v2/checkout.js?ver=2.0
This happens to be particularly notable from my current location [China] since Stripe is often unavailable from China network and causes important page load issue.

This was happening before the update - previous issue https://github.com/decarvalhoaa/woopoly/issues/22 
was incorrectly closed by me - I obfuscated the issue by using Cloudflare RocketLoader javascript delivery.
So this happens on Antonio de Carvalho WooPoly Version 1.0.1 and both previous and current Hyyan versions.

I restested disabling all other plugins apart from:
Polylang	 	by Frédéric Demarle – 2.0.7
Hyyan WooCommerce Polylang Integration	 	by Hyyan Abo Fakher – 0.29
WooCommerce Stripe Gateway	 	by Automattic – 3.0.5
WooCommerce	 	by WooThemes – 2.6.7

In this scenario,
Enabling Hyyan WooCommerce Polylang Integration causes extra checkout scripts to be loaded on all pages.
After disabling Hyyan WooCommerce Polylang Integration again, the checkout scripts are only loaded on the checkout page.

**Comment by hyyan** [comment]
Hey @Jon007  I will investigate this issue more deeply at the weekend and keep you in update , thanks for reporting

**Comment by decarvalhoaa** [comment]
@Jon007 there are many plugins that implement the stripe Gateway. Can you share a link to the plugin page? i'm assuming this is a free plugin...

**Comment by Jon007** [comment]
Hi @decarvalhoaa yes, it's the standard one from by Automattic in the wooCommerce directory, which is now free, and has really easy to use test mode, I put the version number in the list above:
WooCommerce Stripe Gateway	by Automattic – 3.0.5

pages are:
https://wordpress.org/plugins/woocommerce-gateway-stripe/
https://docs.woocommerce.com/document/stripe/

**Comment by Jon007** [comment]
still there, there's a Stripe script for <script type='text/javascript' src='https://js.stripe.com/v2/?ver=1.0'></script> failing on every page load right now
