### ISSUE TITLE
Issues with variations with 2 attributes

### ISSUE THREAD

**Issue by gabrielenosso** [hyyan/woo-poly-integration#88]
Hi, I am quite new to this plugin.
I am using a Wordpress instance with WooCommerce and this plugin, but it doesn't seem to work fine with variations.
I have some products (shoes), with 2 attributes for variations: size and color.
My default language is English: everything is fine there.
I tried to create Italian versions of these products, but in the shop and in the product page it doesn't show me the variations.
It shows a message saying that the product is not available.

When I create the new post, in the variations tab it shows all the checkboxes with the values "Any size" and "Any color".
Am I missing something or is it a bug, or something else?

**Comment by hyyan** [comment]
Hey @gabrielenosso , have you translated your attributes size and color see this issue #5

**Comment by gabrielenosso** [comment]
@hyyan The attributes names ("Color" and "Size") have been added automatically.
Do I need to translate the values to let it work?

**Comment by hyyan** [comment]
@gabrielenosso Yes you need to translate the values too , give it a try and let me know if it is working

**Comment by gabrielenosso** [comment]
@hyyan Thanks, I will do it right now!

**Comment by gabrielenosso** [comment]
@hyyan It works perfectly! 👍 
I just need to recreate again all the variations, but it's not a big issue for me.

Anyway, wouldn't it be possible to create standard translations for all the languages also for the attributes values? (as it happens for the attributes names?)
At least it would work and people won't have to recreate items again :)

**Comment by hyyan** [comment]
@gabrielenosso Glad that it is working for you now , for what you have suggested , it seems a good but stills not an easy job to do . I will consider adding this in next releases

**Comment by hyyan** [comment]
@gabrielenosso  closing this issue as it is resolved , feel free to reopen it if you still have this issue

**Comment by gabrielenosso** [comment]
@hyyan For the moment it works perfectly.
Also the stock management will be synced, right?

**Comment by hyyan** [comment]
@gabrielenosso sure , you can see data which will be synced in the plugin settings page (Meta List)
