### ISSUE TITLE
Products Admin page -> Price of variations is not updated

### ISSUE THREAD

**Issue by gabrielenosso** [hyyan/woo-poly-integration#90]
As you can see from the pictures I attached, I had created a product with variations, all of them had price 30€.
At that point I created the translated (Italian) version.
Then I updated the price of the original product (English) for all the variations to 45€.

Now the price of the translation (Italian) works perfectly, but the Products Admin page still shows the old price. 

![products gabriel max wordpress](https://cloud.githubusercontent.com/assets/4018887/20428625/6d77eb1e-ad8a-11e6-9064-02f3a74569a7.png)

**Comment by hyyan** [comment]
@gabrielenosso not really sure , if this must happen , I will investigate this issue more this evening

**Comment by gabrielenosso** [comment]
Moreover, if you create variations after the translation is created, it doesn't sync them.
I don't know if is intended to work like that or not though...

**Comment by gabrielenosso** [comment]
I found out that the price of the variations (Translated) is not updated at all.
But if you Save the (translated) post again, then it takes the right values.

**Comment by gabrielenosso** [comment]
Any news on that one?

**Comment by Jon007** [comment]
reconfirmed issue still occurs on latest versions

**Comment by Jon007** [comment]
Yes, current behaviour is definitely rather confusing.

I’m going to split this and track on 2 new issues which will also refer back to this one via this comment:

- #146 Variation "Save changes" button does not trigger variation synchronization
- #147 When adding new variations, tool should also add the new variation to other languages
