### ISSUE TITLE
Products Admin Page -> Quick edit shows all categories

### ISSUE THREAD

**Issue by gabrielenosso** [hyyan/woo-poly-integration#91]
In the Products Admin page, the quick edit shows all the categories, not just the ones which are of the same language of the post.

Meanwhile when you edit a post, it only shows the translated categories.

Is this a bug?

**Comment by hyyan** [comment]
@gabrielenosso it is not a bug , this is the default behavior , because the language is set to `all` in admin screen , you can change that be changing the language in admin bar

**Comment by gabrielenosso** [comment]
So why in the page where I edit a post it shows only the categories of that language?
Just to know :)

**Comment by hyyan** [comment]
because in this stage the product will have a language , so polylang can filter everything according to the language

**Comment by gabrielenosso** [comment]
Ok, perfect! :)
I close the issue so!
