### ISSUE TITLE
 woocommerce_product_gallery_attachment_ids filter used in src/Hyyan/WPI/Media.php is deprecated

### ISSUE THREAD

**Issue by decarvalhoaa** [hyyan/woo-poly-integration#92]
PHP Notice:  The woocommerce_product_gallery_attachment_ids filter is <strong>deprecated</strong> since version 2.7! Use woocommerce_product_get_gallery_image_ids instead.

**Comment by decarvalhoaa** [comment]
Solved

**Comment by Bereshka** [comment]
it just kills me, if you solved, why not to share it with other webmasters?))
