### ISSUE TITLE
Product on the homepage are always on the same lang when switching between languages

### ISSUE THREAD

**Issue by decarvalhoaa** [hyyan/woo-poly-integration#95]
Using default Storefront theme from WooCommerce.

**Comment by decarvalhoaa** [comment]
This issue impacts several woocommerce shortcodes. It is not exclusivly a problem found on the Storefront theme neither limited to the homepage.

What is causing the issue?

WC2.7 improves the shortcode [product loop](https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-shortcodes.php#L84-L126) function, to use the transients cache. If a valid transient is found for the requested product query, WC will use the cached query. Therefore, Polylang will not have the opportunity to inject a new language in the query args.

A simple option to resolve this issue, is to request WC team to filter the [return of get_transient()](https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-shortcodes.php#L91). Someline this:

```
$products = apply_filters( 'woocommerce_shortcode_products_query_transient', get_transient( $transient_name, $query_args, $atts, $loop_name );

if ( false === $products || ! is_a( $products, 'WP_Query' ) ) {
	$products = new WP_Query( apply_filters( 'woocommerce_shortcode_products_query', $query_args, $atts, $loop_name ) );
	set_transient( $transient_name, $products, DAY_IN_SECONDS * 30 );
} 
```

@hyyan - I am ready to ask WC team for the filter addition but would appreciate you feedback that this would be a sensible way forward.

**Comment by hyyan** [comment]
@decarvalhoaa please go a head and ask WC team for the new filter , this makes sense for sure

**Comment by hyyan** [comment]
@decarvalhoaa is there away around that for now ?

**Comment by decarvalhoaa** [comment]
The only thing that comes to my mind right now, is be to clear the specific transients (that are affected) on every page load, or a little better when the current language change (using the polylang cookie. It is not very elegant.

But I think the WC people will not do a big deal out of adding a filter.

**Comment by ioannakan** [comment]
Hello guys,
thank you very much for all the work you are doing.
Do you have any news about that issue?

Best regards,
Ioanna

**Comment by Jon007** [comment]
Yes I have developed a fix.

Noting that there was a change in the wooCommerce 3.0.2 "Note woo3.0.2:  Fix – Made cache in the [products] shortcode respect filters from plugins."
I've implemented a filter to handle this.

I will reference this issue when I check it in so a message will appear on this issue.
The code will be available at:
   https://github.com/Jon007/woo-poly-integration

This should be treated as beta software until we have completed the testing, merge and release.
It would be great if you can test it!!!

**Comment by ioannakan** [comment]
Hello,
thank you so much. I tested it with Mystile theme and Woocommerce 3.0.5, and the shortcode for the recent products is at the homepage. It works perfect. I don't have any other woocommerce shortcode at my website in order to test it.

Thanks A LOT again and keep up the great job.

Ioanna
