### ISSUE TITLE
Woocommerce doesn't work for EN language

### ISSUE THREAD

**Issue by Hud1ai2** [hyyan/woo-poly-integration#98]
Hi everyone. I've installed this plugin today and I have some issues with it. First is, that I'm not able to change the properties about products (see the image) - combo is visible but it isn't active, so you can't choose the variations etc. And the second issue is that image of the product isn't visible in each product page. I'm using the Beaver Builder for building the page. But this builder isn't used for product page (doesn't support WooCommerce in this way) so this is "clear WP".  So I don't how to work with products now to see images of it and with the possibilite to change the properties of products. Thanks.
![image](https://cloud.githubusercontent.com/assets/24320756/20842898/741c67ee-b8b9-11e6-8616-ee6bab4c942d.jpg)
![produkty](https://cloud.githubusercontent.com/assets/24320756/20842897/741c534e-b8b9-11e6-8ac2-8742458e7e05.jpg)

**Comment by Hud1ai2** [comment]
And also if I want to add english version of my product to existing one and I press the "plus" button to add the language these lines appears and whole WP admin page is really slow

Warning: set_time_limit() has been disabled for security reasons in /data/web/virtuals/116022/virtual/www/wp-content/plugins/woo-poly-integration/src/Hyyan/WPI/Product/Variation.php on line 80

Warning: set_time_limit() has been disabled for security reasons in /data/web/virtuals/116022/virtual/www/wp-content/plugins/woo-poly-integration/src/Hyyan/WPI/Product/Variation.php on line 114

Warning: set_time_limit() has been disabled for security reasons in /data/web/virtuals/116022/virtual/www/wp-content/plugins/woo-poly-integration/src/Hyyan/WPI/Product/Variation.php on line 80

Warning: set_time_limit() has been disabled for security reasons in /data/web/virtuals/116022/virtual/www/wp-content/plugins/woo-poly-integration/src/Hyyan/WPI/Product/Variation.php on line 114

**Comment by hyyan** [comment]
@Hud1ai2  it seems that you are trying to edit the translation of your product , all fields of  your translations will be synced automatically from your main product in your choosed default language so for example if your default language is EN , you add the products in English first then you add translation for your product  , the plugin will sync all required information from the main product and all you will need to do is to translate the title and description probably.

But you still can override this option from the plugin settings  -> Fields Locker 

WooPoly make it clear in its readme file that you have to choose you default language before you start adding translation to your products as the variation feature requires that so far. so please be aware of this.

For the `set_time_limit` warning , WooPoly reset the time limit before it starts variations sync cause this may take too much time for a large number of variations and large number of languages.

I might add an option for this to toggle in future , not sure yet .

For product images I am not really sure I got what you mean , but you still can choose a gallery in the same place where you edit/add your product ?!

**Comment by Hud1ai2** [comment]
You're right! Thanks a lot for your fast answer! Everything works correctly now. With images is the same. I tried to "override" the images with another one (don't know why, but I have to upload images for CZ and EN version separately) and that was the reason why it didn't work. So next time add the product leave everything as it is and just change the name and description of the product. Thanks one more time hyyan! :)
