### ISSUE TITLE
Payment Gateways Compatibility - WooCommerce Amazon Payments

### ISSUE THREAD

**Issue by Jon007** [hyyan/woo-poly-integration#99]
woo-poly currently seems incompatible with the free Amazon Payments gateway from wooCommerce:
https://docs.woocommerce.com/document/amazon-payments-advanced/

If woo-poly is activated, there are errors activating amazon-payments and it is not shown in the list.
If amazon payments is already activated, then activating woo-poly causes the amazon payments configuration screen to become inaccessible.

I retested to confirm this is not the same as previous issues seen on other forks with being unable to enable/disable payment gateways (https://github.com/decarvalhoaa/woopoly/issues/23 woopoly disables payment gateway changes)

**Comment by Jon007** [comment]
just to confirm this is still the same with latest wooCommerce and amazon payments gateway updates:   as soon as Hyyan is activated the Amazon gateway option just disappears altogether from the admin interface, it appears again when Hyyan is deactivated

**Comment by Jon007** [comment]
confirmed this is still the case on woocommerce 3.0.4, and woo-poly-integration 0.30 release candidate.
It's bizarre, Amazon Payments gateway just disappears when woo-poly-integration is activated..

**Comment by theleemon** [comment]
Apparently, for some reason, this line in the `woocommerce-gateway-amazon-payments-advanced.php` file is not executed:

`add_filter( 'woocommerce_payment_gateways',  array( $this, 'add_gateway' ) );`

**Comment by theleemon** [comment]
If you specify a priority higher than 10 for the `init` action in the `src/Hyyan/WPI/Plugin.php file`, the Amazon gateway appears:

`add_action('init', array($this, 'activate'), 99);`

**Comment by Jon007** [comment]
good spot, will add for 0.30 RC2 ..
